- tests/filecheck/dialects/memref/canonicalize.mlir
- xdsl/dialects/memref.py
- xdsl/transforms/canonicalization_patterns/memref.py
We need to add this to remove the bogus empty tensor used solely for its shape in linalg pools
> dialects: (memref) canonicalize removes unused memref allocs

- tests/filecheck/dialects/csl/csl-stencil-ops.mlir
- tests/filecheck/transforms/stencil-to-csl-stencil.mlir
- xdsl/dialects/csl/csl_stencil.py
- xdsl/transforms/stencil_to_csl_stencil.py
Follow-up from #2766
The original plan was to lower `stencil.access` to `csl_stencil.access` if and only if the access is to neighbour data (i.e. prefetched), while accesses to own data were supposed to remain `stencil.access` without being lowered.
This runs into the very practical problem, that `stencil.access` can only exist within a `stencil.apply` op - which we also want to lower, but this cannot be done with `stencil.access` ops.
> (minor): allow csl_stencil.access to operate on own data

- tests/filecheck/transforms/convert_qref_to_qssa.mlir
- tests/filecheck/transforms/convert_qssa_to_qref.mlir
- xdsl/dialects/qref.py
- xdsl/dialects/qssa.py
- xdsl/tools/command_line_tool.py
- xdsl/transforms/convert_qref_to_qssa.py
- xdsl/transforms/convert_qssa_to_qref.py
Built on top of #2768 
Adds two passes which convert back and forth between the qssa and qref dialects. Also adds filecheck tests that test each pass and roundtrip of the passes
I think the `convert-qref-to-qssa` is particularly hacky, with the saving the old operands of the operation into a tuple, running replace on the operands and then inserting back the old ones. Would be keen to hear better ways to achieve the same behaviour
> transformations: add qref/qssa conversions

- tests/filecheck/backend/csl/print_csl.mlir
- tests/filecheck/dialects/csl/ops.mlir
- xdsl/backend/csl/print_csl.py
- xdsl/dialects/csl/csl.py
Add the `csl.constants` op to define constant-initialized arrays and printing for said operation.
> dialects: (csl) Add csl.constants op and printing

- tests/dialects/test_riscv.py
- tests/filecheck/backend/riscv/verify.mlir
- tests/filecheck/dialects/riscv/riscv_ops.mlir
- tests/filecheck/dialects/riscv_scf/ops.mlir
- tests/filecheck/dialects/riscv_snitch/ops.mlir
- xdsl/dialects/riscv.py
Turns out I broke the verification a while back, the assembly format expects the immediates to be within the signed range, not unsigned. I expect that the arith lowering will be impacted, but this PR does not address that.
fixes #2056
> dialects: (riscv) Fix I, S and shift operation immediate bounds

- xdsl/pattern_rewriter.py
Slight code cleanup for the replace_op function, removing duplicate check of the type of `new_ops`, and making a couple of things more pythony
> misc: Small refactor to `PatternRewriter.replace_op`

- xdsl/backend/riscv/register_allocation.py
- xdsl/ir/core.py
- xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py
Turns out there's a neat built-in way to get the expected behaviour.
> core: replace BlockReverseOps with a Reversible conformance

- tests/dialects/test_riscv_snitch.py
- xdsl/backend/riscv/traits.py
- xdsl/dialects/riscv_snitch.py
- xdsl/traits.py
In order to make progress on #2468 I factored out the insn representation. This will hopefully also make it usable for the RISC-V backend efforts.
> dialects: (riscv) Add HasInsntrait and implement trait for some operations

- xdsl/dialects/riscv.py
This makes `get_register` pure, as it should be.
The op never reads/writes and is safe to DCE and CSE.
> dialects: (riscv) Make riscv.get_register pure

- tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
- tests/interactive/test_get_all_available_passes.py
- xdsl/tools/command_line_tool.py
- xdsl/transforms/test_lower_memref_stream_to_snitch_stream.py
- xdsl/transforms/test_lower_snitch_stream_to_asm.py
- xdsl/transforms/test_optimise_memref_stream.py
Makes it a bit easier to see what is going on, and makes it easier for our paper experiments repos to keep up to date with xDSL developments.
> testing: Extract linalg to snitch pipeline to test passes in bottom-up

- tests/dialects/test_csl_stencil.py
- tests/filecheck/dialects/csl/csl-stencil-ops.mlir
- xdsl/dialects/csl/csl_stencil.py
This PR implements the `csl_stencil.apply` op as outlined in Step 2 of #2747 
This operation combines a `csl_stencil.prefetch` (symmetric buffer communication across a given stencil shape) with a `stencil.apply`. Please see the doc string of the op for a detailed description.
> (dialects): csl_stencil apply op

- .github/workflows/ci-mlir.yml
- Makefile
- docs/marimo/mlir/README.md
- docs/marimo/mlir/onnx-demo.py
- pyproject.toml
Note that this is missing the interpreter part, since the bug is still there with the ABI calling convention not being respected when calling from the interpreter object directly.
> docs: add onnx demo notebook

- tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
In our testing, for realistic sizes of matmuls, this optimisation did not make a noticeable difference (which makes sense, it's 2 cycles per reduction)
> testing: unpeel matmul in bottom-up tests

- tests/filecheck/dialects/memref_stream/ops.mlir
- tests/filecheck/dialects/memref_stream/verify.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
- tests/filecheck/transforms/convert_linalg_to_memref_stream.mlir
- tests/filecheck/transforms/convert_memref_stream_to_loops.mlir
- tests/filecheck/transforms/memref_stream_fold_fill.mlir
- tests/filecheck/transforms/memref_stream_generalize_fill.mlir
- tests/filecheck/transforms/memref_stream_infer_fill.mlir
- tests/filecheck/transforms/memref_stream_unnest_out_parameters.mlir
- tests/filecheck/transforms/memref_streamify.mlir
- tests/interpreters/test_memref_stream_interpreter.py
- xdsl/dialects/memref_stream.py
- xdsl/transforms/convert_linalg_to_memref_stream.py
- xdsl/transforms/convert_memref_stream_to_snitch_stream.py
- xdsl/transforms/memref_stream_generalize_fill.py
- xdsl/transforms/memref_stream_infer_fill.py
I really should not have been lazy and done this from the start. It makes sense from a semantic point of view, since these are converted to loop bounds, which are index-valued already.
Note stacked PR
> dialects: (memref_stream) make bounds in dialect index typed not IntAttr

- tests/test_printer.py
- xdsl/printer.py
This PR makes the `print_string` function in the printer aware of indentation, and will print newlines in strings accordingly.
For cases where this is not desired (such as printing a newline character in the indentation-aware newline logic), `print_string_raw` has been added to print the string ignoring indentation.
Additionally, a helper `indented` function for with statements has been added to control indentation within a scope. Feedback on this would be much appreciated, as a possible concern is that it may not be super intuitive (it indents newlines, not lines).
> core: Make print_string aware of indentation

- tests/filecheck/dialects/memref_stream/ops.mlir
- tests/filecheck/dialects/memref_stream/verify.mlir
- tests/filecheck/transforms/convert_memref_stream_to_loops.mlir
- tests/filecheck/transforms/convert_memref_stream_to_snitch.mlir
- tests/filecheck/transforms/memref_streamify.mlir
- tests/interpreters/test_memref_stream_interpreter.py
- xdsl/dialects/memref_stream.py
- xdsl/interpreters/memref_stream.py
- xdsl/transforms/convert_memref_stream_to_loops.py
- xdsl/transforms/memref_streamify.py
The way this is modeled is with a region already interleaved. This should simplify the lowering to loops, as the region won't need to be modified, and we can
> dialects: (memref_stream) add interleaved iterator

- Makefile
title says it all.
closes #2826
> tests: Do not run marimo mlir tests without MLIR installed

- tests/filecheck/transforms/stencil-to-csl-stencil.mlir
- xdsl/dialects/csl/csl_stencil.py
- xdsl/dialects/tensor.py
- xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
- xdsl/transforms/stencil_to_csl_stencil.py
This PR implements the conversion to csl_stencil.apply op as outlined in Step 2 of https://github.com/xdslproject/xdsl/pull/2747
The `csl_stencil.apply` op combines a csl_stencil.prefetch (symmetric buffer communication across a given stencil shape) with a stencil.apply.
The transformation consists of several steps:
* When rewriting a `stencil.apply`, select the `csl_stencil.prefetch` with the biggest memory overhead (if several are present) to be fused with the apply op into a `csl_stencil.apply`
* Find a suitable split of ops to be divided across the two code blocks
* Re-order arithmetic e.g. `(a+b)+c -> (c+a)+b` to access, consume, and reduce data of neighbours (for input stencil only)
* Move this into first code block, move all other ops into second code block
* Fallback strategy: …
> (transform): convert to csl_stencil.apply

- tests/test_dialect_utils.py
- xdsl/dialects/builtin.py
- xdsl/dialects/utils.py
This is used in a few places, notably in memref.subview custom syntax, which is the next PR
> api: add printing and parsing of dynamic lists as in MLIR

- xdsl/dialects/memref.py
> dialects: (memref) Make memref.extract_strided_metadata have NoMemoryEffect

- tests/backend/riscv/test_preallocated.py
- xdsl/backend/riscv/register_allocation.py
A little correctness improvement, we should only be allocating to s registers if there's a function call, of which there should be 0 for the foreseeable future, but it's nice not to silently miscompile.
> backend: reserve registers not preserved across function calls in RISC-V

- tests/filecheck/backend/riscv/memref_to_riscv.mlir
- tests/filecheck/backend/riscv/print_format_to_riscv_debug.mlir
- xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
- xdsl/backend/riscv/lowering/utils.py
I find this makes it much easier to read and debug the lowered code.
> backend: (riscv) preserve name hints when casting operands

- tests/filecheck/dialects/snitch_stream/ops.mlir
- tests/filecheck/transforms/convert_memref_stream_to_snitch.mlir
- tests/filecheck/transforms/snitch_register_allocation.mlir
- xdsl/dialects/snitch_stream.py
Makes some things easier to read.
> dialects: (snitch_stream) add custom syntax to streaming region

- tests/dialects/test_memref.py
- tests/filecheck/transforms/convert_memref_stream_to_snitch_stream.mlir
- tests/transforms/test_convert_memref_stream_to_snitch_stream.py
- xdsl/dialects/builtin.py
- xdsl/transforms/convert_memref_stream_to_snitch_stream.py
We currently treat all memrefs as raw pointers in our memref_stream.streaming_region lowering, but that's not correct, we want to take the strided layout into account when possible. This PR adds some helpers to compute the appropriate stride map, and uses them to construct the correct snitch stride pattern.
> transformations: handle strided layout attr in memref_stream lowering

- tests/filecheck/dialects/csl/csl-stencil-ops.mlir
- tests/filecheck/transforms/stencil-to-csl-stencil.mlir
- xdsl/dialects/csl/csl_stencil.py
Small fix to add printing of properties to `csl_stencil.apply` op.
> (minor): print properties on csl_stencil.apply

- tests/filecheck/transforms/memref_stream_tile_outer_loops.mlir
- xdsl/dialects/memref.py
- xdsl/tools/command_line_tool.py
- xdsl/transforms/memref_stream_tile_outer_loops.py
We sometimes have too high a rank when lowering to snitch_stream, this avoids that at the memref_stream level, before streamification.
> transformations: Add memref-stream-tile-outer-loops

- tests/pattern_rewriter/test_pattern_rewriter.py
- xdsl/pattern_rewriter.py
closes #2857 
Solves the issue mentioned there and adds the reported testcase as a regression test.
Before, this was actually quite broken as not applying the recursive rewrite, but the normal rewrite, to the region would actually mean that the produced func_op did not even verify (the `function_type` attribute got rewritten properly, whereas the entry_block args would still have the old type). 
The reason why the old type was being printed is that the `print_func_op_like`-utility function defaults to printing the entry_block arguments in some cases.
> core: (rewriting) Fix recursive type conversion in block arguments for nested regions

- tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir
- tests/filecheck/dialects/riscv_snitch/ops.mlir
- xdsl/dialects/riscv_snitch.py
This PR adds a small set of operations to `riscv_snitch` directly mapping on top of the Snitch custom packed SIMD ISA. Further ops are going to need operand constraints to be correctly register allocated.
> dialects: (riscv_snitch) Add f32 mul, add, pack from Snitch packed SIMD extension

- tests/dialects/test_csl_wrapper.py
- tests/filecheck/dialects/csl/csl-wrapper-ops.mlir
- xdsl/dialects/__init__.py
- xdsl/dialects/csl/csl_wrapper.py
The `csl_wrapper` dialect is helps initialise CSL modules and manage params.
* Properties of the `csl_wrapper.module` are passed as BlockArgs to both layout_module and program_module
* The layout module takes `%x` and `%y` BlockArgs, as well as all properties. The layout module offers various simplifications:
* The terminating `csl_wrapper.yield` op is lowered to `@set_tile_code`. Any values yielded are passed as BlockArgs to the program module
* Any operation using `%x` or `%y` will automatically be placed at the correct level of nesting for the generated `@set_tile_code` loop
* Structs do not need to be handled manually at this stage and should be constructed automatically when lowering. At this level, we can simply provide a list of field names and args to yield.
* The …
> (dialects): adding csl_wrapper dialect

- tests/dialects/test_csl_wrapper.py
- tests/dialects/test_stencil.py
- tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
- xdsl/dialects/csl/csl_stencil.py
- xdsl/dialects/csl/csl_wrapper.py
- xdsl/dialects/stencil.py
- xdsl/tools/command_line_tool.py
- xdsl/transforms/csl_stencil_to_csl_wrapper.py
Pass to lower `csl_stencil` to `csl_wrapper`.
* Creates one `csl_wrapper.module` for each module-level function
* Extracts stencil-related params to initialise `csl_wrapper.modue` and both of its `layout_module` and `program_module` regions
* Initialises `layout_module` with everything required for running stencil programs and yields it to `program_module`, specifically: memcpy params, routes config, and `isBorderRegionPE` bool
Not in this PR:
* ~~Handling host-device transferable symbols and setting up exports~~
* ~~Setting up and exporting program entry point~~
~~As such, the translated func is currently simply placed inside the `program_module`.~~
Update:
* Host-device transferable symbols are now added to the `program_module` block args
* The function op is resolved
* The function …
> (transform): csl-stencil to csl-wrapper pass

- tests/filecheck/dialects/csl/csl-wrapper-ops.mlir
- tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
- xdsl/dialects/csl/csl.py
- xdsl/dialects/csl/csl_wrapper.py
- xdsl/transforms/csl_stencil_to_csl_wrapper.py
Minor changes to the `csl` and `csl_wrapper` dialects:
* csl: always allow ops with the `InModuleKind` trait to exist inside `csl_wrapper.ModuleOp`
* csl_wrapper: rename `import_module` to `import`
> (dialect): minor changes to csl and csl_wrapper

- tests/filecheck/dialects/qref/ops.mlir
- tests/filecheck/dialects/qssa/ops.mlir
- tests/filecheck/dialects/quantum/attrs.mlir
- tests/filecheck/transforms/convert_qref_to_qssa.mlir
- tests/filecheck/transforms/convert_qssa_to_qref.mlir
- xdsl/dialects/__init__.py
- xdsl/dialects/qref.py
- xdsl/dialects/qssa.py
- xdsl/dialects/quantum.py
This pr does the following:
- Adds 'quantum' dialect which contains an angle attribute which is shared by both the 'qref' and 'qssa' dialects.
- angles are stored as rational multiples of 'pi' kept to the range [0,2pi)
- Adds rz gate which is parametrised by an angle (at the moment this is given via an attribute.
- Standardises the gate set to the one used in 'http://arxiv.org/abs/1710.07345'. I can revert the removal of the cz gate if this seems like a poor idea.
~Built on top of #2819 to allow '/' in the angle syntax~
Now using ':' instead to avoid the lexing change
> dialects: add parametrised rz gate

- tests/test_is_satisfying_hint.py
- xdsl/irdl/attributes.py
- xdsl/irdl/constraints.py
- xdsl/utils/isa.py
PR 1/2 to make the Pylance errors in operation definitions go away.
The main idea is for the constraint type to carry the upper bound of the Attribute types that will pass verification. It is not guaranteed to be a strict upper bound.
Pyright errors: 489.
> api: add generic parameter to attribute constraint

- tests/filecheck/dialects/irdl/irdl-to-pyrdl/testd.irdl.mlir
In my rename of constr to eq, I missed that pyright now complains about this test file
> testing: fix irdl-to-pyrdl filecheck

- tests/filecheck/dialects/irdl/irdl-to-pyrdl/testd.irdl.mlir
- xdsl/dialects/builtin.py
- xdsl/dialects/csl/csl_stencil.py
- xdsl/dialects/experimental/dmp.py
- xdsl/dialects/linalg.py
- xdsl/dialects/llvm.py
- xdsl/dialects/memref.py
- xdsl/dialects/memref_stream.py
- xdsl/dialects/mpi.py
- xdsl/dialects/omp.py
- xdsl/dialects/onnx.py
- xdsl/dialects/riscv.py
- xdsl/dialects/stencil.py
- xdsl/dialects/stream.py
- xdsl/interpreters/arith.py
- xdsl/transforms/stencil_to_csl_stencil.py
> api: use new base helper in more operation definitions

- xdsl/dialects/qref.py
The `qref.CNotGateOp` initialiser assigned the incorrect number of result qubits.
> dialects: (Qref) fix bug in cnot initialiser

- tests/filecheck/transforms/stencil-to-csl-stencil.mlir
- xdsl/transforms/stencil_to_csl_stencil.py
Bugfix: Erase merged prefetch op. The transform pass combines a `stencil.apply` and a `csl_stencil.prefetch` into a `csl_stencil.apply` op, and also needs to delete the now merged prefetch op.
> (transform): csl_stencil erase merged prefetch op

- xdsl/dialects/builtin.py
> core: fix default builtin type definitions

- pyproject.toml
For some reason I couldn't test this locally, when I install into a different folder with a relative path, the old cmath.py file is also included for some spooky reason...
> bug: ship cmath.irdl file in pypi

- pyproject.toml
- xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
This makes install without all the extras fail, as vanilla xdsl does not depend on attr
> bug: wrong dataclass imported in stencil_tensorize_z_dimension

- tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
I verified that this works in verilator.
> testing: add ssum testcase to bottom-up tests

- tests/filecheck/dialects/riscv_snitch/ops.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
- xdsl/dialects/riscv_snitch.py
It feels like fastmath is still appropriate on the vector ops, also it will make the lowering a little less tedious, by making the vector and scalar arithmetic ops a little more uniform.
> dialects: (riscv_snitch) add fastmath flags in vector ops

- tests/dialects/test_builtin.py
- xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
- xdsl/dialects/builtin.py
- xdsl/transforms/convert_memref_stream_to_snitch_stream.py
These functions to determine the bit/byte width of an element are useful in many places. I think I have them implemented in a couple of different places myself, so I think this abstraction is quite useful in this regard. The functions were now defined in a pass, I simply moved them over.
> core: Add FixedbitWidthType Interface

- xdsl/backend/riscv/register_allocation.py
- xdsl/backend/riscv/register_queue.py
Should make it a little bit harder to "leak" registers by never unreserving them.
> backend: (riscv) add a reserve_registers helper to register queue

- tests/backend/riscv/test_register_allocation.py
- xdsl/backend/riscv/register_allocation.py
- xdsl/backend/riscv/register_queue.py
This is useful as a general factoring out of our loop allocation logic, but is also necessary for future operations that have constraints for results and operands that must be the same register.
> backend: (riscv) add allocate_same method to register allocator

- tests/dialects/test_memref.py
- tests/filecheck/parser-printer/affine_map.mlir
- tests/filecheck/transforms/memref_stream_tile_outer_loops.mlir
- tests/transforms/test_convert_memref_stream_to_snitch_stream.py
- xdsl/dialects/builtin.py
- xdsl/ir/affine/affine_expr.py
- xdsl/ir/affine/affine_map.py
- xdsl/transforms/convert_memref_stream_to_snitch_stream.py
- xdsl/transforms/memref_stream_tile_outer_loops.py
This PR defines `get_affine_map` in the `MemrefLayoutAttr`, and implements this for the available layout attributes.
This is also defined for the memref type. `memreftype.get_affine_map` still returns the element offset, while `memreftype.get_affine_map_in_bytes` returns the byte offset (accounting for element type width).
Additionally, it replaces all code that (partially) implemented this functionality in their respective transforms (mostly `convert-memref-stream-to-snitch-stream`), by using the new interface in the builtin dialect.
> core: Implement getAffine for MemrefLayout attributes

- tests/backend/riscv/test_register_allocation.py
- xdsl/backend/register_allocatable.py
- xdsl/backend/riscv/register_allocation.py
- xdsl/dialects/riscv.py
- xdsl/transforms/canonicalization_patterns/riscv.py
This is required for some of the vector operations in riscv that reuse the rd register as an operand.
> backend: add RegisterConstraints and use in riscv backend

- tests/filecheck/dialects/memref_stream/ops.mlir
- tests/filecheck/transforms/convert_linalg_to_memref_stream.mlir
- xdsl/dialects/memref_stream.py
- xdsl/transforms/convert_linalg_to_memref_stream.py
We are using the `library_call` attribute to designate to which accelerator we want to dispatch a certain linalg generic to. Right now, this information gets lost when converting from linalg.generic to memref_stream.generic, which is somewhat annoying. This PR adds support for these generic attributes in the memref stream dialect.
> dialects: (memref_stream) add doc and library call support

- tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir
- tests/filecheck/dialects/riscv_snitch/ops.mlir
- xdsl/dialects/riscv_snitch.py
We need these to implement matmul_t on f32
> dialects: (riscv_snitch) add vfmac.s and vfsum.s

- tests/filecheck/backend/riscv/convert_arith_to_riscv_snitch.mlir
- tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir
- tests/filecheck/dialects/riscv_snitch/ops.mlir
- xdsl/backend/riscv/lowering/convert_arith_to_riscv_snitch.py
- xdsl/dialects/riscv_snitch.py
This PR adds support for the `vfadd.h` instruction in the riscv backend and fixes lowering of `arith.addf` on `vector<4xf16>` to it for Snitch.
> dialects: (riscv_snitch) lower arith.addf on vector<4xf16> to vfadd.h

- tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
- tests/filecheck/transforms/memref_stream_legalize.mlir
- xdsl/tools/command_line_tool.py
- xdsl/transforms/memref_stream_legalize.py
- xdsl/transforms/test_optimise_memref_stream.py
This PR adds a legalization pass for `memref_stream.generic` operations. The process involves making the payload body legal wrt types that can be streamed by the target.
> transformations: (memref_stream) add memref_stream.generic legalization pass

- tests/test_affine_builtins.py
- xdsl/ir/affine/affine_expr.py
- xdsl/parser/affine_parser.py
we can override the floordiv symbol, which makes for much nicer experience when using `AffineMap.from_callable`, among others.
> core: (affine) override python floordiv symbol

- xdsl/transforms/canonicalization_patterns/memref_stream.py
- xdsl/transforms/memref_stream_fold_fill.py
- xdsl/transforms/memref_stream_interleave.py
- xdsl/transforms/memref_stream_tile_outer_loops.py
- xdsl/transforms/memref_streamify.py
Without these, the attributes still get lost along the way. I forgot to add them to #2928
> transforms: (memref_stream) add missing doc and library call in generic constructors

- xdsl/xdsl_opt_main.py
Currently, any call to xdsl-opt imports csl, which is slow, this change moves the import to only the case when it's intended.
> misc: move print_csl import away from top level

- tests/filecheck/dialects/csl/csl-stencil-canonicalize.mlir
- xdsl/dialects/csl/csl_stencil.py
- xdsl/transforms/canonicalization_patterns/csl_stencil.py
Adds a canonicalisation pass for `csl_stencil.apply`. The op takes an empty tensor as`iter_arg`, which it does not manage itself. The conversion pass in #2803 initialises an `iter_arg` for each instance of `apply`. This canonicalisation pass identifies where this can be re-used, effectively removing redundant allocations.
> (transform): csl_stencil canonicalization pass

- xdsl/__init__.py
Shaves off about 40ms when launching xdsl-opt, or 1/5 of the time.
`make filecheck` goes from 18.26s to 13.10s on my computer with this change.
> misc: make version lazy

- tests/test_traits.py
- xdsl/dialects/csl/csl.py
- xdsl/dialects/csl/csl_stencil.py
- xdsl/dialects/stencil.py
- xdsl/ir/core.py
- xdsl/traits.py
These make the API more complicated than it needs to be, since all traits are frozen dataclasses we can let the dataclass annotation do the heavy lifting for comparison and hashability.
> api: remove parameters field from Trait

- tests/filecheck/dialects/linalg/linalg_ops.mlir
- xdsl/dialects/linalg.py
Linalg named ops have a hidden region that needs to be printed when calling `--[mlir-]print-op-generic`. This is a discrepancy between the upstream dialect and our partial implementation.
To reproduce, run:
```
xdsl-opt --print-op-generic tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
[...]
%sum = "linalg.add"(%2, %2, %3) <{"operandSegmentSizes" = array<i32: 2, 1>}> : (tensor<2x3xf32>, tensor<2x3xf32>, tensor<2x3xf32>) -> tensor<2x3xf32>
```
vs.
```
mlir-opt --mlir-print-op-generic tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
[...]
%2 = "linalg.add"(%1#0, %1#0, %1#1) <{operandSegmentSizes = array<i32: 2, 1>}> ({
^bb0(%arg0: f32, %arg1: f32, %arg2: f32):
%21 = "arith.addf"(%arg0, %arg1) <{fastmath = #arith.fastmath<none>}> : (f32, f32) -> f32 …
```
> (bug): linalg named ops to include hidden regions in generic print

- tests/backend/riscv/test_register_allocation.py
- tests/filecheck/backend/riscv/register-allocation/preallocated.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
- tests/filecheck/projects/riscv-backend-paper/nsnet.mlir
- xdsl/backend/riscv/register_allocation.py
We were overcounting the registers, since there was no uniquing going on.
> backend: (riscv) fix register allocation stats

- xdsl/xdsl_opt_main.py
Filecheck tests go from 12.68s to 11.41s.
> misc: don't import riscv and x86 in xdsl-opt

- tests/filecheck/dialects/csl/csl-stencil-ops.mlir
- tests/filecheck/dialects/linalg/linalg_ops.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/invalid_ops.mlir
- tests/interpreters/test_linalg_interpreter.py
- xdsl/dialects/linalg.py
- xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
I happened to need the fill operator and decided to do the matmul as well. This continues the work of #2959 
I also made sure that the code works on more than just floating points values.
I moved some duplicate code to determine the type arguments of the hidden region into a common method of the `NamedOp` base class.
I also used the implicit builder to build the regions as I think this is much more readable.
Doing the matmul was a bit more tricky:
- for some reason this op prints the attributes in front of the `ins` and `outs`
- generic from includes the `linalg.memoized_indexing_maps` attribute, which are the indexing maps that would be generated when converting to a linalg
> dialects: (linalg) add correct generic printing for fill, and matmul

- tests/filecheck/dialects/arith/arith_ops.mlir
- xdsl/dialects/arith.py
- xdsl/dialects/builtin.py
- xdsl/parser/attribute_parser.py
Upstream mlir accepts the following arith.constant:
```
%t_const = arith.constant dense<1.234500e-01> : tensor<16xf32>
%m_const = arith.constant dense<1.678900e-01> : memref<64xf32>
```
As for tensors, xdsl currently accepts it in generic form and print it in both generic and non-generic form, but will fail to parse the non-generic form.
As for memrefs, xdsl will not accept it and requires an extensive change to the attribute parser to add support for memrefs in `RankedVectorOrTensorOf`. Some code had to be moved after the definition of `MemRefType` to support this change.
> dialects: (arith, core) Constant op to accept tensor and memref

- tests/dialects/test_tensor.py
- tests/filecheck/transforms/stencil-to-csl-stencil.mlir
- xdsl/dialects/tensor.py
If the `tensor.insert_slice` op is set up with dynamic index, the default value should be `DYNAMIC_INDEX`.
This is required by mlir upstream. The default values in the static get method are currently set incorrectly.
> dialects: (tensor) Incorrect default 'dynamic index' on insert_slice op

- tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
- xdsl/dialects/arith.py
- xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
Add support for directly tensorising `arith.constant`, e.g.
```
%0 = arith.constant dense<1.666600e-01> : tensor<510xf32>
```
The more generic way of tensorising any scalar operand (independent of its source) would be `linalg.fill`ing the value a newly created empty tensor. This still works as a generic way. However, in the special case that the scalar operand is a constant, this is much shorter.
> transform: (stencil-tensorize-z-dimension) Tensorize arith.constant directly

- tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
- tests/filecheck/transforms/stencil-to-csl-stencil.mlir
- xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
- xdsl/transforms/stencil_to_csl_stencil.py
Stencil access offsets need to be scaled by a z-shift to translate positive/negative offsets to zero-based offsets. This is done based off of the halo.
> transformations: (stencil-tensorize-z-dim) Scaling z-shifts to avoid negative offsets

- tests/filecheck/dialects/csl/csl-stencil-ops.mlir
- tests/filecheck/dialects/stencil/invalid.mlir
- tests/filecheck/dialects/stencil/stencil_ops.mlir
- tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
- xdsl/dialects/stencil.py
I.e., make stencil.apply able to express computations on reference-semantic fields through destination operands, instead of only value-semantic through results.
> dialects: Enable bufferized stencil.apply

- xdsl/dialects/stencil.py
To be able to run `stencil-bufferize` after `stencil-tensorize-z-dimension`.
> dialects: (stencil) Relax `stencil.return` for tensors

- tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir
- tests/filecheck/dialects/riscv_snitch/ops.mlir
- xdsl/dialects/riscv_snitch.py
> dialects: (riscv_snitch) add vfmax.s

- tests/irdl/test_declarative_assembly_format.py
- xdsl/dialects/builtin.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
This PR enables support for UnitAttr in the assembly format parser.
The upstream MLIR assembly format syntax to represent a UnitAttr may be for instance ([source](https://mlir.llvm.org/docs/Dialects/BufferizationOps/#bufferizationto_memref-bufferizationtomemrefop)):
```
`bufferization.to_memref` $tensor (`read_only` $read_only^)? attr-dict `:` type($memref)
```
Specifically, if the keyword `read_only` is present, then the UnitAttr (of the same name) will be set. In xdsl, it would simply be set by assigning `= UnitAttr()`. The approach here is similar, if the optional keyword is present, then the value should be set.
This change consists of two parts:
* The first is to not change the `unique_base` variable in the assembly format parser in the way it's usually done for builtins. This causes …
> (core) Support UnitAttr in assembly format

- tests/filecheck/dialects/irdl/pyrdl-to-irdl/cmath-conversion.py
This is the coverage bit in the lit config:
``` python
if "COVERAGE" in lit_config.params:
config.substitutions.append(('xdsl-opt', f"coverage run {xdsl_opt}"))
config.substitutions.append(('xdsl-run', f"coverage run {xdsl_run}"))
config.substitutions.append(('irdl-to-pyrdl', f"coverage run {irdl_to_pyrdl}"))
config.substitutions.append(('python', f"coverage run"))
```
We actually already perform this substitution when needed, so there's no need to provide it explicitly.
I found it confusing that I was generating coverage files without actually asking for coverage data.
> CI: don't run coverage by default in cmath conversion test

- pyproject.toml
- xdsl/interpreters/onnx.py
ONNX used to not have type annotations but now does.
> CI: include onnx interpreter for pyright

- pyproject.toml
- tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
As a consequence of updating ruff, it now raises warnings. This updates the config in accordance with ruff's suggestion.
> CI: use .lint when required by ruff

- tests/test_pass_to_spec.py
- xdsl/passes.py
This is useful in a few places, it makes the `xdsl-gui` pass pipeline a little cleaner, as well as the marimo notebook showing the different stages of the pipeline in the slides.
> misc: don't set pass spec arguments from instance when they are the default value

- tests/test_dialect_utils.py
- tests/test_parser_error.py
- tests/test_printer.py
- xdsl/context.py
- xdsl/dialects/riscv.py
- xdsl/dialects/x86/ops.py
- xdsl/interpreters/irdl.py
- xdsl/ir/core.py
Adds a `Dialect.split_name` method as discussed in #3002
> misc: Add `Dialect.split_name` method

- pyproject.toml
In preparation to migrating to use ruff to format the code.
> CI: move ruff line setting to only linting

- .git-blame-ignored-commits
- .github/workflows/code-formatting.yml
- Makefile
- README.md
- pyproject.toml
A bit of cleanup.
1. exclude ruff transition from git blame
2. remove `make black`
3. clean up comments
4. Makefile now also has 88 column width, because why not
5. Add jupyter notebooks and type stubs to ruff formatted file list
> misc: remove mentions of black formatter

- tests/filecheck/dialects/stablehlo/ops.mlir
- tests/filecheck/dialects/stablehlo/test.mlir
- xdsl/dialects/stablehlo.py
Also reorganizes the test.
CC @efferifick
> dialects: (stablehlo) add elementwise add, sub, mul

- tests/interpreters/test_ptr.py
- xdsl/interpreters/ptr.py
There is currently a bug, I used the wrong `struct` code for the encoding of int64.
> interpreter: fix int64 format in ptr dtypes

- tests/filecheck/transforms/linalg-to-csl.mlir
- xdsl/dialects/csl/csl.py
- xdsl/tools/command_line_tool.py
- xdsl/transforms/linalg_to_csl.py
A short pass that translates (bufferized) linalg ops to csl ops.
Memrefs -> DsdType should be done in a separate pass.
> transformations: Add linalg-to-csl pass

- README.md
- pyproject.toml
- requirements.txt
There will be a number of projects using xDSL + JAX, might as well make this easy.
> dependencies: add JAX as an optional dependency of xDSL

- tests/dialects/test_stencil.py
- tests/filecheck/dialects/csl/csl-stencil-canonicalize.mlir
- tests/filecheck/dialects/csl/csl-stencil-ops.mlir
- tests/filecheck/dialects/stencil/canonicalize.mlir
- tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir
- tests/filecheck/dialects/stencil/stencil_ops.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/ops.mlir
- tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
- tests/filecheck/transforms/distribute-stencil.mlir
- tests/filecheck/transforms/stencil-shape-inference.mlir
- tests/filecheck/transforms/stencil-storage-materialization.mlir
- tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
- tests/filecheck/transforms/stencil-to-csl-stencil.mlir
- tests/filecheck/transforms/stencil-unroll.mlir
- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
This makes the following changes:
- Makes assembly format recognise the empty whitespace directive ``` `` ```
- Fixes a bug in the assembly format parsing so that this is actually parsed correctly
- Allows whitespace at the start of an optional group
- Modifies existing stencil tests now that they print correctly (i.e. without a space in `stencil.store`
- Adds tests for new functionality
These changes bring the assembly format closer to the assembly format of mlir
> core: Improved treatment of whitespace in assembly format

- tests/pattern_rewriter/test_pattern_rewriter.py
- xdsl/pattern_rewriter.py
- xdsl/transforms/convert_memref_stream_to_snitch_stream.py
- xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py
- xdsl/transforms/memref_stream_legalize.py
- xdsl/transforms/shape_inference_patterns/stencil.py
This requires absolutely no change in itself, I'm not sure why it was typed BlockArgument specifically?
Also, consider modifying a block argument's type as a modification of the parent operation, if any. Is anyone finding it problematic? It didn't trigger any problem on tested stuff, and it's natural for my use-case; stacked PR to come.
No big deal if it's an alarm, I'll hoist it in my user code.
Note/Usecase: Was intended for:
- #3046 
But I meanwhile just including the logic in my own files instead of waiting on core.
> rewriting: Make `modify_block_argument_type` `modify_value_type`

- flake.lock
- flake.nix
Switches nixpkgs version to unstable to get latest version of `ruff` (0.6.1).
> installation: Update nix flake

- tests/filecheck/dialects/irdl/testd.irdl.mlir
- xdsl/dialects/irdl/irdl.py
- xdsl/printer.py
Adds `RegionsOp`, `RegionOp`, `RegionType`, and `AttributesOp` to irdl
> dialect: (irdl) Add region and attributes operations

- pyproject.toml
- xdsl/interpreters/onnx.py
Numpy changed something in their typing annotations and now our main is broken. We should probably move to something that locks our dependencies for our CI, in the meantime, this PR specifies a numpy version and fixes the type errors.
> dependencies: fix numpy version for subprojects that depend on it

- tests/filecheck/transforms/distribute-stencil.mlir
- xdsl/dialects/experimental/dmp.py
- xdsl/transforms/stencil_bufferize.py
- Implement side effect interface of dmp.swap
- Slightly extend the side-effect analysis of stencil bufferization.
- Add a `dmp.swap` bufferization pattern in `stencil-bufferize`. To just work for now as dmp is only used in stencil so far - decoupling this as shape inference and all is left to future work!
> transformations: Enable dmp.swap stencil bufferization.

- tests/filecheck/transforms/stencil-bufferize.mlir
- xdsl/dialects/tensor.py
- xdsl/transforms/stencil_bufferize.py
(@PapyChacal  edit)
Just implement the right side effect interfaces on the `tensor` dialect, and demonstrate usage in stencil bufferization.
- Checked against MLIR.
- Removed `Pure` from tensor.empty as the upstream is marked ConditionallySpeculatable. Again, we don't have those traits yet.
> dialects: Update `tensor` side-effect traits

- tests/irdl/test_operation_builder.py
- tests/irdl/test_operation_definition.py
- xdsl/irdl/operations.py
Should help fix:
- #3064 
(Hey GitHub, I said should help fix #3064?)
> core: Implement IRDL SameSize options

- tests/dialects/test_stencil.py
- tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
- xdsl/dialects/stencil.py
- xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Now that `stencil-bufferize` can deal with those cases, lift this restriction at the stencil dialect level.
Keep the check in the specific old conversion patterns still assuming this property for least surprise. Point user to use `stencil-bufferize`, which if successful makes those operations disappear.
> dialects: stencil: Allow loading and storing from a same field.

- tests/filecheck/transforms/stencil-bufferize.mlir
- xdsl/dialects/stencil.py
- xdsl/transforms/stencil_bufferize.py
Just forgot to check side-effects *including* the last user when fold `stencil.buffer`
> transformations: `stencil-bufferize` side-effect analysis fix

- tests/filecheck/dialects/stablehlo/ops.mlir
- xdsl/dialects/stablehlo.py
> dialects: (stablehlo) Add support for andOp

- tests/dialects/test_transform.py
- tests/filecheck/dialects/transform/transform_types.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/transform/transform_types.mlir
- xdsl/dialects/transform.py
This PR adds the important operation of the structured match in the transform dialect.
The PR is opened as a draft as I have not been able to find out how to implement the interface-attribute. which should be of kind enum (https://mlir.llvm.org/docs/Dialects/Transform/#transformstructuredmatch-transformmatchop)
@superlopuh @jorendumoulin
> dialects: (transform) Add structured match operation

- tests/filecheck/dialects/stablehlo/ops.mlir
- xdsl/dialects/stablehlo.py
Add support for `stablehlo.returnOp`.
Note: this operation is not listed in the standard, but it is used by examples in the standard. See for example:
```
// %index: -1
// %result_branch0: [0, 0]
// %result_branch1: [1, 1]
%result0, %result1 = "stablehlo.case"(%index) ({
"stablehlo.return"(%result_branch0, %result_branch0) : (tensor<2xi64>, tensor<2xi64>) -> ()
}, {
"stablehlo.return"(%result_branch1, %result_branch1) : (tensor<2xi64>, tensor<2xi64>) -> ()
}) : (tensor<i32>) -> (tensor<2xi64>, tensor<2xi64>)
// %result0: [1, 1]
// %result1: [1, 1]
```
> dialects: (stablehlo) Add support for returnOp

- tests/filecheck/dialects/stablehlo/attrs.mlir
- xdsl/dialects/stablehlo.py
One of the attributes necessary to express dot products
CC @efferifick
> dialects: (stablehlo) add stablehlo.precision

- tests/filecheck/dialects/stablehlo/attrs.mlir
- xdsl/dialects/stablehlo.py
> dialects: (stablehlo) add stablehlo.token

- tests/filecheck/dialects/stablehlo/ops.mlir
- xdsl/dialects/stablehlo.py
Adds support for `stablehlo.bitcast_convert`
> dialects: (stablehlo) add stablehlo.bitcast_convert

- tests/filecheck/transforms/csl_stencil_bufferize.mlir
- xdsl/dialects/csl/csl_stencil.py
- xdsl/transforms/csl_stencil_bufferize.py
The `csl-stencil-bufferize` pass lowers `stencil.field` and `tensor` types to `memref`.
The type conversion pass creates the scenario that some `csl_stencil.access` ops are equal input and output types, for instance, `(memref<512xf32>) -> memref<512xf32>`. This only happens for ops accessing own data. In this case, the access op has no effect and can safely be folded away.
> transformations: (csl-stencil-bufferize) Fold `csl_stencil.access` that have no effect

- tests/filecheck/dialects/stablehlo/ops.mlir
- xdsl/dialects/stablehlo.py
> dialects: (stablehlo) add stablehlo.case

- tests/filecheck/dialects/stablehlo/ops.mlir
- xdsl/dialects/stablehlo.py
> dialects: (stablehlo) add stablehlo.after_all

- tests/test_traits.py
- xdsl/traits.py
It is way simpler than side effects, as an op is either speculatable or is not!
Similarly to what was decided on side effects, I only changed that MLIR has an extra return value signifying "recursively speculatable", where here it is handled by an implementation of the trait, rather than in user code.
This prevents some amount of ninja-coding in said user code, but also a lot of ninja headaches.
> core: Implement speculability trait and helper.

- tests/backend/riscv/test_register_allocation.py
- tests/filecheck/backend/riscv/register-allocation/preallocated.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
- tests/filecheck/projects/riscv-backend-paper/nsnet.mlir
- xdsl/backend/riscv/register_allocation.py
This makes it clearer when reading the assembly later what the allocated registers were, I forgot that `zero` was counted in the registers, and misinterpreted the counts in the paper.
> backend: (riscv) print list of registers to regalloc stats

- tests/filecheck/backend/csl/print_csl.mlir
- xdsl/backend/csl/print_csl.py
Previously param's were printed using their `param_name`, but referenced by the name hint of their ssa value. They are now referenced by the `param_name`
> fix: Param names were not correctly referenced in the printer

- .pre-commit-config.yaml
Brings the precommit version in line with the dependency version. I'm still not sure what the official way to do this is, it feels weird to keep the two in sync manually. IIUC the dependency is used in the VSCode extension, so is also useful...
> CI: update ruff precommit

- tests/filecheck/backend/riscv/canonicalize.mlir
- xdsl/dialects/riscv.py
- xdsl/transforms/canonicalization_patterns/riscv.py
Hello! Canonizing this pattern.
Should it be just `li 0` instead of it's canonized form in the rewrite pattern? In this case it kind of seems like canonization of `li 0` is split to two places.
> dialects: (riscv) canonize x ^ x = 0

- tests/filecheck/dialects/vector/vector_pure_ops.mlir
- xdsl/dialects/vector.py
Add `Pure` trait to `vector.broadcast` and `vector.fma`, fixes #3019
> dialects: (vector) add pure trait to vector.broadcast and vector.fma

- Makefile
The test `/tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir` keeps timing out on my system. Could we either increase the timeout (as in this pr) or fix the test.
> tests: Increase timeout on lit tests

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Adds successors to assembly format. Implementation is very similar to regions.
> core: Add successors to assembly format

- xdsl/dialects/builtin.py
- xdsl/dialects/llvm.py
Some ops in builtin and llvm dialect have the NoMemoryEffect upstream,
but don't have this in xDSL yet, which means that they will always return False on `is_side_effect_free` even though they are completely side-effect-free.
I added all NoMemoryEffects to the current LLVM dialect and Builtin.
> dialects: Add NoMemoryEffect trait in various LLVM and builtin ops

- tests/filecheck/transforms/function-constant-pinning.mlir
- xdsl/transforms/experimental/function_constant_pinning.py
Fixes `function-constant-pinning` pass to not break on functions without a body (external functions).
> transforms: Fix constant pinning breaking for external functions

- tests/filecheck/dialects/scf/scf_ops.mlir
- tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir
- tests/filecheck/frontend/dialects/scf.py
- tests/filecheck/mlir-conversion/with-mlir/control_flow_hoist_collab.mlir
- tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
- tests/filecheck/transforms/cse.mlir
- tests/filecheck/transforms/distribute-stencil.mlir
- tests/filecheck/transforms/function-constant-pinning.mlir
- tests/filecheck/transforms/stencil-bufferize.mlir
- xdsl/dialects/scf.py
Adds custom parsing to some scf ops and fixes the relevant tests.
I noticed during this that `scf.reduce` is now quite different to upstream mlir, but didn't attempt to change this.
> dialects: (scf) Add parse/print to `scf.if`

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Removes `*SegmentSizes` from the required properties seen if the appropriate option is set of the operation
> core: Assembly format shouldn't require `$*SegmentSizes`

- tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
- xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
Add support for enclosing unknown ups such as scf.for
> transformations: (stencil-tensorize-z-dim) Support loops

- tests/dialects/test_cf.py
- tests/filecheck/dialects/cf/cf_ops.mlir
- tests/filecheck/frontend/dialects/cf.py
- tests/filecheck/transforms/cse.mlir
- tests/filecheck/transforms/reconcile_unrealized_casts.mlir
- xdsl/dialects/cf.py
Adds custom parsing to control flow operations. I also changed the message of a `cf.assert` op to be an attribute instead of a property to agree with mlir, but can revert this if there was a good reason for it (/or split it into a separate pr).
> dialects: (cf) Custom Parsing and assert change

- tests/filecheck/backend/csl/print_csl.mlir
- tests/filecheck/dialects/scf/scf_ops.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
- tests/filecheck/transforms/convert_memref_stream_to_snitch_stream.mlir
- xdsl/dialects/scf.py
In mlir, if the iteration variable of `scf.for` does not have an explicit type, then it is assumed to be `index`. This change matches this behaviour in xDSL.
> dialects: (scf) make iteration variable type explicit

- tests/filecheck/backend/csl/print_csl.mlir
- xdsl/backend/csl/print_csl.py
Adds integer and floating point comparisons as well as `and` and `or`.
Signed and unsigned integers are compared the same way.
Ordered and unordered floats are compared the same way.
`true` and `false` float comparisons are printed as `true` and `false` literals.
`ord` and `uno` comparisons result in an error.
`arith.andi` and `arith.ori` produce `and` and `or` operators when operating on `i1` (bools) and `&` and `|` otherwise
> backend: (csl) Add comparison operators to CSL

- tests/filecheck/dialects/llvm/inline_asm.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/inline_asm.mlir
- xdsl/dialects/llvm.py
I apparently made a small yet significant error when I implemented this operation the first time, which sometimes gives weird errors in mixed pipelines.
`has_side_effects`, `is_align_stack` are optional properties defined as UnitAttributes.
I apparently gave a very difficult to find error because I tested them as attributes, and not as properties. and because `has_side_effects` is not exactly the same as `has_side_effect`
I'm not sure the implementation I'm using here for defining optional properties is correct. It seems there are multiple ways of doing this in xdsl?
> dialects: llvm.InLineAsmOp has_side_effects, is_align_stack are properties

- tests/filecheck/backend/csl/print_csl.mlir
- xdsl/backend/csl/print_csl.py
Added a list of CSL language keywords which will be checked along with taken variable names when choosing the name of a new variable.
> backend: (csl) Don't use CSL keywords as var names

- tests/filecheck/transforms/csl_wrapper_to_csl.mlir
- xdsl/transforms/csl_wrapper_to_csl.py
When generating the layout module in `csl_wrapper`, `@set_rectangle` needs to be called with the values of `width` and `height` (via `csl.set_rectangle`).
> fix: Add the missing call to `@set_rectangle`

- xdsl/dialects/scf.py
Didn't catch this on the original PR as the bug is crazy and filecheck isn't checking whole lines. Apparently functions in python cast to true.
Should we enforce matching on whole lines in the `scf_ops.mlir` filecheck test?
> dialects: (scf) fix `scf.if` printing bug

- tests/filecheck/transforms/csl-wrapper-hoist-buffers.mlir
- xdsl/tools/command_line_tool.py
- xdsl/transforms/csl_wrapper_hoist_buffers.py
Adds a new pass to hoist buffer allocations to the `program_module`-level of csl-wrapper.
This is done in a separate pass to allow executing it at the right point in the pipeline.
> transformations: Add new csl-wrapper-hoist-buffers pass

- tests/filecheck/dialects/cf/cf_ops.mlir
- xdsl/dialects/cf.py
Adds `cf.switch` and simple test
> dialects: (cf) add switch

- tests/filecheck/backend/csl/print_csl.mlir
- tests/filecheck/dialects/csl/ops.mlir
- xdsl/backend/csl/print_csl.py
- xdsl/dialects/csl/csl.py
Variables work very much like `memref.global`, but they are scalars.
Ops:
* `csl.variable`: declare variable with optional default value
* `csl.get_var`: get SSA value (constant) of the variable
* `csl.update_var` set variable from ssa value
Types:
* `csl.var<T>`: type of a variable
> dialect: (csl) Adds variables to the dialect

- tests/filecheck/transforms/eqsat-create-eclasses.mlir
- xdsl/tools/command_line_tool.py
- xdsl/transforms/eqsat_create_eclasses.py
This PR addresses https://github.com/xdslproject/xdsl/issues/3170:
* Added initial front end pass `eqsat-create-eclasses` for the minimal example
* Updated the test case to match the pass
> Added initial eqsat front end pass

- xdsl/dialects/csl/csl.py
* docstrings
* verifications
* `get_element_type` in `VariableOp`
These are fixes which should have been in #3183
> fix: various minor fixes for the csl variables

- tests/filecheck/backend/csl/print_csl.mlir
- tests/filecheck/dialects/csl/ops.mlir
- xdsl/backend/csl/print_csl.py
- xdsl/dialects/csl/csl.py
This corresponds directly to the builtin `@activate` combined with a call to the corresponding `@get_<kind>_task_id` to convert the numeric ID to a task id.
> dialects: (csl) add  `csl.activate`

- tests/filecheck/dialects/tosa/ops.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/tosa/ops.mlir
- xdsl/dialects/tosa.py
The attributes are actually properties in tosa.
I got fooled by the `ParsePropInAttrDict` ☹️
> dialects: (tosa) turn attributes into properties

- GETTING_STARTED.md
- tests/filecheck/backend/riscv/canonicalize.mlir
- xdsl/dialects/riscv.py
- xdsl/transforms/canonicalization_patterns/riscv.py
Add a rewrite pattern to the risv dialect for to optimise bitwise xor by zero (x^0 -> x)
> dialects: (riscv) Add rewrite pattern to optimize bitwise xor by zero

- tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
- xdsl/transforms/csl_stencil_to_csl_wrapper.py
Adds call to `unblock_cmd_stream` in the `csl-stencil-to-csl-wrapper` pass as the last instruction of the main program function.
> transformations: (csl-stencil-to-csl-wrapper) Add `unblock_cmd_stream` call

- tests/filecheck/backend/csl/print_csl.mlir
- xdsl/backend/csl/print_csl.py
`arith.select` can be translated to a CSL ternary operator
`if (cond) lhs else rhs`.
> backend: (csl) added arith.select to csl backend

- tests/filecheck/transforms/lower-csl-stencil.mlir
- xdsl/transforms/lower_csl_stencil.py
Lowering csl_stencil.apply's yield op now stores the results to the dest buffer.
> transformations: (lower-csl-stencil) Store results to apply.dest

- tests/filecheck/backend/csl/print_csl.mlir
- xdsl/backend/csl/print_csl.py
Using `_print_or_promote_to_inline_expr` instead of `print`
> backend: (csl) allow `get_dir` to be inlined

- xdsl/backend/csl/print_csl.py
Print via `_use_var` instead of `name_hint`, as that can be `None`.
> bug: Print csl namehint fix

- tests/filecheck/transforms/convert-scf-to-cf.mlir
- xdsl/transforms/convert_scf_to_cf.py
Again this is mainly copied from the implementation in mlir
> transformations: (scf-to-cf) add lowering for index_switch

- tests/filecheck/dialects/csl/csl-canonicalize.mlir
- xdsl/dialects/csl/csl.py
- xdsl/transforms/canonicalization_patterns/csl.py
Folds:
* `GetMemDsdOp` followed by `IncrementDsdOffsetOp`, `SetDsdLengthOp`, `SetDsdStrideOp`
* Chained `IncrementDsdOffsetOp`, `SetDsdLengthOp`, `SetDsdStrideOp` of the same op type
> transformations: Add CSL dsd canonicalisation

- tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
- xdsl/backend/csl/print_csl.py
- xdsl/transforms/csl_stencil_to_csl_wrapper.py
They need to be 2 greater than the dmp topology
@n-io Could you please let me know if this looks right?
> fix: (csl) adjusted width and height of the PE

- tests/filecheck/transforms/lower-csl-stencil.mlir
- xdsl/transforms/lower_csl_stencil.py
Small fix to only send core data to neighbours.
> transformations: (lower-csl-stencil) Send only core data

- GETTING_STARTED.md
- tests/filecheck/backend/riscv/canonicalize.mlir
- xdsl/dialects/riscv.py
- xdsl/transforms/canonicalization_patterns/riscv.py
Added a riscv canonicalization pattern for bitwise or with 0.
> dialects: (riscv) canonicalization pattern added (x|0=x)

- tests/filecheck/dialects/cf/canonicalize.mlir
- xdsl/dialects/cf.py
- xdsl/transforms/canonicalization_patterns/cf.py
Going to work through adding all the canonicalization patterns for the cf ops that are in mlir.
Starting with removing "assert true"
> dialects: (cf) Assert canonicalization pattern

- tests/filecheck/dialects/cf/canonicalize.mlir
- xdsl/dialects/cf.py
- xdsl/transforms/canonicalization_patterns/cf.py
Adds one of the canonicalization patterns for `cf.branch`. The other will need predecessor information for blocks and so is not part of this PR.
> dialects: (cf) branch canonicalization.

- tests/irdl/test_operation_builder.py
- tests/test_use.py
- xdsl/ir/core.py
- xdsl/printer.py
Adds a list of uses to blocks, and adds a function to get the predecessors of a block.
I'm slightly unsure about the code re-use in this PR. It feels slightly wrong to use the `Use` class for both operand usage and successor usage, though the data is the same. I'm also unsure if I should have attempted to unify `OpOperands` and `OpSuccessors` under a single interface, as they are very similar.
> core: Block predecessors

- tests/dialects/test_dmp.py
- xdsl/dialects/experimental/dmp.py
DMP dialect used to not consider what happens when `core_size < halo_size`. This should generate exchanges to further neighbors, instead of requesting more data from the direct neighbor than it actually holds.
This is now fixed.
> dialects: (dmp) Emit multiple swaps if halo is larger than core size

- tests/filecheck/dialects/varith/invalid.mlir
- tests/filecheck/dialects/varith/varith_ops.mlir
- xdsl/dialects/__init__.py
- xdsl/dialects/varith.py
Add a variadic arithmetic dialect.
The goal is to provide a place for nice-to-use arithmetic operations. Also makes re-writing arithmetic easier in some cases, e.g. when you want to split a summation over one set of values into two summations by selecting certain values from the set.
Coming next is two rewrites to canonicalize arith to varith, and then to de-canonicalize back.
> dialects: (varith) Add varith (variadic arithmetic) dialect

- xdsl/dialects/builtin.py
- xdsl/dialects/csl/csl_stencil.py
- xdsl/dialects/stencil.py
- xdsl/transforms/convert_stencil_to_csl_stencil.py
- xdsl/transforms/csl_stencil_to_csl_wrapper.py
Another small step towards updating Pyright, 170 errors -> 142, by using constraints instead of types in a few places.
> dialects: (builtin) add AnyMemRefTypeConstr and AnyTensorTypeConstr

- xdsl/dialects/csl/csl_stencil.py
- xdsl/dialects/experimental/dmp.py
- xdsl/dialects/stencil.py
- xdsl/irdl/constraints.py
- xdsl/transforms/convert_stencil_to_csl_stencil.py
- xdsl/transforms/csl_stencil_to_csl_wrapper.py
- xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
This adds some constraint constants and a new `.constr` helper to construct parametrized constraints for stencil types. Pyright errors 143 -> 133
> dialects: (stencil) add StencilType constraints

- tests/filecheck/transforms/dce.mlir
- xdsl/ir/post_order.py
- xdsl/transforms/dead_code_elimination.py
Introduces a region level algorithm for dead-code elimination, which is capable of deleting unused operations which occur in cycles and deleting blocks. It is modeled on the [mlir implementation](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Transforms/Utils/RegionUtils.cpp). While the mlir implementation separates this into two separate passes (removing dead blocks and then removing dead operations) they have a todo comment for merging them, and so I have implemented it here as a single pass.
I have not implemented removal of block argument removal, for the sake of keeping this PR smaller and my own sanity, as it seems to add a fair bit of complexity.
> transforms: (dce) region-level dce

- tests/irdl/test_attribute_definition.py
- xdsl/dialects/builtin.py
- xdsl/dialects/stablehlo.py
- xdsl/interpreters/irdl.py
- xdsl/ir/core.py
- xdsl/irdl/attributes.py
- xdsl/transforms/canonicalization_patterns/csl.py
Another small step towards updating Pyright, contains small changes that both our current Pyright and the new one are happy with. Pylance errors: 109 -> 94
> misc: miscellaneous linting wrt Pylance

- tests/filecheck/dialects/mod_arith/mod_arith.mlir
- xdsl/dialects/__init__.py
- xdsl/dialects/mod_arith.py
Create a mod_arith dialect with a basic initial operation, based on the Mod Arith dialect in HEIR.
(link to the original dialect: https://github.com/google/heir/tree/main/lib/Dialect/ModArith)
> dialects: (mod_arith) create mod_arith dialect and add initial operation

- tests/dialects/test_llvm.py
- xdsl/dialects/llvm.py
Removes the generic parameter from arithmetic binary operations in the llvm dialect.
CC @lfrenot this will conflict with your PR
> dialects: (llvm) ArithmeticBinOpBase is always on integers

- tests/irdl/test_declarative_assembly_format.py
- tests/tblgen_to_py/test.py
- xdsl/dialects/builtin.py
- xdsl/dialects/csl/csl.py
- xdsl/dialects/stream.py
- xdsl/tools/tblgen_to_py.py
- xdsl/transforms/csl_stencil_bufferize.py
- xdsl/transforms/lower_csl_wrapper.py
- xdsl/transforms/memref_to_dsd.py
Pylance errors: 84 -> 74.
Part of #3264
> misc: add more .constr helpers and constraints

- tests/filecheck/dialects/cf/canonicalize.mlir
- tests/filecheck/dialects/riscv_cf/canonicalize.mlir
- xdsl/pattern_rewriter.py
- xdsl/transforms/canonicalize.py
- xdsl/transforms/dead_code_elimination.py
- Adds ability to specify arbitrary action after processing the worklist in the rewriter
- Canonicalize now adds full dce passes between applying rounds of canonicalization patterns
- Lets the full dce algorithm emit listener events (I'm not sure if this was necessary)
- Updates riscv canonicalization test that now gets more aggressively simplified
- Adds `cf` filecheck test demonstrating the effect of this change
> transforms: (canonicalize) Add full dce

- tests/filecheck/transforms/memref-to-dsd.mlir
- xdsl/transforms/memref_to_dsd.py
Adds support for pre-existent `GetMemDsdOp`s in the `memref-to-dsd` pass, which is needed for #3271
> transformations: (memref-to-dsd) Support pre-existing GetMemDsd ops

- tests/filecheck/dialects/cf/canonicalize.mlir
- xdsl/transforms/canonicalization_patterns/cf.py
> transforms: (cf) fix passthrough operands

- tests/filecheck/backend/csl/print_csl.mlir
- xdsl/backend/csl/print_csl.py
> backend: (csl) Support zero-stride dsd printing

- tests/filecheck/transforms/lower-csl-stencil.mlir
- xdsl/transforms/lower_csl_stencil.py
For full-stencil accesses followed by an *immediate* reduction of a uniform reduction function, use the catch-all `getRecvBufDsd` API call instead of the neighbour-by-neighbour `getRecvBufDsdByNeighbor` function.
Iff this optimisation is applicable, the accumulator dsd might look like this:
```zig
const accumulatorDsd = @get_dsd(mem4d_dsd, .{
.tensor_access = |i,j,k|{directionCount, pattern, chunkSize} -> accumulator[k]
});
```
This is currently implemented by setting the strides of `i` and `j` to 0, which might require a printer update (tbc).
> transformations: (lower-csl-stencil) Optimise full-stencil access

- tests/filecheck/dialects/cf/canonicalize.mlir
- xdsl/dialects/cf.py
- xdsl/transforms/canonicalization_patterns/cf.py
- xdsl/transforms/canonicalization_patterns/scf.py
- xdsl/transforms/canonicalization_patterns/utils.py
First two `cond_br` canonicalization patterns:
- Constant folding (`cf.cond_br %true ^0 ^1` == `cf.br ^0`)
- Passthrough (conditional branch to a branch with just a single `br` op gets forwarded)
> dialects: (cf) cond_br folding

- tests/backend/test_jax_executable.py
- tests/dialects/test_riscv_snitch.py
- tests/filecheck/frontend/dialects/affine.py
- tests/irdl/test_declarative_assembly_format.py
- tests/test_parser.py
- tests/test_traits.py
- xdsl/dialects/builtin.py
- xdsl/dialects/stream.py
- xdsl/frontend/dialects/builtin.py
- xdsl/frontend/type_conversion.py
- xdsl/irdl/attributes.py
- xdsl/tools/tblgen_to_py.py
- xdsl/transforms/varith_transformations.py
I added `reportUnnecessaryTypeIgnoreComment = true` to pyproject.toml to find these
> misc: remove unnecessary pyright ignore comments [NFC]

- tests/filecheck/backend/csl/print_csl.mlir
- xdsl/backend/csl/print_csl.py
Add support for array literals to the printer.
> backend: (csl) Array literals

- docs/irdl.ipynb
- tests/irdl/test_operation_definition.py
- xdsl/dialects/bufferization.py
- xdsl/dialects/builtin.py
- xdsl/dialects/irdl/pyrdl_to_irdl.py
- xdsl/dialects/stencil.py
- xdsl/irdl/constraints.py
- xdsl/irdl/operations.py
Continuation of #2704 
Co-authored-by: Emilien Bauer <papychacal@gmail.com>
> core: Implement RangeVarConstraint

- tests/filecheck/dialects/riscv/riscv_ops.mlir
- xdsl/dialects/riscv.py
`riscv`-only part of https://github.com/xdslproject/xdsl/pull/3272, with a new dialect test added. Thanks for the suggestion of separate tests, I didn't realize those existed and caught an error in the LiOp implementation while adding the test cases.
> dialects: (riscv) add fastmath flag to RdRsRs Float Float Int operations

- tests/filecheck/dialects/cf/canonicalize.mlir
- xdsl/dialects/cf.py
- xdsl/transforms/canonicalization_patterns/cf.py
Adds simplification to `cf.cond_br` when both branches point to the same successor.
The mlir version only performs the reduction when either all the operands are the same, or the common destination branch only has one predecessor. I have no idea why this is and didn't include this condition.
Also updates some of the other tests which now reduce further
> transformations: (cf) cf.cond_br identical successors

- tests/filecheck/dialects/cf/canonicalize.mlir
- xdsl/dialects/builtin.py
- xdsl/dialects/cf.py
- xdsl/transforms/canonicalization_patterns/cf.py
Truth propagation canonicalization pattern.
I have not implemented the `SimplifyCondBranchFromCondBranchOnSameCondition` pattern from mlir, because it seems to be implied from this pattern and previous const folding pattern.
> transformations: (cf) cf.cond_br truth propagation

- tests/filecheck/mlir-conversion/with-mlir/dialects/bufferization/ops.mlir
- xdsl/dialects/bufferization.py
Currently we need only the command with tensor arguments but we should extend it to memrefs as well at some point.
> dialects: (bufferization) add materialize_in_destination

- tests/filecheck/dialects/cf/canonicalize.mlir
- xdsl/dialects/cf.py
- xdsl/transforms/canonicalization_patterns/cf.py
Adds all the switch canonicalization patterns present in mlir. I'm happy to anonymise some of the block names in the filecheck tests if this is deemed worth doing.
> transformations: (cf) switch canonicalization

- tests/dialects/test_csl_stencil.py
- tests/filecheck/dialects/csl/csl-stencil-canonicalize.mlir
- tests/filecheck/dialects/csl/csl-stencil-ops.mlir
- tests/filecheck/transforms/convert-stencil-to-csl-stencil.mlir
- tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
- tests/filecheck/transforms/csl-stencil-materialize-stores.mlir
- tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
- tests/filecheck/transforms/csl_stencil_bufferize.mlir
- tests/filecheck/transforms/lower-csl-stencil.mlir
- tests/filecheck/transforms/lower-csl-wrapper.mlir
- xdsl/dialects/csl/csl_stencil.py
- xdsl/transforms/convert_stencil_to_csl_stencil.py
- xdsl/transforms/csl_stencil_bufferize.py
- xdsl/transforms/csl_stencil_materialize_stores.py
- xdsl/transforms/lower_csl_stencil.py
Both regions of the `csl_stencil.apply` op could take args from a single `var_operand_def`. This is now separated out more cleanly into two separate `var_operand_def`s, one for each region.
> dialects: (csl-stencil) Separate varargs for apply regions

- xdsl/irdl/declarative_assembly_format.py
Relaxes some of the assertions for range variable solving. This allows a range variable to resolve to any sequence (i.e. a tuple) instead of just a list.
> core: relax some types in range variable solving

- tests/filecheck/dialects/scf/unregistered.mlir
- xdsl/printer.py
`scf.for` prints it's blocks without terminators if there are no `iter_args`. Unfortunately the check for whether an operation is a terminator returns true by default for unregistered operations (presumably so that they don't break verification), and so they don't get printed.
This change should make it so that these ops always get printed.
> core: always print unregistered ops

- tests/test_builtin_traits.py
- xdsl/traits.py
Allows operations with the `HasParent` trait to verify when detached. This makes it easier to write unit tests for these operations, as there is no need to nest them within other operations.
>  core: (HasParent) allow no parent for testing

- tests/filecheck/dialects/arith/arith_ops.mlir
- xdsl/dialects/arith.py
Currently dropped, this is needed for #3315 to work correctly.
> dialects: (arith) fix attribute dictionary printing and parsing

- docs/irdl.ipynb
- tests/irdl/test_declarative_assembly_format.py
- tests/irdl/test_operation_definition.py
- xdsl/dialects/affine.py
- xdsl/dialects/arith.py
- xdsl/dialects/comb.py
- xdsl/dialects/csl/csl.py
- xdsl/dialects/eqsat.py
- xdsl/dialects/llvm.py
- xdsl/dialects/ltl.py
- xdsl/dialects/memref.py
- xdsl/dialects/memref_stream.py
- xdsl/dialects/mod_arith.py
- xdsl/dialects/riscv_snitch.py
- xdsl/dialects/scf.py
- xdsl/dialects/seq.py
- xdsl/dialects/stablehlo.py
- xdsl/dialects/stream.py
- xdsl/dialects/varith.py
- xdsl/irdl/operations.py
It turns out that Pyright can infer them, makes relevant code much cleaner IMO
> misc: remove type annotations from VarConstraint ClassVars

- tests/filecheck/transforms/convert-arith-to-varith.mlir
- tests/filecheck/transforms/convert-varith-to-arith.mlir
- xdsl/tools/command_line_tool.py
- xdsl/transforms/varith_transformations.py
Adding a convert-varith-to-arith pass, which reverses the convert-arith-to-varith pass, rewriting varith operations as a sequence of arith operations.
---
> transforms: Add convert-varith-to-arith pass

- tests/filecheck/transforms/convert-arith-to-varith.mlir
- xdsl/transforms/varith_transformations.py
In some edge-cases a single arith op was not folded away. This should be fixed now.
> transformations: (arith-to-varith) Support more cases

- tests/filecheck/backend/riscv/convert_arith_to_riscv.mlir
- xdsl/backend/riscv/lowering/convert_arith_to_riscv.py
`backend`(lowering)-only part of https://github.com/xdslproject/xdsl/pull/3272. Depends on #3275 and #3276.
This should close #2725 once merged
> Arith to riscv lowering fastmath cmpf

- tests/filecheck/transforms/memref-to-dsd.mlir
- xdsl/transforms/memref_to_dsd.py
This pass translates memref allocs to csl array allocs with a get_dsd on top of it, which will be used by various compute ops. This PR add support for memref.load ops, which should continue to load from the memref, not from a get_dsd op.
> transformations: (memref-to-dsd) Support memref.load ops

- tests/filecheck/backend/csl/print_csl.mlir
- xdsl/backend/csl/print_csl.py
When printed as `0`, type is assumed to be `comptime_int` which cannot be implicitly cast to float.
> fix: (csl) Print float zero as `0.0`, not `0`

- tests/filecheck/transforms/linalg-fuse-multiply-add.mlir
- xdsl/tools/command_line_tool.py
- xdsl/transforms/linalg_transformations.py
Introduces a new pass to fuse `linalg.mul` and `linalg.add` into `linalg.generic` with the functionality of an FMA op.
> transformations: New linalg-fuse-multiply-add pass

- tests/filecheck/transforms/linalg-to-csl.mlir
- xdsl/transforms/linalg_to_csl.py
Checks if a `linalg.generic` op is a fused multiply-add and lowers it to `fmacs` or `fmach`, depending on the precision.
> transformations: (linalg-to-csl) Lower generic to fmac(h|s)

- tests/filecheck/dialects/varith/varith_ops.mlir
- xdsl/dialects/varith.py
Apparently putting generic syntax in a roundtrip test never tests the parsing.
Should have listened to @superlopuh
> dialects: (varith) fix switch parsing

- tests/filecheck/dialects/pdl/pdl_operation.mlir
Filecheck test documenting how to match an MLIR operation without return type
> dialects: (pdl) Filecheck test documenting how to match an MLIR operation without return type

- tests/filecheck/transforms/varith-fuse-repeated-operands.mlir
- xdsl/tools/command_line_tool.py
- xdsl/transforms/varith_transformations.py
This PR rewrites 
```
varith.add %n, %n, %n, %x
```
as
```
%three arith.constant 3
%three_n = arith.mulx %n, %three       // mulf or muli
%varith.add %three_n, %x
```
This is useful in particular when operating on tensors, in order to avoid repeatedly adding a large tensor to itself (we have such a case).
The number of repetitions minimally required to trigger fusion behaviour can be controlled via a flag (default=2).
> transformations: New varith-fuse-repeated-operands pass

- tests/filecheck/dialects/arith/canonicalize.mlir
- xdsl/dialects/arith.py
- xdsl/transforms/canonicalization_patterns/arith.py
This adds the first of two canonicalisation patterns `FloatingPointLikeBinaryOperation`s on `arith.constants`.
* Ops with two constant operands are folded by canonicalisation, regardless of math flags
* ~~Chained ops of the form `(const1 * var) * const2` are rewritten as `(const1 * const2) * var` iff the `fastmath<reassoc>` or `fastmath<fast>` flags are set, and if the ops are multiplications or additions. Note, this is not currently implemented in upstream mlir.~~
See [here](https://godbolt.org/z/1KKf6vbfv) to check how it works in upstream mlir.
Note, these canonicalisations currently do not support container types.
> transformations: Canonicalizations for arith on float constants

- tests/filecheck/dialects/arith/canonicalize.mlir
- xdsl/dialects/arith.py
- xdsl/transforms/canonicalization_patterns/arith.py
This adds the second of two canonicalisation patterns for `FloatingPointLikeBinaryOperation`s on `arith.constants`.
* Ops with two constant operands are folded by canonicalisation, regardless of math flags (see #3362 )
* Chained ops of the form `(const1 * var) * const2` are rewritten as `(const1 * const2) * var` iff the `fastmath<reassoc>` or `fastmath<fast>` flags are set, and if the ops are multiplications or additions. Note, this is not currently implemented in upstream mlir.
See [here](https://godbolt.org/z/1KKf6vbfv) to check how it works in upstream mlir.
Note, these canonicalisations currently do not support container types.
> transformations: (canonicalize) Arith const reassociation

- tests/filecheck/dialects/arith/canonicalize.mlir
- xdsl/dialects/arith.py
- xdsl/transforms/canonicalization_patterns/arith.py
Adds some simple canonicalization patterns for `arith.select`
> dialects: (arith) select canonicalization patterns

- tests/filecheck/transforms/csl_stencil_bufferize.mlir
- xdsl/transforms/csl_stencil_bufferize.py
This PR sets destination buffers for linalg ops, if the destination buffer is one of its inputs.
Known caveats:
* Setting the outs for all ops to one buffer known to be writable causes read-after-write conflicts, which the bufferization does not analyse for
* The default behaviour (of mlir-opt's `linalg-fuse-elementwise-ops` pass) is to set `outs` to `input[0]`, which in some cases causes a significant overhead of `memref.alloc`s
Iff the `outs` of a linalg op is its own `input[n]`, this PR re-selects `n` in one of two ways:
* prefer an input with the `writable` flag and no later use, or if none is found
* prefer a linalg op input with no later use (i.e. chaining)
> transformations: (csl-stencil-bufferize) Reselect linalg outs

- xdsl/transforms/canonicalization_patterns/arith.py
Dividing a negative number by zero should output negative inf, while dividing 0 by 0 should output nan. This is to match upstream mlir.
> canonicalisation: (arith) Zero division result fix

- tests/filecheck/dialects/ptr/ops.mlir
- xdsl/dialects/__init__.py
- xdsl/dialects/ptr.py
Porting the ptr dialect proposed [here](https://discourse.llvm.org/t/rfc-ptr-dialect-modularizing-ptr-ops-in-the-llvm-dialect/75142/21). Going to transfer the riscv compilation pipeline to it.
> dialects: (ptr) Introducing ptr dialect

- tests/filecheck/transforms/convert_memref_to_ptr.mlir
- xdsl/transforms/__init__.py
- xdsl/transforms/convert_memref_to_ptr.py
Introducing lowering of some memref operations to a ptr dialect. This will be used to translate riscv compilation to ptr dialect in the future (this is the second pr in the series).
> transformations: Convert `memref` to `ptr`dialect

- tests/filecheck/transforms/convert_memref_to_ptr.mlir
> transformations: check invalid cases in `memref` -> `ptr` conversion

- tests/filecheck/transforms/cse.mlir
- xdsl/dialects/builtin.py
FloatData recently received an `__eq__` method to handle `nan` inequalities. Because of this change, it also needs to provide a `__hash__` method.
> bug: Fix cse for FloatData

- tests/filecheck/transforms/function-persist-arg-names.mlir
- tests/interactive/test_app.py
- xdsl/transforms/__init__.py
- xdsl/transforms/function_transformations.py
Persisting function arg names to arg attributes as suggested [here](https://discourse.llvm.org/t/mlir-capi-how-to-set-function-argument-names-arg0/3892/2).
Note, upstream mlir will say `op arguments may only have dialect attributes`, requiring arg attribute names to be prefixed with a dialect.
> transformations: Persist func arg names as arg_attr

- tests/interactive/test_app.py
- tests/interactive/test_get_all_available_passes.py
- xdsl/interactive/app.py
- xdsl/interactive/get_all_available_passes.py
- xdsl/interactive/passes.py
Changes the interactive app object to store a pass list and context, which are set for now in the initialization function. This will allow further refactors which allow these to be overridden more easily by downstream projects.
> interactive: refactor to one use of get_all_passes/get_all_dialects

- tests/filecheck/backend/riscv/convert_ptr_to_riscv.mlir
- xdsl/transforms/__init__.py
- xdsl/transforms/convert_ptr_to_riscv.py
Part 3 of introducing `ptr` dialect to snitch compilation. Pass to lower `ptr` to `riscv`.
> transformations: `ptr` -> `riscv` conversion

- tests/filecheck/transforms/csl_stencil_bufferize.mlir
- xdsl/dialects/csl/csl_stencil.py
- xdsl/transforms/csl_stencil_bufferize.py
This technically performs some (all?) of the work of `csl-stencil-materialize-stores`, but before bufferization. Not sure if instead of this injection I should rewrite the pass?
> transformations: Materialise stores before bufferization

- tests/dialects/test_llvm.py
- xdsl/dialects/llvm.py
This changes the representation of the exact attribute from a mandatory bool to an optional Unit.
This is to follow the syntax introduced by https://github.com/llvm/llvm-project/pull/115327
> dialects: (llvm) changed the exact attribute to a UnitAttr

- tests/filecheck/transforms/test-add-timers-to-top-level-funcs.mlir
- tests/interactive/test_get_all_available_passes.py
- xdsl/transforms/__init__.py
- xdsl/transforms/csl_stencil_to_csl_wrapper.py
- xdsl/transforms/function_transformations.py
Adds `timer_start()` and `timer_end()` calls at the beginning and end of top-level functions, intended for testing and benchmarking purposes.
> transformations: New test-add-timers-to-top-level-funcs pass

- tests/filecheck/transforms/scf_for_loop_range_folding.mlir
- xdsl/transforms/__init__.py
- xdsl/transforms/scf_for_loop_range_folding.py
Porting mlir pass of the same name. The logic is almost the same. We need this to keep snitch compilation fully inside xdsl.
> transformations: (scf) loop range folding

- tests/irdl/test_declarative_assembly_format.py
- xdsl/dialects/experimental/air.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
The number of results is not passed in when parsing operations. In the generic format, the type of the operation always specifies the types of the results, and `resultSegmentSizes` specifies the ranges of of the results if multiple are variadic. In order to support variadic results, the types an length of all variadic results must be present in the custom syntax.
> misc: raise error if variadic results types aren't referenced in assembly format

- xdsl/dialects/stencil.py
- xdsl/transforms/convert_stencil_to_csl_stencil.py
- xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
Applies various minor fixes evolving around tensorization:
* Relaxes the constraint on the `stencil.LoadOp` in the same way it was previously done on `stencil.StoreOp`.
* Simplifies rebuilding apply op, using operand types as block arg types (bug fix)
* Convert all `stencil.access` to `csl_stencil.access` without bailing out (bug fix)
> transformations: (stencil-tensorize-z-dimension) Minor pipeline fixes

- tests/filecheck/transforms/stencil-shape-minimize.mlir
- xdsl/transforms/shape_inference.py
- xdsl/transforms/stencil_shape_minimize.py
Add a restrict flag to the StencilShapeMinimize pass which restricts the grid size of a stencil computation.
> transforms: add restrict flag to StencilShapeMinimize pass

- pyproject.toml
- tests/dialects/test_builtin.py
- tests/dialects/test_printf.py
- tests/dialects/test_riscv_snitch.py
- tests/dialects/test_stencil.py
- tests/interpreters/test_cf_interpreter.py
- tests/interpreters/test_riscv_func_interpreter.py
- tests/interpreters/test_riscv_scf_interpreter.py
- tests/interpreters/test_scf_interpreter.py
- tests/irdl/test_declarative_assembly_format.py
- tests/riscv/test_abi_spec.py
- tests/test_dominance.py
- tests/test_pass_from_spec.py
- tests/test_pass_lexer.py
- tests/test_pass_to_arg_and_types_str.py
- tests/test_pass_to_spec.py
- tests/test_traits.py
I just ran `ruff check -fix --unsafe-fixes`
> misc: use preferred style for pytest parametrized tests

- tests/filecheck/transforms/eqsat-add-costs.mlir
- xdsl/dialects/eqsat.py
- xdsl/transforms/eqsat_add_costs.py
Instead of storing the cost of the lowest-cost-operand-op, store its index. This will make extraction simpler by avoiding the work of looking again, and does not significantly impact adding costs.
> dialects: (eqsat) add min_cost_index optional attribute to eclass

- xdsl/dialects/riscv.py
- xdsl/dialects/riscv_debug.py
- xdsl/dialects/riscv_snitch.py
We currently have a single base class for two kinds of shared functionality: printing the assembly for the target, and printing the custom format. I'd like to decouple them to migrate some RISC-V operations to custom format, which cannot be provided at the same time as custom printing and parsing functions.
> dialects: (riscv) split out the base classes for custom format and assembly printing

- xdsl/dialects/arith.py
- xdsl/dialects/llvm.py
- xdsl/dialects/riscv.py
- xdsl/dialects/utils.py
- xdsl/transforms/arith_add_fastmath.py
- xdsl/transforms/canonicalization_patterns/riscv.py
Removes the dependency of arith and riscv dialects on llvm, as well as some passes that operate on arith and riscv but not llvm.
> dialects: move FastMathFlag and FastMathAttrBase to xdsl.dialects.utils

- xdsl/dialects/stencil.py
- xdsl/dialects/x86/ops.py
As far as I can tell, these annotated type vars were completely unused, and the tests we have seem to agree with me
> misc: cleanup leftover ConstraintVar

- tests/pattern_rewriter/test_pattern_rewriter.py
- xdsl/pattern_rewriter.py
Step 1 of removing ParamDef is to provide a constraint-based alternative to the type-based `attr_type_rewrite_pattern`.
> rewriting: add attr_constr_rewrite_pattern

- tests/filecheck/dialects/accfg/accfg_ops.mlir
- xdsl/dialects/accfg.py
The `accfg` dialect in snax-mlir has diverged slightly from what it is in upstream xDSL. This PR aims to change that so that we can start upstreaming passes from snax-mlir as well.
Some of things that were reconverged:
* Introduction of `launch_fields` instead of a single `launch_addr`
* Introduction of accfg-effect to model side-effects.
* Introduction of custom syntax on the setup op for improved legibility
> dialects: (accfg) Update ACCFG dialect to match version in snax-mlir

- xdsl/dialects/builtin.py
- xdsl/irdl/attributes.py
- xdsl/irdl/constraints.py
Adds nice syntax for `AllOf`, similar to the one for `AnyOf`
> core: use & for AllOf constraint

- tests/filecheck/transforms/test-add-timers-to-top-level-funcs.mlir
- xdsl/dialects/stencil.py
- xdsl/transforms/canonicalization_patterns/stencil.py
- xdsl/transforms/csl_stencil_handle_async_flow.py
- xdsl/transforms/function_transformations.py
Various minor fixes:
* `stencil`: Add canonicalisation pattern for `stencil.cast` where input type == output type
* `csl-stencil-handle-async-flow`: When creating a function call graph, copy arith constants to the function in which they are used, undoing mlir-opt canonicalisation moving them around.
* `test-add-timers-to-top-level-funcs`: Generate timers as `private` functions
> misc: Stencil and csl lowering fixes

- tests/filecheck/dialects/arm/test_ops.mlir
- xdsl/dialects/arm/ops.py
Add custom ARM assembly syntax and generic roundtrip test to filecheck.
Note: stacked PR
> dialects (arm): add custom syntax

- xdsl/dialects/builtin.py
- xdsl/irdl/constraints.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
This implements something halfway between what I originally had in #3456 and what @superlopuh suggested in https://github.com/xdslproject/xdsl/pull/3456#issuecomment-2479586661 . I think this a strict improvement over the original which uses callables and lambda functions and will merge it into that PR if people agree
> Use classes in place of callables for resolvers

- tests/interpreters/test_pdl_interpreter.py
- xdsl/interpreters/pdl.py
This is the first PR adding some unit tests for the existing matcher before opening the PRs for the eqsat version.
> interpreter: (pdl) fix match_operand matching for already matched value

- tests/interpreters/test_pdl_interpreter.py
- xdsl/interpreters/pdl.py
Another PR adding tests to existing PDL infrastructure.
Note stacked PR
> interpreter: (pdl) add test for result matching

- tests/dialects/test_bufferization.py
- xdsl/dialects/bufferization.py
Removes the `TensorMemrefInferenceConstraint` in favour of a simpler `TensorFromMemrefConstraint`.
> dialects: (bufferization) Simplify tensor/memref constraint

- pyproject.toml
I recently broke this, and didn't realise because I have wgpu installed. Uninstalling it and running make pyright triggered the errors. Changing the pyproject file fixed everything.
> testing: update path to wgpu interpreter for pyright exclusion

- tests/irdl/test_attr_constraint.py
- xdsl/irdl/constraints.py
This seems to work, is there any reason not to do this?
Note: conflicts with #3456
> core: (irdl) ParamAttrConstraint can infer recursively

- tests/filecheck/dialects/tensor/ops.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/tensor/ops.mlir
- xdsl/dialects/tensor.py
This PR adds the following operations to the tensor dialect:
- tensor.InsertOp [docs](https://mlir.llvm.org/docs/Dialects/TensorOps/#tensorinsert-tensorinsertop)
- tensor.ExtractOp [docs](https://mlir.llvm.org/docs/Dialects/TensorOps/#tensorextract-tensorextractop)
that I currently use for a tree ensemble compiler implemented using xdsl ([link](https://github.com/francescodaghero/treeco/tree/main)).
I have tried to mirror the operations available in MLIR, customizing both the print/parse functions, but I am not 100% sure I did it correctly, as this is my first PR.
> dialects: (tensor) add insertop and extractop

- tests/dialects/test_bufferization.py
- tests/dialects/test_builtin.py
- tests/filecheck/dialects/onnx/onnx_invalid.mlir
- tests/irdl/test_attribute_definition.py
- tests/irdl/test_declarative_assembly_format.py
- tests/test_pyrdl.py
- xdsl/dialects/bufferization.py
- xdsl/dialects/builtin.py
- xdsl/dialects/linalg.py
- xdsl/dialects/onnx.py
- xdsl/dialects/stencil.py
- xdsl/irdl/constraints.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
- xdsl/irdl/operations.py
I've gone through a few different refactors this week and have eventually settled on this slightly smaller refactor for the constraint system. The key addition is that each constraint now returns a dictionary of "resolvers" (name can maybe be improved) which resolve a variable from the given attribute. This allows inference to be decoupled entirely from verification, and inference should no longer be quite as fragile/maybe slightly quicker.
In this version, the resolvers are not used for verification, as I had originally planned, and instead the previous verification framework is left as is. I believe this change can enable the following changes in the future:
- Allow constraints on properties to resolve variables in a clean way (see #3318)
- Allow the introduction of "length/int …
> core: new inference system for constraints

- xdsl/dialects/builtin.py
- xdsl/ir/core.py
- xdsl/irdl/declarative_assembly_format.py
Changes `parse_with_type` from a classmethod to a staticmethod allowing a stricter type constraint to be put on the input type and allowing the removal of a cast and pyright suppression
> core: simplify TypedAttribute

- xdsl/ir/core.py
- xdsl/irdl/attributes.py
- xdsl/printer.py
This currently doesn't really do anything because `IntegerAttr` is the only `TypedAttribute`. But after future PRs this will unify the way in which `TypedAttribute` is printed.
There is a potential worry about circularity here if someone calls `print_attribute` in `print_without_type` but I think this would have caused problems anyway
> core: make TypedAttribute printing generic

- tests/irdl/test_attr_constraint.py
- xdsl/irdl/constraints.py
As discussed in #3477 
Fixes #3483
> core: make BaseAttr inferrable

- tests/dialects/test_bufferization.py
- tests/irdl/test_attr_constraint.py
- xdsl/dialects/bufferization.py
- xdsl/irdl/constraints.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
A wrapper class to encapsulate the inference context. I have a feeling that we might want to split out the inference context into range and non-range variable assignments, this will hide the change from the signature of the `infer` method.
> API: add InferenceContext

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Refactors the assembly format directives to:
- Remove some unnecessary classes that made the system rigid
- Separate directives that go in a `type` clause from format directives
This will make it easier to add `operands`, `results`, and `functional-type` directives.
> core: refactor assembly format directives

- tests/irdl/test_attribute_definition.py
- xdsl/dialects/builtin.py
- xdsl/ir/core.py
- xdsl/irdl/attributes.py
As discussed in #3492, this check feels unnecessary and is unwanted for making `DenseIntOrFPElementsAttr` a `TypedAttribute`
> core: remove generic and generic check from TypedAttribute

- xdsl/dialects/stencil.py
- xdsl/irdl/constraints.py
- xdsl/utils/scoped_dict.py
Paring this PR down until it's clear that ScopedDicts are what we want to use for constraint contexts, reducing changes to just getters being nullable.
> misc: use nullable getters in ConstraintContext

- xdsl/dialects/builtin.py
- xdsl/parser/attribute_parser.py
- xdsl/printer.py
A simpler version of #3492 which does not make `DenseIntOrFPElementsAttr` generic.
~Super stacked PR~ Unstacked
> dialects: (builtin) make DenseIntOrFPElementsAttr a TypedAttribute

- tests/filecheck/dialects/fsm/fsm_invalid.mlir
- tests/filecheck/runner/factorial.mlir
- tests/filecheck/runner/with-wgpu/global_id_inc.mlir
- tests/filecheck/transforms/function-constant-pinning.mlir
- xdsl/dialects/arith.py
- xdsl/dialects/builtin.py
- xdsl/irdl/constraints.py
- xdsl/irdl/declarative_assembly_format_parser.py
- xdsl/parser/attribute_parser.py
- xdsl/printer.py
Experiment in using Constraint variables to grab a type from an attribute, and an example of using this for `arith.constant`.
Unsure if this a good idea or cooking too hard.
Edit: I also couldn't really figure out how `TypedAttribute` worked, and was not sure if the functionality could be reused (I have use cases in mind where the associated type would not be a parameter)
> core: introduce TypedAttributeConstraint

- tests/filecheck/dialects/arm/test_ops.mlir
- xdsl/dialects/arm/__init__.py
- xdsl/dialects/arm/assembly.py
- xdsl/dialects/arm/ops.py
- xdsl/xdsl_opt_main.py
Add a mov op that moves data from source to destination
> dialects (arm): add mov op

- flake.lock
- flake.nix
Nixpkgs ruff lags slightly behind pip's `ruff`. At least when using `nix-ld` on my system, pip's ruff runs fine so lets just use that.
> installation: (nix) Update flake and remove ruff

- tests/filecheck/dialects/arm/test_ops.mlir
- xdsl/dialects/arm/__init__.py
- xdsl/dialects/arm/ops.py
Add mul instruction (https://developer.arm.com/documentation/ddi0597/2024-06/Base-Instructions/MUL--MULS--Multiply-?lang=en).
The mul instruction supports either 2 or 3 operands (in the case of 2, the destination is also treated as the 2nd source). This PR only handles the case where 3 operands are provided, 2 source registers and 1 destination.
> dialects (arm): add mul instruction with 2 source registers

- tests/filecheck/transforms/lower-csl-stencil.mlir
- xdsl/transforms/lower_csl_stencil.py
This resulted in `nan`s after a few iterations.
> bug: (lower-csl-stencil) Zero-out accumulator for full reduction access

- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Went slightly too far on the previous refactor. I think this level of abstraction works well for allowing parse errors to be put in the correct place. PRs for operands, results, and functional-type directives to follow based on this PR.
> core: Move assembly format type parsing to directives

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Adds a results directive to the assembly format. Very similar to the operands directive (#3507) but is not a `FormatDirective`, so must be used as part of a `type` or `functional-type` directive. I wonder if it's worth making a shared subclass for this and the operands directive to deduplicate some code. If so I can rebase on top of that PR.
Stacked on #3516. Draft as this needs more tests
> core: Add results directive

- xdsl/dialects/builtin.py
- xdsl/interpreters/builtin.py
- xdsl/interpreters/ml_program.py
- xdsl/interpreters/onnx.py
As they only work for ranked structures, the shape will always be not None
> dialects: (builtin) shape for DenseIntORFPElementsAttr is always known

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
The extractor used in the assembly parser assumed that all properties/attributes were present. We should instead only propagate the extractors from the property constraint if the property is non-optional or there is a default value. The default_value also needs to be given to the extractor for when the property is not present.
Adds 2 tests to demonstrate this.
> core: Fix extractor logic for optional and default-valued properties

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
Variadic arguments were printing whitespace even if they had nothing to print after the whitespace, resulting in extra unnecessary whitespace appearing. This change moves the whitespace printing after the check to see if there's anything to print.
> core: remove unnecessary whitespace printing in assembly format

- docs/Toy/Toy_Ch3.ipynb
- docs/Toy/toy/dialects/toy.py
- docs/Toy/toy/rewrites/lower_toy_affine.py
- docs/Toy/toy/rewrites/optimise_toy.py
- tests/dialects/test_builtin.py
- xdsl/backend/csl/print_csl.py
- xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
- xdsl/dialects/affine.py
- xdsl/dialects/builtin.py
- xdsl/dialects/cf.py
- xdsl/dialects/varith.py
- xdsl/interpreters/builtin.py
- xdsl/interpreters/linalg.py
- xdsl/interpreters/memref.py
- xdsl/interpreters/ml_program.py
- xdsl/interpreters/onnx.py
- xdsl/interpreters/riscv.py
- xdsl/transforms/canonicalization_patterns/cf.py
- xdsl/transforms/convert_stencil_to_csl_stencil.py
- xdsl/transforms/csl_stencil_bufferize.py
- xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
- xdsl/transforms/linalg_to_csl.py
- xdsl/transforms/linalg_transformations.py
To prepare for the change of internal data representation, this PR makes the actual data of the attribute a private attribute. Everthing is accessed with the getters `get_attrs` (IntegerAttr, ...) and `get_values` (int, float).
The check whether the dense is set by a scalar is pretty common, so i included an additional helper function for that as well
> dialects: (builtin) DenseIntOrFPElementsAttr: make data private and use getters instead

- tests/dialects/test_dialects.py
- tests/filecheck/dialects/irdl/cmath_irdl_stub.py
- xdsl/interpreters/irdl.py
Fixes #3527
Stacked but can be unstacked
> interpreters: (irdl) generate better op name

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
Managed to miss the test for when there are no variadic/optional operands or results, and of course it turns out that this case is completely broken.
Actual functionality change is 3 characters.
> core: fix (and test) operands/results directives with no variadics

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Adds the functional-type directive, which takes two typeable directives as input.
The key difficulty here was dealing with the results, which are usually surrounded by parentheses but don't have to be if there is exactly one result.
Still a draft as this needs more tests, also stacked on #3516.
> core: add functional-type directive

- xdsl/dialects/builtin.py
- xdsl/utils/comparisons.py
This flips the dependency of the two files, I'd like to add some more helpers to the utils one for use in `builtin.py`.
> dialects: (builtin) move value range helper definitions to utils

- tests/utils/test_comparisons.py
- xdsl/utils/comparisons.py
I'm not 100% sure of my understanding of the contract of i0 and other width-0 integer types, but some logic I'm going to open a PR for soon depends on this not crashing and being explicitly stated.
> core: fix bitwidth 0 value range

- tests/filecheck/dialects/arith/canonicalize.mlir
- tests/interactive/test_app.py
- xdsl/dialects/arith.py
- xdsl/transforms/canonicalization_patterns/arith.py
Adds two canonicalization patterns to `arith.muli`
The first checks if the left hand side is a constant 1, and removes the multiplication if so.
The second reverses the order of arguments if the right hand side is a constant and the left isn't, and folds the operation if both are constants.
This likely has some merge conflicts with the stuff @superlopuh is doing.
I also had to modify a test for the interactive mode, would appreciate a review on that part.
> dialects: (arith) add muli canonicalization

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/constraints.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Sort of a revert of #3416, but I believe this fixes the underlying problem.
Changes range constraint inference so that passing in a length is optional. The rationale for this is that the length of operands is always known, but the length of results is never known (as they can always be omitted). Similarly updates the `can_infer` function.
Probably needs a test of something. :shrug:
> core: allow result variadic inference

- tests/filecheck/dialects/arith/canonicalize.mlir
- xdsl/dialects/arith.py
- xdsl/transforms/canonicalization_patterns/arith.py
Adds cmpi canonicalization patterns for when the two operands are the same ssa value.
> dialects: (arith) add Cmpi canonicalization

- tests/filecheck/backend/csl/print_csl.mlir
- tests/filecheck/dialects/csl/ops.mlir
- tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
- tests/filecheck/transforms/lower-csl-stencil.mlir
- xdsl/backend/csl/print_csl.py
- xdsl/dialects/csl/csl.py
i6 and friends are signless, meaning that they are bitpatterns that don't have an inherent value. When printing CSL, we currently take the raw data of the IntegerAttr, but it seems like that's not valid for task identifiers, which are positive. This PR changes the printer to always print the unsigned version of the number, and adds a test case to the CSL filecheck.
> dialects: (csl) handle negative-valued task ID representation

- README.md
Adds missing documentation to #3450
> documentation: add experimental features flag guide to README

- tests/filecheck/dialects/arith/canonicalize.mlir
- tests/filecheck/dialects/csl/csl-canonicalize.mlir
- tests/interactive/test_app.py
- xdsl/dialects/arith.py
- xdsl/transforms/canonicalization_patterns/arith.py
Moves constants to the right for an addi operation, similar to what #3557 did for muli. Also replaces `AddImmediateZero` by `AddiIdentityRight`, which removes constant zeros on the right of an addition instead of the left of an addition like the previous pattern did.
Updates interactive tests (and driveby fixes the constant zero being given the SSA value name %two in this test).
> dialects: (arith) add addi constant propagation

- tests/filecheck/dialects/bufferization/bufferization_ops.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/bufferization/ops.mlir
- xdsl/dialects/bufferization.py
Fixes #3489 
In order to make `materialize_in_destination` compatible with mlir, it needs to be able to take a memref type as the destination. However, in mlir there must be no result if the destination is a memref and so the result here must be optional. This causes a further problem in giving the assembly format which I am yet to solve.
Next steps:
> dialects: (bufferization) fix materialize_in_destination

- xdsl/transforms/mlir_opt.py
Stacked PRs:
* #3540
* #3539
* #3538
* __->__#3537
--- --- ---
`PatternRewriter` should only be used for rewrite patterns.
> transforms: use Rewriter instead of PatternRewriter in mlir-opt

- tests/interactive/test_app.py
- xdsl/interactive/app.py
Fixes crash when switching theme caused by a textual update. Also adds a test to catch this in the future.
> interactive: fix dark mode

- tests/dialects/test_builtin.py
- xdsl/dialects/builtin.py
These helper functions will help us deal with dense representations of values.
> dialects: (builtin) add PackableType and StructPackableType

- tests/filecheck/lit.cfg
I copied the approach in https://github.com/llvm/llvm-project/blob/69227a11fe1d00b2fc6f93b2a985abbe888d0876/bolt/test/lit.cfg.py#L55
> CI: set maxIndividualTestTime in lit cfg

- tests/interactive/test_rewrites.py
- xdsl/interactive/rewrites.py
Slight refactor to `get_all_possible_rewrites` to not be quite so eager in walking the module lots of times.
> interactive: small refactor

- xdsl/transforms/individual_rewrite.py
> transformations: (apply-individual-rewrite) give more context in error message [NFC]

- tests/test_printer.py
- xdsl/dialects/builtin.py
- xdsl/printer.py
To allow for printing floats that are not `FloatAttrs` but the type is known (such as for bytes-backed `DenseIntOrFPElementsAttrs`), this changes the `print_float` implementation to accept raw floats with a known type.
> core: split print_float into print_float and print_float_attr

- tests/filecheck/dialects/scf/unregistered.mlir
- xdsl/traits.py
This PR:
- Fixes the implicit addition of a terminator when the last operation is an (allowed) unregisted operation
- Adds a filecheck test for the above
Fixes #3325
> core (traits): Fix implicit terminator when last op is unregistered

- xdsl/transforms/individual_rewrite.py
> transformations: (apply-individual-rewrite) improve error message

- bench/parser/bench_lexer.py
- tests/test_lexer.py
- tests/test_parser.py
- xdsl/ir/core.py
- xdsl/irdl/declarative_assembly_format_parser.py
- xdsl/parser/affine_parser.py
- xdsl/parser/attribute_parser.py
- xdsl/parser/base_parser.py
- xdsl/parser/core.py
- xdsl/printer.py
- xdsl/utils/lexer.py
- xdsl/utils/mlir_lexer.py
A cleanup PR renaming some things, I did it in two steps to make the diff smaller on the previous PR.
Note stacked PR.
> core: rename MLIR-specific lexing constructs

- pyproject.toml
- xdsl/parser/affine_parser.py
- xdsl/parser/attribute_parser.py
- xdsl/parser/core.py
Small bit of cleanup.
Note stacked PR.
> misc: hide base_parser, and avoid circular imports in parser files

- tests/interactive/test_app.py
- xdsl/interactive/app.py
I was really struggling to debug this, but from what I can understand the `child_pass_pipeline` was ending up with duplicate passes because `self.pass_pipeline` shouldn't have been added. 
I'm not 100% this is the correct fix as I didn't manage to work out what everything did and why.
> interactive: do not auto_expand passes_list

- tests/dialects/test_builtin.py
- xdsl/dialects/builtin.py
- xdsl/interpreters/utils/ptr.py
This PR adds the `CompileTimeFixedBitwidthType` to represent values that have a fixed bitwidth and are thus packable, but the bitwidth may not be known until compile time.
The new dependency graph now looks like the following: https://is.gd/q5N7Dx
> dialects: (builtin) add CompileTimeFixedBitwidthType

- tests/filecheck/transforms/convert-stencil-to-csl-stencil.mlir
Revert part of #3584 that removed parts of a filecheck by accident.
> minor: (convert-stencil-to-csl-stencil) Adding accidentally removed filecheck back in

- xdsl/dialects/func.py
This PR:
- uses the declarative assembly format for `func.call` made possible by `functional-type` #3517
> dialects (func): Use assembly format in `func.call` operation

- .coveragerc
- Makefile
This PR:
- Moves coverage options from the `Makefile` to `.coveragerc` and adds the [`ignore_errors`](https://coverage.readthedocs.io/en/latest/config.html#report-ignore-errors) option
- Adds a `coverage-clean` target and lets the coverage module to erase the produced files from a coverage run
- Removes the `TESTS_COVERAGE_FILE` env variable as this is only used in a target to avoid name collision of coverage files; for all purposes using the common prefix as enforced by `COVERAGE_FILE` is enough to make things work uniformly across targets
I would have loved to [move](https://coverage.readthedocs.io/en/latest/config.html#sample-file) the `.coveragerc` configuration to `pyproject.toml`, but it seems that `pytest-cov` does not support it yet.
> misc (Makefile): Update coverage handling in Makefile

- xdsl/dialects/riscv_func.py
- xdsl/dialects/utils/format.py
This PR:
- uses the declarative assembly format for `riscv_func.call` made possible by `functional-type` #3517 
- removes unused utility methods for generic printing/parsing of the above since there are no users for them as a result of the above
Also discussed in #3618
> dialects (riscv_func): Use assembly format for `riscv_func.call` operation

- tests/dialects/test_builtin.py
- xdsl/dialects/builtin.py
the current flow of creating dense attrs is the following:
`parse -> int -> IntAttr -> normalize -> IntAttr -> int -> bytes`
this PR changes the normalization to work on ints to get the following:
`parse -> int -> normalize -> int -> bytes`
which simplifies things somewhat and should improve performance significantly for larger arrays
> dialects: (builtin) apply normalization on ints, not IntAttrs

- Makefile
This PR:
- Removes `export` from `UV_PROJECT_ENVIRONMENT`, according to [here](https://stackoverflow.com/questions/2838715/makefile-variable-initialization-and-export?noredirect=1&lq=1), its function is rather peculiar
- Adds a missed phony target
My issue is that doing:
1) `VENV_DIR=.vevn make venv`
2) `source .venv/bin/activate`
3) `make tests`
issues the following warning:
> warning: `VIRTUAL_ENV=.venv` does not match the project environment path `venv` and will be ignored
and leads to failed tests (cannot find `riscemu`), as `uv run` according to its documentation will create a venv:
> When used in a project, the project environment will be created and updated before invoking the command.
> misc (Makefile): Fix custom `venv` treatment in Makefile

- tests/dialects/test_arith.py
- uv.lock
- xdsl/dialects/arith.py
> dialects: (arith) add truncation option to ConstantOp

- tests/interactive/test_app.py
- tests/interactive/test_rewrites.py
- uv.lock
- xdsl/interactive/app.py
- xdsl/interactive/rewrites.py
- xdsl/transforms/individual_rewrite.py
It's time to make this part of the codebase a bit more extensible and robust, as we will be reusing it for some scheduling exploration. As a first step, this PR changes the rewrite infrastructure to get the available patterns on the operation lazily, instead of by scanning all ops of all dialects.
> transformations: (apply-individual-rewrite) lazily find canonicalization patterns

- tests/interactive/test_app.py
- tests/interactive/test_rewrites.py
- xdsl/interactive/get_all_available_passes.py
- xdsl/interactive/rewrites.py
It doesn't seem that this abstraction currently adds anything, both the available pass and pass itself are already immutable and can be reasoned about directly.
> interactive: use individual rewrite pass directly instead of helpers

- tests/utils/test_disjoint_set.py
- xdsl/utils/disjoint_set.py
This is useful in a few places, notably in bufferization.
> misc: add a DisjointSet data structure

- tests/filecheck/dialects/arith/canonicalize.mlir
- tests/interactive/test_app.py
- xdsl/dialects/arith.py
- xdsl/traits.py
- xdsl/transforms/canonicalization_patterns/arith.py
- xdsl/transforms/canonicalization_patterns/cf.py
- xdsl/transforms/canonicalization_patterns/scf.py
- xdsl/transforms/canonicalization_patterns/utils.py
Got bored of implementing various arith canonicalizations that all looked the same, so I've done a bunch of them generically in one go.
I've missed out a fair few methods (shifting operations in particular stand out) where I wasn't sure if the python operation agreed with the mlir operation.
> dialects: (arith) add SignlessIntegerBinaryOperation canonicalization

- tests/dialects/test_func.py
- tests/filecheck/dialects/func/func_invalid.mlir
- xdsl/dialects/func.py
- xdsl/traits.py
This PR:
- Adds support for the `SymbolUserOpInterface` interface and implements it for `func.call`
- Adds tests (pytest and filecheck) of the above
Resolves #3497
> dialects (func): Add SymbolUserOpInterface implementation for `func.call` operation

- xdsl/interactive/passes.py
This actually adds the mlir-opt pass to the condensed list (see commented line 65), this previous implementation did not do that - it did nothing, in fact.
> interactive: add mlir-opt pass to condensed list

- xdsl/transforms/csl_stencil_bufferize.py
`csl_stencil.AccessOp`s can read directly from memrefs underlying any `bufferization.to_tensor` passed into them.
Currently, in the presence of several buffers (ie, stencil fields translated to memrefs at this stage), all but the main buffer will have intermediate `bufferization.to_tensor` ops, which creates problems in lowering. The AccessOps can instead work directly off of the underlying memrefs.
> transformations: (csl-stencil-bufferize) AccessOp to read to_tensor's underlying memref

- xdsl/interactive/app.py
removes unnecessary variable passed to `get_pass_arguments` function to improve readability.
> interactive: remove unused spec variable from `get_pass_arguments` function 

- tests/filecheck/dialects/builtin/module.mlir
- tests/test_mlcontext.py
- tests/test_printer.py
- xdsl/context.py
- xdsl/parser/core.py
> core: Parse `module` correctly when `allow-unregistered-dialect` is set

- tests/filecheck/dialects/func/func_ops.mlir
- xdsl/dialects/utils/format.py
There is a bug when we want to print a single output parameter with attributes - it still needs to be enclosed in braces.
> core: fix attributes to func outputs

- tests/filecheck/projects/riscv-backend-paper/bottom_up_f32.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up_f64.mlir
There's still a bit of work to do on the f32 front, this PR just splits the test file, and removes erroneous f32 mentions from the f64 kernels.
> testing: split bottom_up into f32 and f64 kernels

- tests/filecheck/projects/riscv-backend-paper/bottom_up_f32.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up_f64.mlir
- tests/filecheck/transforms/memref_streamify.mlir
- xdsl/transforms/memref_streamify.py
There's no point in streaming 0D memrefs, it costs more to set up the streaming registers. In the future we might want to canonicalize away the 0D memrefs on memref_stream operations to loads/stores and generic on scalars, which will be lowered to registers.
Note stacked PR.
> transformations: (memref-streamify) don't streamify 0D memrefs

- xdsl/interpreters/__init__.py
> interpreter: sort interpreter functions registering

- tests/pattern_rewriter/test_pattern_rewriter.py
- xdsl/pattern_rewriter.py
Stacked PRs:
* #3683
* __->__#3682
* #3681
--- --- ---
> core: Delete properly regions in pattern rewriter

- tests/filecheck/mlir-conversion/with-mlir/mlir_opt_fail.mlir
- xdsl/transforms/mlir_opt.py
We currently have two statements that can raise an error when calling out to `mlir-opt`, one for errors the executable raises, the other for parsing in xDSL, these should be reported separately.
> transformations: (mlir-opt) separate mlir-opt pass errors

- docs/marimo/linalg_snitch.py
- tests/interpreters/test_scf_interpreter.py
- tests/test_interpreter.py
- xdsl/interpreter.py
CombinedListener or CombinedListeners?
> interpreter: support a tuple of listeners in Interpreter

- xdsl/rewriter.py
Stacked PRs:
* #3705
* #3704
* #3703
* #3702
* __->__#3701
--- --- ---
These methods were deprecated for a while
> core: Remove deprecated methods in Rewriter

- docs/Toy/toy/frontend/ir_gen.py
- docs/Toy/toy/rewrites/lower_toy_affine.py
- tests/test_op_builder.py
- xdsl/backend/riscv/prologue_epilogue_insertion.py
- xdsl/builder.py
- xdsl/dialects/irdl/pyrdl_to_irdl.py
- xdsl/frontend/jaxpr/__init__.py
Stacked PRs:
* #3705
* #3704
* #3703
* __->__#3702
* #3701
--- --- ---
The constructors `after`, `before`, `at_start`, and `at_end` are removed
as users should use the equivalent `InsertPoint` constructors instead.
These constructors are currently preventing the `Rewriter` to inherit
`Builder`.
> core: Remove some constructors from `Builder`

- tests/dialects/test_builtin.py
- xdsl/dialects/builtin.py
This is useful for `DenseArrayBase`, and will be useful for `DenseIntOrFPElementsAttr` once that migrates to be backed by bytes. #3623
> dialects: (builtin) add unpack and iter_unpack to IntegerAttr and FloatAttr

- xdsl/transforms/test_lower_linalg_to_snitch.py
This was used for the paper at some point, but is now unnecessary.
> transformations: (lower-linalg-to-snitch) remove LINALG_SNITCH_OPTIMIZATION_PASSES [NFC]

- tests/interpreters/test_shaped_array.py
- xdsl/interpreters/shaped_array.py
> interpreter: add type property to ShapedArray

- docs/marimo/linalg_snitch.py
This makes no difference in the code/editor view, and is prettier in the full-screen view.
After:
https://static.marimo.app/static/pr-57qe
> documentation: (marimo) use default code editor for displaying assembly

- tests/dialects/test_builtin.py
- xdsl/dialects/builtin.py
Similar to the implementation for DenseArrayBase in #3706
> dialects: (builtin) DenseIntOrFPElementsAttr: add iterators for values and attrs

- xdsl/backend/csl/print_csl.py
to become unaffected by the representation changes
note: stacked on #3715
> backend: (csl) use iter_attrs method for DenseIntOrFPElementsArray

- xdsl/transforms/memref_stream_interleave.py
When I initially implemented this pass, I assumed that it was better to err on the side of caution, to take the smallest factor above 3. In practice, this isn't the best approach, as a factor of 4 is only good in the scenario with no function cache misses, and it's a safer bet to take bigger values if possible. We also learned from the Snitch backend paper experiments that the register pressure never goes close to the limit for the kernels we care about, so this should not be that risky.
My understanding is that this change is what @zero9178 implemented in Quidditch already.
I'm currently working on automatically pruning the space of possible values, and merging this PR would help keep the logic relatively simple, while sharing some helpers between this heurist-based pass, and the new …
> transformations: (memref-stream-interleave) always take bigger factor

- tests/interactive/test_app.py
- tests/interactive/test_get_all_available_passes.py
- xdsl/interactive/app.py
- xdsl/interactive/get_all_available_passes.py
- xdsl/interactive/passes.py
This part of the code was written when passes were not yet immutable, so it was important to be able to reinitialize them each time. Now that they are immutable, we can store them directly and avoid the initialization work.
I didn't want to migrate everything in one go, but the tree is still in terms of class + spec pairs, once this PR is merged I can open the PR migrating that part of the codebase.
> interactive: store passes in app instead of class+spec tuples

- tests/interactive/test_app.py
- tests/interactive/test_get_all_available_passes.py
- tests/interactive/test_rewrites.py
- xdsl/interactive/app.py
- xdsl/interactive/get_all_available_passes.py
- xdsl/interactive/passes.py
- xdsl/interactive/rewrites.py
Same deal as #3723, we used to need the spec due to potential mutability, now don't need it.
> interactive: AvailablePass now has either a pass type or instance, no spec

- tests/interactive/test_add_arguments_screen.py
- xdsl/interactive/add_arguments_screen.py
- xdsl/interactive/app.py
The main app should be as small as possible, with each screen/view encapsulating logic. Now the AddArguments screen has a contract, the user passes the type to add arguments to, and the screen returns a valid pass or None, depending on what the user did.
Now the screen validates the pass before letting the user enter, and has better error handling during validation, fixing a couple of crashing behaviours.
> interactive: move pass parsing logic to AddArgumentsScreen

- .github/workflows/pythonpublish.yml
The virtual environment was missing from the CI
> CI: Create missing virtual enviroment in the publish job

- .github/workflows/ci-core.yml
- .github/workflows/ci-lockfile.yml
- .github/workflows/ci-notebooks.yml
- .github/workflows/ci-pyright-fails.yml
- .github/workflows/code-formatting.yml
- .github/workflows/jupyterlite.yml
- .github/workflows/pythonpublish.yml
- .github/workflows/remake-lockfile.yml
- .github/workflows/update-lockfile-bot.yml
- Makefile
- setup.py
- uv.lock
- xdsl/__init__.py
UV now supports dynamic versions, by ommitting them from the lockfile! No more need for our workaround.
https://github.com/astral-sh/uv/pull/10622
After this PR is merged, all xDSL contributors must update to uv version 0.5.20 or higher.
> CI: remove version override in uv

- tests/filecheck/dialects/arm/test_ops.mlir
- xdsl/dialects/arm/__init__.py
- xdsl/dialects/arm/ops.py
Add ARM cmp (register) instruction, for comparing values in registers.
> dialects (arm): Add CmpRegOp instruction

- tests/test_op_builder.py
- xdsl/rewriter.py
Stacked PRs:
* #3705
* #3704
* __->__#3703
--- --- ---
`BlockInsertPoint` acts the same as `InsertPoint`, but for blocks.
Its equivalent in MLIR is `Block::iterator`.
> core: Add BlockInsertPoint to simplify the builder API

- tests/test_rewriter.py
- xdsl/builder.py
- xdsl/pattern_rewriter.py
- xdsl/rewriter.py
Stacked PRs:
* #3705
* __->__#3704
* #3703
--- --- ---
This factors out quite a few methods in the `Builder`, `Rewriter`,
and `PatternRewriter`.
> core: Refactor some methods using BlockInsertPoint

- tests/pattern_rewriter/test_pattern_rewriter.py
- tests/test_op_builder.py
- tests/test_rewriter.py
- xdsl/backend/riscv/lowering/convert_riscv_scf_to_riscv_cf.py
- xdsl/builder.py
- xdsl/pattern_rewriter.py
- xdsl/rewriter.py
- xdsl/transforms/convert_scf_to_cf.py
Stacked PRs:
* __->__#3705
* #3704
* #3703
--- --- ---
> core: Deprecate methods that should be using BlockInsertPoint

- tests/test_traits.py
- tests/utils/test_type.py
- xdsl/traits.py
- xdsl/utils/type.py
This PR:
- Adds the `SameOperandsAndResultType` trait
- Tests of the above
A [few](https://github.com/llvm/llvm-project/blob/539b15b41a6a01017c0a555e89b7d2b62ba194d2/mlir/test/IR/traits.mlir#L41) examples of this being tested in upstream MLIR.
> core: (traits) Add `SameOperandsAndResultType` trait

- xdsl/transforms/convert_stencil_to_csl_stencil.py
Makes the doc comment more localized and is rendered better in the online doc (upcoming).
> documentation: move num_chunks doc comment in ConvertApplyOpPattern

- xdsl/dialects/experimental/fir.py
- xdsl/dialects/riscv.py
- xdsl/dialects/riscv_snitch.py
- xdsl/dialects/x86/ops.py
- xdsl/transforms/lower_snitch.py
Makes doc comments prettier and improves rendering in online docs (upcoming).
> documentation: code block in doc comments

- docs/guides/mlir_interoperation.md
- mkdocs.yml
- pyproject.toml
- scripts/gen_ref_pages.py
- uv.lock
Excludes:
- `__main__.py` files
- `_`-prefixed files
- `xdsl/irdl/error.py` as it contains a function called `error` which confuses the doc mechanism for some reason
- `xdsl/ir/*.py` as we've already got curated docs for these files
Still needs a bit of cleanup and to merge the code changes separately.
The big question for this PR is whether we want to commit these files and, if not, how do we review them?
> documentation: automatically generate documentation from all .py files in xDSL

- tests/filecheck/dialects/llvm/example.mlir
- xdsl/dialects/llvm.py
> dialects: (LLVM) Add bitcast op

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
The `attr-dict` directive currently prints attributes/properties which are set to the default value, which is not the correct behaviour.
> core: (assembly-format) omit default attributes/properties from attr-dict directive

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/constraints.py
- xdsl/irdl/declarative_assembly_format_parser.py
This would probably make #3698 obsolete, as it covers the one use case of that PR that I can think of. This is a bit more of an involved change but I feel that there are some interesting a powerful things you could do with this in the future.
Would likely need a few more tests if we want to go with this.
> core: Introduce integer constraints

- README.md
Small PR - Commit bba4671d32019aee7918d51db79e8ca94e657704 moved `mlir_interoperation.md`. This PR adjusts sources to changes. It also fixes a typo along the way.
> documentation: update MLIR interoperation reference

- tests/filecheck/dialects/builtin/module.mlir
- xdsl/dialects/builtin.py
Instead of printing two spaces, print one.
> dialects: (builtin) fix formatting of module printing with attributes

- docs/marimo/mlir_winter_school/1_mlir_ir.py
The previous example made it look like the key names were type. This makes it very clear they are arbitrary strings.
> docs: (mlir-winter-school) improve attribute dictionary example

- tests/filecheck/dialects/llvm/arithmetic.mlir
- tests/filecheck/dialects/llvm/example.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/arithmetic.mlir
- xdsl/dialects/llvm.py
Adds the following llvm floating point operations:
- `llvm.fadd`
- `llvm.fsub`
- `llvm.fmul`
- `llvm.fdiv`
- `llvm.frem`
- `llvm.sitofp`
- `llvm.fpext`
Closes #3780 
I also took the liberty to sort the dialect lists alphabetically
> dialects: (llvm) Add a bunch of float methods

- xdsl/dialects/arith.py
- xdsl/dialects/builtin.py
- xdsl/dialects/varith.py
Improves the python typing bounds on the `ContainerOf` constraint.
> core: (ContainerOf) improve python typing

- tests/filecheck/dialects/arith/arith_attrs.mlir
- tests/filecheck/dialects/arith/arith_invalid.mlir
- tests/filecheck/dialects/arith/arith_ops.mlir
- tests/filecheck/dialects/arith/arith_ops_custom.mlir
This PR to de-indents tests by removing the implicitly added `builtin.module`.
@superlopuh I applied my script to similar files within that test subfolder while at it.
As discussed [here](https://github.com/xdslproject/xdsl/pull/3802#discussion_r1934106464).
> tests: Remove module from `arith` filecheck tests

- tests/irdl/test_declarative_assembly_format.py
- xdsl/dialects/builtin.py
Adds a constraint that applies an integer constraint to the value of an integer attribute.
See: https://github.com/xdslproject/inconspiquous/blob/70f923cfe577b7eb48ece03d6f9a597c296cb698/inconspiquous/dialects/gate.py#L237
and https://github.com/xdslproject/inconspiquous/blob/70f923cfe577b7eb48ece03d6f9a597c296cb698/inconspiquous/dialects/qssa.py#L78
for an example of using this. 
I'm unsure if this is the best place for this to live, or if it should be upstreamed at all.
> core: (constraints) add IntAttrConstraint

- tests/filecheck/frontend/passes/desymref.mlir
It's not very clear from the diff, but here are the changes:
1. remove the outer builtin.module and dedent
2. move check lines above inputs
3. move everything to custom syntax
> testing: move frontend desymref test to custom format

- pyproject.toml
- setup.py
Just a bit of simplification. I tried to remove the whole thing but versioneer breaks.
> misc: simplify setup.py

- xdsl/dialects/func.py
> dialects: (func) clean up is_declaration [NFC]

- xdsl/dialects/memref_stream.py
- xdsl/dialects/snitch.py
Turns out that we can use typing_etensions for default values, leeting us have simpler helpers that leverage more advanced type system things.
> misc: use default-valued type elements for constrs

- tests/irdl/test_declarative_assembly_format.py
- xdsl/dialects/builtin.py
Makes every constr method (found with ripgrep `def\ constr`) a classmethod instead of a staticmethod. This is in preparation for adding a default `constr` method to `Attribute` in a future PR.
> core: make all constr methods classmethods

- tests/irdl/test_declarative_assembly_format.py
- xdsl/dialects/builtin.py
- xdsl/dialects/stencil.py
- xdsl/ir/core.py
- xdsl/transforms/memref_to_dsd.py
Stacked on top of #3826 
Adds a `constr` method to `Attribute` which allows the easy construction of `BaseAttr` constraints. The hope here is to move towards having a single interface for generating constraints, instead of interchangably constructing the constraints manually, using `constr` methods, and using `AnyXConstr` type aliases.
> core: add constr method to Attribute

- xdsl/dialects/builtin.py
- xdsl/dialects/csl/csl.py
- xdsl/dialects/csl/csl_stencil.py
- xdsl/dialects/linalg.py
- xdsl/transforms/csl_stencil_bufferize.py
- xdsl/transforms/csl_stencil_to_csl_wrapper.py
- xdsl/transforms/linalg_to_csl.py
- xdsl/transforms/lower_csl_stencil.py
- xdsl/transforms/memref_to_dsd.py
`MemRefType` now has a default generic, so `AnyMemRefType` is unnecessary.
> dialects: (builtin) remove AnyMemRefType

- tests/filecheck/parser-printer/duplicate_attribute_keys.mlir
- xdsl/parser/attribute_parser.py
- xdsl/parser/core.py
This PR:
- Disallows duplicate keys in properties and attribute dictionaries
- Tests of the above
Bumped into this by accident and the tests are similar to https://github.com/llvm/llvm-project/blob/46b1543dc04970719caab0d4f9f65699fea6adbc/mlir/test/IR/invalid-builtin-attributes.mlir#L485
I don't venture often in the parser, so any feedback is welcome.
> core: Disallow duplicate keys in attribute dictionaries

- tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/invalid_ops.mlir
- xdsl/dialects/linalg.py
This adds a hidden region to the linalg.transpose op to ensure correct generic printing
Also changes permutation to a property instead of attribute.
This resolves the transpose op in #2959 
This has now been checked manually, and will be put in ci with #3837 (but for that 3 other ops need to be fixed, PRs incoming...)
> dialects: (linalg) add hidden region to transpose op

- tests/interpreters/test_linalg_interpreter.py
- xdsl/dialects/linalg.py
To enable correct printing of the hidden regions in generic printing.
Resolves pooling in #2959 , will be tested in #3837 
The constructor of these ops had to change to comply with the NamedOpBase constructor ordering of arguments
>  dialects: (linalg) let PoolingOpsBase inherit from NamedOpBase 

- tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/invalid_ops.mlir
- xdsl/dialects/linalg.py
Resolves pooling in https://github.com/xdslproject/xdsl/issues/2959 , will be tested in https://github.com/xdslproject/xdsl/pull/3837
> dialects: (linalg) add hidden region to BroadcastOp

- tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
- tests/interpreters/test_linalg_interpreter.py
- xdsl/dialects/linalg.py
This enables to correct printing of the hidden regions in generic format
Resolves conv ops in #2959, will be tested with #3837
> dialects: (linalg) let ConvOpsBase inherit from NamedOpsBase

- tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
This PR adds generic printing to the mlir conversion filecheck
This will check whether the issues posed in #2959 are correctly resolved, by checking if mlir correctly parses the generic output of xdsl
There are still reminaing issues, solved in the following PRs:
(stacked on: ) #3838, #3839, #3840, #3841
> dialects: (linalg) enable generic printing in mlir conversion filecheck

- tests/irdl/test_declarative_assembly_format.py
- xdsl/dialects/arith.py
- xdsl/dialects/builtin.py
- xdsl/dialects/csl/csl.py
- xdsl/transforms/lower_csl_wrapper.py
`IntegerAttr` and `IntegerAttr.constr()` are sufficient
> dialects: (builtin) remove AnyIntegerAttrConstr

- tests/test_parser.py
- tests/test_traits.py
- xdsl/dialects/accfg.py
- xdsl/dialects/affine.py
- xdsl/dialects/arith.py
- xdsl/dialects/builtin.py
- xdsl/dialects/csl/csl.py
- xdsl/dialects/csl/csl_stencil.py
- xdsl/dialects/csl/csl_wrapper.py
- xdsl/dialects/experimental/air.py
- xdsl/dialects/experimental/fir.py
- xdsl/dialects/experimental/hlfir.py
- xdsl/dialects/llvm.py
- xdsl/dialects/memref.py
- xdsl/dialects/mod_arith.py
- xdsl/dialects/riscv.py
- xdsl/dialects/riscv_func.py
- xdsl/dialects/seq.py
- xdsl/dialects/transform.py
- xdsl/dialects/x86/assembly.py
- xdsl/dialects/x86/ops.py
- xdsl/interpreters/arith.py
- xdsl/interpreters/builtin.py
- xdsl/interpreters/riscv.py
- xdsl/parser/attribute_parser.py
- xdsl/tools/tblgen_to_py.py
- xdsl/transforms/canonicalization_patterns/cf.py
- xdsl/transforms/canonicalization_patterns/csl.py
- xdsl/transforms/canonicalization_patterns/utils.py
- xdsl/transforms/linalg_to_csl.py
s/AnyIntegerAttr/IntegerAttr/g
> dialects: (builtin) remove AnyIntegerAttr

- tests/test_parser.py
- tests/test_printer.py
- xdsl/dialects/builtin.py
- xdsl/dialects/csl/csl.py
- xdsl/interpreters/arith.py
- xdsl/interpreters/builtin.py
- xdsl/parser/attribute_parser.py
- xdsl/printer.py
- xdsl/transforms/canonicalization_patterns/arith.py
- xdsl/transforms/convert_stencil_to_csl_stencil.py
- xdsl/transforms/linalg_to_csl.py
- xdsl/transforms/lower_csl_stencil.py
Adds a default type to `FloatAttr` and removes `AnyFloatAttr` and `AnyFloatAttrConstr`
> dialects: (builtin) remove AnyFloatAttr(Constr)?

- pyproject.toml
Partial revert of 27bf82162f438557520caf3500f8467dae4a016b, which broke downstream installation.
> installation: fix package discovery

- tests/filecheck/parser-printer/graph_region.mlir
- xdsl/utils/exceptions.py
Fix the MultipleSpanParseError to print multiple lines in the error output
> core: Fix multiline error printing

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/constraints.py
When having an attribute constraint variable `T` and a variable `U` that could infer the
variable `T` (for instance `U = Vector<T>`), the constraint `U` would not realize that it can infer `T`.
> core: Fix bug in extractor when having nested variables

- tests/filecheck/parser-printer/invalid_dense_attr.mlir
- xdsl/parser/attribute_parser.py
Because DenseIntOrFPElementsAttrs are backed by `bytes`, there is no need to convert the hex representation to a list of values when creating the attribute. We can directly convert the hex representation to a BytesAttr when constructing the attribute.
This is a lot faster, and gets rid of a lot of code somewhat duplicating the `StructPackable` things we made.
> parser: parse bytes directly into a BytesAttr for DenseIntOrFPElementsAttrs

- tests/backend/riscv/test_register_allocation.py
- tests/backend/riscv/test_register_queue.py
- xdsl/backend/register_queue.py
- xdsl/backend/riscv/register_allocation.py
- xdsl/backend/riscv/riscv_register_queue.py
- xdsl/transforms/riscv_register_allocation.py
In preparation for ARM and x86 backends, this is the first PR towards interface-based, target-agnostic register allocation.
> backend: (riscv) split out register queue interface from implementation

- scripts/gen_ref_pages.py
- xdsl/irdl/error.py
- xdsl/irdl/operations.py
The auto-generated docs website complained about this function with the same name as its module. We actually have a helper for it already on Operation, and can just remove it.
> misc: remove xdsl.irdl.error.error function

- tests/filecheck/dialects/x86/x86_assembly_emission.mlir
- xdsl/backend/assembly_printer.py
- xdsl/dialects/arm/__init__.py
- xdsl/dialects/arm/assembly.py
- xdsl/dialects/arm/ops.py
- xdsl/dialects/riscv.py
- xdsl/dialects/x86/assembly.py
- xdsl/dialects/x86/ops.py
Now that we're adding more backend infrastructure, I think it would make sense to unify some of the helpers, and iterate on the logic. This PR introduces an AssemblyPrinter class that holds the helpers previously copy/pasted into each of the riscv, x86, and ARM dialects.
> backend: unify assembly printing helpers in AssemblyPrinter

- xdsl/dialects/builtin.py
- xdsl/dialects/mpi.py
- xdsl/dialects/stencil.py
- xdsl/interpreter.py
- xdsl/ir/core.py
- xdsl/irdl/attributes.py
- xdsl/irdl/operations.py
- xdsl/utils/hints.py
Stacked PRs:
* __->__#3836
* #3835
--- --- ---
There was a lot of inconsistencies in the typing of functions that are
using the type to constraint conversion. Having a shorthand makes this
more explicit.
> core: Add shorthand type for types that can be converted to IRDL

- pyproject.toml
Reopens #3848, which fixes a regression introduced by #3815, and partially fixed with #3847.
While the issue is fixed on most installations with the other fix PR it breaks on some systems, and when a `site` folder is present after generating the docs website locally.
We tested this change with @georgebisbas today, on whose linux machine xDSL cannot currently be installed, and works after applying the changes in this PR.
> installation: specify find

- tests/backend/riscv/test_register_queue.py
- tests/filecheck/backend/riscv/register-allocation/frep.mlir
- tests/filecheck/backend/riscv/register-allocation/generic.mlir
- xdsl/backend/riscv/riscv_register_queue.py
- xdsl/dialects/riscv.py
We currently use the same indices which makes them difficult to distinguish and harder to spot.
> backend: (riscv) use separate indices for j and fj registers

- docs/marimo/ir_gen.py
Stacked PRs:
* #3884
* #3883
* #3882
* __->__#3881
* #3886
--- --- ---
> docs: Add IR generation notebook

- tests/dialects/test_x86.py
- tests/filecheck/dialects/x86/x86_registers_invalid.mlir
- xdsl/dialects/x86/register.py
- xdsl/tools/command_line_tool.py
> backend: (x86) Fix register sets test coverage

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Removes a few of the extra classes from the assembly format directives, instead replacing them with methods on the `Directive` class. This should make it simpler to implement custom directives in the future
> core: flatten assembly format class hierarchy

- xdsl/dialects/builtin.py
- xdsl/dialects/experimental/air.py
- xdsl/dialects/pdl.py
- xdsl/parser/attribute_parser.py
Not needed due to default generics.
> dialects: (builtin) remove AnyArrayAttr

- tests/filecheck/dialects/linalg/linalg_ops.mlir
- xdsl/dialects/linalg.py
> dialects: (linalg) fix `linalg.matmul` to correctly store integer arg types

- tests/backend/riscv/test_preallocated.py
- tests/backend/riscv/test_utils.py
- tests/dialects/test_riscv.py
- tests/dialects/test_x86.py
- tests/interpreters/test_riscv_cf_interpreter.py
- tests/interpreters/test_riscv_debug_interpreter.py
- tests/interpreters/test_riscv_emulator.py
- tests/interpreters/test_riscv_interpreter.py
- tests/interpreters/test_riscv_scf_interpreter.py
- tests/interpreters/test_riscv_snitch_interpreter.py
- tests/interpreters/test_snitch_stream_interpreter.py
- xdsl/backend/register_type.py
- xdsl/backend/riscv/lowering/convert_arith_to_riscv.py
- xdsl/backend/riscv/lowering/convert_arith_to_riscv_snitch.py
- xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
- xdsl/backend/riscv/lowering/convert_snitch_stream_to_snitch.py
- xdsl/backend/riscv/lowering/utils.py
- xdsl/dialects/arm/register.py
- xdsl/dialects/riscv.py
- xdsl/dialects/riscv_func.py
- xdsl/dialects/riscv_snitch.py
- xdsl/dialects/x86/register.py
- xdsl/transforms/convert_memref_stream_to_snitch_stream.py
- xdsl/transforms/convert_ptr_to_riscv.py
- xdsl/transforms/convert_riscv_scf_for_to_frep.py
- xdsl/transforms/inline_snrt.py
- xdsl/transforms/riscv_scf_loop_range_folding.py
The .unallocated was a kind of premature optimisation, I'm not sure that it makes sense any more, and it makes the code more difficult to read IMO.
> backend: default register type constructor returns unallocated register

- tests/backend/riscv/test_register_queue.py
- xdsl/backend/riscv/riscv_register_queue.py
This is the only part of the `RiscvRegisterQueue` that mixes the two register types, this split is necessary to make the more fundamental split into two register queues.
> backend: (riscv) split out reserved int and float registers in regalloc

- xdsl/dialects/x86/ops.py
The printer should not emit code like ```rr.add```, but our Python filecheck implementation only checks substrings (even when the dedicated knob is on). I fix the emitter to make it usable but a long-term solution is either to fix the Python filecheck reimplementation or to py-package LLVM filecheck.
> bug: (x86) always remove the register/memory prefix from the emitted assembly

- docs/marimo/mlir_ir.py
Minor nits and rewording of sentences.
> documentation: Fix nits on the first marimo notebook

- pyproject.toml
Removes the following error:
> PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"
> CI: set pytest asyncio_default_fixture_loop_scope

- tests/backend/test_register.py
- xdsl/backend/register_type.py
- xdsl/backend/riscv/riscv_register_queue.py
- xdsl/dialects/arm/register.py
- xdsl/dialects/riscv.py
- xdsl/dialects/x86/register.py
It's nice to have a check to make sure that our fake infinite registers don't clash with the real ones.
> backend: add `infinite_register` class method to RegisterType

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
I have a feeling that our template is too long, and that people just see a wall of text and zone out, when there are actually only two things to pay attention to: 1. read the guidelines if you haven't, 2. add a motivation. We can easily do the labels, reviewers and assignees as maintainers.
> misc: shorten PR template

- docs/mlir_interoperation.ipynb
- tests/filecheck/lit.cfg
- xdsl/tools/xdsl-opt
I tested this locally by installing via a different path, seems like this is just unused at this point.
> misc: remove xdsl-opt file

- tests/filecheck/projects/libxsmm/x86_matmul_kernel.mlir
The use case contained 4 bugs according to computing a matmul:
1- Bad order of vfmadd parameters (AT&T syntax instead of Intel syntax)
2- vfmadd231pd instead of vfmadd231ps (double precision instead of single precision)
3- Incosistency between B dimensions (4x2) and C dimensions (4x4)
4- (performance bug, avoidable dependency) Load all B columns in the same register
> bug: (libxsmm) fix the little matmul use case

- tests/dialects/test_builtin.py
- tests/filecheck/mlir-conversion/with-mlir/dialects/builtin/vector_type.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/vector/ops.mlir
- tests/filecheck/parser-printer/builtin_attrs.mlir
- xdsl/dialects/arith.py
- xdsl/dialects/builtin.py
- xdsl/parser/attribute_parser.py
- xdsl/printer.py
> dialects: (builtin) fix VectorType scalable dimension representation

- tests/dialects/test_stencil.py
Is there a need for this test any more?
I'm not sure what it's testing, it seems to be more of an example of the API needed to represent a stencil in Python, but I'm not sure whether this is useful anymore. There's a TODO comment to move to documentation, but something tells me it can happily not ever happen if no-one's working on the stencil project any more.
> testing: (stencil) remove stencil printing test

- tests/backend/riscv/test_preallocated.py
- tests/dialects/test_riscv.py
- tests/interpreters/test_riscv_emulator.py
- tests/interpreters/test_riscv_interpreter.py
- tests/interpreters/test_riscv_scf_interpreter.py
- xdsl/backend/riscv/lowering/convert_arith_to_riscv.py
- xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
- xdsl/backend/riscv/lowering/convert_snitch_stream_to_snitch.py
- xdsl/dialects/riscv.py
- xdsl/transforms/convert_ptr_to_riscv.py
- xdsl/transforms/convert_riscv_scf_for_to_frep.py
- xdsl/transforms/riscv_scf_loop_range_folding.py
If I remember correctly, this was done as a kind of defensive API measure to make sure that users of the riscv operations knew to assign to the result register an appropriate value. I no longer think that the benefits of explicit result values outweigh the cost of verbose code everywhere. I'm currently refactoring register types, and I'd like to change the init and parsing situation, where it will no longer make sense for the default init with no parameters to create an unallocated register, so the API for those is about to change towards something less ergonomic, which will make the no default parameter situation worse.
> backend: (riscv) make rd unallocated by default

- tests/dialects/test_x86.py
- tests/filecheck/backend/x86/convert_func_to_x86.mlir
- tests/filecheck/dialects/x86/x86_assembly_emission.mlir
- tests/filecheck/dialects/x86/x86_ops.mlir
- tests/filecheck/projects/libxsmm/x86_matmul_kernel.mlir
- xdsl/backend/x86/lowering/convert_func_to_x86_func.py
- xdsl/dialects/x86/ops.py
Addresses [this issue](https://github.com/xdslproject/xdsl/issues/3937)
> bug: (x86) memory-to-register mv operation should not take two operands

- tests/pattern_rewriter/test_pattern_rewriter.py
- tests/test_rewriter.py
One more steps towards removing conftest, two to go.
> testing: remove `assert_print_op` from rewriters tests

- tests/backend/riscv/test_preallocated.py
- tests/backend/riscv/test_utils.py
- tests/dialects/test_x86.py
- tests/interpreters/test_riscv_cf_interpreter.py
- tests/interpreters/test_riscv_debug_interpreter.py
- tests/interpreters/test_riscv_interpreter.py
- tests/interpreters/test_riscv_scf_interpreter.py
- tests/interpreters/test_riscv_snitch_interpreter.py
- tests/interpreters/test_snitch_stream_interpreter.py
- xdsl/backend/register_type.py
- xdsl/backend/riscv/lowering/convert_arith_to_riscv.py
- xdsl/backend/riscv/lowering/convert_arith_to_riscv_snitch.py
- xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
- xdsl/backend/riscv/lowering/utils.py
- xdsl/dialects/riscv_func.py
- xdsl/dialects/riscv_snitch.py
- xdsl/transforms/convert_memref_stream_to_snitch_stream.py
- xdsl/transforms/convert_ptr_to_riscv.py
- xdsl/transforms/inline_snrt.py
Two related changes:
- removes the default value of "" for the register name
- replaces previous unallocated register init calls with no args with the dedicated UNALLOCATED constants
This reduces the users of the init API, which I'm slowly refactoring.
> backend: (riscv) use named unallocated registers instead of empty init

- xdsl/dialects/csl/csl.py
- xdsl/dialects/experimental/fir.py
These are currently stopping the docs website from generating correctly.
> misc: escape code in docstrings

- pyproject.toml
This makes the tests behave more like how clients of xDSL would, with the xdsl module in the venv rather than locally available in the current directory.
> testing: use importlib import mode in pytest

- xdsl/ir/core.py
Toy example of using benchmarking to inform performance optimisation.
In this case, we remove indirection from the `clone_without_regions` method on `Operation` to avoid incurring the cost of creating extraneous `OpOperand` and `Successor` dataclasses, which are then only used to construct iterators on a private property of the original class.
Running `python3 benchmarks/microbenchmarks.py OpCreation.operation_clone timeit`
Before: Test OpCreation.operation_clone ran in: 2.44e-06 ± 3.27e-07s
After : Test OpCreation.operation_clone ran in: 2.15e-06 ± 2.75e-07s
(~10% performance uplift for this limited case of a moderately common feature)
> core: remove indirection in operation cloning

- xdsl/ir/core.py
Stacked PRs:
* #3991
* #3990
* #3989
* #3988
* #3987
* __->__#3986
--- --- ---
Move the definition of SSAValue after the definition of Attributes.
> core: Move SSAValue definitions around (NFC)

- pyproject.toml
- uv.lock
When measuring performance, it's nice to be able to get a visualisation of the trace without too many hoops.
This lets users follow the recommended steps in our wiki: https://github.com/xdslproject/xdsl/wiki/Performance
> dependencies: add viztracer and orjson to bench dependency group

- tests/filecheck/dialects/stablehlo/ops.mlir
- xdsl/dialects/stablehlo.py
This PR includes following changes:
1. Add an abstract elementwise binary operations for integer tensor types `IntegerTensorLikeElementwiseBinaryOperation` like https://github.com/xdslproject/xdsl/blob/a072093aa7815d944a6fb97d17d13bcf4777cda4/xdsl/dialects/math.py#L38
2. Replace `AndOp`'s parent class with `IntegerTensorLikeElementwiseBinaryOperation`
3. Add Xor and Or Op 
4. Update on test cases
> dialects: (stablehlo) Add support for xor and op operations

- xdsl/irdl/declarative_assembly_format.py
Makes it more explicit that the variable contains all the state necessary for inference.
> misc: store context as property on ParsingState

- xdsl/irdl/constraints.py
Avoids unnecessary copies and exposes a more efficient membership method.
> misc: ConstraintContext keys properties are abstract sets

- xdsl/irdl/constraints.py
- xdsl/irdl/declarative_assembly_format.py
When inferring, we know which dictionary to look into, same for when we construct the InferenceContext, so we might as well split it. PR-1 to using the ConstraintContext during inference.
> core: split InferenceContext dictionaries

- tests/dialects/test_bufferization.py
- tests/irdl/test_attr_constraint.py
- xdsl/dialects/bufferization.py
- xdsl/dialects/builtin.py
- xdsl/irdl/constraints.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
In a way, both constraint verification and inference are a matching of a query with data, where we come up with assignments for the variables, and bail if a unique assignment is not found, so it makes sense to me to use the same data structure to represent variable assignment in both cases.
> core: use ConstraintContext for inference

- xdsl/dialects/riscv.py
There's no need for the string, the user can create the register themselves, simplifies API.
> backend: (riscv) make LiOp and float binary ops not take str for rd

- xdsl/dialects/x86/ops.py
Avoids spurious register creation, and minimises the init API usage, which I propose changing in a different PR.
> backend: (x86) use named register constants in ops file

- tests/filecheck/dialects/stablehlo/ops.mlir
- xdsl/dialects/stablehlo.py
This PR includes following changes:
1. Add an abstract elementwise binary operations for integer tensor types `IntegerTensorLikeElementwiseUnaryOperation` like https://github.com/xdslproject/xdsl/blob/a072093aa7815d944a6fb97d17d13bcf4777cda4/xdsl/dialects/math.py#L38
2. Add ShiftLeftOp, ShiftRightArithmeticOp, and ShiftRightLogicalOp as integer tensor binary operations
3. Add CountLeadingZerosOp, PopcntOp, NotOp as integer tensor unary operations
4. Update on test cases
> dialects: (stablehlo) Add support for some unary and binary operations

- xdsl/irdl/operations.py
We can reuse the function instances, so there's no need to redefine them for every operation definition.
Slight perf improvement for `make filecheck`, but it's annoyingly close to the margin off error, I look forward to seeing the perf results later. I also have a feeling that it should help pypy's tracing to have only one of each of these functions for all of xDSL, instead of one per op.
> core: reuse field definition functions across op definitions

- tests/backend/riscv/test_register_allocation.py
- tests/backend/riscv/test_register_queue.py
- tests/dialects/test_riscv.py
Trying to minimise the number of uses of the initialiser that takes strings.
> backend: (riscv) use infinite register helper in more tests

- xdsl/xdsl_opt_main.py
This was just annoying me when looking at traces, we pay the cost of the version function even when we're not going to use it (6ms on my laptop).
> misc: make xDSL version getting lazy

- benchmarks/.gitignore
Add gitignore file for profile outputs in response to [comment](https://github.com/xdslproject/xdsl/pull/4008#discussion_r1978074345)
> bench: add gitignore file for profile outputs

- tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
- xdsl/dialects/riscv.py
We want to be specific in the register name whether the register is int or float, this verifier reflects this.
This verifier will be moved to the RegisterType superclass in the next PR.
> backend: (riscv) narrow verifier of float and int infinite register names

- Makefile
This PR:
- Removes the `.asv` prerequisite from the `asv-clean` target since there is no production rule for it ATM (and there shouldn't be one as it is a plain clean operation) because otherwise it causes `make asv-clean` and `make clean` to fail
> misc: (makefile) Remove prerequisites for removing hidden ASV directory

- tests/backend/test_register.py
- tests/dialects/test_riscv.py
- tests/filecheck/dialects/riscv/riscv_registers_invalid.mlir
- tests/filecheck/dialects/x86/x86_registers_invalid.mlir
- xdsl/backend/register_type.py
- xdsl/dialects/arm/register.py
- xdsl/dialects/riscv.py
- xdsl/dialects/x86/register.py
Adds more extensive verification that can be shared by all register types.
> backend: move register type verification from all subclasses to superclass

- tests/filecheck/dialects/riscv/riscv_registers_invalid.mlir
- xdsl/dialects/riscv.py
RISC-V has at least two ways to indicate the standard integer and floating-point registers, with their ABI names and indexed (x0, x1, ..., f0, f1, ...). With this PR, we support both in the assembly format again.
> backend: (riscv) allow x0... and f0... register names

- tests/test_pass_to_arg_and_types_str.py
- xdsl/interactive/add_arguments_screen.py
- xdsl/passes.py
We currently return a string, which doesn't allow the caller to choose whether and how to display the options.
Plenty of work to do still when the interactive project picks back up, but I feel like it's a step in the right direction.
Fixes #1845
> interactive: return structured tuple in get_pass_argument_names_and_types

- Makefile
This PR: 
- Executes all marimo tests and only reports failures at the end.
I encountered this while porting more than one notebook that was in a state of flux, which was a bit annoying.
Resolves #2841
> misc: (makefile) Run all marimo tests and report at the end

- .readthedocs.yaml
This PR sets up readthedocs hosting for our mkdocs docs, meaning we get the best of both worlds:
- docs for each version of xDSL from now on available in a drop-down menu on a platform we don't need to manage (and maybe even for each PR but I haven't tried that yet)
- we control how the docs are generated and structured in MKDocs's API, which is more flexible and modern than the readthedocs default Sphinx
Check it out here:
https://xdsl.readthedocs.io/en/latest/
We definitely want to clean it up and make it nicer before making public announcements but it seems like a big step forwards.
> documentation: deploy docs website to readthedocs

- tests/backend/test_register.py
- tests/dialects/test_riscv.py
- xdsl/backend/register_type.py
The last PR I have planned for the register types themselves, after this onto the register queue, using this indices to keep track of which registers are reserved or available instead of names.
> backend: add from_index method to register

- .github/workflows/ci-mlir.yml
It slows down all the tests, even though we only upload the coverage data for 3.10 currently. This will help test both branches of #3953.
> CI: only collect coverage data for one Python version

- README.md
> documentation: fix commit hash in readme

- tests/backend/riscv/test_register_allocation.py
- tests/backend/riscv/test_register_queue.py
- xdsl/backend/riscv/riscv_register_queue.py
- xdsl/transforms/riscv_register_allocation.py
As a step towards a generic register queue, I wanted to decouple the init from the ABI default available and reserved registers.
> backend: (riscv) RiscvRegisterQueue makes empty queue, add helper

- tests/backend/riscv/test_register_queue.py
- xdsl/backend/riscv/riscv_register_queue.py
One step closer to generic register queue.
> backend: (riscv) use register indices to track available registers

- pyproject.toml
- uv.lock
Inspired by #4072, I don't think we need to be quite so precise on the pre-commit version.
We might want to revisit the other dependencies.
> dependencies: make pre-commit version less strict

- tests/filecheck/transforms/csl-stencil-handle-async-flow-no-args.mlir
- tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
- xdsl/transforms/csl_stencil_handle_async_flow.py
Require free task IDs to be provided explicitly as a list.
> minor: (csl-stencil-handle-async-flow) Provide task ids as list

- tests/dialects/test_vector.py
- tests/filecheck/dialects/vector/vector_fma_res_acc_shape_matching.mlir
- tests/filecheck/dialects/vector/vector_fma_res_acc_type_matching.mlir
- tests/filecheck/dialects/vector/vector_fma_res_lhs_shape_matching.mlir
- tests/filecheck/dialects/vector/vector_fma_res_lhs_type_matching.mlir
- tests/filecheck/dialects/vector/vector_fma_res_rhs_shape_matching.mlir
- tests/filecheck/dialects/vector/vector_fma_res_rhs_type_matching.mlir
- tests/filecheck/dialects/vector/vector_ops.mlir
- tests/filecheck/dialects/vector/vector_pure_ops.mlir
- xdsl/dialects/vector.py
Makes IR prettier. Changed some names to conform to MLIR, so most of the assembly format strings match exactly. We don't have operand renaming so I changed camelCase operand names to snake_case in the format strings.
CC @watermelonwolverine
> dialects: (vector) add assembly format to vector ops

- tests/dialects/test_vector.py
- xdsl/dialects/vector.py
Makes them conform to our code style and MLIR's names.
> dialects: (vector) fix masked operation class names

- tests/filecheck/dialects/stablehlo/attrs.mlir
- tests/filecheck/dialects/stablehlo/invalid.mlir
- tests/filecheck/dialects/stablehlo/ops.mlir
- xdsl/dialects/stablehlo.py
This PR adds the following operations:
* atan2
* cbrt
* ceil
And the attributes:
* comparison_direction
* comparison_type
> dialects: (stablehlo) add more operations

- tests/irdl/test_attr_constraint.py
- xdsl/irdl/constraints.py
For use in dialect and dialect stub generation. Before this change, the default repr prints the class as `<class xdsl.dialects.builtin.IntegerAttr>` or whatever, and now we just print `IntegerAttr`, which won't work for `eval` if you don't already have the class in your context, but will work for our use-cases for now.
> core: add custom repr to BaseAttr and ParamAttrConstraint

- xdsl/utils/dialect_codegen.py
I mixed up StringIO and TextIO
> misc: loosen type restriction in dialect_codegen out parameter

- xdsl/utils/scoped_dict.py
Due to operations that return `None` when interpreted, a ScopedDict can contain `None` values. For those, the current implicit key check does not suffice.
> misc: Add explicit key check in ScopedDict.

- tests/filecheck/dialects/csl/ops.mlir
- tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir
- tests/filecheck/dialects/stencil/stencil_ops.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/ops.mlir
- tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
- tests/filecheck/transforms/csl-stencil-handle-async-flow-no-args.mlir
- tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
- tests/filecheck/transforms/distribute-stencil.mlir
- tests/filecheck/transforms/lower-csl-stencil.mlir
- tests/filecheck/transforms/stencil-bufferize.mlir
- tests/filecheck/transforms/stencil-inlining.mlir
- tests/filecheck/transforms/stencil-shape-inference.mlir
- tests/filecheck/transforms/stencil-unroll.mlir
- xdsl/dialects/utils/format.py
We sometimes print two spaces, sometimes none, this PR fixes that. All filecheck changes are either adding or removing a space.
> core: fix spacing in print_func_op_like

- tests/filecheck/projects/riscv-backend-paper/bottom_up_f32.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up_f64.mlir
- xdsl/backend/assembly_printer.py
- xdsl/dialects/riscv.py
This lets us avoid a bit of duplication in the emitted assembly, things that belong in the same section now stay in one section as long as they are contiguous.
> backend: add emit_section helper to AssemblyPrinter

- tests/xdsl_opt/test_xdsl_opt.py
- xdsl/xdsl_opt_main.py
This lets us write filecheck tests for exceptions raised during assembly, printing, for example.
> misc: catch DiagnosticExceptions thrown in xDSLOptMain targets

- tests/dialects/arm/test_assembly_arg_str.py
- tests/filecheck/dialects/arm_neon/test_attrs.mlir
- xdsl/dialects/arm_neon.py
---
title: dialects (arm): add arrangement specifier attribute
---
Adding an arrangement specifier attribute for ARM NEON instructions, which specifies the number and size of vector lanes. We assume full 128-bit registers.
> dialects (arm): add arrangement specifier attribute

- tests/filecheck/dialects/accfg/invalid.mlir
- xdsl/dialects/accfg.py
Stacked PRs:
* #3991
* #3989
* #3988
* #3987
* #4125
* __->__#3990
--- --- ---
As there are a redundancy in the assembly format between the first
parsed string and the result type, this should be a parsing error.
> dialects: Raise a parsing error in accfg.setup when result type is invalid

- docs/Toy/toy/dialects/toy.py
- tests/backend/riscv/test_register_allocation.py
- tests/dialects/test_func.py
- tests/pattern_rewriter/test_pattern_rewriter.py
- xdsl/backend/riscv/lowering/utils.py
- xdsl/backend/riscv/register_allocation.py
- xdsl/dialects/func.py
- xdsl/ir/core.py
- xdsl/pattern_rewriter.py
- xdsl/rewriter.py
- xdsl/transforms/convert_memref_stream_to_snitch_stream.py
- xdsl/transforms/convert_memref_to_ptr.py
- xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
- xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py
- xdsl/transforms/experimental/lower_hls.py
- xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
- xdsl/transforms/memref_stream_legalize.py
- xdsl/transforms/shape_inference_patterns/dmp.py
- xdsl/transforms/shape_inference_patterns/stencil.py
- xdsl/transforms/snitch_register_allocation.py
Stacked PRs:
* #3991
* #3989
* #3988
* #3987
* __->__#4125
--- --- ---
SSAValue can no longer change type after creation.
This ensures that we can have a generic type in values,
as otherwise this would be invalidated by changing the type.
> core: Make SSAValue type immutable

- xdsl/ir/core.py
- xdsl/printer.py
- xdsl/utils/test_value.py
Stacked PRs:
* #3991
* #3989
* #3988
* __->__#3987
--- --- ---
Adds a generic parameter to SSAValue that constrains the type associated
with the SSAValue.
This is useful whenever a function only accepts SSAValue of a given type.
> core: Make SSAValue generic

- tests/test_is_satisfying_hint.py
- xdsl/utils/hints.py
Stacked PRs:
* #3991
* #3989
* __->__#3988
* #3987
--- --- ---
`isa(arg, SSAValue[T])` will check that `arg` is an SSA value, and that
its type is `T`.
> core: Add support for typed SSA values in isa

- docs/Toy/toy/rewrites/lower_toy_affine.py
- docs/Toy/toy/rewrites/optimise_toy.py
- xdsl/backend/csl/print_csl.py
- xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
- xdsl/dialects/csl/csl.py
- xdsl/dialects/memref.py
- xdsl/dialects/riscv.py
- xdsl/dialects/stablehlo.py
- xdsl/dialects/stencil.py
- xdsl/dialects/tensor.py
- xdsl/interpreters/memref.py
- xdsl/interpreters/riscv.py
- xdsl/interpreters/tensor.py
- xdsl/irdl/operations.py
- xdsl/transforms/canonicalization_patterns/riscv.py
- xdsl/transforms/canonicalization_patterns/stencil.py
- xdsl/transforms/convert_stencil_to_csl_stencil.py
- xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py
- xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
- xdsl/transforms/lower_riscv_func.py
- xdsl/transforms/memref_to_dsd.py
- xdsl/transforms/shape_inference_patterns/dmp.py
- xdsl/transforms/shape_inference_patterns/stencil.py
- xdsl/transforms/stencil_inlining.py
Stacked PRs:
* __->__#3991
* #3989
* #3988
* #3987
--- --- ---
Now, defining a result with `resname = result_def(T)` will make
`resname` have the type `SSAValue[T]`.
This removes a lot of `cast` and `isa`/`isattr` in our codebase
> core: Make IRDLOperation results typed

- tests/filecheck/backend/riscv/convert_func_to_riscv_func.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up_f32.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up_f64.mlir
- tests/filecheck/projects/riscv-backend-paper/nsnet.mlir
- tests/interactive/test_app.py
- xdsl/backend/riscv/lowering/convert_func_to_riscv_func.py
Now that we can print it in riscv_func directly, we might as well print it that way instead of an explicit directive op.
> transformations: preserve visibility when lowering to riscv_func

- tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
- tests/filecheck/projects/riscv-backend-paper/pres.mlir
- xdsl/dialects/riscv_func.py
Might as well emit in the func since it's always in a text section.
> dialects: (riscv_func) emit .text in func op

- tests/xdsl_tblgen/test.json
- tests/xdsl_tblgen/test.py
- tests/xdsl_tblgen/test.td
- xdsl/tools/xdsl_tblgen.py
Unsure if the way these were done in tablegen changed since making the tool or if it never worked, but in either case this fixes optional attributes and adds a test.
> tool: (xdsl-tblgen) fix optional attributes

- tests/xdsl_tblgen/test.json
- tests/xdsl_tblgen/test.py
- tests/xdsl_tblgen/test.td
- xdsl/tools/xdsl_tblgen.py
Fixes assembly format printing for xdsl-tblgen by wrapping the string in triple quotes. This is necessary to deal with newlines, an alternative would be to replace all the new lines in the assembly format with spaces, or check if the assembly format has new lines before deciding whether to use single or triple quotes.
@Jimmy2027, I believe this should fix the issues addressed in https://github.com/xdslproject/xdsl/pull/4149 now, would you be able to test this commit to see if it can parse the dialect you were testing.
@erick-xanadu Could you confirm this partially fixes #3787 . At least locally this seem to not crash once the second dialect is removed.
> tool: (xdsl-tblgen) fix assembly format

- tests/filecheck/utils/codegen/simple.py
- xdsl/utils/dialect_codegen.py
`Opt` check should be before `Var` check since it's a `Var` subclass. In previous order opt variants were never printed.
> misc: Fix opt_operand and opt_result printing

- tests/filecheck/dialects/arm_neon/test_ops.mlir
- xdsl/dialects/arm_neon.py
Add Floating-point multiply operation to ARM (NEON) dialect (mixed: first source operand is a vector, second is a scalar, destination is a vector).
This instruction multiplies each of the floating-point values in the first source operand by the second source operand and writes the resulting values to the corresponding lanes of the destination.
> dialects (arm): Add NEON FMUL op (mixed scalar/vector)

- tests/filecheck/backend/riscv/convert_func_to_riscv_func.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up_f32.mlir
- tests/filecheck/projects/riscv-backend-paper/bottom_up_f64.mlir
- tests/filecheck/projects/riscv-backend-paper/nsnet.mlir
- tests/interactive/test_app.py
- xdsl/backend/riscv/lowering/convert_func_to_riscv_func.py
Now that the riscv_func.funcs can emit their own .text section as necessary, we don't need the explicit assembly_section structure. With this change, we can look up the riscv func using the standard SymbolOpInterface, like func.funv.
CC @jumerckx - With this the functions will be ported, but I need to do a similar refactor for global data for the switch to symbols in the interpreter to work.
> transformations: no assembly section when lowering to riscv_func

- tests/filecheck/dialects/arm_neon/test_ops.mlir
- xdsl/dialects/arm_neon.py
Floating-point fused Multiply-Add to accumulator (mixed: first source operand is a vector, second is a scalar. Destination is a vector)
This instruction multiplies the values in the first source operand by the second source operand, adds the accumulated value from the destination operand, and writes the resulting values to the destination.
This instruction is similar to FMUL and so this PR follows the same approach as https://github.com/xdslproject/xdsl/pull/4122.
> dialects (arm): Add NEON fmla instruction (mixed: vector/scalar)

- tests/filecheck/dialects/arm_neon/test_ops.mlir
- tests/filecheck/dialects/arm_neon/test_ops_invalid.mlir
- xdsl/dialects/arm_neon.py
Add ```ld1``` instruction to ARM (NEON) dialect. 
Neon structure load instruction reads data from memory into 64-bit Neon registers.
LD1 loads data from memory into up to four registers, with no interleaving.
> dialects (arm): Add NEON ld1 op

- tests/filecheck/dialects/arm_neon/test_ops.mlir
- tests/filecheck/dialects/arm_neon/test_ops_invalid.mlir
- xdsl/dialects/arm_neon.py
Fix the representation of the NEON ```ld1``` instruction to have the destination registers as results, not operands.
> dialects (arm): fix NEON ld1 instruction

- xdsl/pattern_rewriter.py
The op_type_rewrite_pattern decorator fails to apply on methods under certain conditions downstream due to the fact that the type annotations are not evaluated, and passed as strings.
Adding `eval_str=True` in the signature inspector will ensure that the type annotations are evaluated.
> core: Evaluate string annotations in rewrite patterns

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
Stacked PRs:
* #4187
* __->__#4186
--- --- ---
Previously, nesting optional groups would raise asserts in the
declarative assembly format generated parser, as nested groups would not
set their operands and results as empty.
> core: Allow nesting of optional groups in declarative assembly format

- tests/dialects/test_vector.py
- tests/filecheck/dialects/vector/vector_ops.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/vector/extract.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/vector/insert.mlir
- xdsl/dialects/vector.py
Stacked PRs:
* #4202
* __->__#4201
--- --- ---
These operations are defined in MLIR and are meant to replace
vector.insertelement and vector.extractelement.
> dialects: Add vector.insert and vector.extract operations

- tests/backend/test_register.py
- tests/dialects/test_riscv.py
- tests/dialects/test_x86.py
- tests/filecheck/dialects/riscv/riscv_registers_invalid.mlir
- tests/filecheck/dialects/x86/x86_registers_invalid.mlir
- xdsl/backend/register_type.py
- xdsl/dialects/arm/register.py
- xdsl/dialects/arm_neon.py
- xdsl/dialects/riscv.py
- xdsl/dialects/x86/register.py
With this change, a register is uniquely identified by its register set name and index, allowing us to do things like disambiguating registers with multiple register names within a register set, as well as reason about overlapping registers in some simple cases.
> backend: remove instruction set name from register types

- tests/dialects/test_builtin.py
- xdsl/dialects/builtin.py
Useful for some upcoming vector op implementations.
> dialects: (builtin) add get_scalable_dims to vector type

- xdsl/interpreter.py
The recent Pyright update (#4221) requires the default factories to be fully typed, which is a minor change in most of the framework, but messes things up in interpreter.py due to the typealiases for the more complex signatures. I thought I'd split it out for an easier review.
> misc: move some typealiases up in interpreter.py

- benchmarks/parser.py
- benchmarks/workloads.py
- tests/filecheck/dialects/builtin/attrs.mlir
Add parsing benchmarks using existing workloads, peeled from #4008
> bench: add parsing benchmarks using existing workloads

- benchmarks/parser.py
- benchmarks/printer.py
- benchmarks/workloads.py
- tests/test_ssa_value.py
- xdsl/utils/test_value.py
Add printing benchmarks using existing workloads, peeled from #4008. This includes changes to workload generation for more efficient setup.
> bench: add printing benchmarks using existing workloads

- README.md
My markdownlint complains when the first thing in a .md file isn't a header, but the badges belong in the first location, so this adds an ignore. I'm not sure that it's worth adding markdownlint as a dependency, I'd like to keep that discussion to the future if possible, and just add the ignores manually.
Check the new README here: https://github.com/xdslproject/xdsl/tree/sasha/misc/mdlint
> documentation: ignore markdownlint error

- tests/xdsl_tblgen/test.json
- tests/xdsl_tblgen/test.py
- tests/xdsl_tblgen/test.td
- xdsl/tools/xdsl_tblgen.py
re-opened #4160:
fixes issue mentioned in #4158, without this the AnyAttrOf generation is broken:
```python
@irdl_op_definition
class EmitC_ConstantOp(IRDLOperation):
"""Constant operation"""
name = "emitc.constant"
value = prop_def(
AnyOf(
BaseAttr(EmitC_OpaqueAttr),AnyAttr()
)
)
)
v12 = result_def(AnyAttr())
```
with this change the [emitc](https://mlir.llvm.org/docs/Dialects/EmitC/) dialect can be generated without errors.
> tool: (xdsl-tblgen) fix AnyAttrOf generation

- asv.conf.json
#4147 removed the `setup.py` file. This broke the `asv` configuration for environment builds.
This PR adopts the most recent ASV quickstart template which describes how to build from `pyproject.toml`, and uses this to fix `asv` environment builds.
> CI: (asv) Adopt new asv template to fix build issues from removed setup.py file

- xdsl/utils/test_value.py
Fix deprecation message to refer to `create_ssa_value` instead of `test_ssa_value`.
> misc: Fix deprecation message for `TestSSAValue`

- tests/test_affine_builtins.py
- xdsl/ir/affine/affine_map.py
- xdsl/transforms/loop_nest_lowering_utils.py
- xdsl/transforms/memref_stream_unnest_out_parameters.py
Our version of compress dims was more consistent with Python's `itertools.compress`, in that 1 signals to keep an element, than MLIR's `compressDims`, where 1 signals to drop an element. Since there's an inherent confusion in the name here, I propose to make the behaviour consistent with MLIR, while changing the name to be a bit more explicit about the fact that it's dropping the indicated values.
One alternative would be to rename the existing function `keepDims`, and to add a new function called `dropDims`, and have one call the other. It seems that the `keepDims` implementation can be more easily expressed than the dropping version, but it's a very small difference, so I went instead with a smaller API surface.
CC @watermelonwolverine
> core: rename AffineMap.compressDims to dropDims

- tests/dialects/test_affine.py
- tests/filecheck/dialects/affine/affine_ops.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/affine/affine_ops.mlir
- xdsl/dialects/affine.py
Without this change the testcase prints this:
```mlir
builtin.module {
%c0 = arith.constant 2 : index
%0 = affine.apply affine_map<()[s0] -> ((s0 * 4))> [%c0]
}
```
which results in this error when trying to parse with MLIR:
```
temp.mlir:3:53: error: expected '(' in operand list
%0 = affine.apply affine_map<()[s0] -> ((s0 * 4))> [%c0]
^
```
The change should fix the missing parenthesis:
```mlir
builtin.module {
%c0 = arith.constant 2 : index
%0 = affine.apply affine_map<()[s0] -> ((s0 * 4))>() [%c0]
}
```
I'm not quite sure how to test the compatibility with MLIR
> dialects: (affine) Fix ApplyOp printing and add test

- tests/filecheck/dialects/arith/canonicalize.mlir
- xdsl/dialects/arith.py
- xdsl/transforms/canonicalization_patterns/arith.py
I have encountered a pattern where `arith.cmpf` is immediately followed by `arith.select` on the same operands:
```
%cst_0 = arith.constant 3.000000e+00 : f64
%0 = "test.op"() : () -> f64
%1 = arith.cmpf ogt, %0, %cst_0 : f64
%2 = arith.select %1, %0, %cst_0 : f64
"test.op"(%2) : (f64) -> ()
```
This could be simplified to:
```
%cst_0 = arith.constant 3.000000e+00 : f64
%0 = "test.op"() : () -> f64
%1 = arith.maximumf %0, %cst_0 : f64
"test.op"(%1) : (f64) -> ()
```
The ordered comparisons olt/ole and ogt/oge will produce `minimumf` and `maximumf` ([link](https://mlir.llvm.org/docs/Dialects/ArithOps/#arithmaximumf-arithmaximumfop)), respectively. Similarly, the unordered comparisons ult/ule and ugt/uge will produce a `minnumf` and `maxnumf`, respectively. 
Here, ogt and olt mean "ordered …
> canonicalize: (arith) Fold cmpf and select on same operands

- tests/filecheck/transforms/linalg-to-csl.mlir
- xdsl/transforms/linalg_to_csl.py
It turns out, there are functions for max but not for min. Is there an undocumented one?
> transformations: (linalg-to-csl) Translate linalg.max

- xdsl/dialects/builtin.py
- xdsl/ir/core.py
Refactor `has_trait` method to eliminate unnecessary `issubclass` checks for unregistered operations.
> core: refactor has_trait method to eliminate issubclass checks

- tests/filecheck/transforms/arith-add-fastmath.mlir
- xdsl/transforms/arith_add_fastmath.py
> transformations: (arith-add-fastmath) Support arith.cmpf

- tests/filecheck/dialects/transform/transform_types.mlir
- xdsl/dialects/transform.py
named_sequence has the following two traits in MLIR:
* FunctionOpInterface,
* IsolatedFromAbove,
> dialects: (transform) add function-like traits to named_sequence

- tests/filecheck/transforms/stencil-shape-minimize.mlir
- xdsl/transforms/stencil_shape_minimize.py
This PR adds support for stencil types of different dimensionality.
Previously, it used to determine a shape it considers minimal, propagating that throughout the program. Instead, it now builds a separate minimal shape per number of dimensions (e.g. separate for 1-d, 2-d, 3-d, etc).
> transformations: (stencil-shape-minimise) Support missing dims

- tests/filecheck/dialects/transform/transform_ops.mlir
- tests/filecheck/dialects/transform/transform_types.mlir
- tests/interpreters/test_transform_interpreter.py
- xdsl/dialects/transform.py
- xdsl/interpreters/transform.py
Adds semantics for `NamedSequenceOp` and `YieldOp`.
> interpreter (transform): add semantics for `NamedSequenceOp` and `YieldOp`

- xdsl/pattern_rewriter.py
In Zulip, I asked about making this method public and I was told that it should be made public.
> rewriting: make `_replace_all_uses_with` public

- tests/dialects/test_irdl.py
- tests/filecheck/dialects/irdl/cmath.irdl.mlir
- tests/filecheck/dialects/irdl/cmath_irdl_stub.py
- tests/filecheck/dialects/irdl/cyclic-types.irdl.mlir
- tests/filecheck/dialects/irdl/irdl-to-pyrdl/testd.irdl.mlir
- tests/filecheck/dialects/irdl/pyrdl-to-irdl/cmath-conversion.py
- tests/filecheck/dialects/irdl/test-type.irdl.mlir
- tests/filecheck/dialects/irdl/testd.irdl.mlir
- xdsl/dialects/cmath.irdl
- xdsl/dialects/irdl/irdl.py
- xdsl/dialects/irdl/irdl_to_pyrdl.py
- xdsl/dialects/irdl/pyrdl_to_irdl.py
- xdsl/interpreters/irdl.py
Updates irdl to the version in MLIR master.
I think we could benefit from some mlir interop tests here, but xdsl and mlir seems to treat symbols slightly differently which could make this difficult.
> dialects: (irdl) add name properties

- benchmarks/rewriting.py
Four benchmarks work locally but fail in the ASV CI flow (https://github.com/xdslproject/xdsl-bench/actions/runs/14723114736/job/41320444374):
- `Rewriting.Canonicalization.time_block_detach_op`
- `Canonicalization.time_irwithuses_remove_use`
- `Canonicalization.time_operation_drop_all_references`
- `PatternRewriting.time_pattern_rewriter_insert_op`
This PR ignores these benchmarks to ensure the CI flow passes and correctly deploys the website.
> bench: disable benchmarks failing in ASV CI flow

- tests/filecheck/dialects/transform/transform_interpreter.mlir
- tests/filecheck/dialects/transform/transform_types.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/transform/transform_types.mlir
- xdsl/dialects/transform.py
Also possibly change the name of the operands and properties to match funcOp
> dialects: (transform) Add custom syntax for `transform.named_sequence`

- xdsl/backend/csl/print_csl.py
- xdsl/dialects/builtin.py
- xdsl/interpreters/builtin.py
- xdsl/interpreters/memref.py
- xdsl/interpreters/ml_program.py
- xdsl/interpreters/riscv.py
A much simpler version of #3492 using the default valued typevars. The advantage of this is that you can now represent for example `DenseIntOrFPElementsAttr[AnyFloat]` as a type.
I'm not totally happy with this as there doesn't seem to be a good way to write the extraction methods (`get_attrs`/`iter_attrs`) in a way which actually respects the generic type, so any suggestions would be welcome. 
This PR does not attempt to specialise the use of `DenseIntOrFPElementsAttr` anywhere. I also didn't touch the builder methods `tensor_from_list` or `vector_from_list` or `from_list` as I personally believe it might be possible/best to remove the methods in the future, favouring `create_dense_{float/int/index}`.
> dialects: (builtin) add generic parameter to DenseIntOrFPElementsAttr

- xdsl/backend/register_queue.py
- xdsl/backend/riscv/riscv_register_queue.py
This concludes the migration of the register queue itself to be basically target-independent. When the time comes, we can add fairly short target-specific queues that specify the registers reserved and available by the platform ABI.
> backend: (riscv) target-independent LIFO register queue

- xdsl/backend/riscv/register_allocation.py
`allocate` already does the right thing for us, so no need for the extra helper.
> backend: (riscv) remove _allocate_live_ins_per_block helper

- xdsl/backend/riscv/register_allocation.py
- xdsl/transforms/riscv_register_allocation.py
In practice I don't think it's ever correct to exclude the preallocated registers, might as well drop this.
> backend: always exclude pre-allocated registers during regalloc

- xdsl/backend/register_queue.py
- xdsl/backend/riscv/register_allocation.py
- xdsl/backend/riscv/riscv_register_queue.py
Finally it was too tricky to get the typing to work out with the generics. As you can see in #4314, the plan is to add an abstract method for allocatable operations to implement, and that has to be register-type independent, since that's a thing unknown at runtime.
> backend: make RegisterQueue non-generic

- tests/filecheck/dialects/tosa/ops.mlir
- tests/irdl/test_declarative_assembly_format.py
- tests/test_parser.py
- tests/test_printer.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
- xdsl/irdl/operations.py
- xdsl/parser/core.py
Fixes #4306 
I'm not sure this is 100% what MLIR does in every case, but it passes all our tests at seems at least close to mlir behaviour in the cases I tested.
@erick-xanadu can't seem to add you as a reviewer for some reason, but would be good if you could check if this fixes the issues you were having.
> core: (ParsePropInAttrDict) allow a subset of properties to be parsed in attr-dict

- docs/marimo/irdl.py
- tests/irdl/test_attr_constraint.py
- tests/irdl/test_attribute_definition.py
- tests/test_frontend_type_conversion.py
- tests/test_pyrdl.py
- xdsl/dialects/builtin.py
- xdsl/ir/core.py
- xdsl/irdl/attributes.py
This class should be used for builtin attributes that are printed differently than "user-defined" attributes. This include for instance `vector`, `integer`, etc...
All non-`BuiltinAttribute` class should have the `dialect.name` syntax for their name
> core: Create BuiltinAttribute class

- xdsl/dialects/arith.py
Moves `arith.select` to assembly format and uses constraints instead of `_verify`. Might be worth upstreaming the assembly format here to MLIR, since there's been a FIXME for over 3 years.
> dialects: (arith) move select to assembly format

- xdsl/dialects/arith.py
Moves the operation to assembly format, and fixes the previous lack of verification and the non-printing of the fastmath flag.
> dialects: (arith) fix negf

- tests/dialects/test_builtin.py
- xdsl/dialects/builtin.py
- xdsl/dialects/vector.py
This seemed to only be used in two places, both of which could trivially be replaced. Is anyone aware of the reason this exists? (e.g. is it used downstream?)
> dialects: (builtin) remove TensorOrMemRefConstraint

- xdsl/dialects/builtin.py
- xdsl/irdl/constraints.py
I'm pretty sure there was some type unsoundness created by having the parameter on `GenericAttrConstraint` be covariant and then having the extractors use this type parameter. This was highlighted by #4238 , where the `TypedAttributeConstraint` extractor encounters an attribute which is not a `TypedAttribute`.
This PR refactors `get_variable_extractors` to remove the variant parameter, adding in some new necessary checks within the extractor.
> core: (constraints) remove variance on `get_variable_extractors`

- docs/marimo/traversing_ir.py
This PR updates the function name used in the traversal example within the documentation. Previously, the example showed the function named as `@triangle`, which was misleading given the intended functionality of summing squares. With these changes, the function is now correctly labeled as `@sum_of_squares`, aligning with the code's purpose and improving overall readability.
Resolves issue [#4128](https://github.com/xdslproject/xdsl/issues/4128).
---
*Created with [Repobird.ai](https://repobird.ai) 📦🐦*
> documentation: Rename traversal example function to @sum_of_squares for clarity

- tests/irdl/test_operation_definition.py
- xdsl/irdl/constraints.py
This PR adds the following prefix on a verification error for range length constraints:
"incorrect length for range variable:"
> core: Add nicer error messages for RangeOf

- tests/backend/riscv/test_preallocated.py
- tests/backend/test_register_allocation.py
- xdsl/backend/register_allocatable.py
- xdsl/backend/riscv/register_allocation.py
- xdsl/dialects/riscv_func.py
This is half of the class, in a subsequent PR there will actually be an `allocate` method for each subclass to override.
> backend: add RegisterAllocatableOperation abstract base class

- tests/filecheck/transforms/convert_vector_to_ptr.mlir
- xdsl/transforms/__init__.py
- xdsl/transforms/convert_vector_to_ptr.py
Lowering of ```vector.load``` to the ```ptr``` dialect. The memory indexing is done in the ```memref``` world (using ```subview```) rather than in the ```ptr``` world. This way, the low-level pointer arithmetic, which is error-prone and implementation-dependent, is confined to the lowering passes of the ```memref``` dialect.
> transformations: vector load to ptr

- tests/irdl/test_declarative_assembly_format.py
- tests/test_context.py
- tests/test_parser.py
- tests/test_printer.py
- xdsl/context.py
- xdsl/dialects/builtin.py
- xdsl/parser/attribute_parser.py
- xdsl/utils/exceptions.py
With this change, it should be possible to have an attribute and a type of the same name, which is necessary to handle the MLIR `emitc` dialect.
> core: Separate attributes and types in the context

- tests/filecheck/dialects/ptr/ops.mlir
- xdsl/dialects/ptr.py
PR 1/2 adding the canonicalization patterns from [here](https://github.com/llvm/llvm-project/pull/137469/files) that remove chains of to_ptr and from_ptr ops in a simpler way than removing reinterpret casts.
> dialects: (ptr) add FromPtrOp

- tests/test_is_satisfying_hint.py
- xdsl/dialects/csl/csl.py
- xdsl/dialects/llvm.py
- xdsl/transforms/convert_stencil_to_csl_stencil.py
- xdsl/transforms/lower_csl_stencil.py
- xdsl/transforms/lower_csl_wrapper.py
- xdsl/utils/isattr.py
Now that `isa` handles `TypeForm`, we don't need duplicated functionality in `isattr`, making the API a bit simpler.
> core: only pass constraints to `isattr`

- tests/filecheck/dialects/ptr/canonicalize.mlir
- xdsl/dialects/ptr.py
- xdsl/transforms/canonicalization_patterns/ptr.py
Add canonicalization patterns to remove a roundtrip of to/from ptr. These are based on the patterns proposed in [the corresponding MLIR PR](https://github.com/llvm/llvm-project/pull/137469/files), because we don't yet have memory space annotations on `!ptr.ptr`, and will have to be adjusted once that's added.
> dialects: (ptr) add canonicalization patterns to remove to/from ptr

- tests/filecheck/backend/riscv/register-allocation/exclude_snitch.mlir
- xdsl/backend/riscv/register_allocation.py
- xdsl/dialects/riscv_snitch.py
- xdsl/transforms/riscv_register_allocation.py
- xdsl/transforms/snitch_register_allocation.py
Move some of the snitch-specific logic out of the generic RISC-V register allocator, and to the appropriate operations. This preserves the current behaviour of reserving the snitch registers for the whole function if there are any snitch reads or writes.
> backend: (riscv) use RegisterAllocationOperation for snitch reserved registers

- tests/filecheck/dialects/vector/vector_ops.mlir
- xdsl/dialects/vector.py
Support nontemporal attribute in vector.load and vector.store operations.
Fixes #2606
> dialects: (vector) Add nontemporal to vector.load and vector.store

- tests/filecheck/mlir-conversion/with-mlir/dialects/transform/transform_generic.mlir
My local mlir-opt requires this for test operations.
> testing: add unregistered dialect flag to new test

- tests/pattern_rewriter/test_pattern_rewriter.py
- xdsl/pattern_rewriter.py
`notify_op_modified` should be called whenever an operation is modified so that the pattern rewriter can update its internal state.
> core: Add notify_op_modified to the PatternRewriter

- tests/filecheck/transforms/convert_ptr_to_llvm.mlir
- xdsl/transforms/convert_ptr_to_llvm.py
Enables recursive mode for the `RewritePtrTypes` type conversion pattern.
> transforms: (convert-ptr-to-llvm) Enable recursive type rewriting

- tests/filecheck/dialects/memref/memref_ops.mlir
- xdsl/dialects/memref.py
This PR accounts for the default nontemporal value in memref.load and memref.store operations, consistent with [MLIR behavior](https://github.com/llvm/llvm-project/blob/7c366b041cd0effdcf0b7e1f3a7ad4eb39800349/mlir/include/mlir/Dialect/MemRef/IR/MemRefOps.td#L1209).
> dialects: (memref) Add nontemporal default value.

- tests/filecheck/transforms/convert_ptr_to_llvm.mlir
- xdsl/transforms/convert_ptr_to_llvm.py
Adds conversion patterns for `ToPtrOp` and `FromPtrOp`, added by #4334.
> transformations: (convert-ptr-to-llvm) Add conversions for `ConvertToPtrOp` and `ConvertFromPtrOp` 

- xdsl/dialects/builtin.py
Was only used internally in one place and seems pretty easy to combine with `create_dense_int`.
> dialects: (builtin) deprecate create_dense_index

- xdsl/dialects/builtin.py
- xdsl/dialects/cf.py
- xdsl/transforms/canonicalization_patterns/cf.py
- xdsl/transforms/convert_scf_to_cf.py
Creates a `DenseIntElementsAttr` alias (which MLIR also has) and has `cf.switch` use this.
Also switches from `vector_from_list` to `create_dense_int` in preparation for deprecating `vector_from_list`
> dialects: (cf) simplify switch's use of DenseIntElementAttr

- tests/filecheck/transforms/convert_memref_args_to_ptr.mlir
- xdsl/transforms/convert_memref_to_ptr.py
These are a simpler kind of cast to deal with than the unrealized cast, and can trivially be removed by canonicalization. This simplifies #4331.
> transformations: (convert-memref-to-ptr) use to/from ptr ops for casts

- tests/filecheck/dialects/arm_neon/test_ops.mlir
- xdsl/dialects/arm_neon.py
Add ```dup``` instruction to Arm Neon dialect. Duplicate general-purpose register to vector.
> [dialects] arm: Add dup instruction

- xdsl/dialects/builtin.py
Missed a branch of the deprecated function.
Note that although the replacement for this deprecation looks bad, we actually have no cases where this function was used polymorphically across `int` and `float`
> dialects: (builtin) fix deprecated vector_from_list

- docs/Toy/toy/dialects/toy.py
- docs/Toy/toy/rewrites/lower_toy_affine.py
- docs/Toy/toy/rewrites/optimise_toy.py
- tests/filecheck/backend/riscv/memref_to_riscv.mlir
- xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
- xdsl/dialects/affine.py
- xdsl/dialects/builtin.py
- xdsl/dialects/cf.py
- xdsl/dialects/varith.py
- xdsl/interpreters/linalg.py
- xdsl/transforms/canonicalization_patterns/cf.py
Would like some help with the error here, seems to me that the test has a bug in line 96
Hoping that this will make @erick-xanadu 's life easier for adding complex values. In any case these avoid a few casts. They can be eventually replaced with overloads of `get_values` if https://github.com/microsoft/pyright/issues/10232 is resolved.
> dialects: (builtin) add `get_{int/float}_values`

- xdsl/dialects/x86/ops.py
I would like to change the naming convention we use in this dialect, and putting all the abstract base classes in one place makes this easier. More changes to follow.
> dialects: (x86) move all abstract operations to one place

- flake.lock
- flake.nix
Adds `mlir-opt` v20.1.4 to the nix flake, allowing all the tests to be run without compiling mlir.
@superlopuh as far as I can tell, `brew` also installs v20.1.4 now (https://formulae.brew.sh/formula/llvm), should we update versions for next release?
> installation: (nix) include mlir-opt in flake

- tests/filecheck/backend/x86/convert_ptr_to_x86.mlir
- xdsl/backend/x86/lowering/convert_ptr_to_x86.py
Convert the ```ptr.store``` ops to x86 assembly.
> backend: ptr.store to x86

- tests/dialects/test_builtin.py
- tests/dialects/test_math.py
- tests/interpreters/test_linalg_interpreter.py
- xdsl/dialects/builtin.py
Replaces uses of `tensor_from_list` with `create_dense_{int/float}`. Stacked on top of splat initialisation.
> dialects: (builtin) deprecate tensor_from_list

- tests/backend/riscv/test_register_allocation.py
- tests/backend/test_register_allocation.py
- xdsl/backend/register_allocator.py
- xdsl/backend/riscv/register_allocation.py
This class encapsulates the logic to do with updating the registers for values, whether it's a single value, or multiple values that should all be in the same register.
> backend: add ValueAllocator base class for SSAValue allocation

- tests/filecheck/dialects/arm_neon/test_ops.mlir
- xdsl/dialects/arm_neon.py
Variant of MOV instruction which extracts a value from a specified lane in a NEON register into a general-purpose register.
> dialects: (arm) Add mov instruction for Neon -> general-purpose register

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
This adds support for anchoring operation attributes and properties in the declarative assembly format. This allows writing `($optAttr^)?` in `assembly_format`.
For now, only qualified attributes are supported.
> core: Support optional attrs in assembly format

- tests/filecheck/transforms/convert_memref_to_ptr.mlir
- tests/filecheck/transforms/convert_vector_to_ptr.mlir
- xdsl/transforms/convert_memref_to_ptr.py
Also fixes the name so that it's the same as the original memref, as opposed to either `%0` in the case of store, or the name of the result value in the case of load.
> transformations: (convert-vector-to-ptr) cast first then ptr arithmetic

- tests/dialects/test_smt.py
- tests/filecheck/dialects/smt/invalid.mlir
- tests/filecheck/dialects/smt/ops.mlir
- xdsl/dialects/smt.py
This adds the two quantifier operations to the `smt` dialect
> dialects: Add `smt.exists` and `smt.forall` operations

- tests/filecheck/backend/x86/convert_vector_to_x86.mlir
- xdsl/backend/x86/lowering/convert_ptr_to_x86.py
- xdsl/backend/x86/lowering/convert_vector_to_x86.py
- xdsl/backend/x86/lowering/helpers.py
- xdsl/transforms/__init__.py
Lowering of ```vector.fma``` for x86 architectures
> backend: (x86) vector.fma to x86 instructions

- tests/dialects/test_emitc.py
- tests/filecheck/dialects/emitc/emitc_types.mlir
- tests/filecheck/dialects/emitc/emitc_types_invalid_parsing.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/emitc/emitc_types.mlir
- xdsl/dialects/__init__.py
- xdsl/dialects/emitc.py
Register the emitc dialect in xdsl/dialects/__init__.py and add the EmitC Array Type as a first step towards adding the full [emitc dialect](https://mlir.llvm.org/docs/Dialects/EmitC/)
> dialects: (emitc) Add EmitC dialect with the EmitC_ArrayType

- tests/filecheck/backend/x86/convert_ptr_to_x86.mlir
- xdsl/backend/x86/lowering/convert_ptr_to_x86.py
Composition of lowering to x86 passes fixed
> bug: (x86) cast back the result of an ptr operation after lowering to x86

- tests/backend/test_live_ins.py
- xdsl/backend/register_allocator.py
- xdsl/backend/riscv/register_allocation.py
Moves some logic that is not RISC-V-specific to a new ABC.
> backend: add BlockAllocator base class

- tests/dialects/test_smt.py
- tests/filecheck/dialects/smt/ops.mlir
- xdsl/dialects/smt.py
Add the `smt.declare_fun` operation, which is used to declare constants and functions.
Also add the `smt.func` type
> dialects: Add `smt.declare_fun` and `!smt.func`

- tests/dialects/test_builtin.py
- xdsl/dialects/builtin.py
- xdsl/utils/dialect_stub.py
ArrayOfConstraint can now take a range constraint. This means in particular that we can use a RangeVarConstraint in it, which is quite useful for some operations.
> dialects: Allow range constraints in ArrayOfConstraint

- xdsl/transforms/convert_memref_to_ptr.py
This gets rid of the `offset_calculations` helper used in vector and memref lowerings, instead just keeping the `get_ptr` helper that directly gives the new pointer, instead of calculating the offsets separately. This is motivated by the fact that sometimes the offset is 0 in a way that is tedious to calculate before calling the helper itself. An alternative would be to change the type signature to return `None` in the case where no offset ops need to be created, but this seemed simpler.
> transformations: (convert-memref-to-ptr) inline offset_calculations helper

- tests/dialects/test_smt.py
- tests/filecheck/dialects/smt/ops.mlir
- xdsl/dialects/smt.py
`smt.apply_func` is the operation to apply a function to a list of arguments.
> dialects: (smt) Implement `smt.apply_func`

- tests/test_ir.py
- xdsl/dialects/accfg.py
- xdsl/dialects/llvm.py
- xdsl/dialects/memref.py
- xdsl/dialects/stencil.py
- xdsl/dialects/tensor.py
- xdsl/dialects/vector.py
- xdsl/ir/core.py
- xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Add a `type` argument to `SSAValue.get` allowing it to return `SSAValue`s with a more specialised generic paremeter.
This allows us to simplify a lot of cases where an SSAValue is obtained before checking its type.
> core: (SSAValue) make `get` generic

- tests/irdl/test_attr_constraint.py
- xdsl/dialects/bufferization.py
Fixes the init method for `ToTensorOp`. Factors out the logic for converting to and from memref and tensor types to static methods on `TensorFromMemRefType`. 
Stacked on #4428
> dialects: (bufferization) fix ToTensorOp init

- xdsl/interactive/app.py
- xdsl/passes.py
- xdsl/xdsl_opt_main.py
Once upon a time passes were mutable, so `xdsl-gui` needed an immutable representation. Now that this is not needed we can simplify the parsing a bit in both the gui and `xdsl-opt`.
> core: avoid pipeline tuples when parsing pass spec

- tests/dialects/test_x86.py
- xdsl/backend/x86/lowering/convert_vector_to_x86.py
- xdsl/dialects/x86/ops.py
This makes pyright happy and the API less broken.
> dialects: (x86) use typed SSA values for inference in inits

- tests/backend/riscv/test_register_allocation.py
- xdsl/backend/register_allocatable.py
- xdsl/backend/riscv/register_allocation.py
- xdsl/dialects/riscv_scf.py
- xdsl/dialects/riscv_snitch.py
Moves a bunch of per-op logic to the op rather than a shared class! Most importantly this removes the dependency on snitch for the RISC-V register allocator, but it also opens the door for future customisation in the dialect itself vs shared infrastructure.
> backend: add allocate_registers abstract method to RegisterAllocatableOperation

- tests/backend/x86/test_register_allocation.py
- xdsl/dialects/x86/ops.py
This abstract base class lets us do the obvious thing to these instructions when allocating, specifying which values are inputs, which are outputs, and which inputs and outputs are expected to live in the same register.
> dialects: (x86) add RegisterAllocatableOperation annotation to x86

- xdsl/ir/core.py
It's an experimental feature, and seems not to be available in the wasm version of typing extensions.
> misc: only import TypeForm when type checking

- tests/filecheck/utils/codegen/simple.py
- xdsl/backend/register_type.py
- xdsl/dialects/stencil.py
- xdsl/ir/core.py
- xdsl/irdl/attributes.py
- xdsl/irdl/constraints.py
As far as I can tell this has no impact on perf.
@EdmundGoodman, what's the easiest way to do before/after comparisons locally in xDSL?
> core: make ParametrizedAttribute parameters dynamic

- tests/filecheck/backend/x86/x86_allocate_registers.mlir
- tests/filecheck/projects/libxsmm/x86_matmul_kernel.mlir
- xdsl/backend/x86/register_allocation.py
- xdsl/transforms/__init__.py
- xdsl/transforms/x86_allocate_registers.py
Adds the pass and a test, and modifies the end-to-end test to include register allocation in the pipeline.
> backend: add x86-allocate-registers

- xdsl/transforms/apply_pdl_interp.py
This refactor allows passing different interpreter functions, for example for eqsat interpreter functions.
> transformations: (pdl_interp) Refactor `PDLInterpRewritePattern`

- tests/filecheck/backend/x86/convert_vector_to_x86.mlir
- xdsl/backend/x86/lowering/convert_vector_to_x86.py
Convert ```vector.broadcast``` operations into x86 assembly instructions.
> backend: lowering of vector.broadcast to x86

- xdsl/irdl/attributes.py
- xdsl/utils/hints.py
Stacked PRs:
* #4482
* #4481
* #4480
* #4479
* __->__#4478
--- --- ---
Now, irdl_to_attr_constraint will correctly propagate the expected generic
type if it can be inferred from the inputs.
> core: Improve typing of `irdl_to_attr_constraint`

- tests/dialects/test_emitc.py
Remove the duplicated verification test for the emitc array type.
That testcase already exists in the [file check test](https://github.com/xdslproject/xdsl/blob/main/tests/filecheck/dialects/emitc/emitc_types_invalid.mlir#L5)
> dialects: (emitc) Remove duplicated testcase

- tests/dialects/test_emitc.py
- tests/filecheck/dialects/emitc/emitc_types.mlir
- tests/filecheck/dialects/emitc/emitc_types_invalid.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/emitc/emitc_types.mlir
- xdsl/dialects/emitc.py
Add additional checks to the emitc array shape and type verification as implemented in the [reference](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/EmitC/IR/EmitC.cpp)
> dialects: (emitc) add emitc array verify and parsing checks

- GETTING_STARTED.md
- tests/filecheck/backend/riscv/canonicalize.mlir
- xdsl/dialects/riscv.py
- xdsl/transforms/canonicalization_patterns/riscv.py
Implemented the `x >> 0 -> x` canonicalization as per [GETTING_STARTED](https://github.com/xdslproject/xdsl/blob/main/GETTING_STARTED.md) guide.
> transformations: shift right by zero canonicalization for RISCV dialect

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Stacked PRs:
* #4482
* __->__#4481
* #4480
--- --- ---
The `qualified` directive has to be used when an attribute or property is
known to be a base attribute, and where we want to parse the entire attribute,
not just the parameters.
> core: Add support for qualified attributes in assembly format

- tests/filecheck/dialects/emitc/emitc_types_invalid.mlir
The tests are taken from
https://github.com/llvm/llvm-project/blob/main/mlir/test/Dialect/EmitC/invalid_types.mlir#L17
> dialects: (emitc) Add additional invalid emitc array type checks

- xdsl/dialects/stencil.py
Minor change to the API to make the typing a bit more explicit. I'm playing around with better Attribute inits in a branch and this change seemed like a quick separate refactor to consider.
> dialects: (stencil) replace IndexAttr.parse_nested_parameters

- tests/filecheck/dialects/builtin/attrs.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/builtin/dense_elements.mlir
- xdsl/dialects/builtin.py
- xdsl/parser/attribute_parser.py
Parsing and printing of complex types. 
* adds the `create_dense_complex` method to `DenseIntOrFPElementsAttr`
* adds the `get_dense_values` method `DenseIntOrFPElementsAttr`
* adds the `to_complex` method to `_TensorLiteralElement`
* adds cases to print and parse complex values
> dialects: (builtin) Add support for parsing and printing complex types

- tests/interpreters/test_eqsat_pdl_interp_interpreter.py
- xdsl/interpreters/eqsat_pdl_interp.py
~Draft until https://github.com/xdslproject/xdsl/pull/4515 gets merged~
So backtracking is currently fully handled by the interpreter. I like the idea of trying to move logic into the IR itself but I think this is still a good place to start from?
> interpreter: (eqsat) Add backtracking mechanism for `GetDefiningOp`

- xdsl/utils/test_value.py
Deprecated April 14th so seems like fair game.
> testing: remove TestSSAValue deprecated two months ago

- xdsl/irdl/declarative_assembly_format.py
We can specialise here to be more explicit and performant.
```
~/Developer/xdslproject/xdsl sasha/perf/n…embly-format *117 ❯ uv run benchmarks/printer.py Printer.constant_1000 timeit
Test Printer.constant_1000 ran in: 0.0104 ± 0.00018s
~/Developer/xdslproject/xdsl sasha/perf/n…embly-format *116 !1 ❯ uv run benchmarks/printer.py Printer.constant_1000 timeit
Test Printer.constant_1000 ran in: 0.00944 ± 0.000239s
```
> misc: use print_string in assembly format

- tests/irdl/test_attribute_definition.py
- xdsl/dialects/builtin.py
- xdsl/ir/core.py
- xdsl/printer.py
As discussed on zulip, moves all the special casing in `Printer.print_attribute` to `BuilitinAttribute` and uses polymorphism instead. I've called the function `print_builtin` for now.
I feel this has uncovered some uncertainty in what the roles of `print_builtin`, `print_parameters`, and `parse_parameters` are for builtin attributes, but I don't think this PR adds any more confusion.
> dialects: (builtin) move printing to BuiltinAttribute

- tests/test_printer.py
- xdsl/dialects/builtin.py
- xdsl/dialects/csl/csl.py
- xdsl/dialects/experimental/air.py
- xdsl/dialects/irdl/irdl.py
- xdsl/dialects/llvm.py
- xdsl/dialects/memref_stream.py
- xdsl/dialects/pdl.py
- xdsl/dialects/riscv_debug.py
- xdsl/dialects/riscv_scf.py
- xdsl/dialects/scf.py
- xdsl/dialects/smt.py
- xdsl/dialects/snitch_stream.py
- xdsl/dialects/vector.py
Removes all instances of using the variadic behaviour of `Printer.print`. All tests pass if `assert len(argv) == 1` is added to the top of this function.
I haven't added any sort of deprecation/change to `Printer.print` because I wasn't sure how and it didn't seem worth it if we were just going to deprecate the whole thing anyway.
> core: (Printer) remove variadic prints

- xdsl/dialects/accfg.py
- xdsl/dialects/arith.py
- xdsl/dialects/func.py
- xdsl/dialects/irdl/irdl.py
- xdsl/dialects/memref.py
- xdsl/dialects/pdl.py
- xdsl/dialects/riscv_func.py
- xdsl/dialects/utils/format.py
Removes a bunch of uses of `Printer.print`. This isn't complete but I thought doing this in batches would help the reviewing process.
Only non trivial thing I've done here is use some `printer.in_parens()` when possible.
> misc: (Printer) remove print uses, 'easy cases'

- xdsl/irdl/attributes.py
This means that, for example, `i64` is now an `IRDLGenericAttrConstraint[IntegerType]` instead of an `IRDLGenericAttrConstraint[Attribute]`.
I believe this was just an oversight in the original definition and hadn't been a problem yet.
> core: Tighten typing of IRDLGenericAttrConstraint

- xdsl/dialects/x86/ops.py
- xdsl/irdl/attributes.py
With TypeForm, we already handle the case where the TypeVar is a type, it turns out that there were a bunch of uses of this in a context where the TypeVar used was not a generic parameter of the operation, which feels like a bug to me.
> misc: remove TypeVar from list of allowed values in IRDLGenericAttrConstraint

- xdsl/dialects/x86/ops.py
- xdsl/irdl/attributes.py
Note that this wasn't used anywhere, and as far as I can tell was always broken. ConstraintVars are used as one of the list of annotations, and are handled by `irdl_list_to_attr_constraint`, there's no need to pass them to `irdl_to_attr_constraint`.
> misc: remove ConstraintVar from list of allowed values in IRDLGenericAttrConstraint

- .github/workflows/ci-mlir.yml
Seems to me this was just missed at some point?
> Add python 3.13 to mlir ci

- tests/test_printer.py
- xdsl/dialects/builtin.py
- xdsl/printer.py
Series of PRs to try to improve standardisation of `print_int` and `print_float`
This helper seems be used in one place, and it seems we don't want to add the corresponding `print_int_attr` helper, so this PR inlines it.
> core: (Printer) remove print_float_attr

- xdsl/transforms/csl_stencil_set_global_coeffs.py
Split off from #4577. Avoids making unnecessary temporary FloatAttrs which we would like to deprecate.
> dialects: (csl-stencil) avoid making FloatAttrs

- pyproject.toml
The `LICENSE` file is "Apache License v2.0 with LLVM Exceptions", but the `pyproject.toml` licence text is MIT. This PR updates `pyproject.toml` to have the correct licence.
> misc: resolve licence mismatch in pyproject.toml

- xdsl/dialects/irdl/pyrdl_to_irdl.py
- xdsl/transforms/lower_csl_stencil.py
Tiny cleanup PR, Pyright in Zed was complaining about this for some reason, technically each variable can only be declared once in a scope.
> misc: remove some duplicate declarations

- tests/filecheck/frontend/programs/call.py
- xdsl/frontend/pyast/code_generation.py
- xdsl/frontend/pyast/type_conversion.py
Add support for calling functions with positional and keyword arguments defined as symref variables. This supports code generation for cases like this:
```python
from ctypes import c_int32
from xdsl.dialects import arith, builtin
from xdsl.frontend.pyast.context import CodeContext
from xdsl.frontend.pyast.program import FrontendProgram
def add_i32(operand1: c_int32, operand2: c_int32) -> c_int32: ...
p1 = FrontendProgram()
p1.register_type(c_int32, builtin.i32)
p1.register_function(add_i32, arith.AddiOp)
with CodeContext(p1):
def foo(x: c_int32, y: c_int32) -> c_int32:
return add_i32(x, operand2=y)
p1.compile()
print(p1.textual_format())
```
into
```mlir
builtin.module {
func.func @foo(%x : i32, %y : i32) -> i32 {
%0 = arith.addi %x, %y : i32
func.return %0 : i32
}
}
```
which then …
> frontend: (pyast) add support for calling functions with variable arguments

- tests/irdl/test_attribute_definition.py
- tests/test_pyrdl.py
- xdsl/irdl/attributes.py
- xdsl/utils/exceptions.py
Makes our exceptions a little more precise. Also adds doc strings for existing PyRDL errors.
> core: add PyRDLTypeError for irdl_to_attr_constraint

- tests/filecheck/parser-printer/metadata.mlir
- xdsl/printer.py
Cleans up some of the printing functions in `xdsl.printer`, using delimiter/indentation functions where possible, and using `print_int` for integers etc.
> core: (Printer) cleanup core printing functions

- tests/filecheck/dialects/llvm/example.mlir
- xdsl/dialects/llvm.py
The unreachable OP in the LLVM dialect, we need this for the Fortran work and this wasn't part of the xDSL LLVM dialect. A very simple operation in and of itself
> dialects: (llvm) Add unreachable operation

- tests/irdl/test_declarative_assembly_format.py
- xdsl/dialects/builtin.py
Just makes it a bit more ergonomic. Instead of:
```python
IntegerAttr.constr(value=IntAttrConstraint(AtLeast(7)))
```
you can write
```python
IntegerAttr.constr(value=AtLeast(7))
```
cc @Jimmy2027
> dialects: (builtin) allow `IntConstraint`s in IntegerAttr.constr

- xdsl/dialects/builtin.py
- xdsl/tools/xdsl_tblgen.py
As far as I can tell this isn't actually part of MLIR's builtin dialect, and we don't use it anywhere.
> dialects: (builtin) remove SymbolNameAttr

- tests/irdl/test_attr_constraint.py
- tests/irdl/test_attribute_definition.py
- tests/irdl/test_operation_definition.py
- tests/test_pyrdl.py
- xdsl/irdl/constraints.py
I had a go at enforcing that the sets of bases are disjoint in `AnyOf` constraints. This is all the things that need to be changed. I think the only possible meaningful one is the `StencilType` change.
My hope is that this will allow:
- simplifying the verify method for `AnyOf`, as instead of the context copying stuff, we can just ensure that we are going down the correct branch first. An alternative to performing the check manually is to try to enforce that all constraints should check their base is correct before setting any variables (which most do).
- allow variables to be set by `AnyOf`. Extracting variables from anyof should be safe once branches are disjoint. This will allow us to get rid of `TypedAttributeConstraint`
> core: (constraints) ensure `AnyOf` cases are disjoint

- xdsl/dialects/experimental/fir.py
Added BoxOffsetOp to the FIR experimental dialect which is used by Flang 20.1.7 to extract the underlying LLVM pointer of a box which can then be passed to external APIs, such as OpenMP or OpenACC
> dialects: (fir) Add BoxOffsetOp to FIR dialect

- tests/filecheck/dialects/arith/arith_invalid.mlir
- xdsl/irdl/constraints.py
Thought I'd make a draft PR to further motivate the disjointness changes. Could probably be cleaned up a bit, but this is at least a proof of concept. 
Would it be possible to try some of the verification benchmarks on this? Would like to know if this actually improves anything/makes stuff worse/whether it's better to just iterate through tuples rather than making dictionaries and sets etc.
> core: (AnyOf) verify without backtracking

- tests/dialects/test_llvm.py
- xdsl/dialects/llvm.py
The llvm.GlobalOp operation can have a body associated with it, however the operation's initialisation in xDSL always set this to be empty. Therefore have added an optional body parameter to the function so that this can be set by the caller.
The xDSL MLIR filecheck test for globalop already has a body associated with it
> dialects: (llvm) Fixed bug in GlobalOp where body was always empty when initialised

- tests/filecheck/transforms/test_transform_dialect_erase_schedule.mlir
- xdsl/transforms/__init__.py
- xdsl/transforms/test_transform_dialect_erase_schedule.py
Unlike the MLIR counterpart, we erase only named sequence, because we don't have a `TransformOpInterface`. Should get the same result in most cases though.
CC @erick-xanadu
> transformations: add test-transform-dialect-erase-schedule

- tests/filecheck/dialects/omp/ops.mlir
- tests/filecheck/dialects/omp/ops_invalid.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/omp/ops.mlir
- xdsl/dialects/omp.py
Implements the upstream `omp.simd` operation.
I wasn't sure how to handle the "less than or equal to" constraint on `safelen` and `simdlen`. @superlopuh is there some way to do this without the `verify_`?
> dialects:(omp) add omp.simd operation

- tests/filecheck/dialects/omp/ops.mlir
- tests/filecheck/dialects/omp/ops_invalid.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/omp/ops.mlir
- xdsl/dialects/omp.py
This also makes `map_type` and `map_capture_type` required properties of `omp.map.info`. Upstream, in `llvmorg-20.1.7` they are defined as `OptionalAttr<UI64Attr>` and `OptionalAttr<VariableCaptureKindAttr>` respectively, but later assumed to be present, this appears to be a bug.
Both are non-optional on HEAD.
`TargetEnterDataOp`, `TargetExitDataOp` and `TargetUpdateOp` will follow in a separate PR.
> dialects:(omp) add `omp.target_data` op

- tests/filecheck/dialects/omp/ops.mlir
- tests/filecheck/dialects/omp/ops_invalid.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/omp/ops.mlir
- xdsl/dialects/omp.py
Also adds an extra constraint on mapped values which was missed in the previous PR: When the `map_type` is constrained to one of a number of flags, these constraints are on the `var_ptr` operand to `omp.map.info`, not on the result of `omp.map.info`. So we need to keep track of which flags have already been used with which operands.
**Operations added:**
* TargetEnterDataOp
* TargetExitDataOp
* TargetUpdateOp
> dialects:(omp) add task based data mapping ops

- tests/test_ir.py
- xdsl/ir/core.py
It seems like this functionality was deleted at some point.
> core: make Region hashable again

- tests/filecheck/dialects/memref/invalid_ops.mlir
- tests/filecheck/dialects/tensor/invalid_ops.mlir
- xdsl/dialects/memref.py
- xdsl/dialects/tensor.py
- xdsl/dialects/utils/reshape_ops_utils.py
Used by #4245
Inspired by the MLIR counterpart:
https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/Utils/ReshapeOpsUtils.h
I'm thinking that in theory reshape utils can be shared by any dialect having reshape-like ops
> dialects: Add a reshape_ops_utils.py

- tests/ir/test_region_utils.py
- xdsl/ir/region_utils.py
MLIR has a number of utils files with useful functions. I think we would benefit from this kind of pattern to make the surface area of core.py smaller. This file adds a function I'll need to port the vectorization infrastructure.
> API: add region_utils and used_values_defined_above

- docs/Toy/Toy_Ch1.ipynb
- docs/Toy/toy/__main__.py
- docs/Toy/toy/compiler.py
- docs/Toy/toy/frontend/parser.py
- docs/Toy/toy/tests/test_ir_gen.py
- docs/Toy/toy/tests/test_parser.py
This class was written before we enforced snake_case everywhere.
Please note that I'll tweak names and implementation in a later PR, and only want to fix the casing in this one.
> documentation: (Toy) use snake_case in ToyParser methods

- docs/Toy/toy/frontend/ir_gen.py
- docs/Toy/toy/frontend/toy_ast.py
This is the only "functional" helper in the AST that's not to do with the data structure or printing, it belongs in the parser.
> documentation: (Toy) remove flattened_values from LiteralExprAST

- xdsl/ir/core.py
- xdsl/utils/diagnostic.py
There's a few places where types are actually one of a limited set, I propose to migrate to this pattern when this is the case. Two more places to do this: Attribute = ParametrizedAttribute | Data, and then some AST things in Toy.
As a drive-by fix, I replaced the recursive functions on IRNode with loopy ones, this isn't strictly necessary, but should be a bit faster.
> misc: IRNode = Operation | Region | Block

- docs/Toy/Toy_Ch1.ipynb
- docs/Toy/examples/ast.toy
- docs/Toy/toy/frontend/toy_ast.py
Relatively small change to use NamedTuple instead of dataclass in the Toy AST infrastructure.
> documentation: (Toy) use NamedTuple for Toy AST

- tests/filecheck/dialects/emitc/emitc_types.mlir
- tests/filecheck/dialects/emitc/emitc_types_invalid.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/emitc/emitc_types.mlir
- xdsl/dialects/emitc.py
Add the [emitc opaque](https://mlir.llvm.org/docs/Dialects/EmitC/#opaquetype) type with some tests.
> dialects: (emitc) Add OpaqueType

- tests/xdsl_opt/test_xdsl_opt.py
- xdsl/interactive/app.py
- xdsl/interpreters/transform.py
- xdsl/passes.py
- xdsl/xdsl_opt_main.py
A minor change in the API that hopefully simplifies things a bit. I'd like to leverage this class a bit more, so I thought I'd simplify the point of use first.
> misc: replace PipelinePass.iter_passes with parse_spec

- docs/marimo/linalg_snitch.py
- xdsl/interactive/app.py
- xdsl/interactive/get_all_available_passes.py
- xdsl/interactive/passes.py
- xdsl/interpreters/transform.py
- xdsl/passes.py
- xdsl/utils/marimo.py
- xdsl/xdsl_opt_main.py
So I believe that the current situation is kind of broken, in that it's a pass with no name, which feels weird. I think this makes a bit more sense, where the class is not a pass but has a similar API, and cannot be mixed up with other passes as far as the type system is concerned, until it's specified explicitly.
> API: PipelinePass -> PassPipeline

- xdsl/irdl/constraints.py
These are no longer used (and as far as I know we have no plans to use them?)
> core: (ConstraintContext) deprecate copy and update

- tests/test_affine_builtins.py
- xdsl/ir/affine/affine_map.py
Add some more helpers from MLIR's AffineMap.
> core: add AffineMap inverse_and_broadcast_projected_permutation and drop_results

- xdsl/dialects/linalg.py
- xdsl/transforms/csl_stencil_bufferize.py
- xdsl/transforms/linalg_to_csl.py
- xdsl/transforms/linalg_transformations.py
Minor naming cleanup PR before more changes in the dialect.
> dialects: (linalg) use `Operation` as abstract operation suffix

- tests/filecheck/dialects/emitc/emitc_types.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/emitc/emitc_types.mlir
- xdsl/dialects/emitc.py
Add the emitc [SignedSizeTType](https://mlir.llvm.org/docs/Dialects/EmitC/#signedsizettype)
> dialects: (emitc) Add SignedSizeTType

- xdsl/builder.py
- xdsl/pattern_rewriter.py
Spotted this bit of weirdness where we actually have two operations on PatternRewriter, `insert` and `insert_op`. It feels like we should probably have just one, but they're different enough that it would be a bit of a painful transition. This PR makes it so that they at least both set `has_done_action`, maybe we should deprecate one of them in the future.
> API: unify PatternRewriter.insert and .insert_op

- tests/test_affine_builtins.py
- xdsl/ir/affine/affine_map.py
Reopen #4210, I realised that I actually would be useful to have a shortcut to apply permutations to non-int inputs, such as permuting tuples of attributes.
> core: (affine) add apply_permutation helper to AffineMap

- tests/filecheck/dialects/arm_neon/test_attrs.mlir
- tests/filecheck/parser-printer/graph_region.mlir
- tests/filecheck/parser-printer/parse_error.mlir
- tests/interactive/test_app.py
- tests/test_parser_error.py
- xdsl/utils/lexer.py
This seems to be the convention in all IDEs and error messages, and can be verified by copy/pasting one of the changed messages in the filecheck tests to the terminal in VSCode, and command-clicking it, the new 1-indexed columns point to the right place.
> misc: columns in debug messages start at 1

- docs/Toy/toy/compiler.py
- docs/Toy/toy/rewrites/lower_toy.py
I'd like to at some point lower to linalg instead since we have much better support for that, this will minimise the diff when I merge that in the future. I also think that this is just a better name regardless of whether we change the target in the future, as it's more consistent with the other toy passes and xDSL's naming.
> documentation: (Toy) LowerToAffinePass -> LowerToyPass

- tests/irdl/test_declarative_assembly_format.py
- tests/test_parser.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Note: I'm not too familiar with this part of the code base. Some reviews and direction would be greatly appreciated.
This PR adds support for [optional groups' `else-elements`.](https://mlir.llvm.org/docs/DefiningDialects/Operations/#optional-groups)
> Add support for optional groups' `else-elements`

- tests/filecheck/backend/x86/convert_ptr_to_x86.mlir
- xdsl/backend/x86/lowering/convert_ptr_to_x86.py
We should watch out for this pattern. When lowering from SSA to SSA-with-registers, it's important to not introduce aliasing via same-register constraints. In SSA, values are immutable, but when we add registers to the mix mutation can occur, so copies have to be added to be safe. The standard RISC-V ISA doesn't have inout registers, so I've not had to deal with this, but x86 and ARM have plenty of it so we'll have to be careful.
> transformations: (convert-ptr-to-x86) insert mov to inout reg

- pyproject.toml
- tests/filecheck/frontend/programs/code_generation_exceptions.py
- tests/filecheck/frontend/programs/frontend_program_exceptions.py
- tests/test_frontend_python_code_check.py
Removes the last non-marimo Pyright file-wide exceptions!
> CI: add specific Pyright ignores to frontend tests

- tests/pattern_rewriter/test_pattern_rewriter.py
- tests/test_ir.py
- xdsl/ir/core.py
I think we should rarely use raise Exception, and we may want to consider a more precise error for illegal IR manipulation in the future, but this seems like a safe improvement.
> misc: use ValueError in core.py

- tests/filecheck/dialects/snitch_runtime/snitch_runtime_invalid.mlir
- xdsl/dialects/snitch_runtime.py
Seems to be the only generic operation we have, but it's interesting that this seems to work.
> dialects: (snitch-runtime) remove `ConstraintVar`

- pyproject.toml
- tests/dialects/test_arith.py
- tests/dialects/test_llvm.py
- tests/dialects/test_pdl.py
- tests/irdl/test_operation_builder.py
- tests/test_dialect_interfaces.py
- tests/test_frontend_op_inserter.py
- tests/test_frontend_python_code_check.py
- tests/test_immutable_list.py
- tests/test_interpreter.py
- tests/test_ir.py
- tests/test_op_builder.py
- tests/test_rewriter.py
- tests/test_ssa_value.py
- tests/test_traits.py
I think this is a nice linting error. I also moved the message testing to the match clause, which is important for when the exception type is not initialised with just a string.
> testing: use match argument for error testing

- tests/filecheck/utils/codegen/simple.py
- tests/xdsl_tblgen/test.py
- xdsl/dialects/arith.py
- xdsl/dialects/builtin.py
- xdsl/tools/xdsl_tblgen.py
Based on #4785, it seems like prioritising a single parameter to be positional is ergonomic. I propose here making the `type` parameter of `IntegerAttr` positional, as it is by far the most used.
> dialects: (builtin) make `type` positional in IntegerAttr.constr

- tests/irdl/test_operation_definition.py
- xdsl/irdl/attributes.py
- xdsl/irdl/operations.py
`param_def` api means that this can finally be scrapped.
> core: (Constraints) deprecate `ConstraintVar`

- tests/irdl/test_attribute_definition.py
- xdsl/dialects/irdl/pyrdl_to_irdl.py
- xdsl/interpreters/irdl.py
- xdsl/irdl/attributes.py
- xdsl/utils/dialect_stub.py
As suggested in #4755, adds a named tuple for holding information on a parameter. In the future this will hold a converter and possibly default values (if this makes sense).
> core: (ParametrizedAttribute) add `ParamDef` for "resolved" fields

- tests/irdl/test_declarative_assembly_format.py
- xdsl/dialects/builtin.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Adds a new constraint `SymbolNameConstr`, which takes the role that `SymbolNameAttr` does in MLIR (note that `SymbolNameAttr` is not an attribute in MLIR, but some tablegen construct that I think translates to a constraint).
The assembly format then uses this information to parse/print the attribute as a symbol. Made this work with optional attributes and optional groups.
> core: (SymbolNameConstraint) add assembly format symbol names

- xdsl/irdl/operations.py
Seems wasteful, we should probably do a full rewrite of this part of the code to be more performant.
> misc: don't construct a new DenseArrayBase.constr(i32)

- xdsl/dialects/arith.py
- xdsl/irdl/constraints.py
With the new(ish) `AnyOf` mechanisms/restrictions, we can now infer variables from "any of" constraints when that variable appears in all branches. 
This can be used in arith.constant in place of `TypedAttributeConstraint` (which I intend to deprecate)
If wanted, I can split this into two PRs:
- Change AnyOf (finding a suitable test to add)
- Change arith.constant
> core: (AnyOf) allow variable inference and use for arith.constant

- tests/filecheck/frontend/programs/new_api.py
- xdsl/frontend/builder.py
- xdsl/frontend/pyast/context.py
- xdsl/frontend/pyast/program.py
This PR adds a new decorator-based API for frontend code generation. This will supersede the old context manager API.
An example of this new API is as follows:
```python
from xdsl.dialects.arith import AddfOp, MulfOp
from xdsl.dialects.builtin import f64
from xdsl.frontend.pyast.context import PyASTContext
ctx = PyASTContext()
ctx.register_type(float, f64)
ctx.register_function(float.__add__, AddfOp)
ctx.register_function(float.__mul__, MulfOp)
@ctx.parse_program
def test_arith(x: float, y: float, z: float) -> float:
return x + y * z
print(test_arith(1.0, 2.0, 3.0))
print(test_arith.module)
```
> frontend: (pyast) add new decorator-based API for frontend code generation

- tests/irdl/test_range_constraint.py
- xdsl/irdl/constraints.py
Unlike `RangeOf`, which takes an attribute constraint and a length constraint, this constraint takes a range constraint and a length constraint.
> core: add RangeLengthConstraint

- xdsl/dialects/experimental/fir.py
An additional fortran variable flag and optional properties in the global operation that are present in Flang 20.7.1 but were missing in our FIR dialect
> dialects: (fir) FIR compatibility with Flang 20.7.1

- tests/filecheck/dialects/linalg/linalg_ops.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
- xdsl/dialects/linalg.py
This PR includes following changes:
1. Add a class for `CopyOp` in Linalg 
https://github.com/xdslproject/xdsl/blob/b8b33b94230ab42cb7ccdfaf9cc1105bb1e869a0/xdsl/dialects/linalg.py#L754
2. Update test cases for `CopyOp` with tensors and memref
> dialects: (linalg) Add support for copy operation

- benchmarks/README.md
- benchmarks/parser.py
- benchmarks/workloads.py
#4834 discusses speeding up parsing by improving the way byte contents of strings are retrieved. This PR incorporates the benchmark proposed in the PR into the benchmarking suite for xDSL
> bench: incorporate benchmark proposed in #4834

- tests/filecheck/transforms/eqsat-add-costs-with-default.mlir
- tests/filecheck/transforms/eqsat-add-costs.mlir
- xdsl/transforms/eqsat_add_costs.py
In the presence of cycles, our toy cost model falls over, as we calculate costs top to bottom. This PR adds a parameter to both the helper functions and the pass to provide a default value when it cannot be computed. The default behaviour is unchanged, but we now have an escape hatch to guarantee that we can extract something out of nothing (even if the order and dominance aren't guaranteed to be preserved).
> transformations: (eqsat-add-costs) add default cost

- tests/filecheck/dce.mlir
- xdsl/dialects/memref.py
Added traits to operations in the memref dialect where they were missing from, to set the memory effect for operations which is then leveraged by transformation passes so is beneficial to have them provided
> dialects: (memref) Add missing traits to operations

- tests/dialects/test_irdl.py
- tests/dialects/test_irdl_with_annotations.py
- tests/irdl/test_attribute_definition.py
- xdsl/irdl/attributes.py
- xdsl/irdl/operations.py
- xdsl/utils/classvar.py
Makes the error message slightly worse but makes things a bit more consistent.
> misc: (utils) move `is_const_classvar` to utils

- tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/attrs.mlir
I can't figure out hoew go get the CI to catch this.
> CI: use --allow-unregistered-dialect in LLVM attrs test

- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
This is the final field to add to AttributeVariable, PRs from now on will factor out functionality associated with the other fields.
> core: add `is_optional` field to AttributeVariable directive

- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Now a subclass instead of a property.
> core: factor out SymbolNameAttributeVariable

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Adds functionality present in MLIR, where the special assembly format for DenseArrayBase of a specific subclass is printed prettily.
> core: add special handling of DenseArrayBase in assembly format

- tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
- tests/interpreters/test_linalg_interpreter.py
- xdsl/dialects/linalg.py
This is a bug fix for the broadcast and transpose linalg methods, where the result type is varadic but the default result init method is None, which results in an error. This therefore fixes that by defaulting to an empty list.
This also ensures these two operations match MLIR behaviour which is when the outs type is a tensor then the result type of the operation is a tensor, otherwise if the outs type is a memref then there is no result type. The parsing routing did not handle this, so this nuance is now added (the verification already picked this up, as the only result type can be a tensor). This meant we could not use memrefs as output from these operations when passed to MLIR, which we can now.
I have updated the filecheck test to include no result type with memref as outs type
> dialects: (linalg) Broadcast and transpose op init methods take sequence of result types

- tests/filecheck/dialects/tosa/ops.mlir
- xdsl/dialects/tosa.py
Adds operations for `tosa.cos` and `tosa.sin` and a positive roundtrip test case
> dialects: (tosa) implement trig operations

- tests/test_use.py
- xdsl/ir/core.py
- xdsl/transforms/experimental/dmp/stencil_global_to_local.py
- xdsl/transforms/stencil_bufferize.py
- xdsl/transforms/test_constant_folding.py
Stacked PRs:
* #4909
* #4908
* #4907
* __->__#4906
--- --- ---
This is a refactor which will make it easier to make `IRWithUses` use
a linked list.
> core: Abstract `uses` field from `IRWithUses`

- tests/irdl/test_attribute_definition.py
- xdsl/ir/core.py
Removes the deprecated `__init__` and test
> misc: (ParametrizedAttribute) remove deprecated init

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Duplicate region and successor keys were not caught before
> core: (AssemblyFormat) add missing errors for duplicate keys

- xdsl/irdl/declarative_assembly_format_parser.py
> misc: (Format parser) use `in_parens`

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
Adds ref directives, which allow a variable to be passed to a custom directive even if it has already appeared in the assembly format.
> core: (Assembly Format) add ref directive

- tests/filecheck/dialects/linalg/invalid.mlir
- tests/filecheck/dialects/linalg/linalg_ops.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
- xdsl/dialects/linalg.py
The linalg.reduce operation which applies body of calculation on an element by element basis to one or more dimensions of a tensor or memref
> dialects: (linalg) add reduction operation to linalg dialect

- tests/filecheck/dialects/dlti/attrs.mlir
- tests/filecheck/dialects/dlti/attrs_invalid.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/dlti/attrs.mlir
- xdsl/dialects/dlti.py
Added MapAttr to the DLTI dialect. Also added verification check that DataLayoutEntryAttr key is not an empty string (which conforms to MLIR behaviour)
> dialects: (dlti) add mapattr

- tests/filecheck/dialects/x86/x86_assembly_emission.mlir
- xdsl/dialects/x86/ops.py
Clang's assembler on linux is not happy without this being explicitly stated, as it assumes AT&T.
> dialects: (x86) print `.intel_syntax noprefix` in assembly

- tests/filecheck/dialects/x86/canonicalize.mlir
- xdsl/dialects/x86/ops.py
This allows unused reads to get optimised out.
> dialects: (x86) add MemoryReadEffect to DM_Operation

- xdsl/interpreters/eqsat_pdl_interp.py
- xdsl/ir/core.py
- xdsl/transforms/dead_code_elimination.py
Before:
```
❯ python benchmarks/rewriting.py RemoveUnused.is_trivially_dead dis
===========================================
Events recorded: 58
Opcodes recorded: 40
Uninstrumented: 350.35 ns
Uninstrumented per opcode: 8.76 ns/op
Instrumented: 11895.62 ns
Instrumented per opcode: 297.39 ns/op
Elapsed: 4825.74 ns
Elapsed per opcode: 120.64 ns/op
Opcode overhead: 0.00 ns/op
Tracing overhead per opcode: 111.88 ns/op
===========================================
```
After:
```
❯ python benchmarks/rewriting.py RemoveUnused.is_trivially_dead dis ===========================================
Events recorded: 39
Opcodes recorded: 27
Uninstrumented: 220.84 ns
Uninstrumented per opcode: 8.18 ns/op
Instrumented: 7753.91 ns
Instrumented per opcode: 287.18 ns/op
Elapsed: 2951.75 ns
Elapsed per opcode: …
```
> core: speed up checking for uses

- tests/interactive/test_app.py
- tests/interactive/test_get_all_available_passes.py
- tests/interactive/test_rewrites.py
- xdsl/interactive/app.py
- xdsl/interactive/get_all_available_passes.py
- xdsl/interactive/passes.py
- xdsl/interactive/rewrites.py
Currently our individual rewrites are displayed differently, but I'm not sure that the extra logic is pulling its weight, especially since they are printed differently once they are clicked on and added to the pass pipeline.
> interactive: display pass spec in gui always

- tests/dialects/test_dlti.py
- tests/filecheck/dialects/dlti/attrs_invalid.mlir
- xdsl/dialects/dlti.py
DLTI dialect initialises the entry map operations based on a dictionary or list, and the entries themselves are initialised based on str or attribute (for key), and attribute, str, int or float for value. This is for convenience when creating these in code.
Pyright test added for this, along with testing verification of aspects in the dialect too
> dialects: (dlti) Add initialisation convenience from dictionary and python types

- tests/filecheck/transforms/vector-split-load-extract.mlir
- xdsl/transforms/__init__.py
- xdsl/transforms/vector_split_load_extract.py
This transformation doesn't always make sense to perform, but it does in the case of vectorisation of matmul for NEON and AVX. it feels like this might make sense eventually as a transform thing but until then I propose we add a pass.
> transformations: add split-load-extract for manual optimization

- tests/test_parser.py
- xdsl/utils/mlir_lexer.py
Saves 6% = 1-0.782s/0.834s when loading arith
> core: move out KIND_BY_PUNCTUATION_SPELLING in MLIR lexer

- mkdocs.yml
The documentation website style PR commented out the auto-generation of code documentation and jupyter notebooks to speed up development. This was accidentally merged, with this PR uncommenting them to add them back
> documentation: add back autogenerated documentation to nav

- xdsl/xdsl_opt_main.py
I'm guessing that verification is run on Attribute post_init instead of being recursively called from operation verifications as Attributes should be immutable? 
It would be nice to have these not run when `--disable-verify` is on, and this is the best way I could think of doing it. This does feel a bit hacky though, and It won't effect benchmarking. I wonder if it's just worth taking the hit and recursively activating the attribute verification.
> tool: (xdsl-opt) Disable attribute verify on `--disable-verify`

- pyproject.toml
- uv.lock
This lets us add dev dependencies that aren't distributed with xdsl optional dependencies. In the future it would make sense to move things like ruff in there also, even if I think it's useful to ship some dependencies to make it easier to set up downstream xdsl modules.
> misc: add `dependency-groups` to make `uv sync` work

- benchmarks/microbenchmarks.py
- pyproject.toml
It turns out that we didn't check the benchmarks with pyright until now, so we didn't spot some API changes. It would be nice to add some tests in the future also, but for the time being I'll just remove the failing test which we no longer care about, fix some API changes, and add the benchmarks folder to be checked with pyright.
> CI: lint benchmarks with pyright

- renovate.json
I guess we try the default config first and see what happens. From reading the docs this should try to update the lock file once a week. I'm not 100% sure if this is a great idea without any CI but I guess I can manually test the commits for now.
Is there a way to get renovate to test the config in this PR?
> installation: try renovate nix support

- tests/filecheck/backend/x86/convert_ptr_to_x86.mlir
- xdsl/backend/x86/lowering/convert_arith_to_x86.py
- xdsl/backend/x86/lowering/convert_ptr_to_x86.py
- xdsl/backend/x86/lowering/convert_vector_to_x86.py
- xdsl/backend/x86/lowering/helpers.py
The aim of this PR is to unify the register type getters. These shouldn't be separate, as we need a way to generically handle lowering target-independent values passed in functions and as loop iter arguments. The best way I could come up with to model this is the `Arch` enum, although it feels like that's a bit of a misnomer. It would be nice to polish this later and get it to be more in line with how LLVM represents the same concept in its backend, hopefully in an extensible way. I think this will do for now, though.
> backend: (x86) add Arch enum and use for register type selection

- xdsl/dialects/tosa.py
otherwise .get_values() gives pyright errors
> dialects: (tosa) add generic types to multiplier and shift properties

- xdsl/irdl/operations.py
Step one of simplifying some of the variadics infrastructure. This removes the last use of the return value for `get_variadic_sizes`, which should allow that method to be simplified. We instead rely on the operation accessors to get the various variadic ranges.
I've kept the logic to put the slice in the error message instead of referring to it by construct name, as I fear the resulting diff from changing all the tests would be very large.
> core: (Operation) simplify `irdl_op_verify_arg_list`

- tests/dialects/test_smt.py
- xdsl/dialects/smt.py
I really really find the `.from_value_and_type` too verbose.
`BvConstantOp(4, 32)` is much more readable to me than `BvConstantOp.from_value_and_type(4, 32)`, which can often span multiple lines.
> dialects: Overload BvConstantOp.__init__

- xdsl/irdl/attributes.py
Slipped during previous changes, as well as an extra call to `irdl_to_attr_constraint` that's just an identity for attributes anyway.
> misc: remove unused type_var_mapping parameter

- Makefile
- scripts/gen_ref_pages.py
Generating our full API reference is too slow for hot reloading.
> documentation: add make docs-serve-fast for easier debugging

- tests/test_pyrdl.py
- xdsl/backend/csl/print_csl.py
- xdsl/dialects/arith.py
- xdsl/dialects/builtin.py
- xdsl/dialects/cf.py
- xdsl/dialects/comb.py
- xdsl/dialects/csl/csl.py
- xdsl/dialects/emitc.py
- xdsl/dialects/linalg.py
- xdsl/dialects/llvm.py
- xdsl/dialects/varith.py
- xdsl/irdl/attributes.py
- xdsl/parser/attribute_parser.py
- xdsl/transforms/constant_fold_interp.py
- xdsl/transforms/lower_csl_stencil.py
- xdsl/transforms/lower_mpi.py
- xdsl/transforms/varith_transformations.py
Also adds functionality to `get_optional_int_constraint` to construct a constraint from a TypeVar.
I updated the EmitC dialect as it's the only one that cares just about the bitwidth and not signedness.
> dialects: (builtin) make IntegerType generic over width type

- tests/irdl/test_declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format.py
- xdsl/irdl/declarative_assembly_format_parser.py
- xdsl/irdl/operations.py
Verifies the test from #4983 
All ended up a bit messier than I would have liked, an alternative could be to store Accessors in the `op_def`. I can probably also split this into multiple PRs
Probably needs a corresponding `operands` and `operand types` test.
> core: ((Operands|Results)Directive) refactor to allow multiple variadics

- tests/filecheck/dialects/builtin/attrs.mlir
Modernizes the filecheck test `dialects/builtins/attrs.mlir` to use `"test.op"` and `CHECK-NEXT` directives. Also adds tests for `si1` and `ui1`
> testing: (builtin) improve attrs filecheck

- xdsl/ir/core.py
context: https://github.com/xdslproject/xdsl/pull/4968#discussion_r2269571403
> core: make `operation._successor_uses` public

- tests/filecheck/dialects/emitc/emitc_types_invalid.mlir
- xdsl/dialects/emitc.py
Was part of #5072, keeping it separate to investigate a type checker issue in test_emitc.py (ref [discussion](https://github.com/xdslproject/xdsl/pull/5072/commits/07a962200fb02b116dfd45779bac70f4c747790c#r2285734120))
> dialects: (emitc) use EmitCArrayElementType in ArrayType

- README.md
Fixes #5101
We'll need to rewrite the Getting Started section and our website I think before the summer school, but this is a simple enough fix in the short term.
> documentation: fix link to GETTING_STARTED.md

- docs/marimo/expressions.py
When the documentation is shipped to readthedocs.io, the wheel is either in the `latest/` or `stable/` branch, but it is currently unclear how to distinguish. As we currently look in `/` which is universally wrong, I change this to `latest/` hoping to fing a more principled soluation over the next weeks.
> documentation: make mkdocs-marimo work on 'latest' branch

- docs/marimo/expressions.py
As list-lang meanwhile supports `let` and `;`, multi-line input is possible, and a text_area is consequently more appropriate.
> documentation: use text_area in expression example

- docs/marimo/expressions.py
This adds a basic pass pipeline, which is not yet hooked up to an interactive flow. However, we add a single slider. It seems currently this slider does not work as the CSS information needed to display it is unavailable. We push this anyhow, to have an online instance where this can be debugged.
This has been extracted from https://github.com/xdslproject/xdsl/pull/5122.
> documentation: marimo expressions - make pass pipeline work

- docs/marimo/expressions.py
The makethedocs releases carry the version as the first directory in the URL. Our xdsl wheel is in the directory after the version.
> documentation: load xdsl for marimo released builds

- docs/marimo/mlir_introduction.py
This is a draft version of the notebook, which is incomplete.
It can be seen using `uv run marimo run docs/marimo/mlir_introduction.py`.
> docs: Add an MLIR introduction notebook

- benchmarks/workloads.py
- tests/dialects/test_arm_neon.py
- tests/dialects/test_builtin.py
- tests/dialects/test_csl.py
- tests/dialects/test_dlti.py
- tests/dialects/test_gpu.py
- tests/filecheck/utils/codegen/simple.py
- tests/interpreters/test_memref_stream_interpreter.py
- tests/irdl/test_declarative_assembly_format.py
- tests/test_rewriter.py
- xdsl/dialects/builtin.py
- xdsl/dialects/csl/csl.py
- xdsl/dialects/stim/ops.py
- xdsl/interpreters/snitch_stream.py
- xdsl/parser/attribute_parser.py
- xdsl/transforms/csl_stencil_set_global_coeffs.py
- xdsl/transforms/function_transformations.py
- xdsl/transforms/linalg_to_csl.py
- xdsl/transforms/lower_csl_stencil.py
Just find/replace throughout project, I think this is a small but strict improvement.
> misc: use f16, f32, etc constants instead of inits

- docs/marimo/mlir_introduction.py
`mo.ui.code_editor` doesn't support `mlir`, but `mo.md` does.
We need to use "`"*3 instead of "```" because otherwise the export fails
> docs: Use `mo.md` instead of code editor for MLIR

- scripts/gen_ref_pages.py
This unused and broken path has been slowing me down recently when trying to add features to the worse-but-working readonly marimo export, I propose adding the md export back in once the features work.
> documentation: disable marimo docs export

- mkdocs.yml
Either this was always broken or they recently changed the default. In either case now the scf dialect documentation works.
> documentation: show reference for class even if missing doc string

- tests/dialects/test_arith.py
- tests/dialects/test_complex.py
- tests/dialects/test_riscv.py
- tests/dialects/test_smt.py
- tests/filecheck/utils/codegen/simple.py
- xdsl/dialects/arith.py
- xdsl/dialects/complex.py
- xdsl/dialects/riscv.py
- xdsl/dialects/smt.py
- xdsl/interfaces.py
- xdsl/traits.py
This adds the `get_constant_value` method to the `ConstantLike` trait and adds a `ConstantLikeInterface` for ease of use.
> core: add ConstantLikeInterface

- docs/marimo/expressions.py
- tests/dialects/test_arith.py
- xdsl/dialect_interfaces.py
- xdsl/dialects/arith.py
- xdsl/transforms/constant_fold_interp.py
This is a dialect interface containing `materialize_constant` to create a constant operation from a dialect given a constant attribute.
I had to use `if TYPE_CHECKING` to handle a circular import issue.
(on top of https://github.com/xdslproject/xdsl/pull/5233)
> core: add ConstantMaterializationInterface

- tests/test_pass_lexer.py
- xdsl/utils/exceptions.py
- xdsl/utils/parse_pipeline.py
The Lexer Token and spec parser Token have the same fields but in a different order. 
This PR removes the last custom Token class, hopefully a non-controversial bit of cleanup.
> core: use Lexer token in spec parser

- tests/filecheck/dialects/riscv/frep_verification.mlir
- tests/filecheck/dialects/riscv_snitch/ops.mlir
- tests/filecheck/dialects/riscv_snitch/verification.mlir
- tests/filecheck/dialects/snitch_stream/ops.mlir
- xdsl/dialects/riscv.py
- xdsl/dialects/riscv_snitch.py
Tiny change motivated by wanting to drop raw int printing in RISC-V assembly. Encodes the bitwidths of the instruction encoding in the constraints of the op.
> dialects: (riscv_snitch) use i3 and i4 for frep params

- docs/marimo/ir_gen.py
The signature given for the `CmpfOp` in the IR generation Tutorial was inconsistent to how it is defined [here](https://github.com/xdslproject/xdsl/blob/621d8000b386f0f47fa20990bd56104247a0f105/xdsl/dialects/arith.py#L936).
> documentation: fix method signature doc in tutorial notebook

- tests/dialects/test_arith.py
- xdsl/dialects/arith.py
- xdsl/interfaces.py
- xdsl/traits.py
This pr includes
* a `HasFolderInterface` operation interface
* ~~a `get_constant_value` in the `ConstantLike` trait~~ (moved to #5233)
* ~~a `ConstantMaterializationInterface ` dialect interface~~ (moved to #5234)
* an implementation of folding for arith's SignlessIntegerBinaryOperation.
~~I'm opening this as a draft to check whether this seems like the right direction for a folding implementation. If it is, I can split this up in separate PRs.~~
> core: add folding mechanism

- tests/filecheck/backend/x86/x86_allocate_registers.mlir
- xdsl/dialects/x86_scf.py
Now supports register allocation. Mostly a copy/paste of riscv_scf implementation. Makes me think that this should actually go into an `asm` dialect, to share between backends.
> dialects: (x86_scf) ForRofOperation: RegisterAllocatableOperation

- tests/dialects/test_tensor.py
- xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
- xdsl/dialects/memref.py
- xdsl/dialects/tensor.py
- xdsl/transforms/convert_stencil_to_csl_stencil.py
- xdsl/transforms/csl_stencil_bufferize.py
- xdsl/transforms/memref_to_dsd.py
The two definitions of DYNAMIC_INDEX now agree so let's use the one in builtin.
> dialects: (memref) remove memref.SubviewOp.DYNAMIC_INDEX

- tests/irdl/test_declarative_assembly_format.py
- xdsl/dialects/utils/dynamic_index_list.py
Adds support for `custom<DynamicIndexList>` to be used as an aqchorable directive, as in C++ MLIR. This lets it be used in optional clauses, which [some MLIR operations](https://github.com/llvm/llvm-project/blob/6146a88f60492b520a36f8f8f3231e15f3cc6082/mlir/include/mlir/Dialect/Mesh/IR/MeshOps.td#L305) use.
e.g. you can have assembly formats as the following:
```assembly_format = (`keyword` custom<DynamicIndexList>($dynamics, $statics)^)?```
Not super familiar with this code so open to feedback
> core: (assembly-format) Add optional anchor support for `Custom<DynamicIndexList>`

- xdsl/dialects/builtin.py
The layout attribute of a `MemRefType` should allow for any attribute that implements the `MemRefLayoutAttr` base class
Made possible through #5240
> dialects: (builtin) MemReftype layout constraint is MemRefLayoutAttr | NoneAttr

- xdsl/dialects/builtin.py
We used to need this for some constraint logic but we no longer require it.
> dialects: (builtin) remove abstract name from MemRefLayoutAttr

- tests/filecheck/dialects/tosa/ops.mlir
- tests/filecheck/mlir-conversion/with-mlir/dialects/tosa/ops.mlir
- xdsl/dialects/tosa.py
Adds the reciprocal and reduce operations to the TOSA dialect, with xDSL roundtrip and MLIR conversion tests.
> dialects: (tosa) add reciprocal, reduce operations

- tests/utils/test_disjoint_set.py
- xdsl/utils/disjoint_set.py
Sometimes it's useful to force a particular set to become the representative when `union`ing two sets. E.g. in eqsat when merging an `EClassOp` with a `ConstantEClassOp`, we want the `ConstantEClassOp` to be representative.
(`ConstantEClassOp` is yet to be merged)
> misc: (DisjointSet) Add `rooted_union` method to DisjointSet
