xdslproject/xdsl

src/xdsl/printer.py

This allows printing to streams by constructing a Printer using
a StringIO object.

Allow printing to arbitrary stream

---

src/xdsl/rewriter.py
tests/rewriter_test.py

The rewrite pattern takes multiple rewrite patterns, and applies them in order until one match.

Add greedy rewrite pattern

---

src/xdsl/rewriter.py

This commit introduces BlockArguments bookkeeping for the
PatternRewriteWalker. Fixes #19

Rewriter: add support for BlockArguments

---

src/xdsl/dialects/builtin.py
src/xdsl/dialects/memref.py

Add explicit superclasses for attributes, and use annotation type hints.

(NFC) Improve a bit more IDE support

---

src/xdsl/dialects/builtin.py
src/xdsl/ir.py

This adds a new constructor for FuncOp, and also clean two constructors.

Func constructor

---

src/xdsl/ir.py
src/xdsl/pattern_rewriter.py
tests/pattern_rewriter_test.py

This commit allows to add new operations after a match

Add insert_op_after_match

---

src/xdsl/dialects/cf.py
src/xdsl/parser.py
tests/cf_test.py

Basic block arguments are just added as operands to the argument list. The get() interface still needs some testing and the printing is not yet very intuitive.

Add br and cond_br operations to std

---

src/xdsl/ir.py
src/xdsl/irdl.py

This is an attempt at fixing pyright errors in ChocoPy.

Fix build typing error

---

docs/irdl.ipynb
docs/tutorial.ipynb

Updates the jupyter notebooks to the current API.

Update notebook to current API

---

src/xdsl/rewriter.py
tests/rewriter_test.py

I found a small bug in the code I commited yesterday. This fixes it and adds a regression test case.

fix return bug

---

src/xdsl/irdl.py
tests/filecheck/cf_ops.xdsl
tests/operation_builder_test.py

This should fix the segment size issue we had. Fixes #91

Fix segment sizes

---

src/xdsl/dialects/memref.py
src/xdsl/irdl.py
src/xdsl/mlir_converter.py
tests/filecheck/cf_ops.xdsl
tests/filecheck/memref_ops.xdsl
tests/filecheck/mlir-conversion/lit.local.cfg
tests/filecheck/mlir-conversion/ops.xdsl
tests/operation_builder_test.py

This should fix the remaining issues I found in the mlir_conversion.
Fix #90 
Note: first merge #92 and then rebase before merge.

Fix mlir conversion

---

src/tools/xdsl-opt
src/xdsl/diagnostic.py
src/xdsl/dialects/arith.py
src/xdsl/irdl.py
src/xdsl/xdsl_opt_main.py
tests/filecheck/arith_invalid.xdsl

This is one possible solution to support invalid test cases. 
I'm not that happy with it,but I do not see a nicer way of integrating this into the opt tool.

Add support for invalid tests

---

src/xdsl/ir.py

This adds support for cloning operations with regions. 
Remapping of operands and successors is handled in the process

add support for cloning operations with regions

---

requirements.txt

Passing locally, submit for testing, so as to activate dependabot

reqs: Update to latest requirements

---

src/xdsl/dialects/builtin.py
tests/filecheck/builtin_types.xdsl

This patch adds the [TupleType](https://mlir.llvm.org/docs/Dialects/Builtin/#tupletype), since I need it for my project :)

Builtin: add TupleType

---

src/xdsl/__init__.py
src/xdsl/mlir_converter.py

This is another attempt to address #111.

Allow loading custom mlir module with load_mlir_module.

---

pyproject.toml
src/xdsl/diagnostic.py
src/xdsl/dialects/affine.py
src/xdsl/dialects/scf.py
src/xdsl/ir.py
src/xdsl/irdl.py
src/xdsl/parser.py
src/xdsl/pattern_rewriter.py
src/xdsl/printer.py
src/xdsl/rewriter.py
src/xdsl/util.py
src/xdsl/xdsl_opt_main.py
tests/attribute_builder_test.py
tests/attribute_definition_test.py

This is a cleanup PR for a lot of the typing, previously found here: #118 
I fixed the testcase in irdl as @math-fehr suggested. The last commit is most relevant for this fix.

Update typing (fixed testcase)

---

src/xdsl/util.py
tests/is_satisfying_hint_test.py

Remove deprecated functions in `util.py`, and improve typing in `util.py`.
Also, add tests for type hint checking

Cleanup util.py, and test type hint check

---

README.md
docs/irdl.ipynb
docs/tutorial.ipynb

This PR updates the README and the jupyter notebooks to work with version 0.5.1.

[Docu] update to v0.5.1

---

.github/release-drafter.yml
README.md
src/xdsl/dialects/affine.py
src/xdsl/dialects/arith.py
src/xdsl/dialects/builtin.py
src/xdsl/dialects/cf.py
src/xdsl/dialects/cmath.py
src/xdsl/dialects/func.py
src/xdsl/dialects/memref.py
src/xdsl/dialects/scf.py
src/xdsl/ir.py
src/xdsl/irdl.py
src/xdsl/mlir_converter.py
src/xdsl/parser.py
src/xdsl/pattern_rewriter.py
src/xdsl/printer.py
src/xdsl/rewriter.py
src/xdsl/xdsl_opt_main.py
tests/mlir_converter_test.py
tests/operation_builder_test.py
tests/pattern_rewriter_test.py
tests/printer_test.py
tests/use_test.py

@math-fehr is there any reason why we use star imports in xdsl?
https://www.geeksforgeeks.org/why-import-star-in-python-is-a-bad-idea/
Let me know your thoughts.

docs: drop star imports

---

src/xdsl/mlir_converter.py
tests/filecheck/mlir-conversion/llvm_test.xdsl

This PR adds the necessary functionality to convert nested structs form xdsl to MLIR.

[MLIRConverter] add nested struct conversion

---

src/xdsl/parser.py

Cleanup a bit the parser.py file:
* Add skip_whitespace argument on every function, to make it consistent. Each parsing function can now specify if we should skip whitespaces or not.
* Make everything type with pyright strict

Cleanup parser.py

---

src/xdsl/dialects/func.py

This is the semantics MLIR currently has.

Make sym_visibility an optional attribute in func.func

---

src/xdsl/printer.py

This should not have any functional change, just adding better typing in the `printer.py` file.

Make pyright typing pass on printer.py

---

.gitignore
setup.cfg

Tiny fixup changes to make git behave better on Macs and a cleanup of the `setup.cfg` file

ignore .DS_Store

---

setup.cfg
xdsl/diagnostic.py
xdsl/dialects/affine.py
xdsl/dialects/arith.py
xdsl/dialects/builtin.py
xdsl/dialects/func.py
xdsl/dialects/llvm.py
xdsl/dialects/memref.py
xdsl/dialects/scf.py
xdsl/ir.py
xdsl/irdl.py
xdsl/irdl_mlir_printer.py
xdsl/mlir_converter.py
xdsl/parser.py
xdsl/pattern_rewriter.py
xdsl/printer.py
xdsl/rewriter.py
xdsl/util.py
xdsl/xdsl_opt_main.py

I ran `python -m flake8 xdsl`, and went about getting the number of lint messages to 0.
I recommend reviewing by commit, and if there are any changes you're not happy with, let's take them out to a separate PR because these kinds of things tend to diverge from everything else people are working on pretty quickly, I'd love to merge as much of this as possible soon

xdsl: make flake8 happy with our source files

---

docs/irdl.ipynb
tests/operation_builder_test.py
tests/printer_test.py
xdsl/__init__.py
xdsl/dialects/affine.py
xdsl/dialects/irdl.py
xdsl/ir.py
xdsl/irdl.py
xdsl/irdl_mlir_printer.py
xdsl/mlir_converter.py
xdsl/pattern_rewriter.py
xdsl/xdsl_opt_main.py

Fixed low-hanging fruit of what pylance was complaining about, no major bugs to report.

xdsl: fix some pyright issues (526 -> 386)

---

xdsl/dialects/func.py

While working on the frontend, found that builders for call and return ops are wrong.
P.S. Not sure what is the workflow for fixing xDSL (like do I need tests, etc. here).

[func] fixes to return and call ops

---

tests/attribute_builder_test.py
tests/filecheck/arith_ops.xdsl
tests/is_satisfying_hint_test.py
tests/mlir_converter_test.py
tests/pattern_rewriter_test.py
tests/rewriter_test.py
tests/use_test.py
xdsl/dialects/arith.py

I was just playing around with some tests, and added a few minor tests, tiny additions

xdsl: adding f16, f64 in arith_ops.xdsl

---

xdsl/dialects/builtin.py
xdsl/dialects/scf.py

This PR updates the type hints for the existing dialects. closes #251

API: Update type hints on constructors

---

.github/workflows/ci-mlir.yml

This PR updates the ninja installation to something more recent that does not used deprecated nodes.

CI: Update Ninja installation

---

README.md

I added the link on a separate paragraph, to make it more visible, feel free to suggest anything else otherwise!

Add link to the Zulip chat

---

tests/test_irdl.py
xdsl/irdl.py

This is a first PR to add unit tests for IRDL.
It also improve typing in one function, and removes a useless check in another.

tests: Add some IRDL test

---

README.md
docs/mlir_interoperation.md

This PR addresses some of the comments on the README.

docs: Update README

---

README.md

Do not claim we offer a common framework, but instead explain what xDSL really does.

Readme update summary

---

tests/test_ir.py

This PR adds some tests to the cloning functionality of Operations (which in turn also tests the one for Blocks and Regions.

tests: Add operation clone tests

---

README.md

misc: place all badges in README in one line

---

docs/irdl.ipynb
tests/dialects/test_vector.py
tests/test_operation_builder.py
xdsl/dialects/builtin.py
xdsl/dialects/vector.py
xdsl/parser.py

This PR intends to modify the `VectorType.from_type_and_list()` constructor in accordance with [this](https://github.com/xdslproject/xdsl/pull/300#discussion_r1066818410) discussion.

builtin: Improve VectorType.from_type_and_list() constructor

---

README.md
requirements-optional.txt

Also make the README instructions a bit clearer, I think it's nice to make clear that `-e` stands for `--editable`, meaning that the code will be updated as you update the repo.

install: add ipykernel as an optional requirement

---

docs/mlir_interoperation.md

misc: fix typo on mlir interoperation doc

---

docs/Toy/Toy_Ch1.ipynb
tests/test_printer.py

I added some before, and some more I missed in the Chapter 1 PR

misc: replace triple single quotes by triple double quotes

---

.github/workflows/ci-mlir.yml

It seems that I forgot some mentions of the Python bindings. This fixes it.

CI: Remove all occurences of the Python Bindings

---

tests/test_parser.py

tests: fix PytestCollectionWarning due to naming

---

xdsl/dialects/mpi.py

The CI is currently failing, this PR should fix it

bug: Remove use of Attribute `build` method

---

pyproject.toml
pyright-ci.json
tests/test_ir.py
xdsl/_version.py
xdsl/dialects/affine.py
xdsl/dialects/arith.py
xdsl/dialects/memref.py
xdsl/dialects/mpi.py
xdsl/utils/exceptions.py
xdsl/xdsl_opt_main.py

I have a new goal: get to a minimal number of files with lint errors in them, so we can add the Pyright CI with a small list of files to include, and then get that number down to 0 as we go. This way at least we can avoid regressions outside our quarantine zone ☣️ 
Changes in each file in this PR are independent

Reduce number of files with lint errors

---

tests/dialects/test_mpi.py
xdsl/dialects/mpi.py

This PR does not contains any tests, as they will be included in the PR that contains the lowering.

mpi: Cleanup definitions in preperations of the lowering

---

tests/dialects/test_memref.py
xdsl/dialects/memref.py

Pretty self explanatory, I forgot to factor that out of the MPI lowering previously

memref: Add memref.extract_aligned_pointer_as_index

---

tests/dialects/test_gpu.py
tests/filecheck/dialects/gpu/example.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/example.mlir
xdsl/dialects/gpu.py

That is:
- BarrierOp
- BlockDimOp
- BlockIdOp
- GlobalIdOp
- GridDimOp
- LaneIdOp
- NumSubgroupsOp
- SetDefaultDeviceOp
- SubgroupIdOp
- SubgroupSizeOp
- ThreadIdOp

dialects: Add trivial GPU operations.

---

tests/test_attribute_definition.py
tests/test_pyrdl.py
xdsl/irdl.py

core: Improve AllOf to collect failure data of all constraints

---

tests/test_pattern_rewriter.py

misc: call parse_module when parsing module

---

.github/workflows/ci-core.yml
.github/workflows/ci-mlir.yml
.github/workflows/ci-notebooks.yml
setup.cfg
tests/xdsl_opt/test_xdsl_opt.py
xdsl/xdsl_opt_main.py

Additionally, make errors fatal in pytest.
This will make sure for instance that deprecated functions are not called with pytest

tests: Collect tests only from the `test/` directory

---

xdsl/dialects/experimental/math.py

Initial math dialect for sqrt and pow operations, checked into experimental as no tests but needed for benchmarks - other operations will likely be needed to but will commit in stages as they are required.

dialects: Initial math dialect

---

tests/dialects/test_arith.py
xdsl/dialects/arith.py

This adds the `arith.fptosi` operation

arith: Add arith `fptosi` and `sitofp` operations

---

.github/workflows/ci-mlir.yml
.gitignore
docs/mlir_interoperation.ipynb
docs/source.xdsl
tests/dialects/test_vector.py
xdsl/dialects/vector.py
xdsl/xdsl_opt_main.py

Initialising a **draft PR** that I think is useful to exist, even for presentations.
Work in progress will be happy to get your comments and your thoughts.

docs: Init xDSL-MLIR interoperation tutorial

---

tests/dialects/test_memref.py
xdsl/dialects/memref.py

Tiny PR with a self explanatory title. Just avoiding to stack those in my unrelated PR!

dialects: Add memref.Cast.get.

---

tests/dialects/test_llvm.py
tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/llvm_pointer_ops.mlir
xdsl/dialects/llvm.py

This adds the `llvm.store` operation

llvm: Add llvm.store operation

---

tests/filecheck/dialects/stencil/laplace.mlir
xdsl/dialects/experimental/stencil.py
xdsl/transforms/experimental/ConvertStencilToLLMLIR.py

There were a few spots preventing stencil to work in 1D or 2D, this PR should solve that.

dialects: Make stencil work in 1,2,3D.

---

pyright-ci.json
xdsl/ir.py

misc: lint ir.py

---

docs/database_example.ipynb
docs/irdl.ipynb
docs/mlir_interoperation.ipynb
docs/tutorial.ipynb
docs/xdsl-introduction.ipynb
tests/dialects/test_cf.py
tests/filecheck/irdl_missing_operand.xdsl
tests/xdsl_opt/test_xdsl_opt.py
xdsl/dialects/cf.py
xdsl/dialects/gpu.py
xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
xdsl/xdsl_opt_main.py

This is trial-and-error code, it needs a lot of cleanup.
This works on my machine :yum:

dialects: Add a stencil.ApplyOp to gpu.LaunchOp lowering.

---

tests/filecheck/dialects/stencil/copy.mlir
tests/filecheck/dialects/stencil/hdiff_out_of_bound.mlir
tests/filecheck/dialects/stencil/laplace.mlir
tests/filecheck/dialects/stencil/test_access_lowering.mlir
tests/filecheck/dialects/stencil/test_store_lowering.mlir
xdsl/dialects/experimental/stencil.py
xdsl/transforms/experimental/ConvertStencilToLLMLIR.py

This PR adds basic shape inference to the stencil dialect, and error in case of out-of-bound.

dialects: Add basic shape inference to stencil.

---

tests/test_operation_definition.py
xdsl/irdl.py

Duplicate of #583, which was merged on a wrong branch

core: Allow to set attributes using their fields

---

tests/dialects/test_arith.py
tests/filecheck/arith_ops.xdsl
tests/filecheck/mlir-conversion/with-mlir/dialects/arith/arith_fp_conv.mlir
xdsl/dialects/arith.py

ExtFOp and TruncFOp operations added as part of arith dialect

dialect: ExtFOp and TruncFOp in arith dialect

---

tests/dialects/test_mpi_lowering.py
xdsl/dialects/mpi.py
xdsl/transforms/lower_mpi.py

This is part of the #590 PR, only the collectives!

mpi: Add collectives

---

tests/dialects/test_gpu.py
tests/filecheck/dialects/gpu/ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/ops.mlir
xdsl/dialects/gpu.py

This PR implements the gpu.DeallocOp operation and tests.

dialects: Add gpu.DeallocOp

---

xdsl/dialects/experimental/stencil.py
xdsl/transforms/experimental/ConvertStencilToLLMLIR.py

All in experimental
LB and UB on stencil apply set and removal of external store in lowering

dialects: Stencil dialect minor enhancement

---

tests/dialects/test_llvm.py
tests/filecheck/dialects/llvm/array.mlir
tests/filecheck/mlir-conversion/llvm_test.xdsl
xdsl/dialects/llvm.py

The LLVM array type and tests for llvm.array

dialects: LLVM array type

---

tests/dialects/test_builtin.py
tests/filecheck/dialects/builtin/unrealized_conv_cast.xdsl
tests/filecheck/mlir-conversion/with-mlir/dialects/builtin/unrealized_conversion_cast.mlir
xdsl/dialects/builtin.py

Unrealized conversion cast operation for builtin dialect

dialects: Unrealized conversion cast operation

---

.github/workflows/ci-pyright-fails.yml
.github/workflows/ci-pyright.yml
docs/Toy/toy/ir_gen.py
xdsl/dialects/cmath.py
xdsl/irdl.py

ci: update pyright to 1.1.300 in CI

---

pyproject.toml
tests/test_ir.py
tests/test_operation_builder.py
tests/test_parser.py
tests/test_parser_error.py
tests/test_pattern_rewriter.py
tests/test_printer.py
tests/test_rewriter.py
tests/test_ssa_value.py

One commit per test, might be easier to review that way. Each change is trivial, so I thought I'd put them all up in one go.

ci: lint core tests

---

xdsl/dialects/experimental/math.py

Missing operations in the math dialect which now makes this complete wrt the MLIR counterpart. This is experimental (so no tests etc). Therefore when it passes the build tests I will merge it straight in

dialects: Missing math operations

---

tests/filecheck/dialects/stencil/hdiff.mlir
xdsl/dialects/experimental/stencil.py
xdsl/transforms/experimental/ConvertStencilToLLMLIR.py

A revert for PR 648, I think this needs more work as return op doesn't build with get method and the ll-cpu lowering no longer works

dialects: A revert for PR 648

---

tests/dialects/test_arith.py
tests/filecheck/arith_ops.xdsl
tests/filecheck/mlir-conversion/with-mlir/dialects/arith/arith_fp_ops.mlir
xdsl/dialects/arith.py

Added negf operation to the arith dialect and associated tests
Also moved fastmathflags to the top of this file as negf uses it as an optional attribute

dialects: Negf operation added to arith dialect

---

xdsl/transforms/experimental/Apply1DMPIToStencil.py

Transformation that does a simple 1D halo swapping on stencil dialect data. In experimental

dialects: 1D MPI halo swapping for stencil dialect

---

.github/workflows/ci-notebooks.yml
docs/database_example.ipynb

The constructors of Region and Cmp changed and require updates to our database example.

examples: Update database example to latest xDSL

---

tests/dialects/test_builtin.py
tests/filecheck/mlir-conversion/builtin_attrs.mlir
xdsl/dialects/builtin.py
xdsl/parser.py
xdsl/printer.py

This brings us to 3988/4121 tests passed, compare to 3977 before.

dialects: Add ComplexType, and parsing for it

---

tests/test_is_satisfying_hint.py
xdsl/utils/hints.py

This adds support for `tuple[...]` to `isa`.

core: Add tuple support to isa

---

README.md

docs: Fix install guide in the README

---

xdsl/dialects/builtin.py

This is just a typing improvement, no functional changes.

dialects: Make vector generic arguments covariants

---

tests/test_parser.py
xdsl/parser.py

This method is quite useful to have in the parser.

core: Add public 'parse_boolean' methods

---

docs/mlir_interoperation.ipynb
tests/dialects/test_cf.py
tests/dialects/test_func.py
tests/test_frontend_op_inserter.py
tests/test_ir.py
tests/test_operation_builder.py
tests/test_ssa_value.py
xdsl/ir.py

misc: deprecate Block.from_ops

---

docs/Toy/toy/dialect.py
docs/Toy/toy/interpreter.py
docs/Toy/toy/ir_gen.py
tests/test_pattern_rewriter.py
tests/test_rewriter.py
xdsl/dialects/func.py
xdsl/dialects/gpu.py
xdsl/dialects/scf.py
xdsl/ir.py

This is a part of the changes made for the doubly-linked list experiment. I think this API is useful enough to merge apart from the LL changes.

misc: add first/last_op to Block

---

tests/dialects/test_scf.py
xdsl/dialects/scf.py

dialects: scf.if make else region optional

---

.github/workflows/jupyterlite.yml

I'm wondering how many times I read it without noticing it xD

CI: Fix typo in CI

---

.yapfignore
README.md

misc: Update README and remove .yapfignore after switching to black

---

xdsl/frontend/code_generation.py
xdsl/frontend/python_code_check.py
xdsl/printer.py

Replacing list with sequence in:
- `xdsl/frontend/code_generation.py`
- `xdsl/frontend/python_code_check.py`
- `xdsl/printer.py`

misc: Replacing some List with Sequence in core xdsl

---

tests/filecheck/frontend/dialects/scf.py
xdsl/frontend/code_generation.py

This PR adds support for handling Python `if` and `if` expressions.

frontend: Add support for If and IfExpr

---

tests/test_pattern_rewriter.py
tests/test_rewriter.py
xdsl/pattern_rewriter.py
xdsl/rewriter.py

First PR removing the APIs that let you pass an index in, this one is not used in the framework

core: remove inline_block_at_pos

---

xdsl/ir.py
xdsl/transforms/experimental/Apply1DMPIToStencil.py
xdsl/transforms/experimental/stencil_global_to_local.py

Also migrates the two uses to use Rewriter APIs instead

core: remove insert_op_at_pos in Block

---

xdsl/ir.py

core: remove op_at_index

---

tests/filecheck/dialects/riscv/riscv_ops.mlir
xdsl/dialects/riscv.py

Please note that there is an error in FileCheck. Is this related to #428 ?

dialects: Add riscv ecall instruction

---

tests/filecheck/dialects/riscv/riscv_ops.mlir
xdsl/dialects/riscv.py

This adds the EBREAK operation to the RISCV dialect

dialects: add riscv ebreak operation

---

CHANGELOG.md

This file was never used since we use the release drafter

docs: Remove old changelog

---

.github/workflows/ci-mlir.yml
docs/mlir_interoperation.md
tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/global.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/llvm_pointer_ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/mpi/mpi-hello-world-async.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/mpi/mpi-hello-world.mlir

This PR updates the MLIR hash to point to the latest version.

core: Update mlir hash

---

xdsl/transforms/dead_code_elimination.py

core: add dce function to allow for dead code elimination within other passes

---

xdsl/parser.py
xdsl/utils/lexer.py

This is just a simple alias to make things a bit clearer.

core: Add Position as alias for `int`

---

xdsl/ir.py
xdsl/irdl_mlir_printer.py
xdsl/parser.py
xdsl/printer.py
xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
xdsl/transforms/experimental/StencilShapeInference.py
xdsl/transforms/experimental/stencil_global_to_local.py
xdsl/transforms/lower_mpi.py

core: make walk an iterator instead of passing function

---

xdsl/transforms/riscv_register_allocation.py

bug: Fix use of `walk` method

---

tests/filecheck/dialects/riscv/riscv_ops.mlir
xdsl/dialects/riscv.py

Also added region comments to riscv.py, quite useful for large files:

dialects: add jal, j, jalr + LabelAttr to riscv

---

docs/mlir_interoperation.md
tests/filecheck/lit.cfg
xdsl/frontend/README.md

Also removes it from allowed file extensions in filecheck

documentation: remove .xdsl file extension mentions

---

tests/test_parser.py
tests/test_printer.py
tests/test_ssa_value.py
xdsl/ir.py
xdsl/parser.py
xdsl/printer.py
xdsl/rewriter.py
xdsl/transforms/experimental/stencil_global_to_local.py

Fixes #585 
This pull request was an experiment in github codespaces. I did it in 10 minutes and some seconds while recording the screen, from hitting the "Create workspace" button to opening the PR. The idea was to have some material for the presentation about how one can open a PR in 10 minutes without installing anything on their machine.
I'm trying to edit the screen recording to not be the most boring video you've ever seen

core: SSAValue.name -> name_hint

---

tests/filecheck/dialects/riscv/riscv_ops.mlir
xdsl/dialects/riscv.py
xdsl/riscv_asm_writer.py

This lets us bridge the results stored in registers to SSA land

dialects: add riscv.GetRegisterOp

---

tests/dialects/test_stencil.py
xdsl/dialects/experimental/stencil.py

Support optional lower and upper bounds on the load op stencil .get method

dialects: Stencil load op get method enhancement

---

xdsl/dialects/experimental/stencil.py
xdsl/transforms/experimental/ConvertStencilToLLMLIR.py

Lowering from stencil IndexOp to the corresponding loop SSA. Note that this doesn't support the offset provision (and that's commented in the code) as it's not needed yet by our codes and this is in experimental so best to get the general functionality in that I need

dialects: Lowering for stencil indexop

---

tests/dialects/test_memref.py
xdsl/dialects/memref.py

dialects: remove dealloca because it doesn't exist

---

docs/Toy/examples/codegen.toy
docs/Toy/examples/scalar.toy
docs/Toy/examples/tests/optimise_toy.mlir
docs/Toy/toy/__main__.py
docs/Toy/toy/compiler.py
docs/Toy/toy/rewrites/optimise_toy.py

This is the last thing we need before adding Chapter 3

documentation: add Toy optimisations

---

xdsl/dialects/experimental/stencil.py

This PR intends to clean things a bit and remove operations and attributes which are never used yet. We can chose to add them in the future as required, preferably along with tests ;)

dialects: Remove unused things from stencil dialect

---

xdsl/ir.py
xdsl/pattern_rewriter.py
xdsl/rewriter.py

I've hit a use-case where I needed to change one of the methods, thought I'd change them all in one PR

core: use Sequence[Operation] in PatternRewriter

---

tests/dialects/test_pdl.py
xdsl/dialects/pdl.py

Also, add some tests for these constructors, and missing constructors

dialects: Fix some PDL constructors and definitions

---

.github/CODEOWNERS

This will set defaults reviewers when a new PR is added.

CI: Add CODEOWNERS file with math-fehr ownership

---

xdsl/parser.py

These are methods that are not used, and that were using the old tokenizer.
They are already replaced by new methods.

core: Remove some unused and deprecated parser methods

---

docs/ret.mlir
tests/dialects/test_arith.py
tests/dialects/test_cf.py
tests/dialects/test_memref.py
tests/test_ir.py
tests/test_pattern_rewriter.py
xdsl/dialects/arith.py
xdsl/frontend/dialects/arith.py
xdsl/transforms/experimental/Apply1DMPIToStencil.py
xdsl/transforms/experimental/stencil_global_to_local.py
xdsl/transforms/lower_mpi.py

Switches all arith binary operations to use _init_, because it's factored out now!

dialects: Switch all arith binary operations to init

---

tests/dialects/test_irdl.py
tests/filecheck/dialects/irdl/cmath.irdl.mlir
tests/filecheck/dialects/irdl/cyclic-types.irdl.mlir
tests/filecheck/dialects/irdl/test-type.irdl.mlir
tests/filecheck/dialects/irdl/testd.irdl.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/irdl/testd.irdl.mlir
xdsl/dialects/irdl.py
xdsl/xdsl_opt_main.py

This is the dialect as implemented in MLIR.
It has also the same custom printing/parsing.
The tests used are exactly the tests in MLIR.

dialects: Add IRDL dialect

---

tests/filecheck/dialects/arith/arith_ops.mlir
xdsl/dialects/arith.py

Adds custom syntax parsing logic to arith's new binary ops.

dialects: Add custom parsing to arith binary ops

---

tests/dialects/test_stencil.py
xdsl/dialects/experimental/stencil.py

Simple factoring of `stencil.field` and `stencil.temp`

dialects: Factorize stencil types.

---

xdsl/dialects/experimental/dmp.py
xdsl/dialects/experimental/stencil.py
xdsl/irdl.py
xdsl/transforms/experimental/StencilShapeInference.py
xdsl/transforms/experimental/stencil_global_to_local.py

This bundles a bunch of the higher level MPI stuff together.
Blocked by #1004

dialects: Add a dialect for high-level distributed memory parallelism operations

---

requirements-optional.txt
xdsl/dialects/experimental/fir.py
xdsl/xdsl_opt_main.py

The FIR dialect (minus a few types that we are not currently using). This was in another repository, but made sense to commit into experimental and sort formatting/Pyright to conform with repo

dialects: FIR dialect

---

tests/test_lexer.py
xdsl/utils/lexer.py

This makes it easier to get a string literal from a token.

core: Add get_string_literal_value to Token

---

xdsl/irdl.py

avoid recalculating base keys every time, and skip calculation of unused clsdict

core: optimise attr clsdict calculation

---

tests/filecheck/lit.cfg
xdsl/tools/irdl_to_pyrdl.py

@math-fehr  (Intended to be actually merged in your PR if it works as intended)

CI: Count irdl-to-pyrdl in coverage stats.

---

tests/dialects/test_gpu.py
tests/filecheck/dialects/gpu/module_unterminated.mlir
tests/filecheck/dialects/gpu/terminator_terminate.mlir
tests/filecheck/dialects/gpu/yield_terminate.mlir
xdsl/dialects/gpu.py
xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py

Just a refreshing of the existing GPU ops!

dialects: use Op __init__ and traits on gpu operations

---

tests/filecheck/dialects/irdl/irdl-to-pyrdl/testd.irdl.mlir
xdsl/dialects/irdl/irdl_to_pyrdl.py

core: pyrdl generation fix codegen

---

tests/test_builtin_traits.py
xdsl/ir/core.py

I think that was forgotten, or am I missing something?

core: Fix generic Operation verifier for termination

---

tests/dialects/test_gpu.py
tests/filecheck/dialects/gpu/ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/ops.mlir
xdsl/dialects/gpu.py

Also add missing interop tests.

dialects: Implement gpu.unregister_host and gpu.launch_func.

---

tests/filecheck/dialects/affine/affine_ops.mlir
tests/filecheck/mlir-conversion/with-mlir/affine_map.mlir
xdsl/dialects/affine.py

dialects: (affine) add store and load operations

---

Makefile

Adds coverage generation and report (html and markdown) rules to Makefile.

misc: Add coverage generation rules to Makefile

---

tests/test_attribute_definition.py

tests: Remove redundant verify

---

tests/dialects/test_llvm.py
xdsl/dialects/llvm.py

dialects: Fix LLVM variadic functions

---

setup.py

I don't know why, but Pylance has been complaining recently, this brings the number of errors to 0 for me locally.

lint setup.py

---

tests/dialects/test_scf.py
tests/dialects/test_vector.py
xdsl/backend/riscv/lowering/riscv_arith_lowering.py
xdsl/dialects/arith.py
xdsl/dialects/builtin.py
xdsl/dialects/cmath.py
xdsl/dialects/experimental/fir.py
xdsl/dialects/memref.py
xdsl/dialects/snitch_runtime.py
xdsl/dialects/stencil.py
xdsl/frontend/symref.py
xdsl/parser/affine_parser.py
xdsl/parser/attribute_parser.py
xdsl/rewriter.py
xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
xdsl/transforms/experimental/dmp/stencil_global_to_local.py

I don't know what happened to my Pylance but it was suddenly very unhappy about imports. This PR has no functional changes, just imports things from the modules that define them.

misc: fix imports [NFC]

---

tests/test_ir.py

This PR performs a minor cleanup in tests (just `test_ir.py`) wrt changes in the `test` dialect from https://github.com/xdslproject/xdsl/pull/1305:
- Remove helper class `SuccessorOp` since `TestTermOp` accepts successors now
- Adjust `test` dialect import and use `test.TestOp` instead of `TestOp`

tests: (minor) Remove helper class and adjust test dialect import

---

tests/test_parser.py
xdsl/parser/base_parser.py

This fixes a bug in `parse_optional_undelimited_comma_separated_list`, and improve its documentation.

core: Fix bug in method, and improve documentation

---

tests/filecheck/dialects/gpu/ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/ops.mlir
xdsl/dialects/gpu.py

Oops, seems I've been lazy with the filechecks.

dialects: Fix wrong attribute type used for gpu.known_X_size.

---

tests/filecheck/dialects/riscv/riscv_ops.mlir
tests/filecheck/dialects/riscv_func/lower_riscv_func.mlir
tests/filecheck/dialects/riscv_func/lower_riscv_func_main.mlir
xdsl/dialects/riscv.py

This is an initial PR to custom RISCV syntax.
The major change is dropping bracket around operands

dialect: (riscv) initial custom syntax

---

tests/test_ir.py
xdsl/ir/core.py

#610
- Adding `clone` to `Region` class
- Adding respective test

core: Add `clone` to `Region` class 

---

tests/filecheck/dialects/riscv/riscv_ops.mlir
tests/filecheck/dialects/riscv_func/lower_riscv_func.mlir
tests/filecheck/dialects/riscv_func/lower_riscv_func_main.mlir
xdsl/dialects/riscv.py

The only change is to put attributes before regions.

dialect: (riscv) put attribute before region

---

xdsl/traits.py

Forgot to push this before merging #1330..

API: Merge exception cases in SymbolOpInterface.get_sym_attr_name.

---

tests/interpreters/test_riscv_interpreter.py
xdsl/interpreters/riscv.py

interpreter: (riscv) add interpreter functions

---

docs/Toy/toy/rewrites/setup_riscv_pass.py
docs/Toy/toy/tests/test_add_sections.py
tests/backend/riscv/test_regalloc.py
tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
tests/filecheck/dialects/riscv/riscv_ops.mlir
tests/interpreters/test_riscv_interpreter.py
xdsl/dialects/riscv.py
xdsl/interpreters/riscv.py

A rerun of #1370 by @adutilleul with conflicts fixed

dialects: (riscv) add `AssemblySectionOp` and split `DirectiveOp` 

---

tests/filecheck/dialects/riscv/riscv_ops.mlir
tests/filecheck/dialects/riscv_func/lower_riscv_func.mlir
xdsl/dialects/riscv.py

Add custom printing for `RdImmJumpOperation`

dialect: (riscv) Add custom printing for RdImmJumpOperation

---

docs/Toy/toy/dialects/toy_accelerator.py
pyproject.toml
tests/filecheck/frontend/dialects/builtin.py
tests/filecheck/frontend/dialects/invalid.py
tests/test_pyrdl.py
xdsl/dialects/cf.py
xdsl/dialects/gpu.py
xdsl/dialects/llvm.py
xdsl/dialects/memref.py
xdsl/dialects/stencil.py
xdsl/frontend/code_generation.py
xdsl/frontend/python_code_check.py
xdsl/frontend/type_conversion.py
xdsl/interpreters/experimental/wgpu.py
xdsl/interpreters/riscv.py
xdsl/parser/attribute_parser.py

[`F` rule](https://beta.ruff.rs/docs/rules/#pyflakes-f) enforce rules from pyflakes and attempt to auto fix.
Important rules such as
- removal of unused imports
- warn shadowing of same variables name
- remove redundant f-string usage

ci: (ruff) add F rule

---

tests/filecheck/dialects/riscv/riscv_ops.mlir
tests/filecheck/dialects/riscv_func/lower_riscv_func.mlir
tests/filecheck/dialects/riscv_func/lower_riscv_func_main.mlir
tests/filecheck/dialects/riscv_scf/ops.mlir
xdsl/dialects/riscv.py

Add custom syntax to RdImmIntegerOperation and LiOp

dialect: (riscv) Add custom syntax to RdImmIntegerOperation and LiOp

---

xdsl/backend/riscv/riscv_scf_to_asm.py

I should probably have re-run the CI...

misc: import from collections instead of typing

---

tests/filecheck/backend/rvscf_lowering_labels.mlir
xdsl/dialects/riscv_scf.py

Also has a small change to an error message, which has an off by one error for the block argument index

testing: (rsicv) add integer test to for loop lowering

---

docs/Toy/examples/tests/with-mlir/interpret.toy
docs/Toy/toy/compiler.py
tests/filecheck/backend/rvscf_lowering_labels.mlir
xdsl/backend/riscv/riscv_scf_to_asm.py

I added a test for the lowering in Toy, and found a bug in our for loop lowering code. Hurray for tests :)

backend: (riscv) fix riscv_scf lowering

---

xdsl/dialects/arith.py
xdsl/dialects/func.py
xdsl/dialects/llvm.py
xdsl/dialects/scf.py
xdsl/ir/core.py
xdsl/printer.py
xdsl/transforms/experimental/Apply1DMPIToStencil.py
xdsl/transforms/printf_to_llvm.py

Removing some methods that have been deprecated for three weeks or more at @math-fehr's behest

misc: remove some deprecated methods in xDSL

---

tests/filecheck/dialects/pdl/custom-format-empty-rewriter-with-root-op.mlir
tests/filecheck/dialects/pdl/custom-format-empty-rewriter.mlir
tests/filecheck/dialects/pdl/custom-format-external-rewriter-with-arg.mlir
tests/filecheck/dialects/pdl/custom-format-external-rewriter.mlir
tests/filecheck/dialects/pdl/custom-format-inline-rewriter.mlir
tests/filecheck/dialects/riscv/riscv_ops.mlir

Oops, merged #1491 a bit too fast and I didn't properly rename those filecheck commands according to @math-fehr's preference

testing: Fix GENERIC-NEXT filechecks.

---

tests/filecheck/backend/riscv/register_allocation_liveness_block_naive.mlir
tests/filecheck/backend/riscv/register_allocation_liveness_block_naive_limited.mlir
tests/filecheck/backend/riscv/riscv_arith_lowering.mlir
tests/filecheck/backend/riscv/riscv_register_allocation_block_naive.mlir
tests/filecheck/backend/riscv/riscv_register_allocation_jregs.mlir
tests/filecheck/backend/rvscf_lowering_labels.mlir
tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
tests/filecheck/dialects/riscv_func/lower_riscv_func.mlir
tests/filecheck/dialects/snitch/snitch_to_riscv_lowering.mlir
tests/filecheck/with-riscemu/riscv_emulation.mlir
tests/filecheck/with-riscemu/rvscf_lowering_emu.mlir

tests: (riscv) migrate most riscv filecheck ops to custom syntax [NFC]

---

docs/Toy/toy/compiler.py
docs/Toy/toy/rewrites/lower_memref_riscv.py
docs/Toy/toy/tests/test_lower_memref_riscv.py
tests/filecheck/backend/riscv/memref_to_riscv.mlir
xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
xdsl/tools/command_line_tool.py

Only store/load, no alloc/dealloc.

transforms: (riscv) partial lowering of memref to riscv

---

tests/filecheck/backend/riscv/register_allocation_liveness_block_naive.mlir
tests/filecheck/backend/riscv/register_allocation_liveness_block_naive_limited.mlir
xdsl/backend/riscv/register_allocation.py

second attempt at accidentally merged #1522

backend: (riscv) free result registers before allocating

---

xdsl/backend/riscv/register_allocation.py

The idea is that the `riscv_scf.for` op already checks that the types are the same, so we can treat it as a precondition of the loop allocation.

backend: (riscv) simplify for loop allocation

---

xdsl/backend/riscv/register_allocation.py

A lot of the logic is pretty similar, a base class will be useful to make sure they don't go out of sync in unexpected ways.

backend: (riscv) factor out init and allocate for block naive allocators

---

tests/rewriting/composable_rewriting/immutable_ir/test_immutable_ir.py
xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py

This adds properties in the immutable IR.

core: Add support for properties in immutable ir

---

tests/dialects/test_cf.py
tests/interpreters/test_cf_interpreter.py
xdsl/dialects/cf.py

Moves `cf` dialect to init based construction, similar to #1616

dialects: (cf) move to __init__

---

xdsl/ir/core.py

core: make IRNode.parent an abstract property parent_node

---

tests/backend/riscv/test_utils.py
xdsl/backend/riscv/lowering/convert_func_to_riscv_func.py
xdsl/backend/riscv/lowering/utils.py

dialects: (riscv) split move_to_a_regs

---

tests/interpreters/test_pdl_interpreter.py
xdsl/interpreters/experimental/pdl.py

This adds support for `pdl.erase`, and add a test for it.

interpreter: Add support for pdl.erase

---

xdsl/dialects/stencil.py

misc: lint with ruff

---

docs/Toy/toy/emulator/toy_accelerator_instructions.py
requirements-optional.txt
tests/filecheck/with-riscemu/riscv_emulation.mlir
tests/interpreters/test_riscv_emulator.py
xdsl/interpreters/riscv_emulator.py

Beep Boop, I am dependabot. I want to bump riscemu to 2.2.5.

dependencies: Bump riscemu to 2.2.5

---

tests/filecheck/dialects/riscv/riscv_ops.mlir
tests/filecheck/dialects/snitch/snitch_to_riscv_lowering.mlir

testing: (riscv) add missing return values

---

tests/dialects/test_dmp.py
xdsl/dialects/experimental/dmp.py
xdsl/transforms/experimental/dmp/decompositions.py
xdsl/transforms/experimental/dmp/stencil_global_to_local.py

dialects: (dmp) Backport of 3d decomp for devito

---

tests/test_affine_builtins.py
xdsl/ir/affine/affine_map.py

I think we'd benefit from a little helper here

core: (affine_map) add a convenience affine map constructor with lambda

---

tests/interpreters/test_riscv_interpreter.py
xdsl/interpreters/riscv.py

interpreter: (riscv) add cast from float reg to float

---

tests/interpreters/test_riscv_interpreter.py
xdsl/interpreters/riscv.py

interpreter: (riscv) gather data from all .data sections

---

tests/filecheck/backend/riscv/convert_arith_to_riscv.mlir
tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
tests/filecheck/dialects/riscv/riscv_ops.mlir
tests/interpreters/test_riscv_interpreter.py
xdsl/backend/riscv/lowering/convert_arith_to_riscv.py
xdsl/dialects/riscv.py
xdsl/interpreters/riscv.py

Also adds the interpreter functions
CC @xdslproject/risc-v-backend

dialects: (riscv) add fmin.d and fmax.d and lower from arith

---

tests/filecheck/dialects/hw/hw_ops.mlir
tests/filecheck/dialects/hw/invalid.mlir
xdsl/dialects/hw.py
xdsl/tools/command_line_tool.py

I think this is a decent first chunk for `HW`. Wider context available in #1704

dialects: (hw) Implement HW dialect starting with InnerRefAttr

---

tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
tests/filecheck/dialects/riscv/riscv_ops.mlir
xdsl/dialects/riscv.py

Snuck in some more "Pure" annotations.

backend: (riscv) add riscv.fcvt.d.w and riscv.fcvt.d.wu ops

---

tests/filecheck/dialects/omp/ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/omp/ops.mlir
xdsl/dialects/omp.py

Mirror `omp.parallel` from MLIR.

dialects : Implement omp.parallel

---

.github/release-drafter.yml

Add Interactive to release-drafter.yml

ci: Add Interactive to release-drafter.yml

---

tests/interactive/test_app.py
xdsl/interactive/app.py
xdsl/interactive/app.tcss

add remove last pass button
made a second version of this PR as the first one had bizarre failing tests and this was easier.

interactive: add "remove last pass" button (5/7) 

---

xdsl/interactive/app.py

interactive: add comments + docstrings (1/4)

---

xdsl/interactive/app.py

Moving the pass pipeline string construction to own function

interactive: Moving the pass pipeline string construction to own function (2/4)

---

README.md

Fixes broken/old relative link in the README.
@webmiche

misc: fix relative link in README

---

tests/dialects/test_math.py
xdsl/dialects/experimental/math.py

Adding constructor tests for math dialect

tests: (math) Add constructor tests for Math dialect

---

docs/Toy/toy/rewrites/lower_toy_affine.py
tests/test_op_builder.py
xdsl/builder.py

This PR creates the InsertPoint class, and use it in the builder.
This has no functional changes otherwise

core: Expose InsertPoint class (NFC)

---

tests/test_cli.py
tests/xdsl_opt/test_xdsl_opt.py
xdsl/interactive/app.py
xdsl/tools/command_line_tool.py
xdsl/xdsl_opt_main.py

This means we don't load a pass file unless we are using it.
This will save us a lot of startup time when we do the same for operations.
This already put us from 500ms (!!) to 400ms

core: Register passes lazily

---

tests/interpreters/test_riscv_scf_interpreter.py
xdsl/interpreters/riscv.py
xdsl/interpreters/riscv_scf.py

Adds the necessary functions to the interpreter to interpret riscv_scf.while

interpreter: (riscv_scf) add interpreter function for while op

---

tests/filecheck/dialects/scf/scf_ops.mlir
xdsl/dialects/scf.py

Same as MLIR: https://mlir.llvm.org/docs/Dialects/SCFDialect/#scfcondition-scfconditionop

dialects: (scf) add custom syntax for scf.condition

---

tests/filecheck/dialects/riscv_scf/ops.mlir
tests/filecheck/dialects/riscv_scf/verification.mlir
xdsl/dialects/riscv_scf.py

Follows the syntax of scf.while exactly

dialects: (riscv_scf) add custom syntax to riscv_scf.while

---

.vscode/launch.json

Allows us to press play and attach to the Toy compiler, helps for debugging.

misc: (Toy) add toy run action for VSCode

---

tests/interpreters/test_riscv_cf_interpreter.py

I dropped this in my various branches, follow-up to #1956

interpreter: (riscv_cf) add one more interpreter test

---

xdsl/dialects/onnx.py

dialects: (onnx) sort onnx ops alphabetically

---

xdsl/pattern_rewriter.py

core: Move to assertions for modification permission checks 

---

tests/filecheck/dialects/onnx/onnx_invalid.mlir
tests/filecheck/dialects/onnx/onnx_ops.mlir
xdsl/dialects/onnx.py

dialects: (onnx) add onnx.Reshape

---

tests/filecheck/dialects/onnx/onnx_invalid.mlir
tests/filecheck/dialects/onnx/onnx_ops.mlir
xdsl/dialects/onnx.py

dialects: (onnx) add onnx.Abs

---

tests/test_declarative_assembly_format.py
xdsl/irdl/declarative_assembly_format.py
xdsl/irdl/declarative_assembly_format_parser.py

Add attribute variables to the declarative assembly format.
This does not support properties yet, this will be added in a following PR.
The attributes that are parsed by the declarative assembly format are not
parsed/printed back in the attr-dict directive.

core: Add attribute variables to the declarative assembly format.

---

tests/filecheck/dialects/onnx/onnx_invalid.mlir
tests/filecheck/dialects/onnx/onnx_ops.mlir
xdsl/dialects/onnx.py

dialects: (onnx) add onnx.Conv 

---

xdsl/interactive/app.py

Add '' around selected pass list and remove \n so it can be executed in terminal

interactive: changes to label/query

---

.github/workflows/jupyterlite.yml
.github/workflows/update_xdsl_pyodide_build.py

Fix recent issues with typing-extensions in online notebooks - at least on my machine and browser :upside_down_face: 
Please test at https://papychacal.github.io/xdsl (With browser cache cleanup or private browsing mode)

CI: Fix online notebooks

---

tests/filecheck/transforms/individual_rewrite.mlir
tests/interactive/test_app.py
xdsl/tools/command_line_tool.py
xdsl/transforms/individual_rewrite.py

PR 1 out of 4 into getting peephole rewrites to work. 
The way we will do it is by creating a pass that represents an individual peephole rewrite. This enables us to reuse the app's infrastructure (which is pass-based).

interactive: adding an IndividualRewrite pass

---

Makefile

testing: add a timeout for `make filecheck`

---

xdsl/backend/riscv/lowering/convert_snitch_stream_to_snitch.py

PR 1/4 of replacing the snitch_stream.stride_pattern op with an attribute
The lowering from the op will be replaced by a call to the helper created in this PR

transformations: (snitch_strem) factor out stride pattern ops lowering [NFC]

---

tests/filecheck/dialects/snitch_stream/ops.mlir
xdsl/backend/riscv/lowering/convert_snitch_stream_to_snitch.py
xdsl/dialects/snitch_stream.py

PR 2/4 of replacing the snitch_stream.stride_pattern op with an attribute
This introduces the new attribute, currently unused

dialects: (snitch_stream) add stride pattern attribute

---

tests/filecheck/mlir-conversion/with-mlir/dialects/tensor/ops.mlir
xdsl/dialects/tensor.py
xdsl/tools/command_line_tool.py

resolves #2117 
Note: Merging this branch into linalg-add branch so that it can be merged in one

dialects: (tensor) add tensor.Empty

---

pyproject.toml
tests/filecheck/dialects/memref_stream/ops.mlir
tests/filecheck/dialects/snitch_stream/convert_snitch_stream_to_snitch.mlir
tests/filecheck/dialects/snitch_stream/ops.mlir
tests/filecheck/projects/riscv-backend-paper/add_snitch_stream.mlir
tests/filecheck/projects/riscv-backend-paper/conv_target.mlir
tests/filecheck/projects/riscv-backend-paper/ddot_target.mlir
tests/filecheck/projects/riscv-backend-paper/dense_target.mlir
tests/filecheck/projects/riscv-backend-paper/dsum_target.mlir
tests/filecheck/projects/riscv-backend-paper/fill_target.mlir
tests/filecheck/projects/riscv-backend-paper/matmul_target.mlir
tests/filecheck/projects/riscv-backend-paper/max_pool_target.mlir
tests/filecheck/projects/riscv-backend-paper/relu_snitch_stream.mlir
tests/filecheck/projects/riscv-backend-paper/relu_target.mlir
tests/filecheck/projects/riscv-backend-paper/sum_pool_target.mlir
tests/filecheck/transforms/snitch_register_allocation.mlir
tests/interpreters/test_snitch_stream_interpreter.py
xdsl/backend/riscv/lowering/convert_snitch_stream_to_snitch.py
xdsl/dialects/memref_stream.py
xdsl/dialects/snitch_stream.py
xdsl/interactive/app.py
xdsl/interpreters/snitch_stream.py

Note stacked PR
Add a higher-level representation of a streaming region, operating on memrefs and affine maps.

dialects: (memref_stream) add streaming region

---

tests/filecheck/transforms/convert_onnx_to_linalg.mlir
xdsl/tools/command_line_tool.py
xdsl/transforms/convert_onnx_to_linalg.py

transformation: (convert_onnx_to_linalg) add lowering from onnx.Add to linalg.add

---

tests/filecheck/runner/riscv_scf.mlir
xdsl/interpreters/__init__.py

interpreter: add riscv_scf to xdsl-run

---

tests/filecheck/transforms/convert_onnx_to_linalg.mlir
xdsl/transforms/convert_onnx_to_linalg.py

wip on #2181 
dealing with following issues:
1. new ssa value is created rather than one i'm directly trying to reference from the block
2. format of ir in my xdsl-opt mlir doesn't entirely match my construction
i think i have all the "parts" but i need to refine some stuff

(transformations): lower onnx.Relu to linalg

---

xdsl/interactive/app.py
xdsl/interactive/app.tcss

Changing the GUI to be a tree -> first of many PR's
1. move buttons to RHS

interactive: move buttons to RHS (1)

---

tests/interactive/test_get_all_available_passes.py

Should have merged before merging

testing: fix broken test in main

---

tests/filecheck/transforms/convert_onnx_to_linalg.mlir
xdsl/transforms/convert_onnx_to_linalg.py

wip #2194
unsure on how to deal with the attributes of onnx.constant, also constant takes no input 
so not sure whether to just pass in an zero constant

(transformations): lower onnx.Constant to linalg

---

tests/filecheck/transforms/convert_onnx_to_linalg.mlir
xdsl/transforms/convert_onnx_to_linalg.py

(transformations): lower onnx.Reshape to linalg

---

tests/interpreters/test_snitch_stream_interpreter.py
xdsl/dialects/snitch_stream.py
xdsl/interpreters/snitch_stream.py

We'll need this for further testing also in an upcoming PR

dialects: (snitch_stream) add offsets to StridePattern and use in interpreter

---

tests/filecheck/transforms/riscv_cse.mlir
xdsl/dialects/riscv.py

Also amends the cse test to include a matmul kernel to make sure we cse the duplicate pointer access completely.

dialects: (riscv) mul is pure

---

tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
xdsl/dialects/linalg.py

dialects: (linalg) add linalg.mul

---

tests/test_pass_to_arg_and_types_str.py
xdsl/passes.py

This reverts commit 9c702b5e732ae4fd719cec0d8356a86cc24d0776.

Revert "interactive: don't print =none for None value (#2259)"

---

Makefile

testing: change filecheck default timeout to 10s

---

tests/filecheck/projects/riscv-backend-paper/matmul.mlir

I'd like to use this test to keep track of our top-down lowering progress, this PR just minimises the amount of input code.

testing: use arguments in matmul kernel test

---

tests/filecheck/dialects/memref_stream/ops.mlir
tests/filecheck/projects/riscv-backend-paper/source.mlir
tests/filecheck/transforms/convert_linalg_to_memref_stream.mlir
tests/filecheck/transforms/convert_memref_stream_to_loops.mlir
tests/filecheck/transforms/memref_streamify.mlir
xdsl/transforms/convert_linalg_to_memref_stream.py
xdsl/transforms/loop_nest_lowering_utils.py

Forgot to rewrite linalg.yield to memref_stream.yield

transformations: fix memref stream conversion

---

xdsl/pattern_rewriter.py

Accidental change introduced in #2312

core: (pattern_rewriter) Revert accidental change

---

tests/filecheck/dialects/onnx/onnx_ops.mlir
xdsl/dialects/onnx.py

bug: (onnx) fix onnx.Gemm 

---

xdsl/interpreters/onnx.py

interpreter: (onnx) args should be casted to ShapedArray[float] not ShapedArray[int]

---

tests/interpreters/test_ml_program_interpreter.py
tests/interpreters/test_onnx_interpreter.py
xdsl/interpreters/__init__.py
xdsl/interpreters/ml_program.py

interpreter: (ml_program) Add ml_program operations to target MNIST ONNX model 

---

tests/interpreters/test_tensor_interpreter.py
xdsl/interpreters/__init__.py
xdsl/interpreters/tensor.py

interpreter: (tensor) Add tensor operations for ONNX model MNIST targeting

---

tests/dialects/test_x86.py
tests/filecheck/dialects/x86/x86_ops.mlir
xdsl/dialects/x86/__init__.py
xdsl/dialects/x86/ops.py

This is the second pull request in the series of upstreaming the x86 dialect. In this PR I add the "add" operation and all the necessary infrastructure to support it and it's testing. A lot of the structure is designed to resemble the riscv dialect.

dialects: (x86) PR2 - Operations: add

---

tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
xdsl/dialects/linalg.py

dialects: (linalg) add linalg.pooling_nchw_max

---

tests/interpreters/test_linalg_interpreter.py
xdsl/interpreters/linalg.py

interpreter: (linalg) Add linalg operations for ONNX model MNIST targeting

---

tests/filecheck/transforms/convert_onnx_to_linalg.mlir
xdsl/dialects/linalg.py
xdsl/transforms/convert_onnx_to_linalg.py

transformations: (onnx) lower onnx.MaxPoolSingleOut to linalg

---

README.md

Couple issues with getting set up that I encountered, broken links and such.

docs: onboarding papercuts

---

tests/interpreters/test_linalg_interpreter.py
xdsl/interpreters/linalg.py

interpreter: (linalg) Add linalg.PoolingNchwMaxOp and linalg.Conv2DNchwFchwOp interpreter functions

---

tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/invalid_ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
xdsl/dialects/linalg.py

dialects: (linalg) add linalg.broadcast 

---

xdsl/irdl/declarative_assembly_format.py

core: Fix optional operand declarative printing.

---

tests/dialects/test_comb.py
xdsl/dialects/comb.py

This fixes a bug where variadic operands were not passed correctly. I also improved test coverage.

dialects: (comb) Fix bugs in variadic operations

---

pyproject.toml

testing: fix  pyright failures when onnx is not installed

---

tests/frontend/onnx/test_build_ir.py
xdsl/frontend/onnx/ir_builder.py

Integration of matmul operation in onnx frontend.
@superlopuh @compor

frontend: (onnx) integration matmul op in onnx frontend

---

tests/irdl/test_declarative_assembly_format.py
xdsl/irdl/declarative_assembly_format.py
xdsl/irdl/declarative_assembly_format_parser.py

I.e., fix a bunch of cases of first element of optional groups, such as ``($var_operand^ `:` type($var_operand))?``

core: Fix OptionallyParsableDirective.

---

xdsl/dialects/experimental/fir.py

Attributes moved to properties, addition of the new FortranVariableFlagsAttr and new FIR Declare operation added

dialects: (fir) Update to the MLIR hash version of FIR that we use

---

xdsl/dialects/experimental/hlfir.py
xdsl/tools/command_line_tool.py

This is the Higher Level FIR dialect which is a new dialect used by Flang that represents variables and some expressions

dialects: (HLFIR) Addition of the HLFIR dialect

---

tests/filecheck/dialects/hw/hw_module.mlir
xdsl/dialects/hw.py

dialects: (hw) Add visibility keyword to hw.module

---

README.md

misc: add total and last week download counts

---

tests/filecheck/dialects/x86/x86_assembly_emission.mlir
tests/filecheck/dialects/x86/x86_ops.mlir
xdsl/dialects/x86/__init__.py
xdsl/dialects/x86/ops.py

Added labels and directives. The implementation is pretty much the same as in the riscv dialect.

dialects: (x86) PR14 - Labels and Directives

---

tests/filecheck/transforms/convert_linalg_to_loops.mlir
tests/filecheck/transforms/convert_memref_stream_to_loops.mlir
xdsl/transforms/convert_linalg_to_loops.py
xdsl/transforms/convert_memref_stream_to_loops.py
xdsl/transforms/loop_nest_lowering_utils.py
xdsl/transforms/memref_streamify.py

transformations: handle scalar arguments to generic ops when lowering

---

xdsl/transforms/mlir_opt.py

transformations: Fix mlir opt printing to stderr

---

tests/filecheck/backend/riscv/func_and_arith_to_riscv_asm_flow.mlir
tests/filecheck/dialects/snitch_runtime/snitch_runtime_ops.mlir
tests/filecheck/transforms/convert-snrt-to-riscv.mlir
xdsl/dialects/snitch_runtime.py
xdsl/transforms/convert_snrt_to_riscv.py

(hopefully) smaller version of #2428 stripped of all the more complex lowerings introduced in that PR

transforms: (convert-snrt-to-riscv) Add smaller number of ops

---

tests/filecheck/dialects/csl/ops.mlir
xdsl/dialects/csl.py
xdsl/tools/command_line_tool.py

Add just the ops from #2451, hopefully an easier-to-review PR.

dialects: (csl) Add csl dialect ops

---

tests/filecheck/dialects/csl/ops.mlir
xdsl/dialects/csl.py

This PR is first in a series trying to split #2592 into more reviewable chunks. 
Adding basic CSL type representations to the dialect.

dialects: (csl) Added basic types

---

tests/dialects/test_irdl.py
tests/filecheck/dialects/irdl/testd.irdl.mlir
xdsl/dialects/irdl/irdl.py
xdsl/irdl/irdl.py

Add irdl.base to IRDL, which is equivalent to our `BaseConstraint.

core: Add irdl.base

---

tests/filecheck/dialects/hw/hw_module.mlir
xdsl/dialects/hw.py

I factored a lot of logic out of hw.module in order to reuse it for this.

dialects: (hw) Add hw.module.extern

---

tests/filecheck/dialects/scf/canonicalize.mlir
tests/filecheck/transforms/arith-add-immediate-zero.mlir
xdsl/dialects/arith.py
xdsl/transforms/constant_fold_interp.py

Make arith.constant Pure, and fix constant folding that breaks when facing this.

dialects: arith.constant is Pure (no side effects)

---

tests/filecheck/transforms/cse.mlir
xdsl/dialects/scf.py
xdsl/dialects/tensor.py
xdsl/traits.py
xdsl/transforms/common_subexpression_elimination.py
xdsl/transforms/dead_code_elimination.py

Implement a simplified MemoryEffect interface, just saying if the op has any side effect or not.
(The upstream version says if it's a write, read, alloc or free too; but that can be used already, and is part of the API of the upstream one too :slightly_smiling_face:)
Implement NoMemoryEffect and RecursiveMemoryEffect in those terms, also make Pure properly implemented in those terms, and use in CSE.

core: Implement a simplified MemoryEffect interface.

---

xdsl/interactive/app.py

My local VSCode Pylance has some complaints about this file, these minor fixes resolve them

interactive: some minor typing fixes in xdsl-gui

---

tests/filecheck/transforms/function-constant-pinning.mlir

Hotfix for broken filecheck on main due to rework on SSA value naming.

tests: Fix broken filecheck

---

xdsl/pattern_rewriter.py

Splitting out an independent change from #2660

core: add `inline_block_at_location` to `PatternRewriter`

---

tests/filecheck/dialects/arith/arith_invalid.mlir
tests/filecheck/dialects/arith/arith_ops.mlir
xdsl/dialects/arith.py

Add a verifier to `arith.index_cast` op mirroring MLIR.

dialects: (arith) Add verifier to 'arith.index_cast' op and fix returns in inits

---

tests/filecheck/backend/csl/print_csl.mlir
xdsl/backend/csl/print_csl.py

Adding support for `scf.if` conditionals to CSL printer. Also fixing print for boolean type.

backend: (csl) conditional statements

---

xdsl/pattern_rewriter.py

core: (rewriter) Correctly pass safe_erase in replace_op

---

tests/interactive/test_app.py

Dynamically retrieve condensed_list in `test_app.py: test_rewrites()` to decouple test from implemented passes in the framework.

interactive: dynamically retrieve condensed_list in test_rewrites

---

xdsl/dialects/csl.py

Fix some of the things that accidentally went through in #2742.
Also moves the `__init__` to the top of the method definition and adds some docstrings.

dialects: (csl) Improve some constructor inits

---

tests/dialects/test_memref.py
xdsl/dialects/memref.py

By popular request since #2748

Change memref.extract_strided_metadata constructor to init

---

.github/workflows/ci-pyright-fails.yml
pyproject.toml

Lets us drop the parsing step.

ci: use venv pyright in CI action

---

xdsl/dialects/memref.py

dialects: (memref) Make memref.extract_strided_metadata have NoMemoryEffect

---

docs/marimo/mlir/onnx_demo.py
tests/filecheck/projects/riscv-backend-paper/add.mlir
tests/filecheck/transforms/convert_memref_stream_to_snitch_stream.mlir
xdsl/tools/command_line_tool.py
xdsl/transforms/convert_memref_stream_to_snitch_stream.py
xdsl/transforms/test_lower_memref_stream_to_snitch_stream.py

transformations: convert-memref-stream-to-snitch-stream fix name

---

tests/filecheck/backend/riscv/canonicalize.mlir
tests/filecheck/backend/riscv/verify.mlir
tests/filecheck/dialects/riscv_snitch/ops.mlir
tests/filecheck/dialects/snitch/snitch_to_riscv_lowering.mlir
tests/filecheck/projects/riscv-backend-paper/pres.mlir
xdsl/dialects/riscv.py
xdsl/dialects/riscv_snitch.py
xdsl/transforms/canonicalization_patterns/riscv.py
xdsl/transforms/lower_snitch.py

dialects: (riscv_snitch) remove always ZERO rd in snitch config ops

---

docs/marimo/mlir/onnx_demo.py
xdsl/dialects/riscv.py

I would encourage cloning the branch and running the code locally to see the effect.
I think I'll migrate most of this notebook to one that doesn't depend on onnx, so we can have wasm links do it directly.

docs: (marimo) prettify onnx notebook

---

tests/filecheck/dialects/snitch/snitch_to_riscv_lowering.mlir
tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
xdsl/dialects/riscv.py
xdsl/transforms/lower_snitch.py

Hopefully these will help us debug issues a little faster.

transformations: (snitch) add comments when lowering snitch config ops

---

docs/marimo/linalg_snitch.py

https://static.marimo.app/static/linalg-snitch-interp-gawe

docs: (marimo) add interpreter trace to linalg snitch notebook

---

docs/marimo/linalg_snitch.py

The accordion jumps around too much.
https://static.marimo.app/static/linalg-snitch-carousel-kfs1

docs: (marimo) use carousel in linalg snitch notebook

---

xdsl/dialects/accfg.py
xdsl/dialects/csl/csl_wrapper.py
xdsl/dialects/experimental/air.py
xdsl/dialects/experimental/math.py
xdsl/dialects/func.py

misc: use constraints in more operation definitions

---

tests/filecheck/dialects/csl/csl-stencil-canonicalize.mlir

Fix for #2814 which was opened before #2868 and somehow the tests did not re-run

(bug): fix csl_stencil canonicalise

---

tests/test_printer.py
xdsl/dialects/builtin.py
xdsl/dialects/fsm.py
xdsl/dialects/hw.py
xdsl/interpreters/ptr.py
xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py
xdsl/transforms/experimental/function_constant_pinning.py
xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py

I don't think they deserve individual PRs, and I don't know how to group them conceptually, each time it's just fiddling with code to make Pylance happy.

misc: remove some pylance errors throughout the project [NFC]

---

tests/filecheck/dialects/tensor/invalid_ops.mlir
tests/filecheck/dialects/tensor/ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/tensor/ops.mlir
xdsl/dialects/tensor.py

This PR adds the `tensor.dim` and `tensor.cast` operation

dialects: (tensor) add tensor.dim and tensor.cast op

---

tests/filecheck/dialects/snitch_stream/ops.mlir
xdsl/dialects/snitch_stream.py

I did not add a test and am paying the price.

bug: (snitch_stream) fix stride pattern repeat param parsing

---

tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir
tests/filecheck/dialects/riscv_snitch/ops.mlir
tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
xdsl/dialects/riscv_snitch.py

We want to include it in the paper

testing: add relu f32 to bottom-up tests

---

tests/dialects/test_csl_stencil.py
tests/filecheck/dialects/csl/csl-stencil-canonicalize.mlir
tests/filecheck/dialects/csl/csl-stencil-ops.mlir
tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
tests/filecheck/transforms/stencil-to-csl-stencil.mlir
xdsl/dialects/csl/csl_stencil.py
xdsl/transforms/stencil_to_csl_stencil.py

dialects: (csl_stencil) Enable bufferized `csl_stencil.apply`

---

tests/filecheck/dialects/stablehlo/test.mlir
xdsl/dialects/__init__.py
xdsl/dialects/stablehlo.py

This PR adds the `abs` operation for the stablehlo dialect. More to come.

dialects: (stablehlo) Add initial contribution for stablehlo dialect

---

tests/filecheck/dialects/stablehlo/invalid.mlir
tests/filecheck/dialects/stablehlo/ops.mlir
tests/filecheck/dialects/stablehlo/test.mlir
xdsl/dialects/stablehlo.py

dialects: (stablehlo) add transpose

---

tests/irdl/test_declarative_assembly_format.py
xdsl/irdl/declarative_assembly_format_parser.py

Annoyed me enough while looking at other stuff to fix it

misc: Fix typo achorable -> anchorable

---

.pre-commit-config.yaml
tests/interactive/test_app.py

dependencies: update ruff-pre-commit to v0.6.0

---

.pre-commit-config.yaml

I've subscribed to both the precommit hook repos so I'll just keep these updated manually.

CI: update pre-commit-hooks

---

.pre-commit-config.yaml
tests/filecheck/backend/convert_riscv_scf_to_riscv_cf_with_regalloc.mlir
tests/filecheck/backend/riscv/convert_arith_to_riscv_snitch.mlir
tests/filecheck/dialects/accfg/accfg_ops.mlir
tests/filecheck/dialects/memref_stream/canonicalize.mlir
tests/filecheck/dialects/quantum/attrs.mlir
tests/filecheck/dialects/riscv_scf/loop_range_folding.mlir
tests/filecheck/dialects/riscv_snitch/ops.mlir
tests/filecheck/dialects/riscv_snitch/verification.mlir
tests/filecheck/dialects/snitch_stream/convert_snitch_stream_to_snitch.mlir
tests/filecheck/dialects/tensor/ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/invalid_ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
tests/filecheck/projects/riscv-backend-paper/ddot_regalloc.mlir
tests/filecheck/transforms/arith-add-immediate-zero.mlir
tests/filecheck/transforms/arith-individual-rewrite-patterns-DivisionOfSameVariableToOne.mlir
tests/filecheck/transforms/convert_onnx_to_linalg.mlir
tests/filecheck/transforms/convert_qref_to_qssa.mlir
tests/filecheck/transforms/convert_qssa_to_qref.mlir
xdsl/dialects/cmath.irdl

No more manual "please add end of line break" in PRs!

CI: add end of file and end of line pre-commit hooks

---

.github/workflows/ci-core.yml
.github/workflows/ci-mlir.yml
.github/workflows/ci-notebooks.yml
.github/workflows/ci-pyright-fails.yml
asv.conf.json

Just figured I've been working on Python 3.12 for a while now and everything's fine so why not; 3.13 is planned for October!

CI: Python 3.12

---

tests/filecheck/backend/csl/print_csl.mlir
tests/filecheck/dialects/csl/ops.mlir
xdsl/backend/csl/print_csl.py
xdsl/dialects/csl/csl.py

Adding `direction` type to csl

dialects: (csl) Add `direction` type

---

pyproject.toml

CI passed and then it didn't...

Revert "pip prod(deps): bump jax from 0.4.31 to 0.4.32 (#3161)"

---

tests/filecheck/dialects/eqsat/eqsat_ops.mlir
xdsl/dialects/__init__.py
xdsl/dialects/eqsat.py

dialects: (eqsat) add dialect and create new eclass op

---

xdsl/dialects/scf.py

As discussed in https://github.com/xdslproject/xdsl/pull/3157#discussion_r1762987533

dialects: (scf) small refactor for index_switch

---

tests/filecheck/transforms/eqsat-create-eclasses.mlir
tests/interpreters/test_eqsat_interpreter.py
tests/interpreters/test_eqsat_temp_interpreter.py
xdsl/dialects/eqsat.py
xdsl/tools/command_line_tool.py
xdsl/transforms/eqsat_create_eclasses.py

This PR tries to address https://github.com/xdslproject/xdsl/issues/3180
* Uncommented non-working examples (which require features from future PRs 
* Minimized the example for swapping inputs
* Formatted the code

Commented out non-working example with eqsat and minimized the swapping input example

---

tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
xdsl/transforms/csl_stencil_handle_async_flow.py

Minor bug: counter was not updated correctly

bug: (csl-stencil-handle-async-flow) Increment counter correctly

---

docs/marimo/linalg_snitch.py
docs/marimo/mlir/onnx_demo.py

Just to minimize diffs a little when experimenting

misc: re-run notebooks with newer version of marimo

---

tests/filecheck/dialects/cf/canonicalize.mlir
xdsl/dialects/cf.py
xdsl/transforms/canonicalization_patterns/cf.py

Remaining canonicalization pattern for `cf.br`.

dialects: (cf) br folding

---

xdsl/dialects/builtin.py
xdsl/dialects/cf.py
xdsl/dialects/utils.py
xdsl/frontend/code_generation.py

misc: minor linting

---

tests/filecheck/transforms/csl_stencil_bufferize.mlir
xdsl/transforms/csl_stencil_bufferize.py

This causes undesired behaviour in the bufferization.

Revert "transformations: (csl-stencil-bufferize) Inject accumulator in all csl-stencil linalg ops"

---

tests/interactive/test_app.py

misc: reorder imports in `tests/interactive/test_app.py`

---

tests/interactive/test_get_all_available_passes.py

No more updating the pass list when we add a new transform!

testing: use test dialect and custom passes for test_get_all_available_passes

---

xdsl/irdl/declarative_assembly_format.py

I just noticed an abundance of `cast`s, and realized it was partially due to the mutability and hence invariability of `list` being used. When we swap out the `list` for the immutable `tuple` or `Sequence`, Pyright is happier.

misc: remove casts in assembly format implementation [NFC]

---

tests/interactive/test_app.py
tests/interactive/test_get_all_available_passes.py
tests/interactive/test_rewrites.py
xdsl/backend/riscv/riscv_scf_to_asm.py
xdsl/frontend/passes/desymref.py
xdsl/interactive/rewrites.py
xdsl/transforms/__init__.py
xdsl/transforms/eqsat_create_eclasses.py
xdsl/transforms/experimental/dmp/stencil_global_to_local.py
xdsl/transforms/function_transformations.py
xdsl/transforms/individual_rewrite.py
xdsl/transforms/inline_snrt.py

Now again in alphabetical order, and with corresponding names.

misc: clean up passes getters [NFC]

---

tests/filecheck/transforms/eqsat-create-eclasses.mlir

We added this in the WIP branch, might as well add to main

testing: add one more op to eqsat-create-eclasses test

---

pyproject.toml
tests/filecheck/backend/riscv/convert_ptr_to_riscv.mlir
tests/test_printer.py
xdsl/backend/riscv/lowering/convert_arith_to_riscv.py
xdsl/backend/riscv/lowering/convert_arith_to_riscv_snitch.py
xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
xdsl/dialects/onnx.py
xdsl/dialects/riscv.py
xdsl/dialects/tensor.py
xdsl/dialects/x86/assembly.py
xdsl/interpreters/pdl.py
xdsl/ir/core.py
xdsl/irdl/constraints.py
xdsl/irdl/operations.py
xdsl/parser/core.py
xdsl/transforms/convert_ptr_to_riscv.py
xdsl/transforms/lower_affine.py
xdsl/utils/test_value.py

misc: use assert_never to enforce exhaustive matches

---

tests/filecheck/transforms/eqsat-extract.mlir
xdsl/dialects/eqsat.py
xdsl/transforms/__init__.py
xdsl/transforms/eqsat_add_costs.py
xdsl/transforms/eqsat_extract.py

transformations: add eqsat-extract

---

tests/interpreters/test_pdl_interpreter.py

One more unit test, one to go.

interpreter: (pdl) add test for operation matching

---

tests/interpreters/test_pdl_interpreter.py

interpreter: (pdl) add test for attribute matching

---

tests/test_dialect_utils.py
xdsl/dialects/arith.py
xdsl/dialects/csl/csl.py
xdsl/dialects/csl/csl_stencil.py
xdsl/dialects/experimental/air.py
xdsl/dialects/func.py
xdsl/dialects/linalg.py
xdsl/dialects/llvm.py
xdsl/dialects/memref.py
xdsl/dialects/memref_stream.py
xdsl/dialects/omp.py
xdsl/dialects/riscv.py
xdsl/dialects/riscv_func.py
xdsl/dialects/riscv_scf.py
xdsl/dialects/riscv_snitch.py
xdsl/dialects/scf.py
xdsl/dialects/stream.py
xdsl/transforms/arith_add_fastmath.py
xdsl/transforms/canonicalization_patterns/riscv.py

Revert "dialects: (stream) simplify constr helper on stream attributes"

---

xdsl/irdl/declarative_assembly_format_parser.py

core: Remove ParsingContext

---

tests/irdl/test_declarative_assembly_format.py
xdsl/irdl/declarative_assembly_format.py
xdsl/irdl/declarative_assembly_format_parser.py

~Started writing an operands directive but the parse errors appear in the wrong place so might refactor everything again.~ I refactored everything again (#3516)
Also needs more tests.

core: Add operands directive

---

tests/dialects/test_arm_func.py
tests/filecheck/dialects/arm_func/arm_func_ops.mlir
tests/filecheck/dialects/arm_func/test_ops.mlir
xdsl/dialects/arm_func.py

Add funcOp for ARM, similar to that already in RISCV.

dialects (arm): add func op

---

.github/workflows/ci-mlir.yml

In our migration to uv, we missed these

CI: install wgpu and onnx in mlir ci

---

tests/dialects/test_builtin.py
xdsl/dialects/builtin.py

Fixed TensorOrMemrefOf and added some tests

dialects: (builtin) Fix TensorOrMemrefOf and add some tests

---

tests/filecheck/transforms/jax-use-donated-arguments-remove-outputs.mlir
tests/filecheck/transforms/jax-use-donated-arguments.mlir
xdsl/transforms/__init__.py
xdsl/transforms/jax_use_donated_arguments.py

Reuse donated buffers + remove return values if we can load data to buffer.

transforms: Jax buffer donation

---

tests/test_rewriter.py
xdsl/rewriter.py

Stacked PRs:
* #3683
* #3682
* __->__#3681
--- --- ---

core: Allow to erase orphan operations

---

tests/pattern_rewriter/test_pattern_rewriter.py
xdsl/backend/riscv/riscv_scf_to_asm.py
xdsl/pattern_rewriter.py
xdsl/transforms/convert_scf_to_openmp.py

Stacked PRs:
* __->__#3683
* #3682
* #3681
--- --- ---

core: Make PatternRewriter a Builder

---

tests/interactive/test_app.py
xdsl/interactive/app.py
xdsl/interactive/pass_list_item.py

Last PR of the batch, with this the app only deals with pass types or instances, no more specs.

interactive: App tree holds either a pass type or instance, no spec

---

flake.lock

Updates ruff to 0.5.21 in flake

installation: (nix) update flake

---

xdsl/builder.py

documentation: update ImplicitBuilder doc comment

---

pyproject.toml
uv.lock

I'm relatively sure that this dependency isn't used now that we have uv.

dependencies: remove pip

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/issue_template.md

This PR adds:
- A GH issue/bug template

misc: Add GH issue template

---

docs/marimo/mlir_ir.py

First notebook, introduction, check it out [here](https://marimo.app/#code/MQAg9BIM4MYE4EsAOAXAUKOBTAjgVwWygFokBPFACwHsA7EAXhACIA+BgZgDoBGAJmYYQAEyxIstUbRgIsURiADaQkKpYAPYVAA2zADRCAukIhg0aBAFsk1OChCWAhokvVzAfXcBzCVjiOULGF3AHcEKgVmAAZeGJ4AdkFHJCQFJxdqLgBBFIAKMOEqBmZLIIQ8S2YASnM0AAFkpC4YLG1tXMoEUXcYalEGABU4PCwa0QAzEHdcqoAuNDUQKxs7B2crahBHeVdzRfG4aksQTR1mukD1e2XbewBZABkAYQusK4W1A6OTrW0uYQQjm0WBgKHkN1WACMCNoUAhaHotogqIjxnhpIjYOMPqovsdTn88HDtODrLc1hktvJ1Lt9od8b8uEhELRAnAlmTVgAFFlsnEgPEgFBkJDwrwclb2LK0Mj87AoPBwejSsiIx4vVlvFCInnwtmI9YokDQhCw+Go9EwRGuTEwcaImlucwNFLNVrtTrdXr9IYjMZYSbTVxzfmuLiWYS5ODMGOgR4ASQASiAkzHqnKsAqlbUXU0Wm0Ol0sD0+lhBsNRmgJlNcsH5oswxGo2ngKABlq8ECQAAxWxOFBpmqLeWK2g5xpugue4vesu+yvVoPUREoRCOWheYHuS4oEMNzJNg5p-kJ5Pr4QnAAiAGUHiA8FAsFt6BJvWKQNRJlQn0mqVshR2XbjH2AQCrYIhYNCXheGKK5yHCG4G …

documentation: add MLIR IR notebook from workshop

---

docs/marimo/builders.py

[Notebook](https://marimo.app/#code/JYWwDg9gTgLgBCAhlUEBQaD6mDmBTAOzykRjwBNMB3YGACzgF44AiABgDoBGTrgdhZpEYMEwTJUHAIIiAFAEoMaAALCwHAMZ4ANttl1g5PJg0QjjACpQArnkVGAZnEwKAXGjie4oSLHEoQCDhEAGcEdC84BygIEDgAD3IQ7Q4AI2tgbSMob3BoeAAhDKziABo4AEkCEOIYAAUIYAIYDy9o2ISklOsYTLCffP9UYLD4wNbPdrjE5I5yYERtPA0YEI4JelzfeClyeYB5MAmomOmuuYWllbX0zN6CLcGAWTNrJcPyqrJ8KAsATzAeE+zTwPykMBgUGOU06s3mi2Wq3WKE2Az8AGEINUYIhmodjlA8DBrFAHrJjpFdgcwKUKV4iplsrTIpFMdjcTAPnTPFUarAGk0YMyWTyQWCIVBhSKvqDiP9AVKWS9yG88FyRZ5AorImMIIrFBhVCJNDo9AYjCYzHhLDY7GhHM5ZIF5O5IoEOCByLIoCxfQBiOAMkpQEK+liKSKE4mkpRG9RaXT6QzGUzmKy2ex4JwuZ2urzuz3esNB7JhZB4ODWGrkOAwIJNPnwIhUOAQQEkXpY-oPXFwPDxYAhe44OCpbQQDQAaw4cAA6gYlrW6Hg-sFtCEgv3B-AmnAngAZCoAJXK9BXcCo0EnwVHtDg8wcDmIhBg2lXu-iABEAMr7mdVPdDxPUdilLYJCUratayCDRCVICs22IUhgC7coqAXCsPx-fcQMZYgywgqsKGg7xqlqNc4PI …

documentation: add Builders notebook from workshop

---

pyproject.toml
uv.lock

Now lives in https://github.com/xdslproject/xdsl-bench
Results: https://xdsl.dev/xdsl-bench/

dependencies: remove asv

---

tests/dialects/test_bufferization.py
tests/test_traits.py
xdsl/dialects/bufferization.py
xdsl/dialects/builtin.py
xdsl/dialects/csl/csl_stencil.py
xdsl/dialects/memref_stream.py
xdsl/dialects/stencil.py
xdsl/transforms/convert_stencil_to_csl_stencil.py
xdsl/transforms/csl_stencil_to_csl_wrapper.py

dialects: (builtin) remove AnyMemRefTypeConstr

---

docs/marimo/mlir_ir.py

A bug slipped in. In the future we will want to look for ways to test these snippets, maybe, but that's not trivial today.
CC @tobiasgrosser

documentation: fix l1 scf example

---

tests/filecheck/dialects/x86_func/x86_ops.mlir
xdsl/dialects/__init__.py
xdsl/dialects/x86_func.py

Reopening erroneously merged #3867

dialects: (x86_func) add x86_func dialect

---

pyproject.toml
uv.lock

Stacked PRs:
* #3884
* #3883
* #3882
* #3881
* __->__#3886
--- --- ---
As we are going to merge notebooks that depends on sympy, we need an
optional dev dependency.

docs: Add sympy to dev dependencies

---

docs/marimo/pattern_rewrites.py

Stacked PRs:
* #3884
* #3883
* __->__#3882
* #3881
* #3886
--- --- ---

docs: Add notebook for pattern rewrites

---

docs/marimo/rewrite_exercises.py

Stacked PRs:
* #3884
* __->__#3883
* #3882
* #3881
* #3886
--- --- ---

docs: Add notebook for pattern rewrites exercises

---

docs/marimo/defining_dialects.py

Stacked PRs:
* __->__#3884
* #3883
* #3882
* #3881
* #3886
--- --- ---

docs: Add notebook for defining dialects

---

xdsl/irdl/declarative_assembly_format.py
xdsl/irdl/declarative_assembly_format_parser.py

core: remove field on assembly format parser

---

xdsl/dialects/csl/csl.py
xdsl/ir/core.py

Fixes #3897 (at least the actionable part).

core: remove constr from Attribute

---

tests/dialects/test_func.py

Do we need this any more? This seems to be a test for the Python API, which we tend not to test too much these days. I'd like to remove the dependency on `assert_print_op`, so it would be good to figure out how we want to change these tests if we want to keep them to avoid the import.

testing: remove func call printing tests

---

tests/filecheck/backend/csl/print_csl.mlir
tests/filecheck/dialects/csl/csl-canonicalize.mlir
tests/filecheck/dialects/csl/ops.mlir
tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
tests/filecheck/transforms/lower-csl-stencil.mlir
tests/filecheck/transforms/memref-to-dsd.mlir
xdsl/dialects/csl/csl.py
xdsl/transforms/csl_stencil_handle_async_flow.py
xdsl/transforms/lower_csl_stencil.py
xdsl/transforms/memref_to_dsd.py

csl: (dialects) Change csl to use signless integers

---

.github/workflows/ci-docs.yml
mkdocs.yml

Let's make sure it always builds even if we're not deploying it yet.

documentation: use strict flag for building website and add to CI

---

.github/workflows/ci-mlir.yml

https://github.com/actions/runner-images/issues/11101

ci: use ubuntu-latest in ci-mlir

---

tests/dialects/test_riscv.py
tests/filecheck/dialects/riscv/csr_invalid.mlir
xdsl/dialects/riscv.py

backend: (riscv) x0 is same as zero for CSR for verification

---

Makefile

The changes from  #4035 didn't work on my computer, not sure if it's because bash wasn't picked up properly, or a difference in `make`, but this seems to work.
I've also removed the stdout output again from Python.

CI: fix tests-marimo on mac

---

tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
tests/filecheck/transforms/lower-csl-wrapper.mlir
xdsl/transforms/csl_stencil_to_csl_wrapper.py
xdsl/transforms/lower_csl_wrapper.py

This PR updates transforms to cater for sdk version 1.3

transforms: (csl) Support sdk 1.3

---

tests/filecheck/dialects/bigint/attrs.mlir
xdsl/dialects/__init__.py
xdsl/dialects/bigint.py

Add start of bigint dialect, with filecheck tests

dialects: (bigint) Add start of bigint dialect

---

tests/dialects/test_builtin.py
xdsl/dialects/builtin.py

For use in dialect and dialect stub generation.

dialects: (builtin) add custom repr to IntegerType

---

tests/filecheck/utils/codegen/simple.py
xdsl/utils/dialect_codegen.py

This adds a minimal Python codegen stub file, to be filled in later by @mamanain and me. This will be used first by the torch dialect codegen file, and later by the tablegen and potentially other use-cases.

misc: add python dialect codegen file with minimal functionality

---

xdsl/dialects/stablehlo.py

dialects: (stablehlo) Improve documentation

---

tests/filecheck/utils/codegen/simple.py
xdsl/utils/dialect_codegen.py

Filling in the functionality - operands and results

misc: Python dialect codegen - operands and results

---

xdsl/dialects/arm/assembly.py
xdsl/dialects/arm/ops.py

Should make the code a bit more readable and less tedious to extend.

dialects: (arm) add helper to print register SSAValues in ARM assembly

---

Makefile

misc: (makefile) remove directive defining bash location

---

xdsl/ir/core.py

Stacked PRs:
* #3991
* __->__#3989
* #3988
* #3987
--- --- ---

core: Make OpResult and BlockArgument generic like SSAValue

---

pyproject.toml

I thought I'd add some more Pyright rules and comment some of the ones we have to make the reason clearer.

CI: add some more Pyright rules and add comments

---

pyproject.toml
tests/irdl/test_declarative_assembly_format.py
tests/irdl/test_operation_definition.py
tests/test_is_satisfying_hint.py
xdsl/irdl/operations.py
xdsl/utils/hints.py

Might as well keep track of when the ignores are no longer necessary

CI: report unnecessary Pyright ignores

---

tests/filecheck/utils/codegen/simple.py
xdsl/utils/dialect_codegen.py

Printing another part of the OpDef

misc: Print irdl options when dumping ops

---

tests/filecheck/utils/codegen/simple.py
xdsl/utils/dialect_codegen.py

We need to support traits for the torch dialect, decided to do couple more fields while I'm at it.

misc: Print properties, traits and attributes in codegen

---

tests/filecheck/dialects/arm_neon/test_ops.mlir
tests/filecheck/dialects/arm_neon/test_ops_invalid.mlir
xdsl/dialects/arm/assembly.py
xdsl/dialects/arm_neon.py

Neon structure store instruction reads data from memory into 64-bit Neon registers.
ST1 stores one to four registers of data to memory, with no interleaving.

dialects (arm): Add st1 op

---

tests/filecheck/frontend/programs/invalid.py
xdsl/frontend/pyast/code_generation.py
xdsl/frontend/pyast/program.py
xdsl/frontend/pyast/type_conversion.py

Move type registry into type converter.

frontend: (pyast) Move type registry into type converter

---

xdsl/dialects/pdl.py

Stacked PRs:
* __->__#4187
--- --- ---
This moves the manually written PDL parser and printer methods to the
nice assembly format. The format was taken from the PDL dialect
MLIR documentation.

dialects: Move PDL parser and printer to assembly format

---

tests/filecheck/dialects/memref/invalid_ops.mlir
xdsl/dialects/memref.py

Stacked PRs:
* #4202
* #4201
* __->__#4200
* #4199
--- --- ---

dialects: Use new util for dynamic indices in memref dialect

---

docs/Toy/Toy_Ch3.ipynb

documentation: fix chapter 3 name

---

tests/filecheck/frontend/refactor/bigint.py
tests/filecheck/frontend/refactor/operations.py
xdsl/dialects/bigint.py
xdsl/frontend/pyast/code_generation.py
xdsl/frontend/pyast/program.py
xdsl/frontend/pyast/type_conversion.py

Refactor type registration to use instantiated types. Peeled from #4193

frontend: (pyast) Refactor type registration to use instantiated types

---

tests/filecheck/dialects/linalg/linalg_ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
xdsl/dialects/linalg.py

dialects: (linalg) Select op

---

tests/filecheck/dialects/vector/invalid.mlir
xdsl/dialects/vector.py

Stacked PRs:
* __->__#4202
--- --- ---

dialect: Add vector insert and extract verifiers

---

tests/dialects/test_vector.py
xdsl/dialects/vector.py
xdsl/ir/affine/affine_map.py

PR 1/2, adding helpers, actual operations will be merged in #4263.

dialects: (vector) add helpers for transfer ops

---

xdsl/transforms/experimental/stencil_tensorize_z_dimension.py

A minor change that supports tensorizing any `FloatingPointLikeBinaryOperation`.

minor: (stencil-tensorize) Rewrite using base class

---

xdsl/dialects/ptr.py
xdsl/transforms/convert_memref_to_ptr.py
xdsl/transforms/convert_vector_to_ptr.py

Small fixup PR adding inits for a prettier API.

dialects: (ptr) add inits to ptr dialect

---

tests/filecheck/transforms/apply-pdl-interp/apply_pdl_interp_add_zero.mlir
tests/filecheck/transforms/apply-pdl-interp/apply_pdl_interp_extra_file.mlir
tests/filecheck/transforms/apply-pdl-interp/apply_pdl_interp_multi_ops.mlir
tests/filecheck/transforms/apply-pdl-interp/extra_file.mlir
xdsl/interpreters/pdl_interp.py
xdsl/transforms/__init__.py
xdsl/transforms/apply_pdl_interp.py

The final pr of the initial pdl-interp implementation, supersedes https://github.com/xdslproject/xdsl/pull/4162.

transformations: (pdl_interp) Add `pdl-interp-apply` pass

---

xdsl/dialects/builtin.py

Makes the type a little more specific

dialects: (builtin) stricten create_dense_float typing

---

tests/dialects/test_builtin.py
xdsl/dialects/builtin.py
xdsl/printer.py

dialects: (builtin) Make `ComplexType` inherit from `PackableType`

---

docs/Toy/toy/dialects/toy.py
tests/dialects/test_arith.py
tests/test_is_satisfying_hint.py
xdsl/dialects/builtin.py
xdsl/dialects/csl/csl_stencil.py
xdsl/dialects/linalg.py
xdsl/dialects/pdl.py
xdsl/dialects/stencil.py
xdsl/interpreters/arith.py
xdsl/irdl/constraints.py
xdsl/parser/attribute_parser.py
xdsl/pattern_rewriter.py
xdsl/transforms/convert_stencil_to_csl_stencil.py
xdsl/transforms/csl_stencil_bufferize.py
xdsl/transforms/csl_stencil_to_csl_wrapper.py
xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
xdsl/transforms/lower_csl_wrapper.py
xdsl/transforms/lower_mpi.py
xdsl/transforms/memref_to_dsd.py
xdsl/utils/isattr.py

Let's keep it until the next release.

core: deprecate isattr

---

tests/filecheck/backend/x86/convert_ptr_to_x86.mlir
xdsl/backend/x86/lowering/convert_ptr_to_x86.py

The lowering of the operation ```ptr_xdsl.ptradd``` to the x86 dialect

backend: ptr_xdsl.ptradd to x86

---

tests/filecheck/transforms/convert_vector_to_ptr.mlir
xdsl/transforms/convert_vector_to_ptr.py

Lowering of ```vector.store``` to the ```ptr``` dialect

transformations: (vector) vector.store to ptr

---

xdsl/irdl/operations.py

Found these old asserts, maybe pyright fixed the bug

minor: remove old asserts

---

docs/Toy/Toy_Ch3.ipynb
tests/dialects/test_builtin.py
tests/dialects/test_math.py
tests/interpreters/test_linalg_interpreter.py
tests/interpreters/test_memref_interpreter.py
tests/interpreters/test_ml_program_interpreter.py
xdsl/dialects/builtin.py
xdsl/parser/attribute_parser.py
xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
xdsl/transforms/printf_to_llvm.py

dialects: (builtin) deprecate from_list

---

xdsl/dialects/linalg.py
xdsl/dialects/memref.py

Went through and tried to specialise a couple of uses of `DenseIntOrFPElementsAttr`.

dialects: (builtin) simplify uses of DenseIntOrFPElementsAttr

---

tests/filecheck/transforms/convert_vector_to_ptr.mlir
xdsl/transforms/convert_vector_to_ptr.py

This will ensure consistency and hopefully correctness of lowering.

transformations: (convert-vector-to-ptr) share helper for offset calculations

---

flake.nix

installation: (nix) add zlib

---

tests/irdl/test_attr_constraint.py
tests/irdl/test_int_constraint.py
tests/irdl/test_range_constraint.py
xdsl/irdl/constraints.py

just add some more information to some exception messages which should never appear.

core: (constraints) improve inference debug message

---

tests/dialects/test_emitc.py
xdsl/dialects/emitc.py

dialects: (emitc) Add negative dimension verify exception

---

tests/dialects/test_smt.py
tests/filecheck/dialects/smt/ops.mlir
xdsl/dialects/smt.py

Stacked PRs:
* #4482
* #4481
* #4480
* __->__#4479
--- --- ---
It represent the SMT bitvector type

dialects: Add `smt.bv` type

---

pyproject.toml
tests/dialects/test_arith.py
tests/irdl/test_declarative_assembly_format.py
xdsl/dialects/arith.py
xdsl/dialects/builtin.py
xdsl/dialects/gpu.py
xdsl/interpreters/utils/ptr.py
xdsl/parser/base_parser.py
xdsl/parser/generic_parser.py
xdsl/transforms/experimental/dmp/stencil_global_to_local.py
xdsl/transforms/lower_mpi.py

Just pulling out some changes from #3443, to make that easier to iterate on.

misc: remove unused private TypeVars

---

tests/dialects/test_smt.py
tests/filecheck/dialects/smt/bv_ops.mlir
xdsl/dialects/smt.py

Stacked PRs:
* __->__#4482
--- --- ---

dialects: Add bitvector attribute and constant operation

---

benchmarks/README.md

Add a readme file to describe the use of the benchmarking infrastructure. Could also be worth adding examples of using asv, and a workflow for performance diff of a patch?

bench: add readme file to benchmarks directory

---

tests/interpreters/test_eqsat_pdl_interp_interpreter.py
xdsl/interpreters/eqsat_pdl_interp.py

This is essentially the hashcons in egg.

interpreter: (eqsat) `populate_known_ops`

---

tests/interpreters/test_eqsat_pdl_interp_interpreter.py
xdsl/interpreters/eqsat_pdl_interp.py

~Draft until https://github.com/xdslproject/xdsl/pull/4514 gets merged.~

interpreter: (eqsat) Interpret for GetResult(s)Op

---

tests/filecheck/backend/riscv/canonicalize.mlir
xdsl/dialects/riscv.py
xdsl/transforms/canonicalization_patterns/riscv.py

Added the canonicalization pattern of multiply by 1 refer to the GETTING_STARTED guide.

transformations: (riscv) Add canonicalization pattern x*1->x

---

tests/interpreters/test_eqsat_pdl_interp_interpreter.py
xdsl/interpreters/eqsat_pdl_interp.py

~~I still have to add some more comments.~~

interpreter: (eqsat) `run_replace` and `apply_matches`

---

xdsl/dialects/builtin.py
xdsl/dialects/scf.py
xdsl/dialects/utils/format.py
xdsl/parser/attribute_parser.py

Make the type system aware of this existing behaviour.

core: Parser.parse_type returns a TypeAttribute

---

xdsl/dialects/builtin.py
xdsl/parser/attribute_parser.py

Broke main by merging conflicting branches.

misc: fix tuple_type parsing

---

tests/dialects/test_builtin.py
xdsl/dialects/builtin.py

A small step towards this kind of init being generated automatically for all ParametrizedAttributes.

dialects: (builtin) add typed init to DenseArrayBase

---

tests/filecheck/transforms/apply-eqsat-pdl-interp/apply_eqsat_pdl_interp_extra_file.mlir
tests/filecheck/transforms/apply-eqsat-pdl-interp/apply_eqsat_pdl_interp_multi_ops.mlir
tests/filecheck/transforms/apply-eqsat-pdl-interp/egg_example.mlir
tests/filecheck/transforms/apply-eqsat-pdl-interp/extra_file.mlir
tests/filecheck/transforms/apply-eqsat-pdl-interp/rebuilding.mlir
xdsl/transforms/__init__.py
xdsl/transforms/apply_eqsat_pdl_interp.py

~Currently marked as draft as this PR is on top of `jumerckx/eqsat_pdl_interp`.~

transformations: (eqsat) Add apply-eqsat-pdl-interp pass

---

xdsl/dialects/comb.py

It's perhaps easy to do this by dialect

dialects: (comb) remove uses of Printer.print

---

xdsl/dialects/builtin.py
xdsl/dialects/llvm.py
xdsl/dialects/vector.py

dialects: (builtin) replace DenseI64ArrayConstr with DenseArrayBase.constr(i64)

---

xdsl/dialects/csl/csl_stencil.py

Similar to the stencil changes.

dialects: (csl-stencil) remove uses of Printer.print

---

xdsl/dialects/x86/ops.py

This one is a simple string replacement

dialects: (x86) remove uses of Printer.print

---

benchmarks/printer.py

Peel printer changes from #4522

bench: peel printer changes from #4522

---

benchmarks/workloads.py

Peel workload fixes from #4522.

bench: peel workload fixes from #4522

---

benchmarks/microbenchmarks.py

Peel microbenchmark changes from #4522

bench: peel microbenchmark changes from #4522

---

tests/filecheck/dialects/air/air_ops.mlir
xdsl/dialects/experimental/air.py
xdsl/dialects/experimental/fir.py
xdsl/dialects/experimental/hlfir.py

Moved away from using `print`, used `print_int` where possible, and tried to fix the printing for `air.herd`

dialects: (experimental) try to make printing more sane

---

docs/Toy/Toy_Ch2.ipynb
docs/Toy/toy/__main__.py
docs/marimo/mlir_interoperation.py
tests/irdl/test_attribute_definition.py
tests/pattern_rewriter/test_pattern_rewriter.py
tests/test_parser.py
tests/test_printer.py
tests/test_rewriter.py
xdsl/dialects/builtin.py
xdsl/dialects/gpu.py
xdsl/dialects/irdl/irdl.py
xdsl/dialects/llvm.py
xdsl/dialects/memref_stream.py
xdsl/dialects/pdl.py
xdsl/dialects/riscv_snitch.py
xdsl/dialects/seq.py
xdsl/dialects/snitch_stream.py
xdsl/dialects/stim/ops.py
xdsl/dialects/transform.py
xdsl/dialects/vector.py
xdsl/dialects/x86/assembly.py
xdsl/interactive/app.py
xdsl/ir/core.py
xdsl/printer.py
xdsl/transforms/mlir_opt.py

core: (Printer) deprecate Printer.print

---

.github/workflows/ci-core.yml
.github/workflows/ci-docs.yml
.github/workflows/ci-lockfile.yml
.github/workflows/ci-mlir.yml
.github/workflows/ci-notebooks.yml
.github/workflows/ci-pyright-fails.yml
.github/workflows/code-formatting.yml
.github/workflows/jupyterlite.yml
.github/workflows/pythonpublish.yml

These guys recommend it for some reason, I guess it doesn't hurt.
https://codspeed.io/docs/benchmarks/python

CI: use setup-python instead of uv python install

---

tests/filecheck/dialects/tensor/invalid_ops.mlir
tests/filecheck/dialects/tensor/ops.mlir
xdsl/dialects/tensor.py

Adding this in preparation for #4245

dialect: Add ContiguousArrayOfIntArray to tensor dialect

---

xdsl/frontend/pyast/code_generation.py
xdsl/frontend/pyast/program.py
xdsl/frontend/pyast/type_conversion.py

Refactor the type registry in PyAST's frontend

pyast: (frontend) refactor type registry

---

tests/filecheck/dialects/pdl_interp/pdl_interp_ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/pdl_interp/pdl_interp_ops.mlir
tests/interpreters/test_pdl_interp_interpreter.py
xdsl/dialects/pdl_interp.py
xdsl/interpreters/pdl_interp.py

These are the last operation required to parse the Herbie ruleset

interpreter: (pdl_interp) `switch_attribute`, `create_type`, and `create_types`

---

xdsl/dialects/builtin.py

No need to subclass GenericData

core: DictionaryAttr is not generic

---

xdsl/dialects/arith.py
xdsl/dialects/builtin.py
xdsl/dialects/llvm.py
xdsl/dialects/stencil.py

Also split off of #4510. Simplifies various (hopefully non-controversial) AnyOf constraints in the repository.

dialects: simplify various AnyOf constraints

---

xdsl/dialects/builtin.py
xdsl/parser/attribute_parser.py
xdsl/transforms/csl_stencil_bufferize.py
xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
xdsl/transforms/printf_to_llvm.py

I had to messwith some helpers in stencil land.

dialects: (builtin) add init to DenseIntOrFPElementsAttr

---

xdsl/parser/attribute_parser.py

Makes the `AnyOf` cases disjoint.

misc: Simplify use of `RankedStructure`

---

tests/dialects/test_hw.py
xdsl/dialects/hw.py

One more steps towards typed inits everywhere.

dialects: (hw) add init to ModuleType, ModulePort and ParamDeclAttr

---

tests/dialects/test_stencil.py
xdsl/dialects/csl/csl.py
xdsl/dialects/csl/csl_wrapper.py
xdsl/dialects/experimental/dmp.py
xdsl/dialects/stencil.py
xdsl/transforms/csl_stencil_to_csl_wrapper.py

Did a bunch in one go in related bits of code.

dialects: (stencil) add typed inits to stencil and csl attrs

---

tests/irdl/test_attr_constraint.py
tests/irdl/test_attribute_definition.py
tests/irdl/test_declarative_assembly_format.py
tests/test_is_satisfying_hint.py
tests/test_pyrdl.py

testing: add inits to attributes in tests

---

xdsl/dialects/arith.py
xdsl/dialects/csl/csl_stencil.py
xdsl/dialects/tosa.py

AnyFloat is the default parameter.

misc: simplify FloatAttr[AnyFloat]

---

tests/filecheck/dialects/stablehlo/attrs.mlir
xdsl/dialects/stablehlo.py

Just finishing off @joeycarter's PR as he is busy with other things. Happy to continue the discussion here or in Zulip. I also opened this [issue](https://github.com/openxla/stablehlo/issues/2828) on the stablehlo repo itself.
Fixes #4691

dialects: (stablehlo) make batching dimensions optional

---

tests/transforms/test_memref_stream_interleave.py
xdsl/transforms/memref_stream_interleave.py

I'd like to use this bit of logic in some other passes, seems like a good idea to factor it out to a helper.

transformations: (memref-stream-interleave) add factors helper

---

xdsl/utils/scoped_dict.py

I hit a recursion depth limit, this fixes it.

interpreter: (ScopedDict) Don't recurse when getting an item

---

docs/Toy/Toy_Ch3.ipynb
docs/Toy/toy/dialects/toy.py
docs/Toy/toy/frontend/ir_gen.py
docs/Toy/toy/interpreter.py
docs/Toy/toy/rewrites/optimise_toy.py

Our coding style has moved on since we added this, this PR udpates some helpers and init methods.

documentation: (Toy) clean up toy dialect

---

xdsl/dialects/builtin.py
xdsl/parser/attribute_parser.py

misc: remove parameter parsing and printing for builtin data attributes

---

tests/ir/test_attribute.py
xdsl/ir/core.py

Based on suggestion in #4755, adds a `get` method which functions similarly to `SSAValue.get`

core: (Data) add get method

---

tests/test_lexer.py
xdsl/utils/lexer.py

Also make `get_lines_containing` fail on invalid input Spans.

misc: add Input.get_start_of_line and .get_end_of_line

---

tests/test_affine_builtins.py
xdsl/ir/affine/affine_map.py

Another useful helper from MLIR's AffineMap.

core: (affine) add AffineMap.unused_dims and .unused_dims_bit_vector

---

tests/filecheck/dialects/emitc/emitc_types.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/emitc/emitc_types.mlir
xdsl/dialects/emitc.py

Add the emitc [SizeTType](https://mlir.llvm.org/docs/Dialects/EmitC/#sizettype)

dialects: (emitc) Add SizeTType

---

tests/filecheck/dialects/omp/ops.mlir
tests/filecheck/dialects/omp/ops_invalid.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/omp/ops.mlir
xdsl/dialects/omp.py

`omp.distribute` op from upstream MLIR.

dialects:(omp) add omp.distribute op

---

xdsl/irdl/declarative_assembly_format_parser.py

misc: remove a cast in declarative assembly format parser

---

tests/irdl/test_declarative_assembly_format.py
xdsl/irdl/constraints.py

core: (Constraints) deprecate TypedAttributeConstraint

---

tests/filecheck/dialects/omp/ops.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/omp/ops.mlir
xdsl/dialects/omp.py

As defined upstream:
<https://mlir.llvm.org/docs/Dialects/OpenMPDialect/ODS/#ompteams-ompteamsop>

dialects:(omp) add omp.teams operation

---

tests/irdl/test_range_constraint.py
xdsl/irdl/constraints.py

Small bug fix to propagate the variables properly.

core: fix RangeOf variables

---

tests/filecheck/dialects/dlti/attrs.mlir
tests/filecheck/dialects/dlti/attrs_invalid.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/dlti/attrs.mlir
xdsl/dialects/__init__.py
xdsl/dialects/dlti.py

Stacked PRs:
* #4864
* __->__#4863
--- --- ---
This is the last dialect missing to be able to parse the result of
an mlir-translate from LLVM IR to MLIR IR.
https://mlir.llvm.org/docs/Dialects/DLTIDialect/

dialects: Add DLTI dialect

---

xdsl/irdl/declarative_assembly_format_parser.py

Removes a level of indentation in a bit of code I want to refactor a little bit.

core: remove unnecessary isinstance in attribute parser

---

tests/test_parser.py
xdsl/parser/attribute_parser.py
xdsl/parser/base_parser.py

Stacked PRs:
* #4867
* #4866
* #4865
* __->__#4878
--- --- ---

core: Add parse_identifier_or_str_literal method

---

tests/irdl/test_attribute_definition.py
tests/test_parser.py
xdsl/ir/core.py
xdsl/parser/base_parser.py

Stacked PRs:
* #4867
* #4866
* __->__#4865
* #4878
--- --- ---

core: Allow non-keyword enums in StrEnum

---

tests/filecheck/dialects/llvm/attrs-invalid.mlir
tests/filecheck/dialects/llvm/attrs.mlir
tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/attrs.mlir
xdsl/dialects/llvm.py

Stacked PRs:
* __->__#4867
* #4866
* #4865
* #4878
--- --- ---

dialects: Add #llvm.target_features attribute

---

xdsl/irdl/declarative_assembly_format.py
xdsl/irdl/declarative_assembly_format_parser.py

This makes it easier to specialise subclasses of AttributeVariable.

core: factor out parse_attr in AttributeVariable directive

---

xdsl/irdl/declarative_assembly_format.py
xdsl/irdl/declarative_assembly_format_parser.py

Thought I'd do these two in one go.

core: factor out UniqueBase and UniqueTypeAttributeVariable directives

---

tests/irdl/test_declarative_assembly_format.py
xdsl/irdl/declarative_assembly_format_parser.py

This feels like it should be safe.

core: handle VarConstraint in attr/prop directive

---

tests/test_use.py
xdsl/interpreters/eqsat_pdl_interp.py
xdsl/ir/core.py
xdsl/transforms/test_constant_folding.py

Stacked PRs:
* __->__#4909
--- --- ---

core: Use linked list for SSAValue uses

---

tests/filecheck/utils/codegen/simple.py
tests/irdl/test_attribute_definition.py
xdsl/dialects/builtin.py
xdsl/ir/core.py
xdsl/irdl/attributes.py
xdsl/parser/attribute_parser.py

I had a go. I'm not sure if this is the right way to do it but let's iterate.

core: (ParametrizedAttribute) add converters

---

xdsl/irdl/declarative_assembly_format.py

Adds more getters and setters to assembly format directives.

misc: (Assembly Format) add more getters/setters

---

xdsl/irdl/operations.py

Test at hardcoding all the operation accessors. It's unclear whether this is actually worth it.

core: (Operation) optimise accessors

---

tests/interpreters/test_eqsat_pdl_interp_interpreter.py
xdsl/interpreters/eqsat_pdl_interp.py
xdsl/transforms/apply_eqsat_pdl.py
xdsl/transforms/apply_eqsat_pdl_interp.py

fixes https://github.com/xdslproject/xdsl/issues/4539
fixes #3300
This implements egg-style rebuilding.

interpreter: (eqsat) Full rebuilding

---

docs/.nav.yml
docs/index.md

Align documentation and homepage content

documentation: modify navbar and align homepage content

---

tests/irdl/test_int_constraint.py
xdsl/dialects/emitc.py
xdsl/irdl/constraints.py

Allows us to specify a number of possible int values.
CC @Jimmy2027

core: add IntSetConstraint

---

xdsl/irdl/attributes.py

Diff looks horrible because of reorderings, but I think this cleans up the logic a bit.

core: (irdl_to_attr_constraint) slight refactor/cleanup

---

docs/marimo/pattern_rewrites.py

documentation: remove reference to Winter School schedule

---

xdsl/irdl/operations.py

core: (Accessors) stricten typing

---

tests/test_pyrdl.py
xdsl/dialects/builtin.py

Penultimate PR, next one adds it to IntegerType.

dialects: (builtin) make SignednessAttr generic

---

tests/filecheck/dialects/memref/invalid_ops.mlir
tests/filecheck/dialects/snitch_runtime/snitch_runtime_invalid.mlir
tests/test_pyrdl.py
xdsl/dialects/builtin.py
xdsl/dialects/emitc.py
xdsl/dialects/experimental/fir.py
xdsl/dialects/experimental/hlfir.py
xdsl/irdl/attributes.py
xdsl/irdl/declarative_assembly_format_parser.py

No more Annotated in I32 and friends.

dialects: (builtin) make IntegerType generic over Signedness

---

xdsl/transforms/convert_memref_to_ptr.py

transformations: (convert-memref-to-ptr) add get_offset_pointer helper

---

tests/filecheck/dialects/emitc/emitc_types_invalid.mlir
xdsl/dialects/emitc.py

Convert the is_supported_emitc_type function to an AttrConstraint.
As proposed in #5026

dialects: (emitc) Add EmitCTypeConstraint

---

docs/marimo/expressions.py

This will help us to see if we can use the marimo directory to make https://xdsl.readthedocs.io/latest/ load the xdsl wheel correctly.

documentation: use marimo directory for micropip

---

docs/marimo/mlir_introduction.py

Reduce the amount of text until the very first exercise

documentation: shorten title

---

docs/marimo/mlir_introduction.py
xdsl/utils/marimo.py

This mocks up the boolean exercise, still requiring the interpreter to be interactive.

documentation: mlir intro - booleans - structure

---

docs/marimo/mlir_introduction.py

Checks the printed output instead of a value.

documentation: check for arith interpretation output

---

tests/test_pass_to_spec.py
xdsl/passes.py
xdsl/utils/marimo.py

Makes it easier to show in notebooks.

misc: show pipeline pass spec as str

---

tests/interpreters/test_arith_interpreter.py
xdsl/interpreters/arith.py

interpreter: (arith) fix bitwidth issues

---

docs/marimo/mlir_introduction.py

Kind of hardcoded need to double check that they're correct, not sure how to construct automated tests for these.

documentation: check pass exercise outputs

---

docs/marimo/mlir_introduction.py

Reverts xdslproject/xdsl#5192
It seems this PR was incorrect.

Revert "documentation: mlir_intro - fix expected values"

---

tests/backend/test_asm_reporter.py
xdsl/backend/block_throughput_cost_model.py

Doesn't work on my ARM mac.
I propose hard-coding it for now and making it parametrizable in the future.

misc: fix cross-platform llvm-mca call

---

tests/filecheck/transforms/convert_memref_to_ptr.mlir
xdsl/transforms/convert_memref_to_ptr.py

I'm not 100% sure about this yet, will verify this in practice on matmul in another repo before opening for review.

transformations: (convert-memref-to-ptr) lower memref.subview

---

xdsl/transforms/convert_pdl_to_pdl_interp/predicate.py

(+ small fix going from `pdl.AnyPDLType` to `Attribute` in `result_types `)

transformations: (convert_pdl_to_pdl_interp) Ensure ConstraintQuestion is hashable

---

tests/test_affine_builtins.py
xdsl/ir/affine/affine_expr.py

core: add post-order traversal to AffineExpr
