src/xdsl/rewriter.py, tests/rewriter_test.py
Add rewrite patterns, along with rewrite walkers.
This is a first implementation, based on christian and michel version.
It has the flaw that rewrites modifying regions will modify the region for the operation in place, and thus the operands given in the future rewrite patterns will have their regions modified as well.
I'll think about it more for future versions, but for now I'll try to push this version  so we can move forward.
=> Add first rewriter draft

src/xdsl/rewriter.py, tests/rewriter_test.py
Rewriters can now delete SSA values, by mapping them to None it the updater.
This can be used to delete operations for instance.
During the walk, it is checked that no operations are created with the deleted operands, and thus those rewrites are safe to use.
=> Allow rewriters to delete SSA values

src/xdsl/printer.py, tests/rewriter_test.py
Before this patch we print nested regions as:
```
choco.ast.program() {}
{
choco.ast.call_expr() {
choco.ast.id_expr() ["id" = "print"]
}
{
choco.ast.binary_expr() ["op" = "+"]{
choco.ast.binary_expr() ["op" = "+"]{
choco.ast.literal() ["value" = !int<42>]
}
{
choco.ast.literal() ["value" = !int<43>]
}
}
{
choco.ast.literal() ["value" = !int<44>]
}
}
}
```
after this patch we print them as:
```
choco.ast.program() {} {
choco.ast.call_expr() {
choco.ast.id_expr() ["id" = "print"]
} {
choco.ast.binary_expr() ["op" = "+"] {
choco.ast.binary_expr() ["op" = "+"] {
choco.ast.literal() ["value" = !int<42>]
} {
choco.ast.literal() ["value" = !int<43>]
}
} {
choco.ast.literal() ["value" = !int<44>]
}
}
}
```
=> Printer: improve indentation

src/xdsl/dialects/builtin.py, src/xdsl/dialects/memref.py, src/xdsl/dialects/scf.py, src/xdsl/dialects/std.py, src/xdsl/ir.py, src/xdsl/irdl.py
This change no longer highlights code such as:
```python
def translate_def(ctx: Ctx, op: Operation) -> [Operation]:
if isinstance(op, choco_ast.FuncDef):
return translate_fun_def(ctx, op)
def translate_fun_def(ctx: Ctx, fun_def: choco_ast.FuncDef) -> Operation:
...
```
as a typing error.
With this change PyCharm (and I assume mypy) correctly assumes that the type of `op` in the branch is `choco_ast.FuncDef` and not `Operation`),
=> Changed typing to improve type checking in PyCharm

src/xdsl/dialects/builtin.py, src/xdsl/irdl.py, tests/operation_builder_test.py
This PR changes the types of the operand segment sizes to the ones MLIR uses. Furthermore, it changes a builder for the `DenseIntOrFPElementAttrs` to actually respect the type passed as a vector or tensor type.
=> IRDL: fix operand_segment_sizes types

src/xdsl/dialects/affine.py, src/xdsl/dialects/builtin.py, src/xdsl/ir.py
This PR ensures that all of xdsl uses region and block builders to
ensure that the parent attributes of their children are correctly set.
Furthermore, we remove all fields from their constructors to encourage the
usage of builders or getters.
Fixes #38
=> Fix parent attributes of ops and blocks

src/xdsl/dialects/builtin.py, src/xdsl/irdl.py, tests/operation_builder_test.py
This allows to have attributes that can be omitted in operations.
=> Add optional attributes to IRDL

src/xdsl/irdl.py, tests/operation_builder_test.py
This should fix the accessors for optional attributes.
They now return `None` when the attribute is not present, instead of an exception.
=> Add optional attributes accessors

src/xdsl/ir.py
Now, single-block regions have the `ops` property, and single-operation single-block regions have the `op` property.
This means, that for a single-operation single-block region, we can write `region.op` instead of `region.blocks[0].ops[0]`.
=> Add accessors for single-block regions.

src/xdsl/printer.py, tests/printer_test.py
Closes #59 
This gives a bit better error message, when one forgets to add an operation to the IR. This helps in cases like: https://github.com/compiling-techniques/ChocoPyCompiler/pull/297
=> Error: print proper error on missing SSAValue

src/xdsl/ir.py, src/xdsl/printer.py, src/xdsl/rewriter.py, tests/cf_test.py, tests/pattern_rewriter_test.py, tests/rewriter_test.py
Add more functionality to rewrite blocks.
It adds functions to:
* Insert new blocks in regions
* Split blocks
* Inline a block in a position inside another block
This is not ready though, since I need to first add support for insertion points I think
=> Open rewrite API on blocks

src/xdsl/diagnostic.py, src/xdsl/printer.py, tests/printer_test.py
This PR adds a diagnostic class to xDSL, that can be used to print errors in the code.
This can be used in the verifiers, the rewriter, or the IR methods.
=> Add diagnostic engine to xDSL

src/xdsl/ir.py
This should drastically reduce the size of Exceptions during a KeyError for instance
=> Improve the size of __repr__ methods in the IR

src/xdsl/ir.py, src/xdsl/rewriter.py
This commit adds a new field to ErasedSSAValue, which keeps the old ssa value that was deleted.
This is useful to get back the deleted value, in case this value was used in a dictionary for instance.
Also, this fixes a bug in the rewriter, which makes some tests fail in ChocoPy
=> Erased value history

src/xdsl/ir.py, tests/operation_builder_test.py
closes #68
This implements `parent_op`, `parent_region`, and `parent_block` for `Operation`, `Region`, and `Block`. This was the simplest design I could think of, feel free to suggest one if there is a simpler one.
=> Parent pointers

src/xdsl/ir.py, src/xdsl/parser.py, src/xdsl/printer.py, src/xdsl/rewriter.py, tests/printer_test.py, tests/rewriter_test.py
closes #69  This implements a feature that Mathieu and me discussed during the workshop. It adds functionality to preserve the name of an SSAValue. This makes it simpler to see which SSAValues are used where, since in hand-written SSA, the names usually mean something.
So given:
```
%i : !i32 = arith.constant() ["value" = 42 : !i32]
```
this prints:
```
%i : !i32 = arith.constant() ["value" = 42 : !i32]
```
Additionally, this gives insight in how IRs develop. If an op is rewritten to one op, the name of the SSAValue is preserved. If it is written to multiple, it gets renamed (currently old.name + str(i), where i is the index in the op list). So given a transformation that rewrites a constant to a constant and the following input:
```
%i : !i32 = arith.constant() ["value" = 42 : !i32]
%1 : …
```
=> Name preservation

src/xdsl/parser.py
`parse_string` was not failing when the string was not present.
=> Fix error in parser

src/xdsl/ir.py
I just found a small bug in the block erasure. I wanted to clone a region (something which we should add support for as well) and ended up creating an empty Region and the cloning the Region I wanted to clone into it. This, however, meant that I had an empty block at the start of the region, which i wanted to remove again, which failed due to this bug.
In terms of code I did the following:
'''
table = Region.from_operation_list([])
op.table.clone_into(table)
table.erase_block(0) # breaks with "AssertionError: Blocks with parents should first be detached before erasure."
'''
=> fix block erasure bug

src/xdsl/dialects/builtin.py, src/xdsl/ir.py, src/xdsl/irdl.py
This PR will detach IRDL from the different coercion definitions for generic attribute parameters. This PR does not remove nor add any functionality.
Before this PR, each generic data structure used in a `Data` should define in IRDL a way to convert their type (like `ListAttr[T]`) to a corresponding constraint (like `ArrayOf(T)`).
With this PR, each `Data` definition can extend `IRDLGenericCoercion` to provide a translation from their type to a constraint. For instance, this is the corresponding definition of `ArrayAttr`:
```python
@irdl_attr_definition
class ArrayAttr(Data[List[A]], IRDLGenericCoercion):
...
@staticmethod
def generic_constraint_coercion(args: tuple[Any]) -> AttrConstraint:
if len(args) == 0:
return ArrayOfConstraint(irdl_to_attr_constraint(args[0]))
if len(args) == 1: …
```
=> Irdl generic types coercions

src/xdsl/ir.py, src/xdsl/parser.py, src/xdsl/printer.py, tests/printer_test.py
Should fix #113 
This PR allows operations to override `print` and `parse` to essentially implement custom parsing. It also open a bit the API of the printer and parser class.
This PR does not add custom format for dialects defined in xDSL, so there should not be any breaking change.
There is an example of its usage in `tests/printer_test.py`
=> Add support for custom printing and parsing

README.md, setup.cfg
I got import errors due to running on my system version of xdsl as opposed to the local version. Specifying the `pythonpath` in the config lets pytest choose the correct xdsl. I also added `python -m pytest` since that's less likely to use a different python version to the one used to install dependencies.
=> specify pythonpath for pytest

src/xdsl/irdl.py
Fix the `Attribute` case, which before was translated to `BaseAttr(Attribute)` instead of `AnyAttr()`.
=> Fix Attribute case in irdl

src/xdsl/dialects/llvm.py, src/xdsl/mlir_converter.py, src/xdsl/xdsl_opt_main.py, tests/filecheck/mlir-conversion/llvm_types.xdsl
So I need the `llvm.struct<(i32)>` type for my project. Turns out: the llvm dialect is not exposed in the python bindings so I cannot go the usual route. For that reason, I came up with a really mad hack IMO. Feel free to comment if you see any way this could be improved.
=> [LLVM] introduce and convert the LLVMStructType

src/xdsl/dialects/builtin.py, src/xdsl/xdsl_opt_main.py, tests/operation_builder_test.py
This fix two types error, and also fix an error where two functions had the same names.
=> NFC: Some fixes on types and naming

src/xdsl/ir.py, src/xdsl/irdl.py, tests/attribute_definition_test.py, tests/filecheck/cf_ops.xdsl, tests/operation_builder_test.py, tests/operation_definition_test.py
Add accessors to IRDL definitions from operations and attributes. At the same time, do an overall cleaning of the `irdl.py` file.
Also fix a "bug" in IRDL where `operand_segment_sizes` was including the size of non-variadic ones.
Overall, this should allow us to more easily get the IRDL definitions of dialects, which is necessary to translate our python IRDL to MLIR IRDL.
=> Irdl def classes

src/xdsl/parser.py, tests/parser_error_test.py
This should improve the errors we get when parsing a file.
For instance, parsing the following file
```
unkown() {
%0 : !i32 unknown()
}
```
will yield this error
```
xdsl.parser.ParserError: Parsing error at 3:13:
%0 : !i32 unknown()
^
'=' expected
```
=> Parser better errors

src/xdsl/dialects/builtin.py, src/xdsl/mlir_converter.py, src/xdsl/parser.py, src/xdsl/printer.py, tests/mlir_converter_test.py, tests/printer_test.py
This PR concerns UnitAttrs and how to handle them as I need it to add a `llvm.emit_c_interface` to a function operation.
Currently, this is primarily a hack that I used to get UnitAttrs through the MLIRConverter, but I think this nicely opens the can of worms that is design decisions around UnitAttrs. 
The approach of this PR is an implicit one. Anything that maps a str to `None` is just a UnitAttr with that name.
Obviously, this does not add any functionality to `AttributeDef` and just hacks around in the attributes dictionary currently. However, I feel that this might not be too bad, at least not the spirit of it. In my understanding, UnitAttrs are not really something you want to define in an AttributeDef (unless it is as part of an OptAttr), but rather information you want to pass …
=> Unit Attribute Handling

src/xdsl/irdl.py, tests/filecheck/cf_ops.xdsl, tests/operation_builder_test.py, tests/pattern_rewriter_test.py
Since operands and results can all have optional/variadic definitions, we should not duplicate the same code everywhere.
This also adds optional and variadic regions, which are a useful concept as well (mostly optional regions).
=> Refactor IRDL variadic lists, and add variadic regions

tests/filecheck/mlir-conversion/llvm_test.xdsl
Fix `llvm_test.xdsl` test. The test is not part of the CI because it requires an MLIR install, and is currently failing on the git hash we support.
=> Fix func.func printing in test

.github/workflows/release-notes.yml
I missed this, our main branch is called main, and not master.
=> Renamed master to main in workflow

CHANGELOG.md, src/xdsl/dialects/builtin.py, tests/filecheck/affine_ops.xdsl, tests/filecheck/arith_invalid.xdsl, tests/filecheck/arith_ops.xdsl, tests/filecheck/cf_ops.xdsl, tests/filecheck/cmath.xdsl, tests/filecheck/cmath_ops.xdsl, tests/filecheck/func_ops.xdsl, tests/filecheck/irdl-printer/any_and_base_type.xdsl, tests/filecheck/irdl-printer/cmath_program.xdsl, tests/filecheck/irdl_any_and_base_type.xdsl, tests/filecheck/memref_ops.xdsl, tests/filecheck/mlir-conversion/llvm_test.xdsl, tests/filecheck/mlir-conversion/ops.xdsl, tests/filecheck/parser-printer/builtin_types.xdsl, tests/filecheck/parser-printer/escaped_characters.xdsl, tests/filecheck/parser-printer/float_parsing.xdsl, tests/filecheck/parser-printer/region_name_clash.xdsl, tests/filecheck/scf_ops.xdsl, tests/mlir_converter_test.py, tests/pattern_rewriter_test.py, tests/printer_test.py, tests/rewriter_test.py, tests/use_test.py
In MLIR, `module` real name is `builtin.module`.
It was named `module` in xDSL, but this mess up with the mlir_converter, and the MLIR printer.
This should fix it, but this will be a breaking change.
=> Rename module to builtin.module

CHANGELOG.md, src/xdsl/dialects/builtin.py, src/xdsl/dialects/cmath.py, src/xdsl/dialects/llvm.py, src/xdsl/dialects/memref.py, src/xdsl/ir.py, src/xdsl/printer.py, src/xdsl/xdsl_opt_main.py, tests/filecheck/mlir-conversion/llvm_test.xdsl, tests/filecheck/mlir-conversion/ops.xdsl, tests/filecheck/parser-printer/llvm_mlir_printer.xdsl, tests/mlir_printer_test.py
This brings the xDSL output closer to the syntax MLIR is using.
=> Printer: add support to print types in MLIR style

src/xdsl/dialects/llvm.py, src/xdsl/ir.py, src/xdsl/parser.py, src/xdsl/printer.py, tests/mlir_printer_test.py, tests/printer_test.py
This PR adds custom format for parametrized attributes.
We can now parse attributes with two formats:
* The generic format: `!"attrname"<attr1, attr2, ...>`
* A custom format, `!attrname...`, which can be redefined for each attribute.
This is to make it easier to print/parse MLIR (which always use custom format), and make attributes more readable.
The point of using the generic format is to make it easier to parse it from outside Python for instance.
=> Add custom format for attributes

README.md, src/xdsl/mlir_converter.py
This PR adds a function to the mlir_converter that takes a ctx as an argument. With this, I can use things like the PassManager with the same module as returned here and not print and reparse it.
This also fixes the README in that it removes the requirement for the MLIR Python Bindings.
=> [MLIR]: Conversion with ctx and update README

src/xdsl/dialects/builtin.py, tests/filecheck/builtin_types.xdsl
Before this PR, dense attributes did not have any support for floats.
=> Add float support to Dense attribute

src/xdsl/dialects/builtin.py, src/xdsl/parser.py, src/xdsl/printer.py, tests/filecheck/mlir-conversion/builtin_attrs.mlir
This adds the `UnrankedTensorType` type to xDSL.
`UnrankedTensorType` are parsed and printed as `tensor<*xi32>`
=> Add Unranked tensor type

tests/filecheck/mlir-conversion/builtin_attrs.mlir, xdsl/parser.py
Parsing an optional integer type should not fail anymore when the next token starts with an `i`.
=> Fix parsing of optional integer types

.yapfignore, tests/filecheck/arith_ops.xdsl, xdsl/dialects/arith.py
Specification of the ops taken from C++ mlir [here](https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/Arithmetic/IR/ArithmeticOps.td)
New Ops added: 
- DivUI
- DivSI
- RemUI
- Subf
- Divf
- Select
- ShLI
- ShRUI
- ShRSI
Added builder to CmpI to support creating the op from the mnemonic, e.g. using `"eq"` as predicate instead of '0' for an equality comparison.
=> Adding some missing arith ops

setup.cfg, tests/printer_test.py, xdsl/dialects/builtin.py, xdsl/parser.py, xdsl/printer.py
This provides a basic implementation of parsing and printing of dense tensors. One big question is what are the error scenarios and where to verify/bail for each kind of error. I added a basic test for the success case, would be nice to mirror MLIR behaviour for the error cases also, maybe as a follow-up task?
=> xdsl: Add shaped array support for parsing and printing

tests/filecheck/cmath.xdsl, tests/filecheck/irdl-printer/any_and_base_type.xdsl, tests/filecheck/irdl-printer/cmath_program.xdsl, tests/filecheck/irdl_any_and_base_type.xdsl, xdsl/dialects/irdl.py, xdsl/irdl_mlir_printer.py, xdsl/parser.py
Fix the parsing of some IRDL operations and attributes in IRDL, and fix the parsing of array attribute for MLIR.
=> xdsl: Fix parsing of some attributes and operations

tests/filecheck/mlir-conversion/builtin_attrs.mlir, tests/filecheck/parser-printer/builtin_types.xdsl, xdsl/dialects/builtin.py, xdsl/parser.py, xdsl/printer.py
This PR adds signedness semantics for integer types, as MLIR does.
This PR also fix one test that was failing, but not running on the CI since the MLIR tests are not ran on the CI.
(Note, I should fix in a following PR this, since most of the MLIR files do not need MLIR anymore).
=> Add signedness semantics for integer types

tests/filecheck/mlir-conversion/unregistered_ops.mlir, xdsl/parser.py
Unregistered ops were supported by the xDSL parser, but not by the
MLIR parser.
This PR is adding this feature.
Note that the test I added is not running currently, but I tested it on my machine.
=> compiler: Support parsing of unregistered MLIR ops

update_pypi.sh
Remove script that used to update the PyPi package.
Now that this is done in the CI, we do not need to manually do it.
=> install: Remove PyPi update script

xdsl/__init__.py
This PR fixes loading of MLIR modules. The behavior we want here is that, if we call `load_mlir_module` the first time (i.e. when `_mlir_module` is still None), the given argument is written into `_mlir_module` (given that the required submodules are loaded). If the function is called again, the given `mlir_module` argument needs to be the same each time.
=> Compiler: fix mlir module loading

MANIFEST.in, setup.py
It seems that the package does not have typing stubs installed with it.
According to [MyPy Documentation](https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages), this change might fix it.
=> install: Add py.typed in the package

.github/workflows/ci-core.yml
closes #236 
This PR renames the testing CI jobs to be more intuitive to prevent confusion.
=> CI: Rename testing job

.gitignore
These are folders generated by running lit, which we probably don't want on the repo.
=> misc: Add Output folders to gitignore

.github/workflows/ci-mlir.yml
This PR adds a CI for our MLIR-based tests. There are a couple of things to mention here:
- On PRs/Pushes on main, this workflow is triggered.
- From the MLIR repo, only the commit we want is cloned (no history, no branches). This commit is hardcoded in the `Clone MLIR` part of the workflow.
- The workflow uses [CCache](https://github.com/hendrikmuhs/ccache-action) for gh actions to cache compiled files. This cache is saved on the github action cache and restored each time before trying to rebuild. This way, I managed to get the execution time down from around 2h ([here](https://github.com/xdslproject/xdsl/actions/runs/3566592241)) to 10min.
-  If we need to, this cache can be cleaned by following [this](https://github.com/hendrikmuhs/ccache-action/issues/28). 
- Notice that the compiled …
=> CI: Add MLIR-based CI

tests/filecheck/affine_ops.xdsl, tests/filecheck/arith_ops.xdsl, tests/filecheck/builtin_attrs.xdsl, tests/filecheck/cmath_ops.xdsl, tests/filecheck/mlir-conversion/builtin_attrs.mlir, xdsl/dialects/func.py
Previously, there was no verification of `func.func` and `func.return` ops. This PR adds a basic function signature check and fixes wrong xDSL filecheck tests.
=> compiler: Add verifiers to func.func and func.return

xdsl/ir.py
Dialects contains a list of operation/attribute types, rather than a list of operation/attributes.
=> Fix types of Dialect fields

.coveragerc, .github/workflows/ci-core.yml, .github/workflows/ci-mlir.yml, requirements.txt, tests/filecheck/lit.cfg, xdsl/xdsl_opt_main.py
This PR leverages the [Coverage](https://coverage.readthedocs.io/en/7.0.0b1/api.html) package to generate the code coverage of our file checks test suite. Currently, there are a couple of choices that are controversial, which I would like to hear your perspectives. I will add comments to the corresponding locations in the file.
=> CI: Get coverage of filecheck tests

.github/workflows/ci-mlir.yml, tests/filecheck/lit.cfg, xdsl/xdsl_opt_main.py
This PR resolves an oversight in the earlier CI PR. In that version, the source directories were specified in a relative way (which is the only way it really makes sense), but since lit decides to run everything in its subdirectory, these relative paths did not exist. Therefore, all the coverages generated by the filecheck tests were basically empty (no source files) and they were not taken into account.
This is a solution to workaround this issue. The other solution I see would be to try and parametrize the config file somehow, such that an absolute source path can be defined...
=> CI: Generate proper coverage for filecheck tests

tests/test_attribute_builder.py, xdsl/irdl.py, xdsl/utils/exceptions.py, xdsl/utils/hints.py
Fix `Attribute.build`, which failed if too many arguments were given.
It also failed when using `|` rather than `Union`.
Also update the builder tests, and fix obviously wrong ones.
=> compiler: Fix attribute builder

tests/dialects/test_builtin.py, xdsl/dialects/builtin.py
Fixes #179 
The following program can be used to verify that the proposed changes work as expected : 
```
from xdsl.dialects.builtin import *
def test_DenseIntOrFPElementsAttr():
check1 = DenseIntOrFPElementsAttr.tensor_from_list([4, 5], f32)
value1 = check1.data.data[0].value.data
value2 = check1.data.data[1].value.data
res1 = type(value1) == float and value1 == 4.0 and type(
value2) == float and value2 == 5.0
assert (res1)
t1 = FloatAttr.from_value(4.0, f32)
t2 = FloatAttr.from_value(5.0, f32)
check2 = DenseIntOrFPElementsAttr.tensor_from_list([t1, t2], f32)
value3 = check2.data.data[0].value.data
value4 = check2.data.data[1].value.data
res2 = type(value3) == float and value3 == 4.0 and type(
value4) == float and value4 == 5.0
assert (res2)
if __name__ == '__main__': …
```
=> compiler: Fix tensor_from_list method of DenseIntOrFPElementsAttr to properly handle f32 input values

tests/dialects/test_memref.py
This PR provides minor improvements to python tests for `memref` dialect.
=> Testing: Improve tests for memref dialect

tests/test_attribute_definition.py, xdsl/ir.py
This is the beginning of a solution for #275, in the cases for attributes.
Instead of printing them with their automatically defined "repr" format, they are directly printed with
their custom format instead.
I'll take care of operations in a separate PR to keep simple changes.
=> compiler: Print attrs to str in a pretty format

README.md
This PR fixes the link for the docu on MLIR interoperation.
=> docs: Make the link to the MLIR interoperation actually work

.github/workflows/jupyterlite.yml, docs/irdl.ipynb, docs/tutorial.ipynb
Adding a workflow hosting a JupyterLite distribution on GitHub Pages, allowing to use xDSL and the included notebooks from the web with no local installation at all.
One drawback is the necessity to have `%pip install xdsl` in the notebooks for that to work (at the moment; will probably be solved by either pyodide or jupyterlite sometime soon, as it is a problem for many use cases). This can mess things up if using the same notebook locally (where it will install the latest pypi release of xDSL)
=> CI: Publish xDSL-enabled JupyterLite distribution on GitHub Pages.

tests/xdsl_opt/README.md, tests/xdsl_opt/empty_program.xdsl, tests/xdsl_opt/test_xdsl_opt.py, xdsl/xdsl_opt_main.py
This PR hacks together a way to test xdsl_opt_main through some functionality of the arg parser.
Overall, I am feeling like the split of execution models (in a python interpreter vs from command line) will always come back to haunt us. I am not sure whether we actually can build something cleanly without reimplementing lit essentially.
=> tests: Add testing for xdsl_opt_main

tests/filecheck/mlir-conversion/builtin_attrs.mlir, tests/filecheck/mlir-conversion/with-bindings/ops.xdsl, tests/filecheck/mlir-conversion/with-bindings/symbol_tests.xdsl, xdsl/parser.py, xdsl/printer.py
- fix mlir parsing of symbol_ref, e.g.
```
"some.mlirop"() {symbol = @some_symbol} : () -> ()
```
- fix mlir printing of tensors with unknown sizes
Now printed as `tensor<?x128xf32>` instead of `tensor<-1x128xf32>`.
This is required for reparsing with mlir-opt
=> mlir printing and parsing fix

.github/workflows/jupyterlite.yml, docs/irdl.ipynb, docs/tutorial.ipynb
This should solve the CI breaking from the `%pip install xdsl` command - and most annoyances from it.
Still necessary in Jupyter notebooks at the moment, so it's added in the CI for this context.
=> Add %pip install only in JupyterLite context.

tests/dialects/test_affine.py
This PR adds some test case to get the affine dialect to 100%. This mainly consists of cases that throw exceptions.
=> tests: Add tests for affine

.github/workflows/ci-mlir.yml
There seems to be a number of issues with Codecov, that make it sometimes fail to upload the coverage. More details [here](https://github.com/codecov/codecov-action/issues/557) and [here](https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954).
This implements the first suggested simple fix, I am not sure this will be perfect though.
Another issue I noticed is that we are now potentially uploading two coverages (after the change to also test python 3.11), which is probably not a good idea.
=> CI: Fix Codecov token issue

tests/dialects/test_func.py
This PR adds more tests to the func dialect, in particular around the `from_callable` constructor.
=> tests: Add more func tests

tests/xdsl_opt/test_xdsl_opt.py
This removes the awkward coverage test. This test created files on the executor whenever `pytest` was run.
=> tests: Remove awkward test

README.md
- Drop 'about' header and inline the content right at the top
- Move the badges before the first header
- Move TOC after the 'about' part
=> misc: further streamline the header of our README

xdsl/_version.py, xdsl/dialects/builtin.py, xdsl/ir.py, xdsl/irdl_mlir_printer.py, xdsl/pattern_rewriter.py, xdsl/rewriter.py, xdsl/xdsl_opt_main.py
This PR reduces the number of pyright errors to 94.
=> xDSL: Fix several pyright issues

tests/filecheck/frontend/programs/invalid.py, tests/filecheck/frontend/programs/programs.py, tests/filecheck/lit.cfg, xdsl/frontend/context.py, xdsl/frontend/program.py
This is a first patch to support Python front-ends for xDSL. At the moment, only empty module is generated.
=> frontend: Add initial skeleton

tests/test_ir.py, xdsl/ir.py
This PR adds a function to check whether two instances of `IRNode` are structurally equivalent, i.e. they share all relevant fields but don't have to be the same object.
=> xDSL: Add structural equivalence comparison for IRNode

tests/test_ir.py, xdsl/ir.py
This PR extends the check for structural equivalence of IR nodes with support for successors.
=> xDSL: add support for successors in structural equivalence check

.github/workflows/jupyterlite.yml, .github/workflows/update_xdsl_pyodide_build.py, README.md, docs/irdl.ipynb, docs/tutorial.ipynb
This PR now builds a custom Pyodide distribution, embedding xDSL and dependencies, so we can just `import xdsl` in JupyterLite, as desired. It should also improve startup time.
This can be previewed at [papychacal.github.io/xdsl](https://papychacal.github.io/xdsl)
Note you might need to clear your browser's cache for the page, especially if you get some "hash mismatch" error on importing xDSL.
The Pyodide build is cached, so it should take less than 5 minutes once cached.
=> CI: Build a xDSL-embedding Pyodide distribution.

.github/workflows/jupyterlite.yml, .github/workflows/update_xdsl_pyodide_build.py
Following #328. This makes the CI build the JupyterLite distribution with every other test and still deploy it only on pushes to the main branch.
Otherwise, issues affecting the JupyterLite can only be found after a merge..
=> CI: Test JupyterLite build even if not deploying.

tests/test_parser.py, xdsl/dialects/builtin.py, xdsl/parser.py, xdsl/printer.py
Pyright wasn't happy about some of the printing and parsing code, and while fixing the pyright issues I found that the DictionaryAttr types are ambiguous. Bits of code expect the key type to be `StringAttribute`, but the parser constructs it as `str`. The implementation of `DictionaryAttr` declares the data parameter to have type `dict[str, A]`, but the `verify_` function checks that keys are of type `StringAttr`.
This PR is mostly tricks to make the type checker happy, the code functionality should be pretty much the same, modulo the key printing/parsing functions being passed in separately from the value printing/parsing functions.
Happy to add the code that would realign the key types in this PR, or in a follow-up
=> xdsl: fix some type issues with DictionaryAttr printing and parsing

tests/dialects/test_memref.py, tests/dialects/test_vector.py, xdsl/dialects/memref.py
This PR intends to modify the `MemRefType.from_type_and_list()` constructor in accordance with [this](https://github.com/xdslproject/xdsl/pull/300#discussion_r1066818410) discussion.
=> dialects: Improve MemRefType.from_type_list() constructor

tests/filecheck/mlir-conversion/builtin_attrs.mlir, tests/test_mlir_printer.py, tests/test_printer.py, xdsl/dialects/memref.py, xdsl/parser.py, xdsl/printer.py
Currently adds memref as if it was a builtin, which feels a little wrong. Would love some input on how to make it better. Should we add custom formats? Is builtin style ok for now?
The number of tests successfully parsed went from 90 to 97 with current changes.
=> xdsl: parse custom memref format

tests/test_parser.py, tests/test_parser_error.py, xdsl/dialects/builtin.py, xdsl/parser.py
Parse the whole dictionary, including opening and closing braces. This makes a number of things easier to implement, and lets us pass non-optional parsing functions for key and value
=> xdsl: parse dictionary as non-optional

docs/database_example.ipynb, docs/irdl.ipynb, tests/test_irdl.py, tests/test_mlir_printer.py, tests/test_operation_builder.py, tests/test_operation_definition.py, tests/test_ssavalue.py, xdsl/dialects/affine.py, xdsl/dialects/arith.py, xdsl/dialects/builtin.py, xdsl/dialects/func.py, xdsl/dialects/irdl.py, xdsl/dialects/llvm.py, xdsl/dialects/memref.py, xdsl/dialects/scf.py, xdsl/frontend/symref.py, xdsl/irdl.py
This PR updates PyRDL to use type annotations.
This should greatly reduce the amount of PyRight type checking errors.
=> xdsl: Use type annotations in PyRDL

docs/Toy/toy/toy_ast.py
The first of a number of smaller atomic changes used in Chapter 2 of the MLIR tutorials.
=> misc: add flattened_values to LiteralExprAST

docs/Toy/toy/dialect.py
This is one of the two major code additions for Chapter 2. The second one is `MLIRGen`, the class that takes a Toy AST and returns an MLIR operation using xDSL. The tests for this code will be in the other PR.
=> misc: add toy dialect

tests/test_printer.py, xdsl/parser.py
This adds `parse_operand` and `try_parse_operand` to the `Parser`.
This parse a value-id, and then converts it to an `SSAValue`.
The name comes from the MLIR parser.
=> API: Add parser methods to parse SSA values

.github/workflows/jupyterlite.yml
JupyterLite 0.1.0b18 was recently released and breaks a simple behaviour we rely on (see currently [this notebook](https://xdsl.dev/xdsl/retro/notebooks/?path=Toy/Toy_Ch1.ipynb))
This PR fix the used version to 0.1.0b17 which works at the moment. Testable [there](https://papychacal.github.io/xdsl/retro/notebooks/?path=Toy/Toy_Ch1.ipynb).
=> docs: Use JupyterLite 0.1.0b17

tests/conftest.py, tests/test_pattern_rewriter.py, xdsl/dialects/arith.py, xdsl/pattern_rewriter.py
In my quest of fewer squiggly lines, I nerd-sniped myself into resolving this. The main problem with the type checking is that methods take `self` as the first parameters, and functions in general don't. The decorator as it is in the code today handles both, but then the type checker complains that it doesn't know which it is, a 2 or 3 argument method. The 2-argument version is useful for the anonymous case, the 3-argument version is useful for the custom class case.
There are three possible ways to solve this:
1. two decorators
2. decorator that only ever takes 3 arguments, including a dummy self for the anonymous case
3. no decorator for anonymous, determine from type of function passed in whether it needs a check at runtime
I went for 2 in this PR, but maybe 3 is worth a go, will have …
=> misc: make op_type_rewrite_pattern type check

.github/workflows/ci-core.yml, .github/workflows/ci-mlir.yml, requirements-optional.txt, requirements.txt
This PR fixes the MLIR CI to not clone twice and moves some dependencies of the CI from the requirements to the actual CI.
=> CI: Remove CI dependencies from requirements

.github/workflows/ci-mlir.yml, setup.py
This PR intends to make `xdsl-opt` available from anywhere after running `pip install -e . `
=> installation: Add xdsl-opt location to known paths

tests/filecheck/mlir-conversion/builtin_attrs.mlir, xdsl/dialects/builtin.py, xdsl/parser.py, xdsl/printer.py
This adds `dense_resource` attribute to the builtin dialect, and adds the MLIR custom parsing/printing.
=> dialects: Add dense_resource attribute

tests/filecheck/mlir-conversion/builtin_attrs.mlir, xdsl/parser.py
The new parser did not allow to parse dialect types when attributes were expected in the MLIR format.
This should fix #413
=> core: Allow to parse types where attributes are expected

xdsl/irdl_mlir_printer.py, xdsl/xdsl_opt_main.py
Fix two pyright issues in xdsl_opt_main.
In particular, we should use `IO[str]` instead of `IOBase` when requiring a stream for printing.
=> API: Fix pyright issues in xdsl-opt-main

xdsl/printer.py
`type` was used as a variable, which made the use of `type(...)` BEFORE its creation invalid.
=> API: Fix pyright issue in printer.py

.github/workflows/ci-mlir.yml, tests/filecheck/mlir-conversion/with-mlir/lit.local.cfg
This PR changes caching of MLIR such that it caches the full build folder (because we need the PythonBindings)  and then conditionally recompiles MLIR on a cache miss.
This brings the CI execution time down to under a minute, but there is an issue atm:
It looks like the Python Bindings are not properly installed, even though I added a CI step (called `diag`) that prints the content of the respective folder, which looks in order.
Maybe @math-fehr  or @PapyChacal could take a look? I feel like I might be missing something very obvious, but I can't find it... ([Python Bindings Installation](https://mlir.llvm.org/docs/Bindings/Python/#pre-requisites)).
=> CI: Reconfigure CI to cache built binaries

tests/dialects/test_vector.py, tests/filecheck/dialects/vector/vector_ops.xdsl
This PR intends to reduce code duplication in `vector` dialect python tests. It also rectifies two typos ([here](https://github.com/xdslproject/xdsl/blob/d670605e166021e632299fceb08583ef9c66f41b/tests/filecheck/dialects/vector/vector_ops.xdsl#L21) -> expected vector type and [here](https://github.com/xdslproject/xdsl/blob/d670605e166021e632299fceb08583ef9c66f41b/tests/dialects/test_vector.py#L567) -> `Maskedstore` instead of `Maskedload`)
Fixes #410
=> xDSL/Vector: Improve tests

.github/workflows/jupyterlite.yml
This PR stops building and deploying `coverage` in the custom pyodide distribution, that was necessary to ship with until #433.
This saves a tiny bit of CI time, just makes it simpler, and maybe more importantly, make all JupyterLite stuff run a bit more smoothly!
This doesn't touch anything out of JupyterLite build and deploy.
=> CI: Remove coverage from the pyodide/JupyterLite deployment.

tests/test_ir.py, xdsl/ir.py
This test shows the new output, I think this would be useful for debugging, and not much information lost since the printed output is supposed to be unambiguous anyway.
``` python
def test_descriptions():
a = Constant.from_int_and_width(1, 32)
assert str(a.value) == '1 : !i32'
assert f'{a.value}' == 'IntegerAttr(1 : !i32)'
assert str(a) == '%0 : !i32 = arith.constant() ["value" = 1 : !i32]'
assert f'{a}' == 'Constant(%0 : !i32 = arith.constant() ["value" = 1 : !i32])'
m = ModuleOp.from_region_or_ops([a])
assert str(m) == '''\
builtin.module() {
%0 : !i32 = arith.constant() ["value" = 1 : !i32]
}'''
assert f'{m}' == '''\
ModuleOp(
\tbuiltin.module() {
\t  %0 : !i32 = arith.constant() ["value" = 1 : !i32]
\t}
)'''
```
Would there be any downsides to printing like this?
=> xdsl: provide custom __str__ and __format__ functions for attrs and ops

tests/dialects/test_arith.py, tests/dialects/test_func.py, xdsl/dialects/arith.py, xdsl/dialects/func.py
This PR adds the following ops:
- `arith.index_cast`
- `FuncOp.external` to create functions without a body that are used to inform LLVM of external function definitions.
=> dialects: Extend arith and func

tests/dialects/test_memref.py, tests/filecheck/dialects/memref/matmul.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/memref/matmul.mlir, xdsl/dialects/memref.py
This PR aims to get better memref support into xDSL
I want to implement with this PR:
- `memref.dim`
- `memref.rank`
Not added in this PR, but might be of interest in the future.
- `memref.view`and `memref.subview`
- `memref.reshape`
- `memref.realloc`
=> builtins: Extend MemRef to cover more of the MLIR dialect

tests/test_ir.py, xdsl/ir.py
Hi, this minor PR just add a `definition` property to `SSAValue`, usable e.g. to get the `Operation` or `Block`that defined a generic `Operand`.
Motivating example:
```python3
@irdl_op_definition
class OpOp(Operation):
name = "dialect.op"
operand: Annotated[Operand, SomeType]
def verify_(self):
if isinstance(self.operand, OpResult):
if isinstance(self.operand.op, WantedOp):
```
Can just be:
```python3
@irdl_op_definition
class OpOp(Operation):
name = "dialect.op"
operand: Annotated[Operand, SomeType]
def verify_(self):
if isinstance(self.operand.definition, WantedOp):
```
=> core: Add SSAValue.definition property.

tests/dialects/test_gpu.py, tests/filecheck/dialects/gpu/all_reduce_operation_unknown.mlir, tests/filecheck/dialects/gpu/dimension_unknown.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/example.mlir, xdsl/dialects/gpu.py
Following #456.
The attributes definition is definitely hacky, hence the self-sufficient PR, but I can't really do better with the current MLIR syntax.
I could go for a builtin attribute, but this implies deep dependencies that I don't think we want. Work is undergoing to get the MLIR syntax fixed, so I figured it was better to have a self contained hack here in the gpu dialect, to just reimplement it cleanly in-place when fixed in MLIR, rather than expecting a deep refactor.
=> dialects: Add DimensionAttr and AllReduceOperationAttr to GPU dialect

setup.py, xdsl/tools/xdsl_opt.py
This makes the script automatically work on all platforms, the previous method only worked on linux.
=> install: Switch to using entry_points for xdsl-opt script.

tests/filecheck/dialects/memref/memref_ops.xdsl, tests/filecheck/dialects/memref/memref_ops_mlir_conversion.xdsl, tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_mlir_conversion.xdsl
This PR intends to fix the lowering of memref ops to llvm ir and also add a corresponding mlir conversion test (inspired from vector dialect). 
When we try to lower the current memref ir from [here](https://github.com/xdslproject/xdsl/blob/main/tests/filecheck/memref_ops.xdsl), we get the following error 
```
error: 'memref.global' op initial value expected to be of type 'tensor<1xindex>', but was of type 'tensor<1xi32>'
"memref.global"() {"sym_name" = "g", "type" = memref<1xindex>, "initial_value" = dense<[0]> : tensor<1xi32>, "sym_visibility" = "public"} : () -> ()
^
```
Lowering was done as follows: 
```
./xdsl/tools/xdsl-opt -t mlir ./tests/filecheck/memref_ops.xdsl > mlir_memref_check.mlir
``` 
and then 
```
<path-to-mlir-opt> --convert-scf-to-cf --convert-cf-to-llvm …
```
=> dialects: Add mlir conversion test for memref ops

tests/filecheck/irdl_missing_operand.xdsl, xdsl/irdl.py
closes #493 
I argue that the `0 or` is not even needed here, as we know that if something is not a VariadicDef, it has to be a normal def (optionalDefs are also VariadicDefs), so only saying 1 is enough.
=> bug: Fix error message on missing Operands in the context of variadic Operands

tests/filecheck/arith_ops.xdsl, tests/filecheck/mlir-conversion/with-mlir/dialects/arith/arith_attrs.mlir, xdsl/dialects/arith.py
I needed support for the [`arith.fastmath` attribute](https://mlir.llvm.org/docs/Dialects/ArithOps/#fastmathflagsattr), so I added it based on the code [here](https://github.com/llvm/llvm-project/blob/ee9a0f30ca8a3582d0738f7499ea902e1f713b39/mlir/include/mlir/Dialect/Arith/IR/ArithBase.td#L96-L127).
* Are PR adding small details like this to the dialects welcome?
* This is one of my first dialect additions, did I do it right?
=> dialects: Add FastMathFlagsAttr to the Arith dialect.

tests/dialects/test_memref.py, tests/filecheck/dialects/memref/memref_ops.xdsl, tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_mlir_conversion.xdsl, xdsl/dialects/memref.py
This PR intends to add `memref.subview` and `memref.cast` ops in the `memref` dialect. These ops will be later utilised for lowering of some `stencil` dialect operations.
=> dialects: Add memref.subview and memref.cast

xdsl/dialects/affine.py, xdsl/dialects/func.py, xdsl/dialects/gpu.py, xdsl/dialects/memref.py, xdsl/ir.py, xdsl/irdl.py
Currently it's a lot of Any | None, which doesn't match the signature of the function defined in the `irdl_op_definition` annotation. The types reflect the types of the objects currently accepted by the build function.
=> misc: add type annotations to build function

setup.cfg
=> tests: Add the `docs/` to pytest discovery tests

tests/filecheck/func_ops.xdsl, xdsl/dialects/func.py
External functions in func.FuncOp have no body, but do have input types. The validate function fails on this because it checks the body types (which are empty) against the FuncOp input types. Therefore added a check whether the number of arguments and operations is zero and if so do not undertake this validation
=> dialects: Enable validate on func.FuncOp for external functions

tests/filecheck/mlir-conversion/with-mlir/dialects/scf/if.mlir, tests/test_parser.py, xdsl/parser.py
I noticed that parsing of multiple regions is currently broken in the parser. This fixes it.
=> parser: Fix parsing of multiple regions

xdsl/dialects/builtin.py, xdsl/parser.py
Currently calls an MLIRParser method with an instance of XDSLParser, seems dangerous.
=> misc: add method to parse dictionary attr MLIR style to BaseParser

tests/dialects/test_memref.py, xdsl/dialects/memref.py
Tiny PR to allow unranked memrefs where it is possible in MLIR too (in the `memref` dialect).
I specifically need the `memref.cast` to unranked for the GPU demo, so I try to not do more in this one, tell me if you see something necessary though!
=> dialects: Allow UnrankedMemrefType on relevant existing memref ops.

tests/dialects/test_gpu.py, tests/filecheck/dialects/gpu/example.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/example.mlir, xdsl/dialects/gpu.py
This small PR just adds the HostRegisterOp to the GPU dialect.
(It makes a host memref accessible from the device/GPU)
=> dialects: Add HostRegisterOp to GPU

tests/test_is_satisfying_hint.py, xdsl/utils/hints.py
This is an alternative implementation to #500.
Instead of defining a new function per attribute `isinstance` check, we can directly derive it from their IRDL definition! This is less error-prone, and is actually a nice use of IRDL.
This PR reuse the old `is_satisfying_hint` (which was actually completely unused), rename it to `isa` (this is what MLIR uses), and add support for `GenericData`, by reusing the `generic_constraint_coercion` function. The plan is to add more support for it with `ParametrizedAttribute` by introspecting their definitions as well.
Note that compared to #500, we don't have support for `is_array(attr)`, which we need to write as `isa(attr, AnyArrayAttr)` instead. However, this gives us support for nested checks, such as `ArrayAttr[IntegerAttr[IndexType] | …
=> core: Add `GenericData` to `isa` type checks

xdsl/transforms/lower_mpi.py
This PR uses the `mpi-info.c` file in #526 to generate the rest of the library info object.
=> mpi: add all info generated by mpi-info.c

tests/dialects/test_scf.py, tests/filecheck/dialects/scf/parallel_bounds.mlir, tests/filecheck/dialects/scf/parallel_iv.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/scf/parallel.mlir, xdsl/dialects/scf.py
This PR implements scf.parallel partially.
This partial implementation doesn't support reduction and loop-carried variables, which are optional in MLIR. scf.parallel can already be useful without these, so it's an opportunity to merge it progressively too!
Opening the PR as draft before the filechecks for @AntonLydike and @georgebisbas to already have a look or try at it. Not sure if @mesham is interested?
NB: scf.parallel can be translated to GPU by MLIR, so it could be used as a GPU interfacing operation too.
=> dialects: Implement scf.parallel

xdsl/dialects/builtin.py, xdsl/ir.py
Fixing issue #515 by creating a common type for Attributes in the ir.py folder.
=> dialects: Clean up type vars for Attribute types

xdsl/ir.py
Change how SSA Values are printed to cli:
- Block arguments: `BlockArgument<%0: !i32>(num_uses=0)`
- Operation result: `OpResult<%0: !i32>(num_uses=0, op_name=arith.constant)` or `OpResult<%const: !i32>(num_uses=0, op_name=arith.constant)` if it has a `.name` attribute
=> core: Change ssa val `__repr__`

tests/filecheck/dialects/stencil/test_castop_lowering.mlir, xdsl/dialects/experimental/stencil.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
There will be PyRight issues, but I'm opening to get advice: I'm confused by this new typechecking error on ArrayAttr.__new__, and can't remember how to make pyright happy with the type parameter of a MemRefType :thinking:
=> dialects: Add a stencil.CastOp -> memref.Cast lowering.

pyright-ci.json, xdsl/irdl.py
In celebration of the pdl working, I decided to lint irdl.py.
The changes are mostly:
changing lambdas to functions
adding `# type: ignore` when there is no hope of actually typing things properly
2 files, 30 errors to go!
=> misc: lint irdl.py

tests/filecheck/dialects/stencil/test_loadop_lowering.mlir, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
So to avoid implementing affine maps or strided memrefs for the moment, necessary to use memref.subview here, I'll try to use a simple annotation of the memref.cast op (lowered from the stencil.cast) to offset accesses in the stencil.access&co lowerings.
=> dialects: Add stencil.LoadOp -> memref lowering.

xdsl/parser.py
I've found that this is often too granular to be super useful when looking at the backtraces. Do you think it would be ok to remove? @AntonLydike , I remember you saying that you might remove backtracking in the medium term, I thought I'd propose removing this part now.
=> minor: don't backtrack when trying to parse characters

requirements.txt, tests/rewriting/composable_rewriting/immutable_ir/test_immutable_ir.py, tests/test_immutable_list.py, tests/test_ir.py, xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py, xdsl/utils/exceptions.py, xdsl/utils/immutable_list.py
This PR adds an alternative core infrastructure that provides immutability.
Immutability is especially useful for building rewriting systems that support backtracking.
This introduces immutable versions of these core IR constructs:
Operation -> [IOp](https://github.com/xdslproject/xdsl/blob/7987690229bdb16bf528eddf2e8eb78e1b3348db/xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py#L349)
Block -> [IBlock](https://github.com/xdslproject/xdsl/blob/7987690229bdb16bf528eddf2e8eb78e1b3348db/xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py#L213)
Region -> [IRegion](https://github.com/xdslproject/xdsl/blob/7987690229bdb16bf528eddf2e8eb78e1b3348db/xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py#L110)
SSAValue -> …
=> xDSL: add immutable core IR structures

tests/dialects/test_llvm.py, xdsl/dialects/llvm.py
This is a quick helper method that is probably useful for anyone who interacts with pointers and cares about their wrapped type
=> llvm: Add `ptr.is_typed()` method to check if pointer is typed

xdsl/dialects/builtin.py, xdsl/ir.py
This was actually kind of assumed by the code checking for structural equivalence. The parent is currently `None`, which feels about right. We could probably make it the same as `owner`, although I'm not sure it's worth doing if everything works.
=> misc: Pass SSAValue or IRNode for structural equality checking

tests/test_printer.py, xdsl/printer.py
I think this fixes printing of named `BlockArgument` SSA Values. We used them in devito to make SSA much more readable. Feel free to proof-read!
=> printer: Fix printing of named block arguments

tests/filecheck/dialects/stencil/hdiff.mlir, tests/filecheck/dialects/stencil/test_access_lowering.mlir, tests/filecheck/dialects/stencil/test_apply_lowering.mlir, tests/filecheck/dialects/stencil/test_loadop_lowering.mlir, tests/filecheck/dialects/stencil/test_store_lowering.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir, xdsl/dialects/experimental/stencil.py, xdsl/dialects/memref.py, xdsl/dialects/scf.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
This PR adds `stencil.store` and `stencil.return` lowerings, and slightly re"organize" existing lowerings. It now includes a cleanup pass (So we don't have those 'stencil_offset' attributes on the output anymore.)
[tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir](https://github.com/xdslproject/xdsl/compare/emilien/stencil-store-lowering?expand=1#diff-9f450a143c8d386ca1315c78dc7d7a684d434964b838916c8513d1876899dcb4) is a quickly scrapped test showing a lowering to standard MLIR.
I tried on my machine and it seems compilable simply through `|mlir-opt --test-lower-to-llvm | mlir-translate --mlir-to-llvmir | clang -x ir -`. I stopped at the `undefined reference to main`, I'm exhausted by this PR and will get back to that tomorrow!
I expect this lowering to blow up on …
=> dialects: Add stencil lowerings and first lowered example.

xdsl/parser.py
This PR starts the cleanup of the Lexer, to try to incrementally go towards an MLIR-like lexer.
This change is in preparation of a token system, rather than having the Lexer rely on untyped `Span`.
This PR makes the `break_on` field private, and removes the `configured` function, which used to modify `break_on`.
=> core: Make `break_on` in the `Lexer` private

docs/Toy/toy/dialect.py, docs/Toy/toy/parser.py, docs/Toy/toy/tests/test_toy.py, pyproject.toml
I'm using the Toy dialect as a testbed for xDSL features in the workshop repo, and would like to migrate some of them over into this one. This PR is the first of the migration from the workshop, syncing over the existing files.
Three main changes:
1. fix a bug in the parser
2. update the dialect file with fixes from the other repo
3. remove dialect file from pyright exclude list
=> docs: sync toy dialect from workshop repo

xdsl/dialects/experimental/math.py, xdsl/xdsl_opt_main.py
As it says on the tin, I add the math dialect declaration and register it in `xdsl-opt`
=> math: Add a math dialect and register it to xdsl-opt

xdsl/dialects/experimental/stencil.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
This corrects a bug, thanks @meshtag for noticing it!
Basically, shape inference final in-bounds check gave false negatives, when the bounds where correct but instanciated as different integer types.
=> stencil: Correct in-bound checks during shape inference

tests/test_operation_builder.py, tests/test_operation_definition.py, xdsl/irdl.py
While it was possible to have multiple variadic operands and results, it wasn't possible to have multiple variadic regions.
While I'm not sure this will be useful before a while, I quickly wrote this to make the code more homogeneous.
I also added a bunch of tests for accessors, which were missing.
=> core: Add support for multiple variadic regions

tests/dialects/test_gpu.py, tests/filecheck/dialects/gpu/alloc_wrong_dynamic_size.mlir, tests/filecheck/dialects/gpu/ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/ops.mlir, xdsl/dialects/gpu.py
This adds a GPU-specific memref-allocation operation, intended to be used in the next stencil lowerings.
=> dialects: Add gpu.AllocOp

tests/test_mlctx.py, xdsl/dialects/builtin.py, xdsl/ir.py, xdsl/parser.py
Previously, handling unregistered operations was done by the user.
This PR moves the unregistered operation logic to the MLContext, so `get_optional_op` and `get_op` should register `UnregisteredOp` if the corresponding flag is set.
=> core: Move unregistered operation logic to MLContext

pyproject.toml
seems like pyright didn't ignore venv on both my machines, let's specify the paths for the time being
=> misc: specify paths for pyright

docs/Toy/toy/dialect.py, docs/Toy/toy/ir_gen.py, docs/Toy/toy/tests/test_ir_gen.py, tests/dialects/test_op_builder.py, xdsl/builder.py, xdsl/ir.py
I'm writing a bit more IR as part of the PDL work, and thought I'd get this in to make it all a bit neater. I carry on from where we left off in the discussion in the xdsl-workshop repo.
This is a purely additive change, the current code and APIs are fine, although I'd expect that we'll want to transition to being more Builder-based to make the code more similar to MLIR.
=> core: add OpBuilder

bench/parser/bench_lexer.py, bench/parser/bench_parser.py
Add a benchmark for the MLIR parser.
This will let us quickly see if we have performance regressions/improvements when parsing MLIR files.
It will also help us see how many MLIR tests we are parsing.
I'm not sure if we want to have this in our CI though, for two reasons:
* I do not trust GitHub machines for benchmarks, and we might have too much noise from there.
* We need to have MLIR installed to first put all files in generic form
=> bench: Add benchmark for the MLIR parser

.github/workflows/jupyterlite.yml
This (currently draft) PR intends to fix the current JupyterLite deployment failures.
=> CI: fix pyodide-build version.

xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
When replacing stencil.apply with scf.parallel, the transformation removes the block and updates operations to point to the operation that originated each block argument. However, there was a bug as it was replacing the block arguments of an operation based upon the field index in that operation, rather than the index in the block arguments
=> dialects: Minor bug fix for stencil transformation

tests/test_parser.py, xdsl/parser.py
This is the strategy I'd like to use to slowly deprecate the tokenizer in favor of the lexer.
The parser has both the lexer and the tokenizer, and we expect the tokenizer to always be up to date.
Once we want to use the lexer, we first synchronize both, to advance the lexer to the last tokenizer position, then
after parsing we advance the tokenizer back to the end of the lexer position.
=> core: Add lexer in parser

tests/test_printer.py, xdsl/parser.py
We always supported parsing attributes with `#"attr_name"<param1, param2, param3>`, which is a generic way of parsing parametrized attributes.
With the new lexer, these cannot be parsed anymore, because the lexer is unhappy about `#` not being followed by a name.
While I first felt that we should slightly tweak the lexer, I realized that I was just too attached to that feature that we never used anyway, so I think that we should remove it until we need it.
The only reason I like this feature is that it meant that  someone else could easily interact with xDSL through this. However, this feature was anyway so hidden that no one would have found it in the first place :shrug:
Depends on #638 only so I can require both features in another PR, while these are being reviewed.
=> core: remove generic attr parsing

tests/dialects/test_builtin.py, tests/filecheck/mlir-conversion/builtin_attrs.mlir, xdsl/dialects/builtin.py, xdsl/parser.py, xdsl/printer.py
This PR adds the strided layout attribute (https://mlir.llvm.org/docs/Dialects/Builtin/#stridedlayoutattr),
as well as its parsing.
The parsing for the attribute inside a `memref` will be added in a later PR.
This PR depends on #639
=> dialects: Add strided layout attribute

xdsl/parser.py
This is necessary to allow the tokenizer and the lexer to be
used at the same time. Otherwise, when the tokenizer backtrack,
it is moved forward by the lexer/tokenizer synchronization.
=> core: move backtracking from tokenizer to parser

tests/test_parser.py, xdsl/parser.py, xdsl/utils/lexer.py
This PR adds the `parse_punctuation` and `parse_optional_punctuation` method that
will replace the `parse_char` and `parse_characters` methods.
Note that we differ with MLIR here, since MLIR has a single method for each punctuation, which is quite heavy.
Depends on #643 for keeping a linear PR stack
=> core: add punctuation parsing

xdsl/dialects/experimental/math.py, xdsl/dialects/gpu.py, xdsl/dialects/mpi.py, xdsl/dialects/pdl.py, xdsl/ir.py, xdsl/irdl.py
I added the `is None` check in the `build` implementation, and updated some usages, I think this makes the code clearer and avoids annoying boilerplate. This is a purely additive change.
=> core: allow optional attribute values in build argument

tests/dialects/test_arith.py, tests/filecheck/arith_ops.xdsl, tests/filecheck/mlir-conversion/with-mlir/dialects/arith/arith_cmp.mlir, xdsl/dialects/arith.py, xdsl/frontend/dialects/arith.py
Added cmpf operation in arith dialect, which is a comparison for floating point numbers. I have based this on the structure of the existing cmpi operation. Associated tests included.
=> dialects: cmpf operation in arith dialect

requirements-optional.txt
Will give us dependabot pings when we need to update pyright, we'll just need to remember to update CI at the same time. I added a comment to remind us of this.
=> misc: add pyright to requirements-optional.txt

docs/Toy/toy/dialect.py, requirements-optional.txt, tests/dialects/test_arith.py, tests/filecheck/arith_ops.xdsl, tests/filecheck/dialects/stencil/hdiff.mlir, tests/filecheck/mlir-conversion/unregistered_dialect.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/arith/arith_fp_ops.mlir, xdsl/dialects/arith.py, xdsl/dialects/experimental/stencil.py, xdsl/dialects/gpu.py, xdsl/ir.py, xdsl/irdl.py, xdsl/parser.py, xdsl/printer.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
This allows us to parse `!singleton`, a type or attribute with no parameters.
This requires us to include the `<` and `>` in the values of unregistered attributes.
This allows us to parse from  2764 to 3040 files (over 4799)
=> core: Allow parsing of singleton unregistered attrs

tests/filecheck/dialects/stencil/hdiff.mlir, tests/filecheck/dialects/stencil/hdiff_gpu.mlir, tests/filecheck/dialects/stencil/heat_stencil_inference_ll.mlir, tests/filecheck/dialects/stencil/test_access_lowering_2d.mlir, tests/filecheck/dialects/stencil/test_access_lowering_3d.mlir, tests/filecheck/dialects/stencil/test_store_lowering.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
This patch improves for me performance from 42.00 secs to 6.00 secs.
clang-17 -O3  -fopenmp 3d_diff.main.o 3d_diff.cpu.o 3d_diff.interop.o -o 3d_diff.out ./3d_diff.out
Timestamp is: 596620.54
Timestamp is: 596662.62
End of time is: 596662.62
Elapsed time is: 42.00 secs
python3 compare.py --name  3d_diff -d 300 300 300 -nt 300 Max error: 2.980232238769531e-07
Max abs value: 0.4215346574783325
rm 3d_diff.main.o 3d_diff.interop.o
clang-17 -O3  -fopenmp 3d_diff.main.o 3d_diff.cpu.o 3d_diff.interop.o -o 3d_diff.out ./3d_diff.out
Timestamp is: 596595.97
Timestamp is: 596602.00
End of time is: 596602.00
Elapsed time is: 6.00 secs
python3 compare.py --name  3d_diff -d 300 300 300 -nt 300 Max error: 2.980232238769531e-07
Max abs value: 0.4215346574783325
rm 3d_diff.main.o 3d_diff.interop.o
=> dialects: Reverse array indexing for converting `stencil` to LLMLIR

tests/dialects/test_memref.py, tests/dialects/test_vector.py, tests/test_traits.py, xdsl/utils/test_value.py
There's quite a lot of `OpResult(typ, [], [])` in the tests, which is not ideal, as `[]` is neither an `Operation` nor an `int`, which makes the type checking unhappy. Adding a test value with no owner made it clear that sometimes we were passing the Python class of the xDSL type, as opposed to an instance of the type, and I'm not sure how that ever worked :) There are a few other bugs that surfaced after this change, for future PRs.
=> tests: add a TestSSAValue object for tests

.github/workflows/ci-pyright-fails.yml, .github/workflows/ci-pyright.yml, requirements-optional.txt, tests/dialects/test_memref.py, tests/dialects/test_vector.py, tests/filecheck/dialects/stencil/hdiff.mlir, tests/filecheck/dialects/stencil/hdiff_gpu.mlir, tests/filecheck/dialects/stencil/heat_stencil_inference_ll.mlir, tests/filecheck/dialects/stencil/test_access_lowering_2d.mlir, tests/filecheck/dialects/stencil/test_access_lowering_3d.mlir, tests/filecheck/dialects/stencil/test_store_lowering.mlir, tests/filecheck/mlir-conversion/builtin_attrs.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir, tests/test_traits.py, xdsl/parser.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py, xdsl/utils/test_value.py
There was a check in the parser that was preventing this.
=> core: Add support for parsing dense with vector type

tests/test_pattern_rewriter.py, xdsl/pattern_rewriter.py
This allows us to factor more code when a rewrite should allow multiple input operation types.
=> core: Allow op_type_rewrite_pattern to use unions

xdsl/transforms/experimental/ConvertStencilToLLMLIR.py, xdsl/transforms/experimental/stencil_global_to_local.py
This adds a pass to move `memref.alloc`, `mpi.comm.rank` and some others out of potential loops up to the function level.
It does some very basic loop-invariance checking, err-ing on the side of caution.
=> dialects: mpi+stencil Add a loop-invariant-code-motion pass to move allocations and mpi_comm_rank calls out of loops

xdsl/ir.py, xdsl/parser.py
This gives an alternative to the builder methods. A subsequent PR will deprecate the other buidlers and migrate existing code to the API we settle on.
One alternative to consider is passing a list of ops as opposed to a vararg. I'm happy with either.
=> core: add block init with all the fields

docs/Toy/toy/dialect.py, docs/Toy/toy/ir_gen.py, docs/mlir_interoperation.ipynb, tests/dialects/test_affine.py, tests/dialects/test_func.py, tests/dialects/test_scf.py, tests/test_frontend_op_inserter.py, tests/test_ir.py, tests/test_operation_builder.py, xdsl/builder.py, xdsl/dialects/affine.py, xdsl/dialects/experimental/stencil.py, xdsl/dialects/func.py, xdsl/dialects/pdl.py, xdsl/frontend/code_generation.py, xdsl/ir.py, xdsl/irdl.py, xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py
In my new push to minimise surface area and simplify xDSL APIs, blocks and regions, which are little more than containers of a list of ops or blocks, get the first treatment.
=> core: use init for creating regions, as opposed to constructor method

tests/test_parser.py, xdsl/parser.py
This adds a useful function to parse integers.
This one exists in MLIR, though it doesn't have the option to deactivate booleans or integers.
I feel this option is quite useful, to improve code reuse.
=> core: Add parse_integer function

tests/test_parser.py, xdsl/parser.py
This allows us to specify no delimiters where parsing lists.
This require however to parse at least one element.
=> core: Allow to parse comma separated undelimeted lists

tests/filecheck/mlir-conversion/value_tuple.mlir, tests/filecheck/mlir-conversion/value_tuple_access_oob.mlir, tests/filecheck/mlir-conversion/value_tuple_wrong_number.mlir, tests/test_parser.py, xdsl/parser.py
This PR allows us to parse value tuples (not sure what their exact names are in MLIR).
This means we can now parse 3913 tests compared to 3754 before (over 4121 total).
=> core: Allow using value tuples in MLIR syntax

tests/filecheck/mlir-conversion/builtin_attrs.mlir, xdsl/parser.py
This brings us to 3992/4121 tests passed, compare to 3988 before, because the previous parser was not handling well 0-sized dimensions.
=> core: Reimplement shape parser with new lexer

xdsl/dialects/builtin.py
This is purely a typing improvement, it doesn't change at all the implementation.
This change will make such that `IntegerAttr(value, typ)` will be correctly a `IntegerAttr[T]` when `typ` is of type `T`, and an `IntegerAttr[IntegerType]` when `typ` is of type `int`.
=> dialects: Add better init for IntegerAttr

.github/workflows/ci-mlir.yml
This PR removes codecov from our CI, as it seems they have been hacked? Or at least 
the package has been removed from PyPi: https://pypi.org/project/codecov/
I just commented the parts in the CI, so we can add them back once the situation is resolved.
=> CI: Remove codecov in CI

xdsl/dialects/builtin.py, xdsl/parser.py
In MLIR, dense attributes are not allowed to be unranked.
=> dialects: Disallow unranked dense attributes

tests/filecheck/mlir-conversion/builtin_attrs.mlir, xdsl/parser.py
Also, allows the parsing of integers in float attributes, like `4 : f32`.
=> core: Parse negative and hexadecimal values in integer attributes

xdsl/transforms/experimental/ConvertStencilToLLMLIR.py, xdsl/transforms/experimental/StencilShapeInference.py, xdsl/xdsl_opt_main.py
Simple refactor PR, moving the stencil shape inference pass in its own file.
=> dialects: Move stencil shape inference to its own file

tests/dialects/test_builtin.py, tests/filecheck/arith_ops.xdsl, tests/filecheck/dialects/vector/vector_broadcast_type_matching.xdsl, tests/filecheck/dialects/vector/vector_createmask_indexing.xdsl, tests/filecheck/dialects/vector/vector_fma_res_acc_shape_matching.xdsl, tests/filecheck/dialects/vector/vector_fma_res_acc_type_matching.xdsl, tests/filecheck/dialects/vector/vector_fma_res_lhs_shape_matching.xdsl, tests/filecheck/dialects/vector/vector_fma_res_lhs_type_matching.xdsl, tests/filecheck/dialects/vector/vector_fma_res_rhs_shape_matching.xdsl, tests/filecheck/dialects/vector/vector_fma_res_rhs_type_matching.xdsl, tests/filecheck/dialects/vector/vector_load_indexing.xdsl, tests/filecheck/dialects/vector/vector_load_type_matching.xdsl, tests/filecheck/dialects/vector/vector_maskedload_indexing.xdsl, tests/filecheck/dialects/vector/vector_maskedload_memref_passthrough_type_matching.xdsl, tests/filecheck/dialects/vector/vector_maskedload_memref_res_type_matching.xdsl, tests/filecheck/dialects/vector/vector_maskedstore_indexing.xdsl, tests/filecheck/dialects/vector/vector_maskedstore_memref_storevec_type_matching.xdsl, tests/filecheck/dialects/vector/vector_ops.xdsl, tests/filecheck/dialects/vector/vector_ops_mlir_conversion.xdsl, tests/filecheck/dialects/vector/vector_store_indexing.xdsl, tests/filecheck/dialects/vector/vector_store_type_matching.xdsl, tests/filecheck/mlir-conversion/builtin_attrs.mlir, xdsl/dialects/builtin.py, xdsl/parser.py, xdsl/printer.py
This is a feature that was missing in our current vector implementation.
I added support for it in the parser/printer and in the type.
=> core: Add scalable dimensions to vector

tests/filecheck/mlir-conversion/builtin_attrs.mlir, xdsl/parser.py
Previously, function types were only parsed when an attribute was expected, but not when a type was expected.
=> core: Fix function type parsing

tests/test_pattern_rewriter.py, xdsl/ir.py
This patch will allow `insert_at` to accept negative positions, which are then calculated as offsets from the back of the ops list.
Note that the test for this doesn't print/parse a whole module, reducing test time by an order of magnitude.
part of #557
=> core: allow block.insert_op to take negative positions

xdsl/dialects/arith.py, xdsl/dialects/gpu.py, xdsl/dialects/llvm.py, xdsl/dialects/memref.py
As I had promised @webmiche. Sorry again for the trouble.
That should be all of them.
closes #519
=> minor: Remove classmethod from op constructors

tests/dialects/test_func.py, xdsl/dialects/func.py
Inspired by #557 
This adds:
- `get_return_op()` to get the Return statement
- `args` property to return the block arguments as a tuple
- `update_function_type` to update the `function_type` attribute according to block argument types and return op argument types
- `replace_argument_type(idx | arg, new_type)` to change the type of an argument and immediately update the function type attribute
Not sure if this is too big in one, let's see. Am happy to split this if needed!
=> dialects: Add helpers to FuncOp to make rewriting easier

xdsl/dialects/builtin.py, xdsl/dialects/scf.py, xdsl/frontend/code_generation.py, xdsl/ir.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py, xdsl/transforms/lower_mpi.py
This shortens the code needed to access the block in a single-block region and also documents the expectation that there is just a single block in the region.
=> Add Region.block property for single-block Regions

docs/tutorial.ipynb, tests/dialects/test_func.py, tests/dialects/test_gpu.py, tests/dialects/test_irdl.py, tests/test_ir.py, tests/test_pattern_rewriter.py, xdsl/dialects/builtin.py, xdsl/dialects/func.py, xdsl/ir.py, xdsl/transforms/experimental/stencil_global_to_local.py
This is the last deprecation in favour of `Region.__init__` one thing to watch out for is that `Region.get([])` produces a region with a single empty block, and `Region([])` produces a region with no blocks. In the now closed variadic init PR, this meant that the new way to spell `Region.get([])` was `Region(Block())` I wonder if we want to make `Region()` create an empty single block region? Or maybe that would be more confusing? If so, maybe this would be the PR to add it.
I look forward to your feedback!
=> core: deprecate Region.from_op_list

xdsl/dialects/pdl.py, xdsl/ir.py, xdsl/irdl.py
EDIT: This PR refactors Operation creation on top of the IRDLOperation split.
Now, `Operation` and `IRDLOperation` factories (respectively, `create` and `build`) are based on those type's `__init__`s.
The main impact being that all subclasses can now "standardly" define custom `__init__`s, leveraging the new `IRDLOperation`'s `__init__`, just as `get` was leveraging `build` up until now.
This is a kind of second breath for this PR. I would say the discussion about the current proposal starts at [this comment](https://github.com/xdslproject/xdsl/pull/700#issuecomment-1508710769)
=> core: Refactor operation creation to be __init__ based.

xdsl/ir.py, xdsl/pattern_rewriter.py, xdsl/rewriter.py
Add APIs to block updating that are operation as opposed to index-based. Right now make it do the same thing, but will become much more efficient with linked list.
=> core: add Block.insert_op(s?)_(before|after)

docs/Toy/toy/dialect.py, docs/Toy/toy/ir_gen.py, xdsl/dialects/func.py, xdsl/dialects/gpu.py, xdsl/ir.py
This is related to the linked list changes. It's a small addition, but quite useful to simplify empty checks instead of `len`, which will become more expensive to compute.
=> misc: add is_empty property to block

docs/database_example.ipynb, docs/irdl.ipynb, docs/xdsl-introduction.ipynb
Given that we now support MLIR output well, our public documentation should also use MLIR output.
=> docu: Make notebook use MLIR output

docs/Toy/Toy_Ch2.ipynb, docs/Toy/toy/ir_gen.py, docs/Toy/toy/tests/test_interpreter.py, docs/Toy/toy/tests/test_ir_gen.py, docs/database_example.ipynb, docs/mlir_interoperation.ipynb, tests/dialects/test_func.py, tests/dialects/test_llvm.py, tests/dialects/test_memref.py, tests/dialects/test_mpi_lowering.py, tests/dialects/test_scf.py, tests/interpreters/test_pdl_interpreter.py, tests/test_interpreter.py, tests/test_ir.py, tests/test_pattern_rewriter.py, tests/test_printer.py, xdsl/dialects/builtin.py, xdsl/frontend/code_generation.py
I thought I'd deprecate instead of deleting since it's the most widely-used Operation, but I'd be ok with deleting the constructor also.
=> core: deprecate ModuleOp.from_region_or_ops

xdsl/irdl.py
This halves xDSL initialization time on my machine! :slightly_smiling_face:
```
time echo "" | xdsl-opt
Traceback (most recent call last):
[...]
EOFError
real	0m0.338s
```
to
```
time echo "" | xdsl-opt
Traceback (most recent call last):
[...]
EOFError
real	0m0.163s
```
=> core: Hoist get_type_hint in from_pyrdl

docs/mlir_interoperation.ipynb, docs/source.mlir, docs/source.xdsl
I removed also a bit of the document that was talking about moving to xDSL and MLIR syntax (since there is only the MLIR syntax currently soon).
=> tests: Move mlir_interoperation notebook test to MLIR syntax

tests/conftest.py, tests/dialects/test_func.py, tests/test_pattern_rewriter.py, tests/test_printer.py, tests/test_rewriter.py
This patch moves many tests to the MLIR syntax.
Note that 2-3 tests that were testing generic syntax were removed, as they are not supported in the MLIR syntax.
=> tests: Move some pytest tests to MLIR syntax

xdsl/utils/test_value.py
Test values should be usable anywhere any of the other SSAValue subclasses could be used, so this brings the functionality to parity.
=> tests: make test_value hashable

docs/Toy/Toy_Ch2.ipynb, tests/conftest.py, tests/test_printer.py, tests/xdsl_opt/test_xdsl_opt.py, xdsl/printer.py, xdsl/xdsl_opt_main.py
This removes the printing of the xDSL syntax.
=> core: Remove xdsl syntax printer

tests/filecheck/dialects/riscv/riscv_ops.mlir, xdsl/dialects/riscv.py
This PR adds all the instructions in the RV32I/RV64I Section 2.4 (Integer Register-Immediate Instructions) of the spec. It also reorders all of the previously existing instructions according to the spec sections.
=> dialects: add all rv32i/rv64i register-immediate instructions

tests/filecheck/dialects/riscv/riscv_ops.mlir, xdsl/dialects/riscv.py
This PR adds all the instructions in the RV32I/RV64I Section 2.4 (Integer Register-Register Instructions) of the spec. It also adds `NOP` since it is defined in the same section (due to the fact that the *canonical* `NOP` is encoded as `ADD x0, x0, 0`).
=> dialects: add all rv32i/rv64i register-register instructions

xdsl/frontend/README.md
There were some questions on zulip about frontend, and I realised that I never moved the old README here. This PR starts the migration by adding a simple toy example.
Next, the plan is to talk about architecture, partial evaluation of constants using `Const[i32]`, and desymrefier.
P.S. Toy example should be less basic, but I have to move more things from `frontend` branch prior to doing so.
=> frontend: Add README with a toy example

xdsl/dialects/affine.py, xdsl/dialects/builtin.py, xdsl/dialects/cf.py, xdsl/dialects/func.py, xdsl/dialects/gpu.py, xdsl/dialects/llvm.py, xdsl/dialects/memref.py, xdsl/dialects/scf.py, xdsl/dialects/vector.py, xdsl/ir.py
Issue #636 following pr #798 
Moving list to Sequence / Iterable in:
- xdsl/dialects/affine.py
- xdsl/dialects/builtin.py
- xdsl/dialects/cf.py
- xdsl/dialects/func.py
- xdsl/dialects/gpu.py
- xdsl/dialects/llvm.py
- xdsl/dialects/memref.py
- xdsl/dialects/scf.py
- xdsl/dialects/vector.py
- xdsl/ir.py
Also moving sequence import from `collection.abc` to `typing`
=> misc: Moving list to Sequence/Iterable in `xdsl/dialects`

tests/dialects/test_riscv.py, tests/filecheck/dialects/riscv/riscv_allocation.mlir, xdsl/dialects/riscv.py
This lets us to do partial register allocation by assigning an index on the type of the SSA value. I can confirm that this "works" in the `sasha/workshop-all` branch, where code in Toy is lowered to RISC-V and runs, including things like functions & function calls, syscalls, etc. My understanding is that it works slightly differently in the ChocoPy project, but I haven't looked at that yet, so would appreciate feedback on how this approach might be better or worse than that, and other ideas.
=> dialects: add register index and name to riscv.Register

tests/test_printer.py, xdsl/ir.py, xdsl/parser.py, xdsl/printer.py
This PRs adds back support for operation custom format.
This means that we can add custom printing and parsing functions to our operations, so they are printed in a more concise and readable way.
=> core: Add operation custom format

xdsl/transforms/lower_mpi.py
This just adds `LowerNullRequestOp` to the `lower-mpi` pass, apparently I forgot that previously.
=> dialects: add LowerNullRequestOp to lower-mpi pass

xdsl/transforms/experimental/ConvertStencilToLLMLIR.py, xdsl/transforms/experimental/stencil_global_to_local.py
This moves the `MpiLoopInvariantCodeMotion` pass to a two-stage rewrite because it does nonlocal modifications
=> dialects: fix the MpiLoopInvariantCodeMotion pass

tests/dialects/test_riscv.py, tests/filecheck/dialects/riscv/riscv_ops.mlir, xdsl/dialects/riscv.py
This PR adds all the instructions in the RV32I/RV64I Section 2.8 (Control and Status Register Instructions) of the spec.
WIP: this section of the spec defines instructions with weird behavior, like:
> Atomically swaps values in the CSRs and integer registers. CSRRW reads the old value of the CSR, zero-extends the value to XLEN bits, then writes it to integer register rd. The initial value in rs1 is written to the CSR. The initial value in rs1 is written to the CSR. **If rd=x0, then the instruction shall not read the CSR and shall not cause any of the side-effects that might occur on a CSR read.**
In order to expose this *full* (e.g.: *read/write*) VS *limited* (e.g.: *write only*) behavior the idea is to treat instructions like regular ones by taking into account their *full* behaviour …
=> dialects: add all rv32i/rv64i CSR instructions

docs/irdl.ipynb, tests/dialects/test_pdl.py, tests/interpreters/test_pdl_interpreter.py, tests/test_attribute_definition.py, tests/test_parser.py, tests/test_pyrdl.py, xdsl/dialects/builtin.py, xdsl/dialects/llvm.py, xdsl/dialects/pdl.py, xdsl/interpreters/experimental/pdl.py, xdsl/parser.py
This PR lint PDL operations by making use of `__init__`, and fix 1-2 inconsistencies I found compared to the MLIR dialect.
=> dialects: Fix PDL definitions, and lint it with latest xDSL features

docs/irdl.ipynb, tests/test_attribute_definition.py, tests/test_parser.py, tests/test_pyrdl.py, xdsl/dialects/builtin.py, xdsl/dialects/llvm.py, xdsl/parser.py
parse_int_literal used the old tokenizer, while parse_integer uses the new lexer.
=> core: Remove parse_int_literal with parse_integer

tests/dialects/test_stencil.py, xdsl/dialects/experimental/stencil.py
Moved dims field from OpAttr IntegerType to IntegerAttr as this was incorrect before. Also can now have zero arguments to the apply op, with the result type provided explicitly now and the number of results too (was previously derived from the first argument)
=> dialects: Improvements to stencil dialect for indexop and applyop

xdsl/dialects/memref.py, xdsl/ir.py
Remove build from Attribute as proposed in #752 - this PR also replaces one remaining use with a constructor call.
=> core: Remove build from Attribute

tests/dialects/test_stencil.py, xdsl/dialects/experimental/stencil.py, xdsl/dialects/stencil.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py, xdsl/transforms/experimental/StencilShapeInference.py, xdsl/xdsl_opt_main.py
This PR moves the `CastOp` out of experimental. The CastOp design is unlikely to change, and has full test coverage.
It might make sense to move the `IndexAttr` first, let me know if that is wanted!
=> dialects: Move stencil `CastOp` from experimental to main

tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir, tests/xdsl_opt/test_xdsl_opt.py, xdsl/dialects/riscv.py, xdsl/riscv_asm_writer.py, xdsl/xdsl_opt_main.py
Adds option to emit basic RISC-V assembly with `xdsl-opt -t riscv-asm`
=> dialects: Add xdsl-opt option to emit RISCV assembly

.github/workflows/ci-core.yml, .github/workflows/ci-mlir.yml, .github/workflows/ci-notebooks.yml, .github/workflows/ci-pyright-fails.yml, .github/workflows/ci-pyright.yml, README.md, requirements-optional.txt, requirements.txt, setup.py
This PR makes the following changes:
- moves development dependencies to requirements-optional.txt
- imports all dependencies for CI jobs
- updates setup.py to handle requirements in this format: 
- `git+https://github.com/antonlydike/riscemu.git@25d059da090760862f9143478524ed6daf0ab449#egg=riscemu`
The way pip install works, is that it runs setup.py to get its dependencies. Our setup.py gives it the dependencies from requirements.txt, meaning that anyone running `pip install xdsl` would install lit along with it, which is not ideal. This PR changes that, so only the dependencies needed to run xdsl are installed.
This fixes #441
=> install: move dev imports to requirements-optional

tests/filecheck/dialects/snitch/snitch_ops.mlir, xdsl/dialects/snitch.py, xdsl/xdsl_opt_main.py
This PR adds a first draft of the Snitch dialect. Please consider that this is meant to be a *low-level dialect* in the sense that:
* It works on `riscv` types directly (e.g.: all arguments are of `riscv.reg<>` type)
* It is meant to be as close as possible to the asm that aims at generating (e.g.: each operation can be lowered as a sequence of few `riscv` instructions, potentially just one)
Edit: TODO list moved to #883
=> dialects: add snitch low-level dialect

xdsl/dialects/experimental/stencil.py
I couldn't find any use for `IntOrUnknown` in the `stencil` dialect, so I think we should clean things a bit and remove it. 
(/cc @PapyChacal @mesham )
=> dialects: Remove unused constraint from stencil dialect

tests/filecheck/dialects/snitch/snitch_ops.mlir, xdsl/dialects/snitch.py
This PR is an attempt at streamlining `snitch` ops, moving away from messy LLVM pseudo-instructions that were an attempt at cramping together multiple stream configuration options just for IR convenience reasons. For instance, this former op was meant to configure both bound and stride for a specific dimension:
```mlir
"snitch.ssr_setup_shape"(%s0, %bound, %stride) {"dimension" = 0 : i32} : (!riscv.reg<>, !riscv.reg<>, !riscv.reg<>) -> ()
```
This PR forces each op to take care of a single configuration parameter, for example:
```mlir
"snitch.ssr_set_dimension_bound"(%stream, %bound) {"dimension" = 0 : i32} : (!riscv.reg<>, !riscv.reg<>) -> ()
"snitch.ssr_set_dimension_stride"(%stream, %stride) {"dimension" = 0 : i32} : (!riscv.reg<>, !riscv.reg<>) -> ()
```
By breaking this up in two …
=> dialects: streamline snitch to basic config ops

tests/filecheck/dialects/riscv/riscv_ops.mlir, xdsl/dialects/riscv.py
This PR adds the standard extension 'M', RV32M/RV64M instructions in Chapter 7 of the spec.
=> dialects: add 'M' standard extension rv32m/rv64m

tests/dialects/test_stencil.py, xdsl/dialects/stencil.py
This relaxes the cast op verifier to also allow casting of known shapes as long as input and output shape are exactly the same.
@mesham This should fix your issue, right?
=> dialects: Relax castOp verifier

.github/workflows/ci-mlir.yml, .github/workflows/ci-notebooks.yml, requirements-optional.txt
NB: to run these on your machine you need to pass one more parameter than in the CI:
```
python -m pytest -W error --nbval -vv docs --ignore=docs/mlir_interoperation.ipynb --nbval-current-env
```
=> testing: add nbval to requirements-optional

tests/dialects/test_stencil.py, xdsl/dialects/experimental/stencil.py
Deprecate `from_type()` in favour of `__init__()` method and add a simple test.
=> dialects: Improve stencil result type

tests/dialects/test_pdl.py, tests/interpreters/test_pdl_interpreter.py, xdsl/dialects/pdl.py
Reorder the RewriteOp constructor, to add more optional arguments to the end.
=> dialects: Change RewriteOp constructor

tests/dialects/test_riscv.py, xdsl/dialects/riscv.py, xdsl/riscv_asm_writer.py
This PR adds inline comments, that are aligned to column 50 when possible, and a comment on their own line when not.
This PR has orthogonal functionality but has a conflict in the implementation with #906, some code will need to be moved around depending on which is merged first, but that change should be pretty trivial.
=> dialects: add ability to print comments in riscv assembly

xdsl/transforms/experimental/stencil_global_to_local.py
This fixes a faulty `sge` which should have been a `sgt`. Obviously. :roll_eyes:
=> dialects: Fix a comparison in mpi lowering

tests/filecheck/dialects/scf/for_body_args_number_much.mlir, tests/filecheck/dialects/scf/for_body_args_types.mlir, tests/filecheck/dialects/scf/for_yield.mlir, tests/filecheck/dialects/scf/for_yield_number.mlir, tests/filecheck/dialects/scf/for_yield_types.mlir, tests/filecheck/parser-printer/builtin_attrs.mlir, xdsl/ir.py, xdsl/parser.py
Move the block parser to the lexer.
This doesn't change any functionality, besides fixing a bug in multiple tests.
It also removes the `declared-at` from the block, which was a hack in my opinion.
=> core: Move block parser to lexer

tests/test_pass_lexer.py, xdsl/utils/exceptions.py, xdsl/utils/parse_pipeline.py
This PR starts to add pass arguments. We first provide a very simple tokenizer for the syntax of passes. We implement a subset of MLIRs pass syntax here.
This is needed to get passes such as domain slicing for MPI going.
=> core: Add lexer for more complex pass pipeline specs

tests/dialects/test_cf.py, tests/test_operation_builder.py, xdsl/dialects/cf.py, xdsl/irdl.py
This PR adds successors to IRDL, with the current syntax:
```
class MyOp(IRDLOperation):
successor1: Successor
opt_succ: OptSuccessor
var_succ: VarSuccessor
```
=> core: Add successors to IRDL

xdsl/parser.py
This function is nor used nor tested anymore, and was still using the old tokenizer
=> core: Remove unused try_parse_value_id_and_type method

tests/test_parser.py, xdsl/parser.py
This moves the parsing of symbols and `SymRefAttr` attributes to the lexer.
=> core: move symbol parsing to lexer

docs/Toy/toy/rewrites/lower_llvm.py, docs/Toy/toy/tests/test_end_to_end.py, tests/filecheck/dialects/riscv_func/lower_riscv_func.mlir, xdsl/dialects/riscv.py, xdsl/dialects/riscv_func.py, xdsl/riscv_asm_writer.py, xdsl/transforms/lower_riscv_func.py
Since SectionOp is not useful in the current state of things for the riscv dialect (and optimized later) remove it to use directly DirectiveOp instead.
=> [WIP] dialects: riscv: remove SectionOp and use DirectiveOp instead

tests/test_pass_from_spec.py, xdsl/passes.py, xdsl/transforms/experimental/stencil_global_to_local.py, xdsl/utils/parse_pipeline.py, xdsl/xdsl_opt_main.py
This is the final stage of the pass pipeline parser.
This PR hooks up the parser to xdsl-opt. A pass is now a dataclass that can have fields:
```python
@dataclass
class CustomPass(ModulePass):
name = "custom-pass"
number: int | float
int_list: list[int]
non_init_thing: int = field(init=False)
str_thing: str
optional: str | None
```
Which can then be called from the command line as `custom-pass{number=1 int_list=1,2,3 str_thing=hello}`.
Optional fields are not required to be present.
*A note on edge cases:*
Due to the nature of the syntax, we can't know if `x=3` means `3` or `[3]`. So if we see an annotation like `int | list[int]` we cannot know how to convert. This implementation will always resort to non-lists in cases like this.
=> core: Integrate parser for more complex pass pipeline specs into xdsl-opt

tests/filecheck/dialects/gpu/terminator_launch.mlir, tests/test_builtin_traits.py, tests/test_traits.py, xdsl/dialects/func.py, xdsl/dialects/gpu.py, xdsl/traits.py
This trait check that an operation have a specific parent operation type.
This is exactly the same trait as the MLIR one.
=> core: Add HasParent trait

tests/dialects/test_func.py, tests/filecheck/dialects/builtin/attrs.mlir, tests/filecheck/dialects/cf/cf_ops.mlir, tests/filecheck/dialects/gpu/module_unterminated.mlir, tests/filecheck/frontend/passes/desymref.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/arith/arith_attrs.mlir, tests/filecheck/parser-printer/attribute_names.mlir, tests/filecheck/parser-printer/region_name_clash.mlir, tests/filecheck/xdsl_opt/split_input.mlir, tests/test_parser.py, tests/test_pattern_rewriter.py, tests/test_rewriter.py, xdsl/dialects/builtin.py, xdsl/dialects/func.py, xdsl/parser.py, xdsl/printer.py
Previously, both empty regions and regions with an empty block were parsed and printed the same.
I rewrote the region  parser with the lexer, and now follow the same syntax as MLIR.
Additionally, I fixed a bug in `func` that was relying on the printing of empty regions.
Empty region:
```
{}
```
Region with empty block:
```
{
^bb0:
}
```
Region with a non-empty block:
```
{
"test.op"() : () -> ()
}
```
=> core: parse region properly

tests/dialects/test_stencil.py, tests/filecheck/dialects/stencil/copy.mlir, tests/filecheck/dialects/stencil/hdiff.mlir, tests/filecheck/dialects/stencil/hdiff_gpu.mlir, tests/filecheck/dialects/stencil/hdiff_inference.mlir, tests/filecheck/dialects/stencil/hdiff_out_of_bound.mlir, tests/filecheck/dialects/stencil/heat_stencil.mlir, tests/filecheck/dialects/stencil/heat_stencil_inference.mlir, tests/filecheck/dialects/stencil/heat_stencil_inference_ll.mlir, tests/filecheck/dialects/stencil/laplace.mlir, tests/filecheck/dialects/stencil/stencil_apply_float_arg.mlir, tests/filecheck/dialects/stencil/test_access_lowering_1d.mlir, tests/filecheck/dialects/stencil/test_access_lowering_2d.mlir, tests/filecheck/dialects/stencil/test_access_lowering_3d.mlir, tests/filecheck/dialects/stencil/test_apply_lowering.mlir, tests/filecheck/dialects/stencil/test_castop_lowering_1d.mlir, tests/filecheck/dialects/stencil/test_castop_lowering_3d.mlir, tests/filecheck/dialects/stencil/test_loadop_lowering.mlir, tests/filecheck/dialects/stencil/test_store_lowering.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir, xdsl/dialects/experimental/stencil.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py, xdsl/transforms/experimental/stencil_global_to_local.py
This PR adds custom syntax to `stencil.index` for readability (and switch it to using IntAttr).
The meaningful changes are in`xdsl/`, the rest is all filechecks and pytests updates!
=> dialects: Add custom syntax for stencil.index

tests/filecheck/dialects/stencil/copy.mlir, tests/filecheck/dialects/stencil/hdiff.mlir, tests/filecheck/dialects/stencil/hdiff_gpu.mlir, tests/filecheck/dialects/stencil/hdiff_inference.mlir, tests/filecheck/dialects/stencil/hdiff_out_of_bound.mlir, tests/filecheck/dialects/stencil/heat_stencil.mlir, tests/filecheck/dialects/stencil/heat_stencil_inference.mlir, tests/filecheck/dialects/stencil/heat_stencil_inference_ll.mlir, tests/filecheck/dialects/stencil/laplace.mlir, tests/filecheck/dialects/stencil/stencil_apply_float_arg.mlir, tests/filecheck/dialects/stencil/test_access_lowering_1d.mlir, tests/filecheck/dialects/stencil/test_access_lowering_2d.mlir, tests/filecheck/dialects/stencil/test_access_lowering_3d.mlir, tests/filecheck/dialects/stencil/test_apply_lowering.mlir, tests/filecheck/dialects/stencil/test_castop_lowering_1d.mlir, tests/filecheck/dialects/stencil/test_castop_lowering_3d.mlir, tests/filecheck/dialects/stencil/test_funcop_lowering.mlir, tests/filecheck/dialects/stencil/test_loadop_lowering.mlir, tests/filecheck/dialects/stencil/test_store_lowering.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir, xdsl/dialects/experimental/stencil.py, xdsl/parser.py
This PR adds custom syntax to the stencil types (`stencil.temp` and `stencil.field`) for readability.
The meaningful change is in `xdsl/`, the rest is just filechecks updates!
Stacked on #975
=> dialects: Add custom syntax to stencil types

tests/test_ir.py, xdsl/ir.py
Comparing two operations that have operands that are not in
the context would fail.
Now, when operands and successors are not in the context, we
compare operands and successors by equality.
=> core: Fix is_structurally_equivalent

tests/filecheck/dialects/builtin/dense_array_invalid_dims.mlir, tests/test_parser.py, xdsl/dialects/arith.py, xdsl/dialects/builtin.py, xdsl/dialects/llvm.py, xdsl/parser.py
The function `parse_comma_separated_list` should be used instead, and is using the new parser.
I also added the `parse_type` function that I needed for one of the method.
This PR does not change any functionality.
=> core: Remove `parse_list_of` and remove its uses

tests/test_operation_definition.py, xdsl/irdl.py, xdsl/utils/hints.py
Allow to create Generic operations, to factor some code.
For instance, this will let us write a generic `BinaryOperation`, that is parametrizable.
```python
class BinaryOperation(Generic[_T], Operation, ABC):
lhs: Annotated[Operand, _T]
rhs: Annotated[Operand, _T]
res: Annotated[OpResult, _T]
def verify():
...
``` 
And we can then use it with inheritance.
```python
@irdl_op_definition
class Addi(BinaryOperation[Annotated[IntegerType, i32]):
name = "arith.addi"
```
=> core: Allow generic operations

xdsl/dialects/arith.py
Use the new Generic Operation base class possibility brought by #979, make BinaryOperation generic, delete a third of `arith.py` :tada: 
I'm going to chop the rest of it soon!
=> dialects: Make arith.BinaryOp Generic.

tests/test_printer.py, xdsl/dialects/llvm.py, xdsl/parser.py
This renames `try_parse_type` and `try_parse_attr` to `parse_optional_type` and `parse_optional_attr`.
We should follow the `parse_optional` naming (as in MLIR), and this will require incremental changes in the parser.
=> core: rename some methods in parser (NFC)

tests/xdsl_opt/test_xdsl_opt.py, xdsl/dialects/experimental/stencil.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py, xdsl/transforms/experimental/stencil_global_to_local.py, xdsl/transforms/lower_mpi.py, xdsl/xdsl_opt_main.py
This makes it so that stencil no longer loweres the MPI stuff itself, but now there's a separate pass `dmp-to-mpi{slices=4}`.
This also names the decomposition pass `dmp-decompose-2d{slices=4}`. Names are still open to discussion
=> dialects: Factoring out some mpi passes, adding support for pass args

tests/test_pass_from_spec.py, xdsl/passes.py
I missed adding support for default values for dataclass fields for the pass arguments, that's now handled as well!
=> Core: Allow default values and default factories in dataclasses

docs/irdl.ipynb, tests/dialects/test_builtin.py, tests/filecheck/dialects/arith/arith_invalid.mlir, tests/test_attribute_definition.py, tests/test_operation_definition.py, tests/test_pyrdl.py, xdsl/dialects/arith.py, xdsl/dialects/builtin.py, xdsl/irdl.py, xdsl/utils/hints.py
We can now specify in the PyRDL definition that some types should be equal.
BinaryOperation is now using this to specify that both operands and the result have the same type.
For instance:
```python
@irdl_op_definition
class ConstraintVarOp(IRDLOperation):
name = "test.constraint_var_op"
T = Annotated[IntegerType | IndexType, ConstraintVar("T")]
operand: Annotated[Operand, T]
result: Annotated[OpResult, T]
attribute: OpAttr[T]
```
Both the operand, result, and attribute should have the same type (or value for the attribute).
This also magically works out of the box for generics!!!
```python
@irdl_attr_definition
class ConstraintVarAttr(ParametrizedAttribute):
name = "test.constraint_var"
T = Annotated[IntegerType, ConstraintVar("T")]
param1: ParameterDef[IntegerAttr[T]]
param2: …
```
=> core: Add PyRDL constraint variables

tests/dialects/test_riscv.py, tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir, xdsl/dialects/riscv.py
This PR adds the LabelOp in the riscv dialect (based on the current version found in `sasha/workshop-all` branch).
[Labels][1] can be used as targets for branches, unconditional jumps and symbol offsets, e.g.,
```
loop:
j loop
```
A label can also be associated with a region, e.g.:
```
mylabel:
add a0, a1, a2
```
[1]: https://github.com/riscv-non-isa/riscv-asm-manual/blob/master/riscv-asm.md#labels
=> dialects: riscv: Add LabelOp to riscv dialect

tests/dialects/test_stencil.py
This should bring us one step closer to our goal of bringing `stencil` out of experimental.
=> dialects/Stencil: Add tests for store, index and access

tests/dialects/test_stencil.py, tests/filecheck/dialects/stencil/copy.mlir, tests/filecheck/dialects/stencil/hdiff.mlir, tests/filecheck/dialects/stencil/hdiff_gpu.mlir, tests/filecheck/dialects/stencil/hdiff_inference.mlir, tests/filecheck/dialects/stencil/hdiff_out_of_bound.mlir, tests/filecheck/dialects/stencil/heat_stencil.mlir, tests/filecheck/dialects/stencil/heat_stencil_inference.mlir, tests/filecheck/dialects/stencil/heat_stencil_inference_ll.mlir, tests/filecheck/dialects/stencil/laplace.mlir, tests/filecheck/dialects/stencil/stencil_apply_float_arg.mlir, tests/filecheck/dialects/stencil/test_access_lowering_1d.mlir, tests/filecheck/dialects/stencil/test_access_lowering_2d.mlir, tests/filecheck/dialects/stencil/test_access_lowering_3d.mlir, tests/filecheck/dialects/stencil/test_apply_lowering.mlir, tests/filecheck/dialects/stencil/test_castop_lowering_1d.mlir, tests/filecheck/dialects/stencil/test_castop_lowering_3d.mlir, tests/filecheck/dialects/stencil/test_loadop_lowering.mlir, tests/filecheck/dialects/stencil/test_store_lowering.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir, xdsl/dialects/experimental/stencil.py, xdsl/dialects/stencil.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py, xdsl/transforms/experimental/StencilShapeInference.py, xdsl/transforms/experimental/stencil_global_to_local.py
This enables `stencil.field` and `stencil.temp` to carry bounds information rather than absolute size only.
It switches the operations to not use attributes to encode this information anymore, but their operands/results types.
It potentially decouples analysis and lowering steps, and just feels more natural to me in the MLIR mindset.
As a comparison: layouted memrefs also carry this information in their type, note onloy in the defining operation's attributes, and those bounds are ultimately mapped to memref offsets.
The only exception here is `stencil.store`, as it is the starting point for shape inference. To allow giving the output size, this operation still works with "ub"/"lb" attributes, because typing the operand is the same thing as typing the defining operation's result, so …
=> dialects: switch stencil to carry bounds in SSA values types.

tests/test_is_satisfying_hint.py, xdsl/utils/hints.py
Adds support for `Literal` in isa, as in:
```python
assert isa("cpu", Literal["cpu"])
```
It looks super useless, and it is for direct use!
It gets handy when used in infra though; stacked PR ~~coming up soon!~~ opened: #1031
=> misc: Add support for isa(arg, Literal[...])

docs/Toy/toy/dialects/toy.py, docs/Toy/toy/frontend/ir_gen.py, tests/dialects/test_func.py, tests/test_linked_list.py, xdsl/dialects/builtin.py, xdsl/dialects/gpu.py, xdsl/dialects/irdl.py, xdsl/interpreters/experimental/pdl.py, xdsl/ir.py, xdsl/pattern_rewriter.py, xdsl/printer.py, xdsl/rewriter.py
I recently discovered that PEP8 recommends using truthiness for collection is empty check. This makes sense to me, as a lot of collections have O(n) length calculations, including strings and our recently introduced Block linked list. Here's the relevant bit:
```
For sequences, (strings, lists, tuples), use the fact that empty sequences are false:
Yes:
if not seq:
if seq:
No:
if len(seq):
if not len(seq):
```
https://pep8.org/#programming-recommendations
=> core: use truthiness for block ops is_empty check

xdsl/builder.py
From the discussion on #1017, I thought it might be better to make the ImplicitBuilder public in a separate PR.
=> core: make ImplicitBuilder public

tests/test_pass_lexer.py, xdsl/utils/parse_pipeline.py
This change makes it so `2d-grid` is tokenized to `[IDENT(2d-grid)]` instead of `[NUMBER(2), IDENT(d-grid)]`
=> core: Correctly parse identifiers that start with a number [Minor]

docs/database_example.ipynb, docs/irdl.ipynb, docs/xdsl-introduction.ipynb, tests/filecheck/mlir-conversion/with-mlir/dialects/func/func_ops.mlir, tests/test_ir.py, tests/test_printer.py, xdsl/ir.py, xdsl/printer.py
This PR allows graph regions to be printed by the `Printer`.
Since there is no way of knowing if the user is currently printing operations in a graph region, this means that we cannot print operands with a `%<UNKNOWN>` when they haven't been printed yet.
Thus, printing an operation that has free operands will not fail anymore.
Note that this means that some dominance bugs are not catched anymore. These should be handled with a proper domination check in the verifier later on.
=> core: Allow graph regions in printer

tests/filecheck/dialects/stencil/hdiff_gpu.mlir, tests/test_pass_from_spec.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py, xdsl/xdsl_opt_main.py
Get rid of `convert-stencil-to-gpu` as it can be a simple flag now.
Use a `Literal` flag type to enforce specific values only.
Add tests for that case.
Stacked on #1030
=> transformations: Add a flag for target selection on stencil conversion.

tests/filecheck/dialects/stencil/heat_stencil_inference_ll.mlir, tests/filecheck/dialects/stencil/iterate.mlir, tests/filecheck/dialects/stencil/test_funcop_lowering.mlir, xdsl/dialects/experimental/stencil.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
This adds support for returning `stencil.field` from a `func.func`, and using `stencil.field`s as `scf.for` carried variables.
=> dialects: extend the stencil lowerings

tests/filecheck/transforms/stencil-shape-inference.mlir
Add a test-case with no stencil.access for Shape inference coverage; it is currently covered by shape inference + lowering tests, as revealed when switch to separate inference/lowering tests !
=> testing: Polish stencil shape inference filechecks

pyproject.toml, tests/dialects/test_arith.py
Found a bug! One of the tests was not running due to obscured name, linters ftw
=> misc: lint test_arith.py

docs/Toy/examples/tests/optimise_toy.mlir, tests/filecheck/dialects/gpu/alloc_wrong_dynamic_size.mlir, tests/filecheck/dialects/gpu/ops.mlir, tests/filecheck/dialects/llvm/pointers.mlir, tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir, tests/filecheck/dialects/riscv/riscv_ops.mlir, tests/filecheck/dialects/riscv/riscv_register_allocation.mlir, tests/filecheck/dialects/scf/for_args_number.mlir, tests/filecheck/dialects/scf/for_args_types.mlir, tests/filecheck/dialects/scf/for_body_args_number.mlir, tests/filecheck/dialects/scf/for_body_args_types.mlir, tests/filecheck/dialects/scf/for_yield.mlir, tests/filecheck/dialects/scf/for_yield_number.mlir, tests/filecheck/dialects/scf/for_yield_types.mlir, tests/filecheck/dialects/scf/parallel_bounds.mlir, tests/filecheck/dialects/scf/reduce_arg_type_missmatch.mlir, tests/filecheck/dialects/stencil/hdiff_gpu.mlir, tests/filecheck/dialects/stencil/stencil_ops.mlir, tests/filecheck/dialects/vector/vector_maskedload_memref_passthrough_type_matching.mlir, tests/filecheck/dialects/vector/vector_maskedload_memref_res_type_matching.mlir, tests/filecheck/dialects/vector/vector_maskedstore_memref_storevec_type_matching.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir, tests/filecheck/parser-printer/operation_signature.mlir, xdsl/parser.py
This checks that the operation signature is consistent with the given operands.
For instance:
```mlir
builtin.module {
%0 = "test.op"() : () -> !test.type<"foo">
%1 = "test.op"(%0) : (!test.type<"bar">) -> !test.type<"bar">
}
```
will raise an error at parsing time, since the operation signature has the wrong type for the operand.
Will fix #472
=> core: check correctness operation signatures

xdsl/dialects/memref.py
This seems to also be the case for mlir, so we don't actually need it
=> dialects: (memref) Make alignment for memref.alloc optional

tests/filecheck/parser-printer/graph_region.mlir, tests/filecheck/parser-printer/operation_signature.mlir, tests/test_printer.py, xdsl/parser.py
This PR allows the parsing of graph regions, by allowing the parsing of operations with undefined operands.
How this works:
* `parse_optional_unresolved_operand` parse an operand that may be forward declared.
* `resolve_operand` takes an unresolved operand, and either return a proper `SSAValue`, or returns a forward declared value.
* A forward declared value is represented by a type of `SSAValue`. At the end of `parse_module`, it is checked that no forward declared values are left in the parser context.
* When a result is parsed, if the value was already defined as a forward declared value, all uses of this value are replaced by the operation result.
=> core: Allow parsing graph regions

tests/filecheck/transforms/stencil-shape-inference.mlir, xdsl/transforms/experimental/StencilShapeInference.py
To naturally handle different input offsets.
Add a test case for this.
Now, shape inference walk ops regions first; each stencil.access offset it's stencil.temp operand size individually. stencil.apply shape inference then just spreads these bounds to its operands (from its block arguments).
=> transformations: Split ApplyOp and AccessOp shape inference patterns.

tests/filecheck/dialects/scf/for_body_args_number.mlir, tests/filecheck/dialects/scf/for_body_args_number_much.mlir, tests/filecheck/dialects/scf/for_body_args_types.mlir, tests/filecheck/dialects/scf/for_yield.mlir, tests/filecheck/dialects/scf/for_yield_number.mlir, tests/filecheck/dialects/scf/for_yield_types.mlir, tests/test_attribute_definition.py, xdsl/dialects/builtin.py
Follow-up PR of https://github.com/xdslproject/xdsl/pull/1027 to split the changes properly.
=> dialects: (builtin) add range verifier for `IntegerAttr`

tests/test_pattern_rewriter.py, xdsl/interpreters/experimental/pdl.py, xdsl/pattern_rewriter.py
I never liked the overload based on number of parameters for the op type thing, this PR separates out the two flows. I think that this makes things a bit less confusing, there's one annotation for the method rewrite, and another annotation that builds a rewrite based on a standalone function.
I'm doing a bit of work in the rewrites, and having the two be separate also makes it easier for me to experiment, but that's not really the primary goal of the PR.
=> core: separate out decorator for anonymous rewrite pattern

docs/irdl.ipynb, tests/dialects/test_func.py, tests/dialects/test_stencil.py, tests/dialects/test_vector.py, tests/filecheck/parser-printer/verifier_error.mlir, tests/test_builtin_traits.py, tests/test_operation_definition.py, tests/test_traits.py, xdsl/ir.py, xdsl/utils/diagnostic.py
This PR improves debugging on errors triggered in Operation.
It adds an `emit_error` method that will print back the IR, and display an error at the correct location.
Additionally, the `verify` method of `Operation` will now print back the entire IR if verification fails.
=> core: better errors printing in operation

xdsl/dialects/builtin.py, xdsl/parser.py
These functions weren't used, and were using the legacy tokenizer.
=> core: remove some legacy parser function

tests/filecheck/dialects/riscv/riscv_ops.mlir, tests/filecheck/parser-printer/operation_signature.mlir, tests/filecheck/parser-printer/value_tuple_wrong_number.mlir, tests/test_parser_error.py, xdsl/parser.py
This removes the operation parser written with the legacy tokenizer to the lexer.
This does not change any behavior, besides a fix in the operation parser.
=> core: (NFC) rewrite operation parser in lexer

tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
The StencilTypeConversionFuncOp pattern didn't play nice with this example unless moved to the second pass.
Moving it there for now, as we first need those examples to work. Let's think of a way to interleave them at some point, but use what works first!
=> transformations: Add a lowering test for counterintuitive stencil offsets.

docs/Toy/toy/frontend/parser.py
Just a small change to help me debug, only throw errors if something has gone wrong, bool/optional otherwise.
=> docs: (toy) optional instead of error in parser

pyproject.toml, tests/dialects/test_llvm.py, tests/dialects/test_stencil.py, tests/test_attribute_definition.py, tests/test_ssa_value.py, tests/xdsl_opt/test_xdsl_opt.py, xdsl/dialects/builtin.py, xdsl/dialects/llvm.py, xdsl/frontend/op_resolver.py, xdsl/interpreters/experimental/pdl.py, xdsl/ir.py, xdsl/irdl.py, xdsl/parser.py, xdsl/printer.py, xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py, xdsl/transforms/lower_mpi.py, xdsl/utils/exceptions.py
I feel like we can trust our types at this point, or at least trust them by default. There are some dodgy things in the Attributes that are created dynamically, but otherwise if a type says A | B we don't need to check for other things.
=> misc: add back check for unreachable code

xdsl/dialects/func.py, xdsl/parser.py
This moves the parsing of types to the lexer, from the tokenizer.
It does not change any functionality.
=> core: Move type parsing to lexer (NFC)

tests/test_parser.py, xdsl/parser.py
Move the attribute parsing from the tokenizer to the lexer.
Also, make some function private, as they are not supposed to be used outside of the parser.
=> core: move attribute parsing to lexer (NFC)

docs/Toy/toy/dialects/toy.py, docs/Toy/toy/interpreter.py, tests/dialects/test_builtin.py, tests/dialects/test_vector.py, xdsl/dialects/builtin.py, xdsl/dialects/experimental/stencil.py, xdsl/dialects/llvm.py, xdsl/dialects/memref.py, xdsl/printer.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
This adds two things:
- an `element_count` property to the `ShapeType`, that is automatically derived and uses the `get_shape` method internally
- A new `ContainerType` class that allows us to have a common interface for types that encompass another type (e.g. MemRef, Vector, Tensor, Dense, llvm pointer)
In the process, I moved most of them over to this. That changed their shape return value to `tuple` (previously array for some builtins). I fixed some tests and had to touch the printer a bit sadly.
(This was done in response to me finding a bug in how memref element counts are calculated in the mpi lowering, which was pretty sad)
=> dialects: Add element_count to ShapedType and add ContainerType

tests/test_attribute_definition.py, tests/test_parser.py, tests/test_printer.py, tests/xdsl_opt/test_xdsl_opt.py, xdsl/dialects/experimental/dmp.py, xdsl/dialects/memref.py, xdsl/parser.py
This removes the tokenizer, in favor of the parser.
This makes the parser twice as fast (since we don't keep the synchronization between the lexer and the tokenizer)
=> core: Remove the tokenizer

tests/filecheck/dialects/snitch_runtime/lower_snitch_to_func.mlir, tests/filecheck/dialects/snitch_runtime/lower_snrt_to_func.mlir, tests/filecheck/dialects/snitch_runtime/snitch_runtime_ops.mlir, xdsl/dialects/snitch_runtime.py, xdsl/transforms/lower_snitch_runtime.py, xdsl/xdsl_opt_main.py
This pull request does two things:
* it introduces a lowering pass that lowers all snrt runtime operations, to a currently present to func.func, with an accompanying external function call for use with mlir-opt and clang -x ir. (interop tests with mlir-opt and clang are not included).
* It slightly refactors snitch runtime with the recently introduced generics #979 to reduce code size (1D and 2D DMA operations now have their own base classes for both regular and `wideptr` variants).
=> dialects: Add lowering pass to convert snitch-runtime to external func.funcs

tests/filecheck/dialects/stencil/invalid.mlir, tests/filecheck/dialects/stencil/stencil_ops.mlir, tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir, tests/filecheck/transforms/stencil-shape-inference.mlir, xdsl/dialects/stencil.py, xdsl/transforms/experimental/ConvertStencilToLLMLIR.py, xdsl/transforms/experimental/StencilShapeInference.py
Implement `stencil.buffer`, and the corresponding shape inference and conversion patterns.
=> dialects: Implement stencil.BufferOp

tests/filecheck/parser-printer/graph_region.mlir, tests/test_builtin_traits.py, tests/test_ir.py, tests/test_operation_builder.py, xdsl/dialects/cf.py, xdsl/dialects/func.py, xdsl/dialects/scf.py, xdsl/dialects/test.py, xdsl/ir/core.py, xdsl/traits.py
This PR adds the [`IsTerminator`][3] trait.
It is a spinoff of the discussion [here][1] and specifically [this][2] recommendation regarding the initial (and pending) attempt to add the `NoTerminator` trait.
[1]: https://github.com/xdslproject/xdsl/pull/1049
[2]: https://github.com/xdslproject/xdsl/pull/1049#issuecomment-1573537005
[3]: https://mlir.llvm.org/docs/Traits/#terminator
=> Core: Add IsTerminator trait

tests/filecheck/dialects/print/invalid.mlir, tests/filecheck/dialects/print/print_basics.mlir, xdsl/dialects/print.py, xdsl/xdsl_opt_main.py
This adds the initial `print.println` operation (without lowering so far), as presented on [zulip](https://xdsl.zulipchat.com/#narrow/stream/362011-xDSL/topic/Print.20dialect/near/364592223).
@math-fehr Pyright complains because I print an SSA value with `print_block_argument`, because I want to print `%name : type`. Do you have a suggestion how to fix this? Or is printing `name: type` pairs a big no no?
=> dialects: (print) Initial println op added

tests/dialects/test_stencil.py, tests/filecheck/dialects/stencil/invalid.mlir, tests/filecheck/transforms/stencil-shape-inference.mlir, xdsl/dialects/stencil.py
And just move ApplyOp's definition up the file a bit, pylance was grunting otherwise with the trait definition.
I added get_rank on ApplyOp as it will probably be used all over the verifiers. Should probably be an interface method at some point :slightly_smiling_face:
=> dialects: Add more stencil rank verification

tests/test_is_satisfying_hint.py, xdsl/utils/hints.py
This adds `set` to the list of supported types for `isa` checks
=> core: Add support for `isa(..., set)`

tests/test_attribute_definition.py, xdsl/dialects/builtin.py, xdsl/irdl.py
Previously, `Data` was expecting a `verify` method whenever the `Data` type parameter was not a class.
This is now removed, as we trust the user to respect the types.
=> core: Remove runtime type check in Data

tests/test_ir.py, tests/test_operation_builder.py, xdsl/ir/core.py
This adds a verification check as implemented in MLIR [here][1].
Namely, this requires that successor blocks should belong to the same region as their terminator operation.
This is an intermediate step before addressing #1049 (`NoTerminator` trait) and after having merged #1080 (`IsTerminator` trait).
[1]: https://github.com/llvm/llvm-project/blob/22f5dc7501b5eb97e406fd6c5e44048bb712ecc3/mlir/lib/IR/Verifier.cpp#L150
=> core: Add successor branching verification

tests/filecheck/dialects/stencil/hdiff_gpu.mlir, xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
This lowering is expected to be used against MLIR's `scf-parallel-loop-tiling`+`gpu-map-parallel-loops`.
MLIR's GPU mapping pass really wants 3D parallel loops, so I enforce it here.
This also reverse loop order when targetting GPU, because the outermost loop is greedily mapped to the GPU threads first dimension, so as to have a lowering that make sense on CPU and GPU from a common representation.
This yielded a speedup of one order of magnitude on the usage we have of it on Cirrus/NV100.
=> transformations: Update the stencil lowerings targetting GPU

tests/filecheck/dialects/gpu/invalid.mlir, tests/filecheck/dialects/gpu/ops.mlir, xdsl/dialects/gpu.py
And test them.
The `gpu.func` implementation is partial:
- In the same sense as the `func.func` one. All that's missing there is missing here (e.g. argument attributes)
- It is not handling any workgroup/private memory allocation.
- It is not implementing `gpu.known_block_size` nor `gpu.known_grid_size`. Those two will follow, we use them in the stencil->GPU flow. I don't have any motivating usecase yet for the others though :shrug:
=> dialects: implement partial gpu.FuncOp and gpu.ReturnOp

tests/dialects/test_arith.py, tests/filecheck/dialects/arith/arith_ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/arith/arith_cmp.mlir, xdsl/dialects/arith.py
The semantic of MLIR specifies that the operands for `arith.cmpi` should use "signless-integer-like" (https://mlir.llvm.org/docs/Dialects/ArithOps/#operands-8) but currently it's using `IntegerType` in xDSL which is as far I can see incorrect.
=> dialects: (arith): use signlessIntegerLike for arith.cmpi

tests/filecheck/dialects/memref/memref_ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_mlir_conversion.mlir, xdsl/dialects/memref.py
The semantic of MLIR specifies that the alignment attribute should be optional for `memref.alloca` "An optional alignment attribute, if specified, guarantees alignment at least to that boundary." (https://mlir.llvm.org/docs/Dialects/MemRef/#memrefalloca-memrefallocaop).
=> dialects: (memref): make alignment attribute optional in memref.alloca

tests/interpreters/test_pdl_interpreter.py, xdsl/interpreters/experimental/pdl.py
This PR aims to make the interpretation of the rewrite a bit less convoluted. Instead of interpreting the whole module, the rewrite pattern now interprets just the RewriteOp.
=> dialects: (pdl) simplify rewrite pattern and implementations

xdsl/transforms/experimental/dmp/stencil_global_to_local.py
Stacked on #1158 
The initial lowering is generating full-blown loop-nests to copy the data to temporary buffers, and is restricted to 2D for sanity.
Using the meanwhile implemented subview constructor and memcopy op, make it relatively trivial, generic, and probably more efficient :thinking: Last point left as an exercise..
Oh, right: also checked for correctness on a 4x4 grid decomposition! The results seemed exactly the same to the bit.
=> transformations: Use subviews and memcopy in stencil distribution pass.

docs/Toy/toy/__main__.py, docs/Toy/toy/dialects/toy.py, docs/Toy/toy/interpreter.py, xdsl/interpreter.py, xdsl/traits.py
Just the bare minimum in terms of functionality for now.
=> core: add CallableOpInterface and use in interpreter

tests/dialects/test_func.py, tests/dialects/test_memref.py, tests/filecheck/dialects/affine/examples.mlir, tests/filecheck/dialects/cf/cf_ops.mlir, tests/filecheck/dialects/cmath/cmath_ops.mlir, tests/filecheck/dialects/func/func_ops.mlir, tests/filecheck/dialects/scf/scf_ops.mlir, tests/filecheck/dialects/stencil/hdiff_gpu.mlir, tests/filecheck/dialects/stencil/stencil_ops.mlir, tests/filecheck/frontend/dialects/affine.py, tests/filecheck/frontend/dialects/func.py, tests/filecheck/frontend/dialects/scf.py, tests/filecheck/mlir-conversion/with-mlir/dialects/func/func_ops.mlir, tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir, tests/filecheck/transforms/stencil-shape-inference.mlir, tests/filecheck/transforms/stencil-storage-materialization.mlir, tests/interpreters/test_pdl_interpreter.py, xdsl/dialects/func.py, xdsl/frontend/code_generation.py
This PR:
- adds an `__init__` constructor for `func.Return`, deprecating the old one.
- Adds custom print and parse as per MLIR docs
=> dialects: (func) Add custom syntax for func.return

Makefile, README.md
This adds a `Makefile` containing a collection of common tasks in the project.
=> misc: Add makefile and update readme

tests/filecheck/dialects/snitch_runtime/snitch_runtime_ops.mlir, xdsl/dialects/snitch_runtime.py
This PR adds support for some operations that read memory adresses at runtime
=> dialects: Add snrt memory ops and barrier

tests/dialects/test_stencil.py, tests/filecheck/dialects/stencil/hdiff_gpu.mlir, tests/filecheck/dialects/stencil/stencil_ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir, tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir, xdsl/dialects/stencil.py, xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Optional offset mapping on stencil apply operation which will enable mapping of reduced number of enclosing loop dimensions. Also removed unnecessary zero addition on the stencil access index (the offset addition was put in regardless even if zero) - this would likely be optimised out by later stages of the pipeline so probably won't improve performance but it makes the generated SSA cleaner.
=> dialects: offset mapping on stencil apply

tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir, xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
`convert-stencil-to-ll-mlir` currently crashes on external func.func.
This fixes it, regression-tests it, and test that the type conversion happen on external funcs still.
Doesn't change the output :slightly_smiling_face: (Well, on previously working cases!)
=> transformations: Fix a crash on stencil conversion

xdsl/parser/affine_parser.py, xdsl/parser/base_parser.py, xdsl/parser/core.py
Currently, `parser/core.py` is a huge file that should be factored more.
This first PR factors out `BaseParser` out of that file, which contains the mains methods that are used in the different parsers we will have (AffineParser, BuiltinAttrParser, AsmParser).
Factoring this also helps understanding what base functions are available.
This PR only moves methods, and improve a bit on some documentation, but has no functional change.
=> core: Factor BaseParser out of the parser (NFC)

xdsl/dialects/builtin.py, xdsl/dialects/scf.py, xdsl/ir/core.py, xdsl/parser/core.py
This PR cleans up a bit the Operation and IRNode definition.
In particular:
* Creating an IRNode always create it with `parent=None`.
* Fields that appear in `Operation.__init__` do not need a default value.
* `Operation` constructors now have `()` defaults instead of `None`.
=> core: Cleanup Operation and IRNode definition

Makefile
This lowers the expected time to see an error, since notebook tests are the slowest to run, and the least likely to break. I also split out the toy tests to their own target since that's something I run a lot when working on that bit of code, all that does is change the order of execution.
=> misc: reorder test execution order in Makefile

xdsl/dialects/builtin.py
We marked these deprecated long ago that now no one should use them anymore.
=> dialects: Remove deprecated builtin constructors

tests/filecheck/parser-printer/unregistered_dialect.mlir, xdsl/ir/core.py, xdsl/xdsl_opt_main.py
This PR refines terminator conditions for unregistered operations.
Namely, if we allow unregistered operations, then their terminator conditions are implicitly fulfilled.
It also modifies `has_trait` to assume the existence of any trait for unregistered operations.
This is modelled after the [`mayBeValidWithoutTerminator`][2] and [`mightHaveTrait`][1] in MLIR.
Resolves https://github.com/xdslproject/xdsl/issues/1167
[1]: https://github.com/llvm/llvm-project/blob/268032f6f10d595bb723f6b4a21632a9f3b35be8/mlir/include/mlir/IR/OperationSupport.h#L288
[2]: https://github.com/llvm/llvm-project/blob/268032f6f10d595bb723f6b4a21632a9f3b35be8/mlir/lib/IR/Verifier.cpp#L100
=> core: Fix terminator conditions for unregistered operations

tests/dialects/test_printf.py, tests/filecheck/dialects/print/invalid.mlir, tests/filecheck/dialects/print/print_basics.mlir, tests/filecheck/dialects/print/printf_to_llvm.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/print/printf_to_llvm.mlir, tests/interpreters/test_print_interpreter.py, xdsl/dialects/printf.py, xdsl/interpreters/printf.py, xdsl/transforms/printf_to_llvm.py, xdsl/xdsl_opt_main.py
`print` is a pretty useful builtin Python function that is not available if you write `from xdsl.dialects import print`
=> dialects: (printf) print -> printf

tests/dialects/test_affine.py, tests/test_frontend_op_inserter.py, xdsl/dialects/affine.py, xdsl/frontend/code_generation.py
=> dialects: (affine) add result_types to For from_region helper

tests/dialects/test_affine.py, tests/filecheck/dialects/affine/affine_ops.mlir, tests/filecheck/dialects/affine/examples.mlir, tests/filecheck/frontend/dialects/affine.py, xdsl/dialects/affine.py, xdsl/dialects/builtin.py, xdsl/ir/affine/affine_expr.py, xdsl/ir/affine/affine_map.py
=> dialects: (affine) use maps in affine.for bounds, and add some helpers

tests/dialects/test_scf.py, tests/filecheck/dialects/scf/for_args_types.mlir, tests/filecheck/dialects/scf/for_yield.mlir, xdsl/dialects/scf.py
This PR adds a custom verification condition to `scf.for` and fixes/adds pytests for a canonical for (with and without loop-carried vars).
This was picked up while adding the `SingleBlockImplicitTerminator` trait to this dialect.
In more detail:
- Adds check to make sure the iterator is of index type
- Adds filecheck test for the above
- Fixes a unit test that did not verify and actually calls `.verify()`
- Adds the equivalent test as above for the case when there are no loop-carried variables
=> dialects: (scf) Enhance and fix scf.for verification

tests/conftest.py, tests/filecheck/dialects/builtin/attrs.mlir, tests/filecheck/dialects/builtin/parse_with_location.mlir, tests/test_printer.py, xdsl/dialects/builtin.py, xdsl/parser/core.py, xdsl/printer.py, xdsl/xdsl_opt_main.py
This commit introduces basic support for location attributes. This only
supports unknown locations for now.
Printers and parsers now support locations on arbitrary operations and
block arguments, along with locations as attributes.
=> [core] Introduce LocationAttr (unknown only)

tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir, tests/filecheck/with-riscemu/riscv_emulation.mlir, tests/interpreters/test_riscv_emulator.py, xdsl/dialects/riscv.py
riscemu currently has a bug in sw, mixing up the rs1 and rs2 operations, but only for `sw rs1 rs2 imm`, not the `sw rs2 imm(rs1)` format. This PR introduces the custom format printing for those two ops, as well as a bit of refactoring in the instruction printing code.
=> dialects: (riscv) add custom format for lw and sw instructions

tests/filecheck/transforms/reconcile_unrealized_casts.mlir, xdsl/transforms/reconcile_unrealized_casts.py, xdsl/xdsl_opt_main.py
During multiple partial conversions when lowering to a target dialect, casts operations (`builtin.unrealized_conversion_cast`) are added to a module to ensure it is still type-checkable at any stage (by MLIR invariant).
Thus, cast operations that became no-op can be removed at the end of a given lowering.
This PR adds such a pass that might be useful in the general case and should soon be used for the `riscv` infrastructure.
=> transformations: Add `reconcile-unrealized-casts` pass to remove no-op casts

xdsl/ir/affine/affine_expr.py
This patch allows users to walk on the AffineExpr AST by matching the corresponding AffineExpr class. Also significantly reduces the code size.
=> core: Restructure AffineExpr

requirements-optional.txt, requirements.txt, xdsl/interpreters/shaped_array.py
Self is a very useful type to have available, introduced in 3.11. In Python 3.10 a third-party module is required for the same functionality. I reckon the extra dependency is worth it for the kind of thing we'd like to express.
It seems to me like it's necessary to make it a required dependency as core code should be able to use Self, so users of pip install should inherit it as well. It's a bit annoying to have a dependency that's only required for python 3.10 but it seems worth it to me.
=> reqs: add typing-extension dependency

tests/dialects/test_riscv.py, tests/interpreters/test_riscv_func_interpreter.py, xdsl/backend/riscv/lowering/riscv_arith_lowering.py, xdsl/backend/riscv/register_allocation.py, xdsl/dialects/riscv.py, xdsl/dialects/riscv_func.py, xdsl/dialects/snitch.py, xdsl/transforms/lower_riscv_func.py
When I initially wrote the register types, the reasoning in my mind was that I wanted an optional register name, and `Data` cannot accept an optional generic parameter. But actually an empty string seems more appropriate than None anyway. Now that we have floats in riscv, and some duplication, it feels like a good idea to simplify. This also includes a rename of RegisterType to RegisterAttr, since we don't exclusively use them as types.
After some discussions with @kingiler  on the changes in #1269, I thought I'd play around with the code to see how to make the generics work for both Register/FloatRegister and RegisterType/FloatRegisterType. There were always some issues with it locally, and quite a lot of complexity due to the extra step of indirection. This is what led me to the changes …
=> dialects: (riscv) remove Register class

xdsl/parser/core.py
Currently some hand-written parsers do not resolve operands correctly. This helper function will reduce the boilerplate needed to resolve operands.
=> core: (parser) factor out resolve_operands

.github/parse_pyright_version.py, .github/workflows/ci-pyright-fails.yml, requirements-optional.txt
This should be less brittle than before (and removes a python script from the project)
=> CI: remove `parse_pyright_version.py` and change to simple sed script

.github/workflows/ci-mlir.yml
Had an issue again with codecov, figured we might want to try something like this.
Just an auto-retry, 10 times spaced by 10 seconds here.
=> CI: Add a retry on codecov upload.

Makefile
I frequently run `make tests` (thanks again) and this is minor noise when the diff contains files that aren't Python.
=> misc: make pyright only runs on .py files

tests/filecheck/dialects/riscv/riscv_ops.mlir, tests/filecheck/dialects/riscv_func/lower_riscv_func.mlir, tests/filecheck/dialects/riscv_func/lower_riscv_func_main.mlir, xdsl/dialects/riscv.py
This change introduces trivial custom printing to the `riscv` dialect to bring in the core code changes that enable custom printing for RISCV. All code changes are introduced by expanding the `RVOp` operation, such that any subclass can in the future evolve its format by overloading the methods for custom parsing and printing.
The IR changes itself are trivial and only drop the `"` around the instruction names:
```diff
- %addi = riscv.addi(%0) {"immediate" = 1 : i32}: (!riscv.reg<>) -> !riscv.reg<>
+ %addi = riscv.addi(%0) {"immediate" = 1 : i32}: (!riscv.reg<>) -> !riscv.reg<>
```
We also switch the format of the `riscv_ops.mlir` file to custom IR.
Future changes will bring the format closer to assembly code, e.g., by dropping the `()` around the operand list or by providing shorter …
=> dialect: (riscv) add support for trivial custom IR format

xdsl/irdl.py
This renames `_OpT` to IRDLOperationInvT, and also adds covariant and contravariant versions.
=> core: Rename _OpT to IRDLOperationInvT (NFC)

tests/dialects/test_gpu.py, xdsl/dialects/gpu.py, xdsl/parser/core.py
Add `gpu.known_block_size` and `gpu.known_grid_size` to `gpu.func`.
Add `__init__` to `gpu.FuncOp`.
=> dialects: Add attributes and __init__ to gpu.FuncOp

Makefile, docs/Toy/examples/interpret.toy, docs/Toy/examples/tests/with-mlir/interpret.toy, docs/Toy/examples/tests/with-mlir/lit.local.cfg, docs/Toy/toy/__main__.py, docs/Toy/toy/compiler.py
This is the first non-xdsl pass in Toy, I'm not sure whether it would be worth reimplementing `--canonicalise`, `--cse`, and `--lower-affine` in the short term.
=> documentation: (toy) use MLIROptPass to lower affine

tests/interpreters/test_wgsl_printer.py, xdsl/interpreters/experimental/wgsl_printer.py
This PR fix the issue when there is index type arguments in mlir translated into wgsl will not be converted to u32, and will keep index instead
=> Interpreter: index type arguments in mlir translate to wgsl

tests/interpreters/test_wgsl_printer.py, xdsl/interpreters/experimental/wgsl_printer.py
This pull request resolves a specific type inconsistency issue that arises when linearizing multi-dimensional arrays into a 1D array in the WebGPU Shading Language (WGSL).
=> Interpreter: Use unsigned integer when calculate array index

tests/test_declarative_assembly_format.py, xdsl/irdl/__init__.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py, xdsl/irdl/irdl.py
This PR adds the first version of the [declarative assembly format](https://mlir.llvm.org/docs/DefiningDialects/Operations/#declarative-assembly-format).
In its current form, it only supports the `attr-dict` directive, which specifies where the attribute dictionary should be parsed.
The structure of the PR is:
* `irdl.py` was modified (and moved to `irdl/irdl.py`) to allow specifying a declarative format with the `assembly_format` field.
* `declarative_assembly_format_parser.py` will parse the format and create the corresponding data structures, as well as checking that the format is correct. The parser is written by reusing the MLIR format lexer and parser. This is slightly hacky, but makes the change much smaller.
* `declarative_assembly_format.py` contains the data structure to …
=> core: Add declarative assembly format specification to IRDL

tests/test_traits.py, xdsl/dialects/builtin.py, xdsl/interpreter.py, xdsl/traits.py
That is, the `is_optional_symbol` method of `SymbolOpInterface`, matching MLIR's `isOptionalSymbol` on `Symbol`
Implement OptionalSymbolOpInterface for user-friendliness. Test it.
Our current implementation of SymbolOps is not compliant with MLIR's, which allows optionally symbol operations :upside_down_face: 
The most famous example being `builtin.module`, which can be anonymous as often for the top-level module, thus not containing any `sym_name` attribute.
I also take the opprtunity to make `builtin.module` an optional symbol operation. With this MLIR-compliant implementation, the only impact is to make the interpreter work with this compliance :slightly_smiling_face:
=> Implement is_optional_symbol for MLIR compliance.

tests/test_pass_from_spec.py, xdsl/passes.py
This helped me debug some things before.
=> misc: more detailed error message in pass from spec

tests/interpreters/test_wgsl_printer.py, xdsl/interpreters/experimental/wgsl_printer.py
Just using the actual function name when translating it to WGSL. Will be useful for the upcoming WGPU interpreter!
=> interpreter: Use `sym_name` when translating a `gpu.func` to WGSL.

tests/dialects/test_scf.py, tests/filecheck/dialects/scf/scf_ops.mlir, xdsl/dialects/scf.py
- Fixing a bug where in `scf.While.get` we used
```Python
return While.build(
operands=operands, result_types=result_types, regions=[before, after])
```
instead of 
```Python
return While.build(
operands=[operands], result_types=[result_types], regions=[before, after])
```
- Marking `scf.While.get` as deprecated
- Adding respective tests for the bug and `scf.While.__init__()`
=> dialect: Dropping `scf.While.get`

tests/dialects/test_func.py, xdsl/dialects/func.py, xdsl/transforms/lower_mpi.py, xdsl/transforms/lower_snitch_runtime.py
#1120: Migrate `func.Call` to use init from get methods
=> dialects: Migrate func dialect to use init from get methods

tests/test_declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py
This PR adds support for punctuation in the declarative assembly format.
For instance, "`(` `)` attr-dict" will parse correctly "test.op()".
Note that some punctuations will implicitly add spaces before/after them.
=> core: Add punctuation directive to the assembly format

tests/dialects/test_llvm.py, xdsl/dialects/llvm.py, xdsl/transforms/lower_mpi.py, xdsl/transforms/printf_to_llvm.py
Making respective changes from .get to __init__ in mpi lowering and llvm/mpi tests
=> dialect: Deprecating `.get` in llvm dialect

docs/Toy/examples/interpret.toy, docs/Toy/examples/tests/accelerate_toy.mlir, docs/Toy/examples/tests/with-mlir/interpret.toy, docs/Toy/toy/__main__.py, docs/Toy/toy/compiler.py, docs/Toy/toy/dialects/toy_accelerator.py, docs/Toy/toy/emulator/toy_accelerator_functions.py, docs/Toy/toy/rewrites/lower_to_toy_accelerator.py, docs/Toy/toy/rewrites/lower_toy_affine.py
The main idea is to show how to divert the compilation flow to a toy accelerator. This is much simpler than the plan with snitch etc, but still shows the vague idea of matching on affine loops and raising them to a different builtin operation.
As part of the Toy compilation, we know that the accelerator matches all the possible affine loops that we create, meaning that we can compile it end-to-end in python without relying on MLIR.
=> documentation: (toy) add toy accelerator dialect

xdsl/transforms/lower_riscv_func.py
While we're still not supporting multi-block riscv functions it's possible that the input functions have multiple blocks. This change makes this lowering compatible with that in the future, without functional changes to the code today.
=> dialects: (riscv) fix multi-block riscv func lowering

tests/filecheck/parser-printer/builtin_attrs.mlir, tests/test_traits.py, xdsl/dialects/builtin.py, xdsl/dialects/gpu.py, xdsl/dialects/irdl/irdl.py, xdsl/ir/core.py, xdsl/traits.py
The SymbolTable  trait offer Symbol lookup utilites and ensure Symbol uniqueness amongst its children Symbols.
This implements it, tests it, and use it on implemented operations, that is: `builtin.module`, `gpu.module`, and `irdl.dialect`.
For reference: https://mlir.llvm.org/docs/SymbolsAndSymbolTables/
NB: This documentation states "Described above are Symbols, which reside within a region of an operation defining a SymbolTable." but I could not find any enforcment of this anywhere in the codebase, so I didn't implement it. If anyone finds it, please tell :slightly_smiling_face:
=> API: Implement and use the SymbolTable Trait

tests/filecheck/dialects/riscv_scf/ops.mlir, xdsl/dialects/riscv_scf.py, xdsl/dialects/rvscf.py, xdsl/tools/command_line_tool.py
This adds the `rvscf.for` and `rvscf.yield` ops to the new `rvscf` dialect, which we want to use to do register allocation at higher levels
=> dialects: (riscv-scf) Add riscv_scf.for and yield ops

xdsl/dialects/func.py, xdsl/printer.py
The parser already have an optional parameter on `parse_optional_attr_dict_with_keyword` to handle attribute names that should not be in the generic attribute dictionnary of the custom syntax.
I'd like to do the same thing on the printing side, to simplify func here.
I'm preparing to merge an implementation of the SymbolTable trait, adding a *bunch* of `sym_name` attributes all over, I feel this might help. (e.g. next user is `builtin.module`)
=> API: Add reserved attribute names functionality to the printer.

pyproject.toml
The dependency has linting issues, I don't think we care about them
=> misc: ignore wgpu interpreter file

docs/irdl.ipynb, tests/test_is_satisfying_hint.py, xdsl/dialects/builtin.py
So I added a test, that fails because `isa` is failing  unexpectedly on that case, and I think it was because of the verifier of `ArrayAttr`. I solve it, then add a regression test for the related `DictionaryAttr`.
=> core: Fix cornercase fail in `isa`

tests/test_declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py
This PR adds keyword to the declarative assembly format.
For instance, "`keyword` attr-dict" will parse "test.op keyword" correctly.
=> core: Add keyword to the declarative assembly format

tests/test_pattern_rewriter.py, xdsl/dialects/builtin.py, xdsl/ir/core.py, xdsl/pattern_rewriter.py
So, I want to have something that looks like type conversion infrastructure in xDSL.
MLIR offers this as TypeConverters, with many nuances, because they have well-defined infrastructure for dialect conversion passes, including partial conversions. Their type conversion smartly builds on top. We don;t have any of this, and I don't have the bandwidth right now to start implementing it all.
So I'm offering something else, still helpful and nice to use but more brutal; a PatternRewrite subclass, on which we can override
```python
def convert_type(self, typ: Attribute, /) -> Attribute | None:
...
```
Rather than
```python
def match_and_rewrite(self, op: Operation, rewriter: PatternRewriter):
...
```
Right now, it has two knobs:
- recursive : Set the conversion to be recursive or not (e.g. …
=> transformations: Add TypeConversionPattern

docs/database_example.ipynb, docs/xdsl-introduction.ipynb, tests/dialects/test_arith.py, tests/interpreters/test_arith_interpreter.py, tests/interpreters/test_cf_interpreter.py, xdsl/dialects/arith.py, xdsl/frontend/dialects/arith.py, xdsl/transforms/experimental/Apply1DMPIToStencil.py, xdsl/transforms/experimental/dmp/stencil_global_to_local.py, xdsl/transforms/lower_mpi.py, xdsl/transforms/printf_to_llvm.py
swapping over arith dialect to using __init__ as opposed to static get methods. Update usages of arith in xdsl tests and experimental interpreters.  added a test for arith select op but unsure if it is actually helping
@superlopuh @math-fehr
=> dialects: Updating arith to init

docs/Toy/examples/tests/with-mlir/interpret.toy, docs/Toy/toy/__main__.py, docs/Toy/toy/compiler.py, docs/Toy/toy/rewrites/setup_riscv_pass.py, docs/Toy/toy/tests/test_add_sections.py
Adds the structure of the riscv lowering and the first pass. I added some future changes as TODOs so that the remaining work is clear.
=> documentation: (toy) add initial lowering to riscv

xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Fix the error message for verifying bounds to print upper bounds if they are wrong instead of lower bounds.
=> dialects: (stencil) Correct bounds verifier error message

tests/filecheck/dialects/dmp/canonicalize.mlir, tests/filecheck/dialects/dmp/ops.mlir, xdsl/dialects/experimental/dmp.py, xdsl/tools/command_line_tool.py, xdsl/transforms/canonicalize_dmp.py
This adds the `dmp-canonicalize` pass that removes empty exchange declarations and swap ops.
=> transforms: (dmp) Add canonicalization for dmp

docs/Toy/toy/__main__.py, docs/Toy/toy/compiler.py, docs/Toy/toy/rewrites/lower_memref_riscv.py, docs/Toy/toy/tests/test_lower_memref_riscv.py
Memref lowering with tests as part of the toy flow upstreaming (https://github.com/xdslproject/xdsl/pull/1379).
=> documentation: (toy) add lowering from `memref` to toy accelerator pass

.github/workflows/ci-mlir.yml, docs/Toy/toy/__main__.py, docs/Toy/toy/rewrites/lower_memref_riscv.py, docs/Toy/toy/tests/test_lower_memref_riscv.py, xdsl/interpreters/riscv.py
Turns out the mlir-based workflow was accidentally never enabled. We are using it to prototype parts of the RISC-V backend, so would be nice to keep it tested continuously.
=> ci: run Toy with-mlir tests on CI

.github/workflows/update_xdsl_pyodide_build.py, pyproject.toml, tests/dialects/test_mpi_lowering.py, tests/filecheck/frontend/dialects/affine.py, tests/filecheck/frontend/dialects/arith.py, tests/filecheck/frontend/dialects/scf.py, tests/test_declarative_assembly_format.py, tests/test_frontend_type_conversion.py, tests/test_operation_builder.py, tests/test_operation_definition.py, tests/test_pass_lexer.py, tests/test_traits.py, xdsl/_version.py, xdsl/dialects/builtin.py, xdsl/frontend/context.py, xdsl/frontend/dialects/builtin.py, xdsl/frontend/op_resolver.py, xdsl/frontend/type_conversion.py, xdsl/ir/core.py, xdsl/irdl/irdl.py, xdsl/parser/core.py, xdsl/printer.py, xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py, xdsl/transforms/lower_mpi.py, xdsl/utils/hints.py, xdsl/utils/test_value.py
Type ignore sometimes hides the wrong issue. We sometimes want to just get pyright to stop complaining about a private funciton call and then, when the function interface changes or is deleted, we miss the type error. When ignoring pyright, it's best to always write `pyright: ignore[specific, issues]` as opposed to a blanket `type: ignore`. I also found some `type: ignore[specificIssue]` but that's not actually a syntax that `type: ignore` supports, it just ignores the whole line.
=> misc: disable type ignore

xdsl/transforms/experimental/dmp/decompositions.py
This was a tiny bug with big implications on correctness, I'm a bit sad we didn't catch it earlier...
This basically put an x-coordinate where a y-coordinate was expected. Not good.
=> transforms: (dmp) Fix small mistake in decomp swaps generation

tests/filecheck/parser-printer/operation_signature.mlir, xdsl/parser/core.py
After parsing the types, `current_token` points to the next operation, so the diagnostic is misleading.
=> core: print error on operation with mismatched types, not next one

.github/workflows/ci-mlir.yml
This PR adds `mlir-cpu-runner` to the CI, the MLIR CPU execution driver.
Basically it allows you to run a program written in MLIR, by (JIT-)compiling LLVM MLIR-dialect to an actual binary (and immediately running it.) This can be useful for end-to-end tests, where you actually want to see what comes out of running the program.
It is provided in the same way that mlir-opt is provided, this means that:
* It is mainly intended to be run with tests in `tests/filecheck/mlir-conversion` ([example is waiting here](https://github.com/xdslproject/xdsl/blob/a1dd52d6d80da6704d755fb0b5ec0797b0de2d7a/tests/filecheck/mlir-conversion/with-mlir/dialects/print/printchar_to_putchar.mlir#L1))
* It is cached, just like `mlir-opt`
Note that this addition does not seem to add any extra time to the build of the …
=> ci: Add mlir-cpu-runner to mlir-build step

tests/dialects/test_stencil.py, xdsl/dialects/stencil.py
This adds `.get_accesses()` to the stencil apply operation, which returns an `AccessPattern` for each stencil field.
Each access pattern contains a list of accesses, and offers some helpers like `is_diagonal`, `get_diagonals`, etc.
=> dialects: (stencil) Add access pattern analysis

tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir, xdsl/dialects/riscv.py
`flw` and `fsw` were not updated in (https://github.com/xdslproject/xdsl/pull/1256), now they are also using the same custom assembly format.
=> dialects: (riscv) add custom assembly format for `flw` and `fsw` instructions

tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir, xdsl/dialects/riscv.py
Immediate argument to `riscv.csrrwi` was marked as optional. Fixed by marking it as mandatory to abide by the ISA.
=> riscv: make CSRRWI immediate mandatory

docs/Toy/examples/tests/with-mlir/interpret.toy, xdsl/backend/riscv/register_allocation.py
Just allocates a fresh register to use as the loop variable
=> backend: (riscv) add infinite register allocation for for loops

tests/test_builtin_traits.py, xdsl/dialects/irdl/irdl.py, xdsl/traits.py
Main change is the use of `*args` for `parameters`. Another change is using generators instead of list.
=> core: (trait) Polish HasParent trait

pyproject.toml
Add `ruff` rule [`UP`](https://beta.ruff.rs/docs/rules/#pyupgrade-up). It mainly upgrades python usages such as:
- deprecated usage, `List` to `list`, `typing.Sequence` to `collections.abc.Sequence`
- PEP604, `isinstance(x, (A, B))` to `isinstance(x, A | B)`
- prevent some weird typing hint such as `Optional[SSAValue] | None`.
- f-string usage when possible
Main file change is `pyproject.toml` and rest of files are auto-fixed by `ruff`.
```diff
-select = ["E", "F", "W", "I"]
+select = ["E", "F", "W", "I", "UP"]
+"versioneer.py" = ["ALL"]
+"_version.py" = ["ALL"]
```
**Edit:**
Now some rules from UP is excepted to minimize diff.
=> ci: Add ruff rule UP from pyupgrade

pyproject.toml, xdsl/dialects/riscv.py
The rule is to avoid extraneous parentheses.
A bug was found when adding ruff rule UP034. The code intends to have a tuple of strings but a missing comma makes it becomes extraneous parentheses.
=> ci: (ruff) Add rule UP034

docs/Toy/toy/interpreter.py, docs/Toy/toy/rewrites/lower_to_toy_accelerator.py, pyproject.toml, xdsl/dialects/llvm.py, xdsl/irdl/irdl.py, xdsl/transforms/experimental/dmp/stencil_global_to_local.py, xdsl/utils/hints.py
The rule is to use `X | Y` instead of `(X, Y)` for `isinstance` and `issubclass` methods. See PEP604.
=> ci: (ruff) Add rule UP038

Makefile
`make` without arguments defaults to building the first entry in the makefile.
Moving `venv` to be the first target instead of `clean` solves the problem of accidentally deleting venv when running make without arguments.
=> misc: (make) make without arguments no longer deletes `venv`

tests/riscv/test_abi_spec.py, xdsl/backend/riscv/targets.py, xdsl/transforms/riscv/targets.py
This is the start of my crusade to get a concept of ABI, targets, etc into the RISC-V backend.
I also moved this into a riscv folder, because I didn't know where to best place this. I feel that we should probably bundle all the risc-v stuff into a single submodule.
This is still missing all the linker stuff. Although I'm unsure if we even want that in here, as we may or may not want to do any linking.
This is still not quite ready, I have an error in the `march` extension formatting. But that's not really relevant to get the discussion going I feel.
I don't know if the codebase actually *needs* this, but I feel we need to discuss this a bit before we continue with the current path. Opinions welcome!
*Quick disclaimer:* I feel that time spent on this wasn't wasted as it helped me refresh …
=> dialects: Add the basic concept of compilation targets

xdsl/dialects/func.py, xdsl/dialects/riscv.py, xdsl/parser/core.py, xdsl/printer.py
I implemented the custom parsing syntax for `func.call`, and found that I needed to make some significant changes to the helpers to make it work. The attribute dictionary is not preceded by `attributes` in `func.call`, since there's no region for it to be confused with.
=> core: unify some attribute printing/parsing methods

pyproject.toml, tests/test_parser_error.py
Since we are using `pytest`, it would be better if our tests are written in a consistent and concise way. Ruff's [PT](https://beta.ruff.rs/docs/rules/#flake8-pytest-style-pt) is based on flake8's pytest style.
Some rules are ignored in this PR to minimize the diff.
```diff
-select = ["E", "F", "W", "I", "UP"]
-ignore = ["E741"]
+select = ["E", "F", "W", "I", "UP", "PT"]
+ignore = ["E741", "PT006", "PT007", "PT011", "PT012", "PT015", "PT017", "PT018"]
```
This series of PR should not cause any API changes in the core xDSL code base but only for the tests.
=> ci: (ruff) Add rule PT for pytest

docs/Toy/toy/tests/test_lower_memref_riscv.py
We've decided not to support f64 officially for the time being, so I thought I'd convert the test as part of the float support changes.
=> tests: (riscv, memref) use f32 in memref to riscv lowering test

docs/Toy/examples/tests/with-mlir/interpret.toy, docs/Toy/toy/compiler.py, tests/filecheck/backend/rvscf_lowering_labels.mlir, xdsl/backend/riscv/riscv_scf_to_asm.py
The changes for #1457 were reverted as part of some follow-up work stacked PR chaos. Re-merging already approved changes.
=> backend: (riscv) fix riscv_scf lowering (#1457 again)

tests/test_declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py
This PR adds operands to the declarative assembly format.
An operand is parsed with the `$operand_name` syntax, and should also have its type parsed with the `type($operand_name)` syntax.
For instance, ``$lhs `,` $rhs `:` type($lhs) `,` type($rhs)`` will parse `test.op %0, %1 : i32, i64` correctly.
All operands should be parsed exactly once, and should have their type parsed exactly once as well.
Future PRs will add support for optional/variadic operands, as well as removing the need to parse their types if they have a unique type, or if their type can be deduced from the other parsed types.
=> core: Add operands in declarative assembly format

docs/Toy/toy/compiler.py, tests/filecheck/backend/riscv/optimisation_riscv.mlir, xdsl/backend/riscv/lowering/optimisation_riscv.py, xdsl/dialects/riscv.py, xdsl/tools/command_line_tool.py, xdsl/transforms/canonicalize.py
Also fixes some other issues:
- redundant mv elimination should only eliminate allocated registers, not unallocated
- I forgot to register `CanonicalizePass` with xdsl-opt
- move the file definiing the canonicalization pattern one level up in the hierarchy
=> backend: (riscv) use canonicalization to optimize riscv

docs/tutorial.ipynb, tests/backend/riscv/test_utils.py, tests/filecheck/parser-printer/operation_with_properties.mlir, tests/test_traits.py, xdsl/backend/riscv/lowering/utils.py, xdsl/dialects/builtin.py, xdsl/dialects/gpu.py, xdsl/dialects/memref.py, xdsl/ir/core.py, xdsl/irdl/irdl.py, xdsl/parser/core.py, xdsl/printer.py, xdsl/transforms/printf_to_putchar.py
This PR moves the arguments from `__init__`, `create`, and `build` to named arguments only.
This means that `MyOperation.create([arg1, arg2])` is not allowed for instance, and should be changed to `MyOperation.create(operands=[arg1, arg2])`.
This both makes it clearer, and avoid easy mistakes.
Note that this doesn't affect custom `__init__` created by users, so things like `Addi(arg1, arg2)` will stay the same for instance.
=> core: Move Operation create/build/init parameters to named arguments

tests/filecheck/dialects/pdl/mlir-tests.mlir, xdsl/dialects/pdl.py
`pdl.replace` had a `printer` function instead of a `print` one, so it was calling the generic print instead.
=> dialects: Fix printer function of pdl.replace

tests/dialects/test_riscv.py, tests/filecheck/backend/riscv/optimisation_riscv.mlir, tests/filecheck/dialects/riscv/riscv_ops.mlir, xdsl/backend/riscv/lowering/optimise_riscv.py, xdsl/dialects/riscv.py
This doesn't really use it anywhere yet, just provides the ability to express copying a value from one register to another. Hopefully we'll actually manage to optimise out this operation for all the cases we care about, but it's possible that we won't so we'll need to implement a lowering to the rountrip through memory before printing.
=> dialects: (riscv) add fmvop

pyproject.toml
The links have nice urls so it's easier to see what exactly we're ignoring.
=> misc: add links to ruff documentation in pyproject

docs/Toy/toy/__main__.py, docs/Toy/toy/compiler.py, tests/interpreters/test_riscv_interpreter.py, xdsl/interpreters/riscv.py
This is technically in Toy but we're currently using this pipeline for the riscv paper experiments, so would benefit from this change for critical work.
=> documentation: (toy) add optimisation steps to Toy

docs/Toy/toy/__main__.py, docs/Toy/toy/compiler.py, tests/filecheck/backend/riscv_reduce_register_pressure.mlir, tests/interpreters/test_riscv_interpreter.py, xdsl/backend/riscv/lowering/reduce_register_pressure.py, xdsl/interpreters/riscv.py, xdsl/tools/command_line_tool.py
First rewrite among many that will help reduce the number of registers live at any time. Future work will include things like moving constant definitions closer to their use etc.
=> backend: (riscv) add riscv-reduce-register-pressure pass

tests/riscv/test_abi_spec.py, xdsl/backend/riscv/targets.py
I managed to find a proper document specifying the ABI, and did some exploring in the compiler explorer.
My initial version of the ABI was almost correct, I had just missed a couple of smaller issues (such as stack alignment and float calling conventions).
This should now conform to the original spec.
=> backend: (riscv) Clean up abi and arch specifications

xdsl/backend/riscv/register_allocation.py, xdsl/transforms/riscv_register_allocation.py
Functions are a natural boundary for register allocation scopes, this is a small refactoring change that simplifies the register allocation code a little bit.
=> backend: (riscv) move module walking logic to register allocation pass

tests/filecheck/backend/riscv/riscv_register_allocation_jregs_no_loops.mlir, xdsl/backend/riscv/register_allocation.py, xdsl/transforms/riscv_register_allocation.py
We can simulate the J reg allocator with the block naive allocators limited to 0. This PR allows passing 0 as the value, and tests that for code with no loops the result is the same as the J register allocator.
=> backend: (riscv) limit_registers None by default

tests/filecheck/backend/riscv/register_allocation_liveness_block_naive.mlir, tests/filecheck/backend/riscv/register_allocation_liveness_block_naive_limited.mlir, xdsl/backend/riscv/register_allocation.py
I'm not sure exactly what the purpose of `to_free` was. @compor @adutilleul am I missing something here? It feels like it just prevents us from reusing the result register for operand register, which seems like generally a good idea.
=> backend: (riscv) free result registers before allocating

xdsl/backend/riscv/register_allocation.py, xdsl/backend/riscv/register_queue.py, xdsl/transforms/riscv_register_allocation.py
Decouple the traversal logic from available register logic. This change just uses the helper class instead of having the logic inline, future changes will do a bit more separation.
=> backend: (riscv) use register_queue for register management

tests/filecheck/dialects/riscv_func/riscv_func_ops.mlir, xdsl/dialects/riscv_func.py
This PR adds to `riscv_func.FuncOp` the same visibility attribute that `func.FuncOp` has. This is the first step towards emitting correct assembler directives for global symbols.
=> backend: (riscv) add sym_visibility attr to riscv_func.FuncOp

xdsl/backend/riscv/register_allocation.py
Small refactor that gives both register allocators three abstract methods to implement, processing a generic RISC-V operation, processing a func op, and processing a for loop.
=> backend: (riscv) factor out op processing in register allocators

tests/test_interpreter.py, xdsl/interpreter.py, xdsl/interpreters/printf.py
Improvement upon #1422 
Adds support for registering external functions similar to operation and cast implementations by marking them with `@impl_external(sym_name)`
=> interpreter: Add support for external implementations

.github/workflows/jupyterlite.yml
Good news: the new daily JupyterLite nighlty workflow seems to work (I was just mistaken and set it to run at 5AM not 5PM. If anybody cares, this PR is a nice time to argue about the exact time!)
I just forgot to remove a now obsolete condition on the deploy job, so it was not triggered. (It only built the page without deploying it) This PR solves this.
First scheduled run: https://github.com/xdslproject/xdsl/actions/runs/6092690186
=> CI: Remove conditions on JupyterLite deploy.

docs/database_example.ipynb, tests/filecheck/dialects/scf/reduce.mlir, tests/filecheck/dialects/scf/scf_ops.mlir, tests/filecheck/dialects/stencil/hdiff_gpu.mlir, tests/filecheck/dialects/stencil/stencil_ops.mlir, tests/filecheck/frontend/dialects/scf.py, tests/filecheck/mlir-conversion/with-mlir/dialects/scf/for_custom.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/scf/for_generic.mlir, tests/filecheck/transforms/convert-stencil-to-ll-mlir-tiled.mlir, tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir, tests/test_parser.py, xdsl/dialects/scf.py, xdsl/dialects/utils.py, xdsl/parser/core.py
Also makes a minor change to the parser API, to require the argument label for `expect_type` in parse_argument. Happy to remove it, but seems like a good thing to require the argument label for an ambiguous bool-valued argument such as this.
=> dialects: (scf) add custom syntax to scf for and yield

tests/filecheck/backend/riscv/register_allocation_preallocated.mlir, xdsl/backend/riscv/register_allocation.py, xdsl/transforms/riscv_register_allocation.py
Without this our code is somewhat broken, especially in the presence of function calls or function arguments.
=> backend: (riscv) exclude preallocated registers by default

docs/Toy/toy/tests/test_lower_memref_riscv.py, tests/backend/riscv/test_preallocated.py, tests/dialects/test_riscv.py, tests/interpreters/test_riscv_emulator.py, tests/interpreters/test_riscv_interpreter.py, tests/interpreters/test_riscv_scf_interpreter.py, xdsl/backend/riscv/lowering/convert_arith_to_riscv.py, xdsl/backend/riscv/lowering/convert_memref_to_riscv.py, xdsl/dialects/riscv.py
Similarly to an earlier PR, unifying two abstract operations, in preparation for the addition of some vector ops required for Snitch.
=> backend: (rsicv) unify RdRsRs(Integer|Float)Op

docs/Toy/toy/rewrites/setup_riscv_pass.py, docs/Toy/toy/tests/test_add_sections.py, tests/dialects/test_riscv.py, tests/filecheck/backend/riscv/convert_func_to_riscv_func.mlir, tests/filecheck/backend/rvscf_lowering_labels.mlir, tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir, tests/filecheck/dialects/riscv/riscv_ops.mlir, tests/filecheck/dialects/riscv_func/lower_riscv_func.mlir, tests/filecheck/dialects/riscv_func/lower_riscv_func_main.mlir, tests/filecheck/with-riscemu/riscv_emulation.mlir, tests/filecheck/with-riscemu/rvscf_lowering_emu.mlir, tests/interpreters/test_riscv_emulator.py, tests/interpreters/test_riscv_func_interpreter.py, xdsl/backend/riscv/lowering/convert_func_to_riscv_func.py, xdsl/dialects/riscv.py, xdsl/dialects/riscv_func.py, xdsl/transforms/lower_riscv_func.py
I don't think we need the extra step of rewriting to labels, and we benefit from skipping it. For one, fewer rewrites means fewer opportunities for bugs. Also, we get fewer `GetRegisterOp`s, and having 0 of them lets us interpret the code directly. As discussed before, dropping the region from labels also makes the code a bit less weird/confusing.
=> backend: (riscv) print assembly from riscv_func, remove region from label

tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir, tests/filecheck/dialects/riscv/riscv_ops.mlir, xdsl/dialects/riscv.py
=> backend: (riscv) add vfadd and vfmul instructions

docs/Toy/Toy_Ch0.ipynb, docs/Toy/toy/compiler.py
Now that we've removed the dependency on mlir-opt we can run our end-to-end riscv compiler + emulator in the browser.
=> documentation: (toy) add end-to-end demo notebook

tests/interpreters/test_pdl_interpreter.py, xdsl/interpreter.py, xdsl/interpreters/experimental/pdl.py
added run_attribute to the pdl interpreter.  Not super happy with how the test asserts, but not sure best way to go about it. @superlopuh  @math-fehr
=> Interpreter: Handling attributeOp in pdl rewrites

tests/filecheck/projects/riscv-backend-paper/pres.mlir
This PR adds a filechek file to keep track of changes to the target IR that we want to produce when compiling to snitch. Currently has the first two examples, scalar and vectorised, more to follow.
=> misc: add filecheck file with assembly-level IR output for riscv paper/presentation

tests/test_operation_definition.py, xdsl/irdl/irdl.py
Currently, `operand_segment_sizes` is not registered as an attribute in the operation definition class (`OpDef`).
This PR adds this to the operation definition.
This is going to simplify the update to latest MLIR, as these will become properties.
=> core: Add segment sizes attributes to IRDL operation definition

tests/test_parser.py, xdsl/dialects/builtin.py, xdsl/parser/core.py
This implements properties retrocompatibility in the parser as MLIR does, that is, allow to parse a properties-defining operation in generic syntax when it has no property dictionary at all.
In that case, and only that case, it will extract properties from the attribute dictionnary to the properties one.
By *only* that case, I mean that the point is not to relax the cut between properties and attributes: if properties are present on the generic syntax of the operation, we won't be fetching missing ones from the attribute dictionary. This is meant only to parse operations printed before switching to properties.
=> core: Implement properties retrocompatibility in the parser.

xdsl/interpreters/experimental/wgsl_printer.py
Use the IRDL-defined attribute accessor as eitherway needed for the properties update.
=> interpreter: Small nit on WGSL printer

tests/test_ir.py, xdsl/ir/core.py
`Operation.clone` and `Operation.is_structurally_equivalent` weren't checking for properties.
=> core: check for properties in clone and equivalence check

tests/test_pattern_rewriter.py, xdsl/dialects/test.py, xdsl/pattern_rewriter.py
This adds support for properties in the attribute/type converter.
Note that this also adds properties to the `TestOp` classes. They are required unlike attributes because only defined propreties can be used.
=> core: Add support for properties in attribute converter

tests/interpreters/test_pdl_interpreter.py, tests/test_ir.py, xdsl/interpreters/experimental/pdl.py, xdsl/ir/core.py
This PR adds support for properties in the PDL interpreter.
In particular, this means that matching an operation will match attributes both in the attribute and property dictionary.
Also, creating a new operation with the PDL attribute dictionary will split the dictionary into an attribute and property dictionary, using the IRDL operation specification.
=> interpreter: Support properties in PDL interpreter

xdsl/dialects/experimental/math.py, xdsl/transforms/printf_to_putchar.py
Using `__init__()` instead of `get()` for experimental dialect `maths`. This follows the previous changes on dialect. It will also make the tests for the dialect easier to write.
=> dialects: (maths) Using `__init__()` instead of `get()`

tests/test_operation_definition.py, xdsl/irdl/irdl.py
Extracted (and cleaned up) from the MLIR bump PR, this allows to make "operand_segment_sizes" and friends implemented as property on the Op rather than an attribute.
=> core: Implement AttrSizedSegments option to implement as a property.

tests/test_traits.py, xdsl/interpreters/experimental/wgpu.py, xdsl/traits.py
Extracted and polished from #1582.
This make SymbolOpInterface and SymbolTable working with the expected `sym_name` as an attribute or property transparently, as in the targetted MLIR version.
=> core: Make SymbolOpInterface and Symboltable properties-ready.

tests/test_operation_builder.py, xdsl/irdl/irdl.py
I forgot something while extracting this from #1582 in #1603; This is fixed and tested here.
Basically, by switching some helpers to use the IRDLOptions types rather than placeholder instances, I forgot to actually get the option instance when using this option in the irdl generated builder, causing this to always fall back to the attribute-based behaviour and causing errors in the property-expecting case (hence no regression appearing with no dialect ops using properties yet). Fixed :wrench: 
this is also the last core-preparing PR before #1582 :tada: Opening a Zulip thread in a moment to discuss that.
=> core: test and fix IRDLOptions as properties

docs/database_example.ipynb, tests/dialects/test_memref.py, tests/dialects/test_scf.py, tests/interpreters/test_scf_interpreter.py, tests/test_op_builder.py, xdsl/dialects/scf.py, xdsl/frontend/code_generation.py, xdsl/transforms/experimental/Apply1DMPIToStencil.py, xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py, xdsl/transforms/experimental/dmp/stencil_global_to_local.py, xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py, xdsl/transforms/experimental/lower_hls.py, xdsl/transforms/lower_affine.py, xdsl/transforms/printf_to_putchar.py
Move the `scf` dialect from `.get()` to `__init__` to be more in line with the rest of the project.
=> dialects: (scf) convert constructors from get to init

tests/test_printer.py, xdsl/printer.py
This PR is part of #1607 and adds:
- Ability to optionally skip printing a terminator operation
- Tests of the above
When this is to happen is left on the specific dialect; the immediate application of this is used in custom printing/parsing in order to avoid printing implicit terminators (this is part of #1607).
=> core: (printer) Allow optional printing of block terminator operations

docs/Toy/toy/emulator/toy_accelerator_instructions.py, tests/interpreters/test_riscv_interpreter.py, xdsl/interpreters/riscv.py
A first step towards handling 64-bit values in riscv, removes a bit of custom logic fromt the custom riscemu instructions in Toy. Also aligns our riscv interpreter to riscemu in using little-endian ordering.
=> documentation: (toy) use RawPtr to read buffer of values

Makefile
This PR replaces the `source` invocation from the `Makefile` when building a virtual env by using the dot operator.
This fails because `make` seems to search the `PATH` for a program called `source`.
The way to invoke a shell script and run its contents in the current shell within a `Makefile` is by using `.` operator (which is also POSIX-compliant).
I saw this fail on @dshaaban01's MacBook last week and I've been able to replicate it on my Linux box.
Not sure how it was missed.
=> misc: (makefile) Fix shell invocation in Makefile for venv creation

docs/Toy/toy/__main__.py, docs/Toy/toy/emulator/toy_accelerator_instruction_functions.py, tests/interpreters/test_riscv_interpreter.py, tests/interpreters/test_riscv_scf_interpreter.py, tests/test_interpreter.py, xdsl/interpreter.py, xdsl/interpreters/riscv.py, xdsl/tools/xdsl_run.py
This is necessary for some further interpreter changes. The interpreter function implementations are suposed to be stateless, and the riscv interpreter functions currently violate that, by caching the data on the functions object itself. This PR fixes that by introducing a new cache on the interpreter object, which is stateful already.
=> interpreter: add mechanism to store runtime data in the interpreter

xdsl/ir/core.py
Pyright complains that it's technically mutable with different types, so someone could set `parent` to any `IRNode`.
=> core: make IRNode.parent an abstract property parent_node

xdsl/dialects/riscv.py
Pyright complains otherwise that `|` cannot be used between the arguments in `parse`
=> dialects: (riscv) use dict instead of mapping in riscv.py

tests/dialects/test_seq.py, tests/filecheck/dialects/seq/seq_invalid.mlir, tests/filecheck/dialects/seq/seq_ops.mlir, xdsl/dialects/seq.py, xdsl/tools/command_line_tool.py
`seq` dialect first part, as discussed on zulip.
Opened as WIP but looking for feedback. Pinging @superlopuh @tobiasgrosser @compor and @JosseVanDelm as having participated in the discussion on zulip. Not sure who’s signing off on changes down the line.  
There seems to be quite a lot to discuss just on this first type/operation
- One thing nagging me in particular is that printing the `ClockDivider`’s power of 2 attribute with `print_attribute` means we get `seq.clock_div %clk by #int<4>` instead of the input syntax `seq.clock_div %clk by 4` -- should I print the naked `int` value to get the right syntax instead?  It seems to be parsed back fine.
- I haven’t managed to coerce this `pow2` attribute to be signless 8-bit, no matter how much I’ve been messing around with `IntAttr`, …
=> dialects: (seq) Add ClockType and ClockDivider

tests/dialects/test_builtin.py, tests/filecheck/parser-printer/float_parsing.mlir, xdsl/backend/riscv/lowering/convert_memref_to_riscv.py, xdsl/dialects/builtin.py
This PR:
- Adds a `get_bitwdith` read-only API method on `FloatType`s similar to MLIR [here](https://github.com/llvm/llvm-project/blob/39d55321bd0b8ce436d6fcd8e5ba51b8bf535559/mlir/lib/IR/BuiltinTypes.cpp#L89)
- Tests of the above
- One use case of this API method
=> dialects: (builtin) Add bitwidth accessor to float types

tests/test_traits.py, xdsl/dialects/gpu.py, xdsl/irdl/irdl.py
This is an alternative implementation to #1505, which implements the laziness at the traits field level, instead of the trait definition level.
Note that we could force all traits definitions to use `traits_def`, while right now operations can both use `traits = frozenset(...)` and `traits = traits_def(frozenset(...))` and `traits = traits_def(lambda: frozenset(...))`.
I believe this implementation reduces the complexity of the traits definitions, as they don't need to specify if they are lazy or not. If a circular dependency arise, this only require a change in the operation definition, and not the trait definition, which I think is better.
=> core: Add support for lazy traits in IRDL

Makefile
This PR marks the `venv` Make target as phony as it should not depend on whether the directory exists or not.
If the `venv` directory is created and any of the subsequent commands of the target fail, the target is not rerun (i.e., always up to date) unless the directory is removed.
Moreover, this behaviour differs when a different venv dir is selected when `VENV_DIR` is set.
=> misc (makefile): Mark venv target as phony

tests/interpreters/test_pdl_interpreter.py, xdsl/interpreters/experimental/pdl.py
Add support for `pdl.apply_native_constraints` in the PDL interpreter, and test it
=> interpreter: Add support for pdl.apply_native_constraints

tests/interpreters/test_pdl_interpreter.py, xdsl/interpreters/experimental/pdl.py
Add support for constants in `pdl.apply_native_constraint`.
Something like
```python
%attr = attribute = 10
pdl.apply_native_constraint "constraint"(%attr: !pdl.attribute)
```
where `%attr` is not bound
=> interpreter: pdl native constraints constant

tests/test_declarative_assembly_format.py, xdsl/dialects/arith.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py
This PR adds support for results in the declarative assembly format.
The rule is that all results should appear exactly once in the declarative format, and nested under a `type` directive.
This PR also adds this format for `arith.ext*` and `arith.trunc*` operations.
=> core: Add results in declarative format

tests/filecheck/backend/riscv/canonicalize.mlir, xdsl/dialects/riscv.py, xdsl/transforms/canonicalization_patterns/riscv.py
**implementation of and-bitwise rewrite pattern**
This PR includes the code that implements a rewrite pattern for an and-bitwise operation. 
It was introduced:
- the class class ```BitwiseAndByZero(RewritePattern)``` in ```xdsl/transforms/canonicalization_patterns/riscv.py``` containing the rewrite pattern for the and-bitwise operation.
- the class ```BitwiseHasCanonicalizationPatternsTrait(HasCanonicalisationPatternsTrait)``` in ```xdsl/dialects/riscv.py``` for bitwise operations (maybe was ```AndHasCanonicalizationPatternsTrait(HasCanonicalisationPatternsTrait)``` better instead?). I didn't find an already existing class appropriate for and operation.
-  test for the new rewrite pattern.
@tobiasgrosser, @superlopuh, @compor, please let me know if there is anything should be done …
=> dialects: Add and-bitwise rewrite pattern

docs/Toy/toy/compiler.py, docs/irdl.ipynb, docs/tutorial.ipynb, tests/dialects/test_riscv.py, tests/interpreters/test_pdl_interpreter.py, tests/interpreters/test_riscv_emulator.py, tests/interpreters/test_wgpu.py, tests/interpreters/test_wgsl_printer.py, tests/rewriting/composable_rewriting/immutable_ir/test_immutable_ir.py, tests/test_declarative_assembly_format.py, tests/test_ir.py, tests/test_mlctx.py, tests/test_parser.py, tests/test_parser_error.py, tests/test_pattern_rewriter.py, tests/test_printer.py, tests/test_rewriter.py, tests/test_use.py, xdsl/ir/core.py, xdsl/tools/command_line_tool.py, xdsl/tools/irdl_to_pyrdl.py, xdsl/transforms/canonicalize.py
This PR renames `register_*` with `load_*`.
`load_*` is the naming used by MLIR, so it makes sense to go there.
Also, I would like to add a `register_*` methods, as in #1116
=> core: Rename register_* with load_*

.vscode/launch.json, xdsl/tools/xdsl_opt.py
This should only affect users of VSCode, and not really impact anyone else. By default xdsl-opt launches with the currently open file as argument, parsing and printing it. I use launch configs a lot for debugging and would love to have the file in the repo.
=> misc: add a launch.json to launch xdsl-opt from vscode

xdsl/backend/riscv/lowering/utils.py
Adds a small helper for when you don't want to cast all the operands. The code is already fully tested.
=> backend: (riscv) split logic for casting operands to regs

tests/filecheck/backend/riscv/canonicalize.mlir, tests/filecheck/backend/riscv/verify.mlir, tests/filecheck/dialects/riscv/frep_verification.mlir, tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir, tests/filecheck/dialects/riscv/riscv_ops.mlir, tests/filecheck/dialects/riscv_snitch/ops.mlir, tests/filecheck/dialects/snitch/snitch_to_riscv_lowering.mlir, tests/filecheck/projects/riscv-backend-paper/pres.mlir, xdsl/dialects/riscv.py, xdsl/dialects/riscv_snitch.py, xdsl/tools/command_line_tool.py, xdsl/transforms/canonicalization_patterns/riscv.py, xdsl/transforms/lower_snitch.py
This PR:
- Factors out `frep.inner`, `frep.outer`, `scfgw` and `scfgwi` from the `riscv` to the `riscv_snitch` dialect.
Nothing else changed.
=> backend (riscv): Factor out Snitch ISA extensions

tests/test_affine_builtins.py, xdsl/ir/affine/affine_map.py
I couldn't find an equivalent helper in MLIR Affine, but seems like an appropriate place to put it. Adds a helper to create the affine map from a matrix to its transpose.
=> core: (affine) add AffineMap.transpose_map

tests/xdsl_opt/test_xdsl_opt.py, xdsl/passes.py, xdsl/xdsl_opt_main.py
Also makes the behaviour of `print-between-passes` actually correspond to the behaviour of only printing between passes, not after every pass.
=> core: add PassPipelinePass with optional callback in between passes

xdsl/tools/command_line_tool.py, xdsl/transforms/experimental/dmp/stencil_global_to_local.py
(This is targetting the devito backport branch, not main)
The actual domain (and grid) dimensionality of dmp-decompose-2d is now parameterized, making the old-name pretty confusing in user-code. Simple rename to make it clear the dimensionality is not fixed by the pass :slightly_smiling_face:
=> transformations: Rename dmp-decompose-2d to dmp-decompose

tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_custom.mlir, xdsl/dialects/memref.py
mlir actually drops the nontemporal = false, as that's the default. I have not reimplemented this behaviour, as it's not really critical and parses just fine.
=> dialects: (memref) add attributes in memref store load custom syntax

tests/test_builtin_traits.py, xdsl/dialects/riscv_scf.py, xdsl/dialects/scf.py
This PR resolves #1218 :
- Adds lazy traits support (introduced in #1529) to break the circular dependency between ops and traits that require them.
=> dialects: (scf, riscv_scf) Use lazy traits support

tests/filecheck/backend/riscv/canonicalize.mlir, xdsl/dialects/riscv.py, xdsl/transforms/canonicalization_patterns/riscv.py
Also throw in some Pure() annotations
=> backend: (riscv) Add canonicalization pattern for AddImmediateConstant

tests/dialects/test_riscv.py, xdsl/dialects/riscv.py
=> dialects: (riscv) assembly section op creates a valid region in init

tests/filecheck/backend/riscv/convert_func_to_riscv_func.mlir, tests/filecheck/backend/riscv/memref_to_riscv.mlir, tests/filecheck/backend/rvscf_lowering_labels.mlir, tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir, tests/filecheck/dialects/riscv/riscv_ops.mlir, tests/filecheck/projects/riscv-backend-paper/pres.mlir, tests/filecheck/with-riscemu/riscv_emulation.mlir, xdsl/dialects/riscv.py
CC @xdslproject/risc-v-backend
=> dialects: (riscv) omit ": () -> ()" for riscv ops

tests/dialects/test_snitch.py, tests/filecheck/dialects/snitch/snitch_ops.mlir, tests/filecheck/dialects/snitch/snitch_to_riscv_lowering.mlir, xdsl/dialects/snitch.py, xdsl/transforms/lower_snitch.py
I'm not sure what exactly the tradeoff is between making things a plain intattr or the integer attr with signedness, but it feels like if we're operating on things that are actually 5 or 7 bits wide and keeping them in i32 for some reason then it's a bit more confusing. I'm also not sure we want to take the time now to ensure that the values fit in those widths, that'll be true for our lowerings by construction.
@xdslproject/risc-v-backend
=> backend: (riscv) make dimension an IntAttr in snitch ops

tests/dialects/test_snitch.py, tests/filecheck/dialects/snitch/snitch_ops.mlir, tests/filecheck/dialects/snitch/snitch_to_riscv_lowering.mlir, xdsl/dialects/snitch.py, xdsl/transforms/lower_snitch.py
Two main changes:
`stream` -> `dm` in snitch, since those ops correspond more to the assembly level than the stream level, and having naming consistent with the docs and snitch runtime library seems advantageous.
operand -> attribute, we always have that data at compile-time, so we might as well avoid the dance of `li` + `addi` canonicalisation, and just create the `li` at the end.
@xdslproject/risc-v-backend
=> backend: (riscv) SsrSetStreamConfigOperation has dm attr instead of stream operand

xdsl/parser/core.py
This removes methods in `Parser` that are already duplicated in `AttrParser`.
=> core: Remove duplicated methods

docs/Toy/examples/lit.cfg, docs/Toy/toy/compiler.py
The only one that still fails is Chapter 0 of the Toy tutorial because it runs riscemu in it... I'm not sure if we want to make riscemu required for it but I'd say that a single notebook failing if you don't have riscemu installed and otherwise local `make tests` still working seems like like progress.
=> testing: make fewer tests fail if riscemu is not installed

tests/dialects/test_mpi.py, tests/dialects/test_mpi_lowering.py, xdsl/dialects/mpi.py, xdsl/transforms/experimental/Apply1DMPIToStencil.py, xdsl/transforms/experimental/dmp/stencil_global_to_local.py, xdsl/transforms/lower_mpi.py
Replacing `get` method with `init` in mpi dialect and respective places, `get` methods in mpi diaclect are marked as deprecated.
=> dialects: Replacing get with init in mpi dialect and respective places

xdsl/dialects/riscv_scf.py, xdsl/dialects/utils.py
Just a little helper that should remove some boilerplate code as we add new dialects with a yield-like operation. I only used it in riscv-scf for now but am happy to migrate the rest of them in this PR.
=> core: add AbstractYieldOperation and use in riscv-scf

tests/test_attribute_definition.py, tests/test_pyrdl.py, xdsl/dialects/builtin.py, xdsl/dialects/linalg.py, xdsl/dialects/llvm.py, xdsl/dialects/riscv.py, xdsl/dialects/test.py, xdsl/parser/attribute_parser.py, xdsl/parser/base_parser.py, xdsl/printer.py
More MLIR compliancy! This is a step of my proper opqaue syntax implementation quest.
Basically, the angle brackets we use in Data attributes are not supposed to be part of the general syntax, but is just a convention adopted by most attributes.
This reverts this hardcoding, moving those brackets in every Data Attribute's custom parsing/printing code.
It already implements helpers for this; both for my laziness and for next users' sanity :slightly_smiling_face:
=> core: Remove hardcoded angle brackets from Data printing/parsing.

tests/dialects/test_linalg.py, tests/interpreters/test_linalg_interpreter.py, xdsl/dialects/linalg.py, xdsl/interpreters/linalg.py
This PR:
- Uses the abstract base implementation of Yield in `linalg.yield`
- Rename class from `Yield` to `YieldOp` (white we are at it)
=> dialects: (linalg) Use abstract yield operation in `linalg.yield`

xdsl/dialects/scf.py
This PR:
- Uses the abstract base implementation of Yield in `scf.yield`
Similar to #1735.
=> dialects: (scf) Use abstract yield operation in `scf.yield`

tests/filecheck/parser-printer/unregistered_dialect.mlir, xdsl/parser/attribute_parser.py, xdsl/printer.py
This is @math-fehr's fix on unregistered attribute for opaque syntax, sister PR to #1726.
=> core: Fix unregistered attribute opaque syntax handling

tests/dialects/test_affine.py, tests/filecheck/dialects/affine/affine_ops.mlir, xdsl/dialects/affine.py
The verifier of affine.for was working on the assumption that no runtime dimension or symbols were used in the bounds.
NB, I don't use multiple variadic operands, because apparently MLIR doesn't use the segment sizes either for this operation :thinking: so I'm repeating a bit of IRDL work.
=> dialects: Correct affine.for verifier.

tests/filecheck/dialects/memref/memref_ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_custom.mlir, xdsl/dialects/memref.py
Mirror `memref.alloca_scope` and `memref.alloca_scope.return` from MLIR.
=> dialects: Implement memref.alloca_scope and memref.alloca_scope.return.

tests/dialects/test_hw.py, xdsl/dialects/hw.py
InnerSymTarget is a utility class that is used to store the targets of inner symbols. It is not usable as part of the dialect, but will be used by classes in `HW`. I’m not sure if there’s much more to test about it -- it’s really just there to keep a reference to an operation with some additional metadata.
Standalone PR in an effort to keep them small and reviewable -- see #1704 for context.
=> dialects: (hw) Add InnerSymTarget class to HW dialect

pyproject.toml
I accidentally enabled `flake8` on my computer today, to find that we're in violation of some of the rules. We don't actually specify it as a dependency, and my understanding is that ruff is now the source of truth wrt formatting, so we might as well get rid of these lines of spec.
=> misc: remove flake8 config

tests/dialects/test_memref.py, tests/filecheck/dialects/memref/memref_ops.mlir, xdsl/dialects/memref.py
This PR adds the `memref.memory_space_cast` op to the `memref` dialect.
We intend to use this to properly handle `memref` transfers between the different memory spaces in a snitch cluster.
=> dialects: Add memref.memory_space_cast

tests/dialects/test_memref.py, tests/filecheck/dialects/memref/memref_ops.mlir, xdsl/dialects/memref.py
This PR adds support for memref layout and memory space attributes in the memref.alloc and memref.alloca operations
@JosseVanDelm
=> dialects: (memref) add layout and memory space support in memref.alloc(a)

tests/filecheck/version.mlir, xdsl/xdsl_opt_main.py
Adds a `--version` flag to xdsl-opt displaying the package version. Helpful for debugging which xdsl-opt is used in any given environment.
=> misc: Add a version flag to xdsl

Makefile
This PR:
- Uses a better message in the `make` target for all tests when they succeed.
Super minor but it started becoming irksome (to me).
=> misc: (Makefile) Use a better message for `tests` target

tests/filecheck/backend/riscv/register_allocation_exclude_snitch.mlir, xdsl/backend/riscv/register_allocation.py, xdsl/transforms/riscv_register_allocation.py, xdsl/transforms/snitch_register_allocation.py
This PR adds:
- Exclusion of FP registers (currently `ft0-ft2`) from RISC-V register allocation in the presence of `snitch_stream` IO ops (`strided_read` and `strided_write`).
- Tests of the above functionality.
Resolves https://github.com/opencompl/riscv-paper-experiments/issues/63
=> backend: (riscv) Exclude FP registers from RISC-V regalloc in the presence of `snitch_stream` IO ops

tests/test_operation_definition.py, xdsl/utils/hints.py
This allows Operation classes to inherit from multiple classes, when one of the classes is a generic.
Before that, this was not allowed.
=> core: Allow multiple inheritance when one parent is generic

tests/dialects/test_llvm.py, tests/filecheck/dialects/llvm/arithmetic.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/arithmetic.mlir, xdsl/dialects/llvm.py
This PR adds multiple LLVM integer binary operations, along with their custom syntax.
=> dialects: Add binary arithmetic llvm operations

tests/dialects/test_dmp.py, xdsl/dialects/experimental/dmp.py, xdsl/transforms/experimental/dmp/decompositions.py, xdsl/transforms/experimental/dmp/stencil_global_to_local.py
This adds a `GridSlice3d` decomposition, that used the `_flat_face_exchanges_for_dim(shape, dim)` helper.
This helper generates the exchange declarations for the two opposite flat faces in dim `dim` of any n-dimensional hypercube (n>1 I think?).
I wrote some tests for the `_flat_face_exchanges_for_dim` method, but no filechecks as of yet (they will follow). I would invite @mesham and @mcjamieson to be a second and third brain + pair of eyes, as I am not entirely sure I got everything right yet. [The test](https://github.com/xdslproject/xdsl/pull/1672/files#diff-fbe221f08ca78dc534bcc61aae61ffe1c7f1d88dec29fd56316245dae9976d66) is probably a good point to look at the result, and then you can dive into the code from there. Feel free to drop by my office too, I have some diagrams to support …
=> transforms: (dmp) Add a 3D domain decomposition (with n-d generalization)

tests/filecheck/mlir-conversion/with-mlir/scope.mlir, tests/filecheck/parser-printer/scope.mlir, tests/test_ir.py, xdsl/ir/core.py, xdsl/parser/base_parser.py, xdsl/parser/core.py
Only parsing, no printing. This unlocks us being able to parse MLIR IR directly output from the `mlir-opt` command, without generic syntax or "local scope". I needed this to unlock our experiments for the linalg to frep project, since we use MLIR as the input, and our version of MLIR had different names for some properties, which messed up the generic syntax. I think that the main xdsl project would benefit from these changes also.
In my understanding, this is more permissive than MLIR itself, that has specific rules for which ops can drop names and which ones cannot. I'm not sure whether we want to be as strict as them on this.
=> core: add ability to parse MLIR IR that drops dialect names from operations

tests/test_parse_spec_format.py, tests/test_pass_lexer.py, xdsl/passes.py, xdsl/utils/parse_pipeline.py
Added a function that takes a pipelinepasspsec and returns its string version. this helps with being able to print out directly what should be used in the terminal (after the xdsl-opt command)
=> interactive: adding function that takes a pipelinepasspsec and returns its strings+ tests 

tests/filecheck/dialects/gpu/ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/ops.mlir, tests/filecheck/transforms/gpu-map-parallel-loops.mlir, xdsl/dialects/gpu.py, xdsl/ir/core.py, xdsl/tools/command_line_tool.py, xdsl/transforms/gpu_map_parallel_loops.py
Implement `gpu-map-parallel-loops`, and the corresponding attribute `gpu.loop_dim_map`.
Dimension wise, this is doing the reverse of MLIR's `gpu-map-parallel-loops`, as per their own [TODO](https://github.com/llvm/llvm-project/blob/9930f3e2982cd590b75f1252ea5253e53401b605/mlir/lib/Dialect/GPU/Transforms/ParallelLoopMapper.cpp#L70), which maps `scf.parallel`'s faster varying iterator to `gpu.launch` innermost dimension, to have performing codegen for both GPU and CPU cases without specializing the `scf.parallel`. 
Tests are exactly the ones from MLIR, with the said mapped dimensions swapped.
=> transforms: implement gpu-map-parallel-loops

tests/dialects/test_memref.py, tests/filecheck/dialects/memref/memref_ops.mlir, xdsl/dialects/memref.py
This PR adds support for dynamic dimensions to the `memref.alloc` and `memref.alloca` operations.
The operands of the `alloc` operation (`%d` of type `index`) indicate the size of the dynamic dimension in the result:
```mlir
%0 = memref.alloc(%d) : memref<8x?xf32, 1>
```
There is also a verify method to check if the amount of operands is equal to the amount of dynamic dimensions in the memref.
Additionally, I also aligned the implementation of `alloc` and `alloca` to be identical.
@JosseVanDelm
=> dialects: (memref) add alloc(a) dynamic dimension support

xdsl/passes.py, xdsl/utils/parse_pipeline.py
The `from_pass_spec()` function in passes.py is used in my interactive app. Unfortunately, the way it is implemented is that it mutates the PassPipelineSpec and empties out its arguments dictionary. This causes some drama as I still need to reuse the spec in my app, and do not want the arguments to be altered/mutated.
After discussions with @superlopuh , we originally had the idea of altering the below code: 
```
@dataclass(eq=True, frozen=True)
class PipelinePassSpec:
"""
A pass name and its arguments.
"""
name: str
args: dict[str, PassArgListType]
```
and instead replacing `args` with:
`args: tuple(tuple(str,PassArgListType))`
This will come in a future PR or issue, tbd.
And so, for now, I have changed the normalize_arg_names() to return a new `PassPipelineSpec` altogether in order to …
=> interactive: change normalize_arg_names() in parse_pipeleline.py to return a tuple instead of dict

docs/Toy/toy/tests/test_lower_memref_riscv.py, tests/filecheck/backend/riscv/memref_to_riscv.mlir, xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
We only handled 1d and 2d now we handle arbitrary ranks of memrefs with known dimensions.
@xdslproject/risc-v-backend
=> backend: (riscv) support any memref shape for access lowering

tests/backend/riscv/test_register_queue.py, xdsl/backend/riscv/register_allocation.py, xdsl/backend/riscv/register_queue.py
Turns out there's a bug with our handling of iteration arguments in the register allocator. This is PR 1/2 to fix this issue (I'll open the other ones in order to avoid stacking), it just abstracts reserving and unreserving registers in the register queue class.
@xdslproject/risc-v-backend
=> backend: (riscv) add mechansim to reserve and unreserve registers

tests/interactive/test_app.py, xdsl/utils/exceptions.py
Hey, I'm trying to have fun with MLIROptPass as part of our Python DSL integration.
Sadly, when chaining a ParserError (such as when MLIROptPass fails because xDSL can't parse back MLIR's output), it looks like this:
```
>       raise ParseError(at_position, msg)
E       xdsl.utils.exceptions.ParseError: (Span[1151:1154](text='ptr'), 'type expected')
```
Which isn't very helpful.
This PR offers to force it to display nicely in this case too, yielding instead:
```
raise ParseError(at_position, msg)
xdsl.utils.exceptions.ParseError: <unknown>:23:52
%19 = "llvm.mlir.undef"() : () -> !llvm.struct<(ptr, ptr, i64, array<3 x i64>, array<3 x i64>)>
^^^
type expected
```
Which is more actionnable.
I'm not sure overriding `__str__` is the only nor the best solution though. WDYT?
=> core: correct `__str__`/`__repr__` usage in ParseError

xdsl/dialects/llvm.py
Before it all makes sense in MLIR someday, here's a small improvement on `llvm` types parsing from xDSL!
We had some special cases scattered over the place, I just refactored it in top-level functions.
Then, I implement the `array<>` special case too.
=> dialects: Refactor and improve llvm type parsing.

tests/filecheck/dialects/llvm/example.mlir, xdsl/dialects/llvm.py
Mh, we're lacking MLIR interop tests I guess :thinking:
=> dialects: switch llvm to properties.

xdsl/dialects/builtin.py
Pyright and Pylance are out of sync for some reason, this small refactoring seems to fix things.
=> misc: make VSCode Pylance happy with int type

xdsl/irdl/irdl.py
This makes it hashable, so able to be inserted into a set or used as a key in a dictionary. The class is already designed to be immutable, and we need this change for the frep lowering.
=> core: make ConstraintVar frozen

docs/Toy/toy/dialects/toy.py, docs/Toy/toy/frontend/ir_gen.py, docs/Toy/toy/rewrites/lower_toy_affine.py, docs/Toy/toy/tests/test_ir_gen.py, docs/Toy/toy/tests/test_lower_memref_riscv.py, docs/irdl.ipynb, docs/tutorial.ipynb, tests/backend/riscv/test_utils.py, tests/dialects/test_builtin.py, tests/dialects/test_gpu.py, tests/dialects/test_memref.py, tests/dialects/test_stencil.py, tests/dialects/test_vector.py, tests/interpreters/test_affine_interpreter.py, tests/interpreters/test_linalg_interpreter.py, tests/interpreters/test_memref_interpreter.py, tests/interpreters/test_wgsl_printer.py, xdsl/dialects/builtin.py, xdsl/dialects/gpu.py, xdsl/dialects/memref.py, xdsl/dialects/vector.py, xdsl/interpreters/experimental/wgpu.py, xdsl/parser/attribute_parser.py, xdsl/printer.py, xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py, xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py, xdsl/transforms/lower_mpi.py, xdsl/transforms/printf_to_llvm.py
We currently use `IntegerAttr` for shapes in vector, tensor, and memref types.
They were also inconsistent, since some of them allowed index types, while other did not.
In MLIR, these dimensions are not typed anyway, so that makes sense.
I also removed the "get" constructors in favor of a single `__init__` one. It is not possible to deprecate
these constructors, as their type changed anyway.
=> dialects: Use IntAttr in Vector/Tensor/MemRef types

tests/dialects/test_arith.py, tests/filecheck/dialects/arith/arith_ops.mlir, tests/filecheck/dialects/arith/arith_ops_custom.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/arith/arith_ops_custom.mlir, xdsl/dialects/arith.py
Add `arith.addui_extended` operation.
It works like `arith.addi`, but returns a flag that indicates if the addition overflowed.
=> dialects (arith): Add arith.addui_extended operation

xdsl/transforms/constant_fold_interp.py
I often uninstall wgpu to make my tests run faster, since there's a very small chance of me breaking it with my work. Turns out that if you don't have it installed then the new constant folding using the interpreter messes with some tests. This PR removes this weird behaviour.
=> interpreter: don't use wgpu interpreter functions for constant folding

tests/filecheck/projects/riscv-backend-paper/ddot_regalloc.mlir, xdsl/backend/riscv/register_allocation.py
The iteration arguments live in registers that currently are not protected from being clobbered by the register allocator. This PR fixes this by reserving them form being reused inside the body, by using the newly introduced reserve/unreserve mechanism.
=> backend: (riscv) reserve iter arg from allocation inside of riscv_scf body

tests/filecheck/dialects/llvm/pointers.mlir, xdsl/dialects/llvm.py
Another small and retro-compatible update to parse some MLIR output.
=> dialects: (llvm) Make llvm.alloca's alignment property optional

.github/workflows/pythonpublish.yml
User should be `__token__` instead of `api` for api keys.
=> CI: Fix user name for api key

docs/Toy/toy/frontend/ir_gen.py, docs/Toy/toy/rewrites/lower_toy_affine.py, tests/test_op_builder.py, xdsl/builder.py, xdsl/dialects/irdl/pyrdl_to_irdl.py
The constructors for `Builder` and `InsertPoint` were too ambiguous, so they are removed in favor of named constructors `at_begin`, `at_end`, `before` and `after`.
Some naming changed as well in `InsertPoint`, and documentation improved.
This should hopefully make the code more readable
=> core: Add constructors to `Builder` and `InsertPoint`

tests/test_op_builder.py, xdsl/builder.py
Add methods to create blocks with the builder.
These methods create a block, place it in the IR, and put the insertion point in it.
I'm not a fan that the insertion point is moved, but that's what MLIR does so I'd rather follow them.
The reason why these methods are in the builder is so that they can be "listened" to.
=> core: Add methods to create blocks with the builder

tests/test_op_builder.py, xdsl/builder.py
These callbacks are called whenever an operation or block is created and inserted.
They are used in the pattern matching engine to keep the worklist updated.
=> core: Add callbacks to the `Builder`

xdsl/parser/attribute_parser.py
This PR fixes a very small mistake in the docstring of the attribute parser.
The code parses a `#` symbol (which is correct), while the docstring mentions `!`
=> fix attribute docstring

tests/filecheck/dialects/pdl/verifiers.mlir, xdsl/dialects/pdl.py
Add missing patterns to `pdl.pattern`, and add tests for it.
I also realized that I merged the last PDL PR without addressing one review about the `split-input-file` tests, really sorry for that. This PR is fixing it at the same time (it's just 5-6 line changes)
=> dialects (pdl): Add better verifiers to `pdl.pattern`

tests/test_ir.py, xdsl/ir/core.py
This PR allows to change the traversal order of `walk` through the `region_first` option and `reverse` option.
* `reverse` will reverse the order of traversal of blocks, regions, and operation lists.
* `region_first` will make the traversal first traverse the regions, then the current operation. 
This also deprecates `walk_reverse`, which should be replaced by `walk(region_first=True, reverse=True)`.
This is stack on top of an unrelated PR because GitHub doesn't allow me to stack a PR on top of two unrelated PRs (which I'll do on the next PR).
=> core: Add options to `walk` to control traversal order

tests/pattern_rewriter/test_pattern_rewriter.py, xdsl/builder.py, xdsl/pattern_rewriter.py
This PR adds the `Listener` class in `PatternRewriter`.
The plan is to use the `Listener` class to implement the walker with a worklist, where each callback will add the operations to the worklist (in the next PR).
=> core: Add listener in PatternRewriter

tests/filecheck/dialects/onnx/onnx_invalid.mlir, tests/filecheck/dialects/onnx/onnx_ops.mlir, xdsl/dialects/onnx.py, xdsl/tools/command_line_tool.py
onnx dialect initial support, as discussed on zulip. 
* Add elementwise binary operations, `onnx.Add`, `onnx.Sub`, `onnx.Mul`, `onnx.Div` (see [doc](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Add) for add semantics; the others are equivalent). 
* Add verification of broadcastable arguments
* Add lit tests
Resolves #1894
=> dialects (onnx): Initial onnx dialect support

tests/test_ir.py, xdsl/ir/core.py
This is useful for things like scf to cf rewriting.
=> core: add method for splitting block before a given operation

tests/test_printer.py, xdsl/printer.py
Seems like it pops up a few times for custom syntax, I'd like to use this helper for the `scf` and `riscv_scf` `while` custom syntaxes.
=> core: add helper for function type printing

tests/filecheck/dialects/riscv_cf/assembly_emission.mlir, tests/filecheck/dialects/riscv_cf/ops.mlir, tests/filecheck/dialects/riscv_cf/verification.mlir, tests/pattern_rewriter/test_pattern_rewriter.py, tests/test_rewriter.py, xdsl/dialects/riscv_cf.py, xdsl/pattern_rewriter.py, xdsl/rewriter.py, xdsl/tools/command_line_tool.py
This adds the riscv_cf dialect, duplicating some instructions in the riscv dialect, but with dataflow semantics with successors etc. This lets us reason about dataflow using xDSL IR constructs, and is a step towards being able to interpret exactly the same IR that we use to print assembly.
I forgot to add two things, will do them tomorrow:
=> dialects: (riscv_cf) add riscv_cf dialect

tests/filecheck/dialects/onnx/onnx_invalid.mlir, xdsl/dialects/onnx.py
Two small nits highligthed by VSCode that I missed in my review:
- FloatAttr and IntegerAttr are generic, and Pylance isn't happy when the generic parameter is not specified. AnyFloatAttr and AnyIntegerAttr is probably what we want if we want to allow any bitwidth in the types. Pylance is the version of Pyright built into VSCode, not sure why it disagrees with the one we have in the CI.
- There was dead code after the `assert False`, not sure why Pyright didn't bring this up in the CI either, but we should test for it also.
=> dialects: (onnx) lint onnx.py

tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir, tests/filecheck/dialects/riscv_snitch/ops.mlir, xdsl/dialects/riscv_snitch.py
These ops are useful for the lowest level representation of the compiled operations, they are not printed in the assembly, but help us with leverage SSA dataflow.
=> dialects: (riscv_snitch) add get_stream, read, write ops

docs/Toy/toy/rewrites/lower_toy_affine.py, tests/dialects/test_affine.py, tests/filecheck/dialects/affine/affine_ops.mlir, tests/filecheck/dialects/affine/examples.mlir, tests/filecheck/frontend/dialects/affine.py, tests/filecheck/mlir-conversion/with-mlir/dialects/affine/affine_ops.mlir, tests/filecheck/transforms/lower_affine.mlir, tests/interpreters/test_affine_interpreter.py, tests/test_frontend_op_inserter.py, xdsl/dialects/affine.py, xdsl/frontend/code_generation.py, xdsl/interpreters/affine.py, xdsl/transforms/lower_affine.py
Refresh affine:
- `affine.for`:
- Rename (lower|upper)_bound -> (lower|upper)BoundMap
- Split variadics arguments in 3 variadic arguments :tada: 
- `affine.if`:
For some reason `affine.if`'s condition is not a property.
Add interoperability test.
=> dialects: Refresh Affine, add interoperability test.

tests/dialects/test_memref.py, tests/filecheck/dialects/memref/invalid_ops.mlir, tests/filecheck/dialects/memref/memref_ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_mlir_conversion.mlir, tests/utils/test_bitwise_casts.py, xdsl/dialects/memref.py, xdsl/utils/bitwise_casts.py
Hi!
I was trying to parse a compiled neural network from tensorflow when I hit a memref.global op that did not have an alignment property/attribute (?) defined.
```
^^^^^^^^^^^^^^^-----------------------------------------------------------------------------------------------------------------------------------------------
| Operation does not verify: property 'alignment' is not defined by the operation. Use the dictionary attribute to add arbitrary information to the operation.
--------------------------------------------------------------------------------------------------------------------------------------------------------------
```
According to:
https://mlir.llvm.org/docs/Dialects/MemRef/#memrefglobal-memrefglobalop
This is supposed to be a i64 value that has to be a power of two.
=> dialects: Add optional alignment property to memref.global

tests/filecheck/parser-printer/aliases.mlir, xdsl/parser/attribute_parser.py, xdsl/parser/core.py
This adds support for aliases in the textual format.
Aliases are defined with the format `alias-name = attribute`, and have to be defined at the top-level.
For example:
```
!ii32 = i32
#attr = 0 : !ii32
"test.op"() {"attr" = 1 : !ii32} : () -> ()
"test.op"() {"attr" = !ii32} : () -> ()
"test.op"() {"attr" = vector<1x!ii32>} : () -> ()
"test.op"() {"attr" = #attr} : () -> ()
"test.op"() {"attr" = [#attr]} : () -> ()
```
=> core: Add parsing of aliases

tests/filecheck/dialects/memref/memref_ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_mlir_conversion.mlir, xdsl/dialects/memref.py
Adds an optional "constant" unit attribute to the memref global, which is emitted by upstream MLIR, but not yet parsed by xDSL :(
=> dialects: Add constant unitattr to global

tests/filecheck/dialects/func/func_ops_generic.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/func/func_ops_generic.mlir, xdsl/dialects/func.py
This is also part of my crusade to get some tflite models to be parseable by xDSL:
Adds an optional result arguments dictionary attribute to func.func.
This PR does not add parsing/printing support yet in its current form, could someone help me with that please!
Thanks!
=> dialects: Add result arguments to func.func

docs/Toy/toy/rewrites/setup_riscv_pass.py, tests/pattern_rewriter/test_pattern_rewriter.py, xdsl/pattern_rewriter.py
Use a worklist for pattern rewriting.
This means that every time an operation is modified, inserted, removed, the worklist gets updated, and only the operations in the worklist are rewritten.
This will allow us to remove restriction in our pattern matches, such that only operations right before, after, or nested in the matched operation can be rewritten.
These restrictions will be removed later on.
=> core: use worklist in pattern matching algorithm

xdsl/pattern_rewriter.py
Now that the pattern rewriter use the worklist, it is not necessary to keep track of the inserted operations before/after
the matched operation.
We can thus remove all these checks.
=> core: Simplify the pattern rewriter

tests/test_declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/irdl.py, xdsl/parser/core.py
This is MLIR's behaviour. Probably only when there is no specified prop-dict in the format, but on the current commit, this prop-dict is only used in their tests, so I'm not rushing implementation :)
Some secondary changes:
- Factor out the property retro-compatibility from the core Parser to OpDef
- Don't forbid Operations with defined attributes. Why was it forbidden? @math-fehr They are already usable through the attr-dict, simply not in directives, am I missing something?
=> core: Make assembly format use attr-dict for properties

tests/test_declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py, xdsl/irdl/irdl.py
This PR allows us to infer the types of some operands and results from the types of other operands and results.
It does so by adding three functions in `AttrConstraint`:
* `get_resolved_variables`: This function returns the set of `ConstraintVar` that will be set during verification.
* `can_infer`: Returns `True` if we can infer a unique attribute represented by the `AttrConstraint` from the assignment of `ConstraintVar`.
* `infer`: Returns the only attribute that satisfy this constraint, given the constraint variables.
We use these methods to get all `ConstraintVar`  from the parsed operand/result types present in the syntax, then infer the constraints on the types that are not in the syntax.
=> core: Add support for nested inferrence in IRDL

tests/filecheck/transforms/arith-add-fastmath.mlir, xdsl/tools/command_line_tool.py, xdsl/transforms/arith_add_fastmath.py
This PR:
- Adds a rewrite pass to set the `fastmath` flags of FP binary `arith` operations.
- Tests of the above.
Resolves #2017
=> Add pass to set `fastmath` flags of FP binary operations from `arith`

docs/Toy/Toy_Ch0.ipynb
Now that Toy lowers to print_format, we can compile it to LLVM, leveraging the printf flow added in #1142 .
=> documentation: (Toy) add instruction on how to jit Toy using lli

tests/dialects/test_builtin.py, tests/dialects/test_memref.py, tests/dialects/test_stencil.py, tests/dialects/test_vector.py, tests/interpreters/test_linalg_interpreter.py, xdsl/dialects/mpi.py, xdsl/dialects/vector.py, xdsl/interpreters/experimental/wgsl_printer.py, xdsl/parser/attribute_parser.py, xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py, xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py, xdsl/transforms/lower_mpi.py
Following up on #1997, I forgot to switch all imports!
=> dialects: Import MemRefType from builtin.

tests/dialects/test_linalg.py, tests/test_affine_builtins.py, xdsl/dialects/linalg.py, xdsl/ir/affine/affine_map.py
Currently, loop bounds are not computed correctly for linalg.generic lowering
=> bug: fix AffineMap.inverse_permutation

tests/filecheck/dialects/riscv_scf/ops.mlir, xdsl/dialects/riscv_scf.py
Adds the `riscv_scf.rof` (reverse order for) operation.
MLIRs for loops have the implicit constraint that `lb < ub`, and `step > 0`.
In order to express loops that count down in higher-level IR, the rof op
is needed.
ROF has the semantics of going from ub to lb, decrementing by step each time.
In order to convert a for to a rof, one needs to switch lb and ub.
(for the normalized case that `(ub - lb) % step == 0`)
=> dialects: (riscv_scv) Add reverse order for (rof) op

tests/dialects/test_riscv.py, tests/filecheck/backend/riscv/convert_arith_to_riscv.mlir, tests/filecheck/dialects/riscv/riscv_ops.mlir, tests/filecheck/dialects/riscv_snitch/ops.mlir, tests/filecheck/dialects/snitch_stream/ops.mlir, xdsl/backend/riscv/lowering/convert_arith_to_riscv.py, xdsl/dialects/riscv.py
This PR:
- Adds `fastmath` flags to the single- and double-precision variants of `fsub`, `fadd`, `fmul` and `fdiv`.
- Modifies filechecks for the above
In a follow-up patch, we plan to use these flags to enable contraction (fusion) between ops via canonicalization.
This will allow our backend to follow the same conventions as other compilers when producing fused ops (i.e., `fmadd`, etc).
Related to: https://github.com/opencompl/riscv-paper-experiments/issues/137
=> Add fastmath flags to riscv dialect

tests/filecheck/dialects/memref/invalid_ops.mlir, tests/filecheck/dialects/memref/memref_ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_custom.mlir, xdsl/dialects/memref.py
Simple PR to add support for:
* https://mlir.llvm.org/docs/Dialects/MemRef/#memrefexpand_shape-memrefexpandshapeop
* https://mlir.llvm.org/docs/Dialects/MemRef/#memrefcollapse_shape-memrefcollapseshapeop
Note that these two ops have quite a bit of verification happening in upstream, which this PR does not implement.
=> dialects: Add memref.expand_shape and memref.collapse_shape ops

tests/pattern_rewriter/test_pattern_rewriter.py, tests/test_rewriter.py, xdsl/pattern_rewriter.py, xdsl/rewriter.py
Slightly modifies the semantics of inlining, bringing it in line with MLIR's behaviour, in my understanding. Currently, xDSL empties the block when inlining it to a different block, but does not erase it. With this PR, this behaviour is changed to erasing the block, potentially leaving an empty region.
=> core: add replacement arg_values to inline_block_before

tests/filecheck/projects/riscv-backend-paper/conv_target.mlir, tests/filecheck/projects/riscv-backend-paper/ddot_target.mlir, tests/filecheck/projects/riscv-backend-paper/dense_target.mlir, tests/filecheck/projects/riscv-backend-paper/dsum_target.mlir, tests/filecheck/projects/riscv-backend-paper/fill_target.mlir, tests/filecheck/projects/riscv-backend-paper/matmul_target.mlir, tests/filecheck/projects/riscv-backend-paper/max_pool_target.mlir, tests/filecheck/projects/riscv-backend-paper/relu_target.mlir, tests/filecheck/projects/riscv-backend-paper/sum_pool_target.mlir, xdsl/tools/command_line_tool.py, xdsl/transforms/test_lower_linalg_to_snitch.py
The idea is to grow the compiler to snitch_stream bottom-up, meaning that the target output is fixed, and the input rises in abstraction level over time. This PR introduces both the kernels for which we know exactly what the assembly should be, and a test pass that fixes our compilation pipeline, currently copied from the Makefile.rules in the other repo
=> testing: add kernels from our paper with verified assembly

tests/filecheck/dialects/onnx/onnx_ops.mlir, xdsl/dialects/onnx.py
=> dialects: (onnx) add onnx.EntryPoint

tests/filecheck/dialects/riscv_cf/ops.mlir, xdsl/dialects/riscv_cf.py
This PR:
- Allows float register types for block argument types
- Filecheck test of the above
=> dialects (riscv_cf): Allow float register types for block argument types

tests/test_printer.py, xdsl/printer.py, xdsl/xdsl_opt_main.py
I heard multiple struggles with flows working with MLIR versions predating properties.
xDSL implemented the same retro-compatibility as MLIR, that is, parsing operations with no properties and hoisting defined properties, allowing to take input predating properties.
This PR offers to add *printing* retro-compatibility: Printing all properties in the output attribute dictionary, allowing MLIR tools predating properties to parse this output.
From recent discussions, I guess @math-fehr might want to make the property/attribute name clash an error?
=> core: Implement Printer property retrocompatibility.

tests/filecheck/dialects/linalg/linalg_ops.mlir, xdsl/dialects/linalg.py
This PR includes the optional attributes `doc` and `library_call` to the custom printer and parser of `linalg.generic` ops.
=> dialects: (linalg) add custom printer and parser support for doc and library call

tests/test_attribute_definition.py, tests/test_op_builder.py, xdsl/dialects/builtin.py, xdsl/utils/comparisons.py
Also uses same calculation for the interpreter helpers and the integer attr verifier.
=> dialects: (builtin) fix ranges for integers

.vscode/launch.json
VSCode started telling me that "python" is deprecated, I followed it's advice to replace with "debugpy".
=> testing: switch to debugpy in vscode launch config

tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir, xdsl/dialects/linalg.py
resolves #2115, where no argument is present for results type. 
Note: Parsing code for the result is also added in this PR
=> dialects / bug : (linalg) linalg.generic constructor does not have a result types argument

tests/frontend/onnx/test_elem_type.py, xdsl/frontend/onnx/elem_type.py
PR about re-arrange get elem type @superlopuh
=> frontend: (onnx) re-arrange elem type

tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir, xdsl/dialects/linalg.py
=> dialects: (linalg) add linalg.add

tests/test_declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py
We can either use the python or the irdl name in the custom assembly format, it make sense to me to stick to the IRDL name of things to be portable. Not sure if there's an aspect that I'm missing here.
=> core: add custom attr and prop name support to assembly format

.github/workflows/ci-mlir.yml, pyproject.toml, tests/frontend/onnx/test_tensor_type.py, xdsl/frontend/onnx/shape_type.py
Also adds onnx as an optional dependency, that doesn't get installed by default even with `-r requirements.txt`, and adds a unit test that gets skipped if onnx is not installed.
=> frontend: (onnx) add get_shape and get_tensor_type

xdsl/interactive/app.py
Changed input text to be an example where you can see an example of rewrite on gui launch. A canonicalizaiton pattern for Add Immediate Zero was pushed, and thats why this example will show a rewrite and the other one did not (no rewrite defined yet). Still need to add more rewrite patterns --> next PR's.
=> interactive: change input text so you can see example of a rewrite on gui launch 

tests/interpreters/test_snitch_stream_interpreter.py, xdsl/dialects/snitch_stream.py, xdsl/interpreters/snitch_stream.py
This PR brings the documentation and interpreter implementation of snitch_stream stride patterns in line with the snitch_stream lowering to snitch.
This is a PR with only a functional change in the interpreter, but with consequences on upcoming lowerings from memref_stream to snitch_stream. When I first added snitch_stream and the corresponding interpreter functions, I was under the impression that the snrt functions took bounds and strides from the outermost loop inwards, but it's the reverse. The distinction is now somewhat arbitrary, since we are planning to link to snrt any more, and could actually implement the lowering from snitch_stream to snitch with the inverse order of bounds. I think that we should stick to the current order of bounds, implement the complete lowering first, and …
=> dialects: (snitch_stream) reverse bounds and strides in snitch_stream

xdsl/dialects/llvm.py
Fixes use of attributes dict when dialect specifies prop_def for:
llvm.extractvalue
llvm.insertvalue
Seems like a bug left over from #1874
=> dialects: (LLVM) Fix use of attributes dict when dialect specifies prop_def

tests/filecheck/dialects/snitch_stream/convert_snitch_stream_to_snitch.mlir, tests/filecheck/dialects/snitch_stream/ops.mlir, tests/filecheck/projects/riscv-backend-paper/add_snitch_stream.mlir, tests/filecheck/projects/riscv-backend-paper/conv_target.mlir, tests/filecheck/projects/riscv-backend-paper/ddot_target.mlir, tests/filecheck/projects/riscv-backend-paper/dense_target.mlir, tests/filecheck/projects/riscv-backend-paper/dsum_target.mlir, tests/filecheck/projects/riscv-backend-paper/fill_target.mlir, tests/filecheck/projects/riscv-backend-paper/matmul_target.mlir, tests/filecheck/projects/riscv-backend-paper/max_pool_target.mlir, tests/filecheck/projects/riscv-backend-paper/relu_snitch_stream.mlir, tests/filecheck/projects/riscv-backend-paper/relu_target.mlir, tests/filecheck/projects/riscv-backend-paper/sum_pool_target.mlir, tests/filecheck/transforms/snitch_register_allocation.mlir, tests/interpreters/test_snitch_stream_interpreter.py, xdsl/backend/riscv/lowering/convert_snitch_stream_to_snitch.py, xdsl/dialects/snitch_stream.py, xdsl/interpreters/snitch_stream.py
PR 4/4 of replacing the snitch_stream.stride_pattern op with an attribute
The operation is removed, and the stride pattern is specified as an attribute on the streaming region op. When lowering the streaming region, the dm is inferred.
Note that the assembly that is returned by our lowering is entirely unchanged after this refactor.
=> dialects: (snitch_stream) replace stride pattern op with attribute

tests/interactive/test_app.py, xdsl/interactive/app.py, xdsl/interactive/get_condensed_passes.py
attempt to split t[his PR](https://github.com/xdslproject/xdsl/pull/2131/files#diff-6c0fd122274ca87c3f88d46a4abe86a2d09289633359f7c9830925aeb2137178L56) into smaller ones. 
PR 1 
1. Move "get_condensed_pass_list" and ALL_PASS variable to a separate file to reduce code in app.py
2. Introduce "AvailablePass" Named Tuple + adjust the function types/tests affected by this change.
=> interactive: add AvailablePass NamedTuple and move code to new file for cleanliness 1/3

tests/filecheck/backend/riscv/convert_func_to_riscv_func.mlir, xdsl/backend/riscv/lowering/convert_func_to_riscv_func.py, xdsl/backend/riscv/lowering/convert_scf_to_riscv_scf.py, xdsl/backend/riscv/lowering/utils.py
We currently incorrectly insert fmv.s when moving float registers, even when the actual value stored is f64. This is usually at the boundary between the standard and riscv dimensions, where the combination of casting to a register type and moving to/from an "a" register loses the relevant type information. This PR amends some helpers in the riscv backend to take into account the floating-point type of the operand when moving floating point values.
=> backend: (riscv) correctly handle f64 moves when lowering

tests/filecheck/mlir-conversion/with-mlir/mlir_opt.mlir, xdsl/transforms/mlir_opt.py
Phew this one got me running in circles!
Had a case where using our `mlir-opt` pass was arong, because it currently just discards any attributes on the parsed top-level module.
=> transformations: Make mlir-opt pass take the top-level module attributes into account.

tests/filecheck/backend/rvscf_scf_lowering.mlir, xdsl/backend/riscv/lowering/convert_scf_to_riscv_scf.py
I accidentally used the new register types, as opposed to the old fp types, which prevents us from picking the correct move instruction, I added this to the lowering test.
=> backend: (riscv) fix scf to riscv scf lowering

xdsl/interpreters/ptr.py, xdsl/interpreters/riscv.py
These helpers aren't useful only for the riscv-based interpreter function implementations, they might as well live in their own file
=> interpreter: move RawPtr and TypedPtr to own file

tests/filecheck/mlir-conversion/with-mlir/mlir_opt.mlir, xdsl/transforms/mlir_opt.py
Fixes #2120
I'm not sure how to test this, we need to somehow intercept that the syntax passed to mlir-opt is in a certain format, but we pass it along directly... I think just testing that it works with true, false, and nothing is enough for now.
=> transformations: add "generic" parameter to MLIROptPass

tests/dialects/test_hw.py, xdsl/dialects/hw.py
This is another standalone part of #1704 (which you can refer to for broader context). It introduces 2 main classes, `InnerSymbolTable` and `InnerRefNamespace` (which are too interconnected to add separately), as well as 2 smaller (and similarly intricated) `InnerSymbolTableCollection` and `InnerRefUserOpInterface`.
Note that I’ve tried reducing as much as I could but this is as small as I can make this contribution (~150 loc / 4 classes + tests).
The PR introduces a verification step, called `verifyInnerRefs`:
- I think the most explicit description is from the [Symbol and Inner Symbol Rationale document](https://circt.llvm.org/docs/RationaleSymbols/#innerrefnamespace):
> **InnerRefNamespace**
> 
> [As class:] Combines InnerSymbolTableCollection with a SymbolTable for resolution of …
=> dialects: (hw) Add InnerSymbolTable and InnerRefNamespace to HW dialect

tests/filecheck/transforms/scf-parallel-loop-tiling-partial.mlir, xdsl/transforms/scf_parallel_loop_tiling.py
- If we figure out there's nothing to tile, bail out.
- Drop extra tile sizes if we're tiling a lower-dimensional loop nest.
=> transformations: scf-parallel-loop-tiling fixes.

tests/filecheck/dialects/llvm/inline_asm.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/inline_asm.mlir, xdsl/dialects/llvm.py
This PR attempts to add the LLVM InlineAsm op, which allows to bake in inline assembly from within MLIR.
Some things I noted while making this:
* The docs mention this:
> The InlineAsmOp mirrors the underlying LLVM semantics with a notable exception: the embedded asm_string is not    allowed to define or reference any symbol or any global variable: only the operands of the op may be read, written, or    referenced. Attempting to define or reference any symbol or any global behavior is considered undefined behavior at    this time.
I'm assuming this means that this constraint is never actually checked/verified :sweat_smile: ?
* There's an additional attribute to select the inline assembly dialect (not dialect in context of MLIR, choices are AT&T or Intel). I just implemented this as an …
=> dialects: Add LLVM InlineAsm op

tests/utils/test_hashable_module.py, tests/utils/test_hasher.py, xdsl/utils/hashable_module.py, xdsl/utils/hasher.py
These utils are planned to be used in `xdsl-gui`, but may well be useful outside of that project. The Hasher contains logic I've used a lot before, it seems to work well enough. In the future, we might want a more efficient way to compute equality/inequality for modules, but we might as well add a working helper class now and optimise later.
=> core: add Hasher and HashableModule

xdsl/dialects/llvm.py
@superlopuh pointed out that #2203 contains an erroneous implementation of a UnitAttr being implemented as properties. This is incorrect, since upstream prints the UnitAttrs as attributes and properties.
It was a bit confusing because some other ops in the LLVM dialect have the same mistake right now.
This happens under the radar because in testing, properties are printed as attributes.
This PR fixes the inline_asm operation.
=> dialects: Fix inline_asm unitattrs to not be properties

tests/interactive/test_app.py, xdsl/interactive/passes.py
I have a feeling this should have been the case from the get-go. The main reason to condense is to show the available transformations, to make it quick and easy to go towards your target. There are three reasons why a pass might fail:
1. it's mlir-opt and it has weird stdout/stderr behaviour that breaks textual
2. it's a pass that requires parameters to run
3. it actually fails
I would say that none of these are useful by themselves to show in the "quick and easy" list. If the user knows to use a certain pass, they can always "uncondense" and pick the pass that they want, possibly with the parameters they're interested int. The passes that currently require parameters should probably either provide default parameters or provide a range of options to try in the future, but that can be done …
=> interactive: remove passes that raise errors from condensed list

tests/irdl/test_declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py
Stacked on #2106.
Add optional operands and type directives; very similar to the variadic ones. Adds the notion of "variadic-like" to relate to checks added in #2106
=> Implement and test optional operand and result variables.

tests/filecheck/backend/riscv/convert_func_to_riscv_func.mlir, tests/filecheck/backend/riscv/memref_to_riscv.mlir, xdsl/backend/riscv/lowering/convert_func_to_riscv_func.py
I'm not 100% sure what the lowering should be. Godbolt seems to drop external function declarations, should we skip them during assembly printing?
=> transformations: (riscv_func) handle external function declarations

xdsl/interactive/app.py
Quick fix to remove the pass for the current node from the path from the root to the one passed in the event.
=> interactive: don't apply selected pass twice

tests/filecheck/dialects/tensor/invalid_ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/tensor/ops.mlir, xdsl/dialects/tensor.py
=> (dialects): add tensor.reshape

tests/filecheck/dialects/onnx/onnx_ops.mlir, xdsl/dialects/onnx.py
This PR fixes the bug in ```onnx.reshape```:
The input tensor's shape and the output tensor's shape are required to have the same number of elements. This means the product of the dimensions of the input shape and output shape must be equal not the rank.
This PR checks for the dimension products and fixes a test to align with the according new changes
=> onnx.reshape should check for product not length 

tests/filecheck/dialects/memref/memref_ops.mlir, tests/filecheck/dialects/onnx/onnx_ops.mlir, xdsl/irdl/declarative_assembly_format.py
Supernit fix: The assembly_format currently doesn't print a space after the attribute dictionary.
=> core: Assembly format spacing fix.

xdsl/transforms/convert_onnx_to_linalg.py
ONNX denotes broadcastable dimensions with `-1,` whereas MLIR does with `?.` This PR fixes the bug where `1` was used instead of `-1`.
=> (bug): update add op lowering to check for -1 not 1

tests/irdl/test_declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py
This covers optional groups with no else group, only literal first then element, and optional/variadic operand/result/type anchors. I think this is the most widely used, it enables the typical `` (`(` $variadic_operand`)`)?``
=> core: Implement first cases of assembly format optional groups

xdsl/ir/core.py, xdsl/printer.py
Enables:
- #2249
A mistake slipped in because all initial EnumAttributes where OpaqueSyntaxAttribute. linalg.IteratorType is the first one not to, hence the fix.
=> core: Spacing fix in EnumAttribute and OpaqueSyntaxAttribute

tests/filecheck/projects/riscv-backend-paper/conv_target.mlir, tests/filecheck/projects/riscv-backend-paper/ddot_target.mlir, tests/filecheck/projects/riscv-backend-paper/dense_target.mlir, tests/filecheck/projects/riscv-backend-paper/dsum_target.mlir, tests/filecheck/projects/riscv-backend-paper/fill_target.mlir, tests/filecheck/projects/riscv-backend-paper/matmul_target.mlir, tests/filecheck/projects/riscv-backend-paper/max_pool_target.mlir, tests/filecheck/projects/riscv-backend-paper/relu_target.mlir, tests/filecheck/projects/riscv-backend-paper/sum_pool_target.mlir, tests/interactive/test_app.py, xdsl/tools/command_line_tool.py, xdsl/transforms/test_lower_linalg_to_snitch.py
The main idea is that we want to keep a part of this stable, since we still have some tests defined as snitch_stream in the RISC-V backend paper experiments. I'd like to propose having two passes, one for linalg to snitch stream, and a second for lowering snitch stream down to assembly.
=> testing: rename test-lower-linalg-to-snitch to test-lower-snitch-stream-to-asm

tests/filecheck/dialects/memref_stream/ops.mlir, xdsl/dialects/memref_stream.py
linalg.generic supports it, and so should memref_stream.generic
=> dialects: (memref_stream) allow scalar argument to memref_stream generic

xdsl/dialects/linalg.py, xdsl/dialects/memref_stream.py, xdsl/ir/core.py, xdsl/printer.py
Stacked on:
- #2248 
Just a little reuse.
Had to remove the `@final` to add brackets.
@math-fehr, do you still believe those brackets belong in individual attributes? Is there an MLIR attribute that does not use them in non-opaque syntax?
=> dialects: make linalg.IteratorType an EnumAttribute

tests/filecheck/transforms/convert_memref_stream_to_snitch.mlir, tests/interpreters/test_snitch_stream_interpreter.py, xdsl/dialects/snitch_stream.py, xdsl/interpreters/snitch_stream.py, xdsl/transforms/convert_memref_stream_to_snitch_stream.py
Note stacked PR
When lowering convolutions, we run out of stream dimensions, hence this PR, which lowers the number of dimensions in the stream. In a future PR, we'll only convert a memref operand to a `generic` to a stream when we know that the stride pattern will be less than some parameter. For now, we just convert first and then hope for the best.
=> transformations: simplify stride patterns when lowering memref_stream

tests/filecheck/dialects/riscv_scf/loop_range_folding.mlir, xdsl/transforms/riscv_scf_loop_range_folding.py
We currently only support folding multiplications, this adds folding addition into the loop bounds.
=> transformations: (riscv-scf-loop-range-folding) add riscv.add support

tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
=> testing: manually simplify stride patterns in bottom-up test

tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/invalid_ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir, xdsl/dialects/linalg.py
=> (dialects): add linalg.tranpose

requirements.txt
Our pattern is too coarse, the tests all passed locally, but broke with the new minor version.
=> ci: use old pytest

.github/workflows/ci-core.yml, .github/workflows/ci-mlir.yml, .github/workflows/ci-notebooks.yml, .github/workflows/ci-pyright-fails.yml, .github/workflows/code-formatting.yml, .github/workflows/jupyterlite.yml, .github/workflows/pythonpublish.yml, requirements.txt
The CI gave me a warning and a link to this website, listing the actions updated in this PR:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> ci: update actions from node 16 to node 20

xdsl/interpreters/ptr.py, xdsl/interpreters/riscv_libc.py
This was never leveraged or tested, and I'm not sure that it's safe to have in the general case. If a user implements some sort of custom allocator that uses one large RawPtr instance, then the whole thing shouldn't be deallocated just because a part of it was.
=> interpreter: remove deallocated property on RawPtr

tests/filecheck/mlir-conversion/with-mlir/mlir_opt.mlir, tests/filecheck/mlir-conversion/with-mlir/mlir_opt_fail.mlir, xdsl/transforms/mlir_opt.py
This adds the `executable` option to the `mlir-opt` pass that allows one to pass a custom executable (e.g. `mlir-opt-17`, or a path to a binary that is not in `PATH`).
=> transformations: (mlir-opt) Add option to specify mlir-opt binary in args

requirements.txt
Follow up on #2291. I will save you dependabot!
Updates the requirements on [pytest](https://github.com/pytest-dev/pytest) to permit the latest version.
- [Release notes](https://github.com/pytest-dev/pytest/releases)
- [Changelog](https://github.com/pytest-dev/pytest/blob/main/CHANGELOG.rst)
- [Commits](https://github.com/pytest-dev/pytest/compare/1.0.0b3...8.1.0)
---
updated-dependencies:
- dependency-name: pytest
dependency-type: direct:production
...
=> pip prod(deps): update pytest requirement from <8.1  to <8.2

xdsl/interactive/app.py
Small bug in the code. Selecting root node of tree of passes adds node to pass pipeline - this is not allowed.
=> interactive: fix bug - do not allow users to be able to select root node to be added to the pass pipeline

xdsl/ir/core.py, xdsl/parser/core.py, xdsl/utils/test_value.py
This PR makes `SSAValue` hashable so that pyright will stop complaining when I use it in the `value_mapper` dict of `Operation.clone`.
The hash of an SSA Value is it's `id`, which should be safe as two SSA Values are only the same if they are literally the same value.
=> core: Make SSAValue hashable

tests/dialects/test_hw.py, tests/filecheck/dialects/hw/hw_ops.mlir, tests/filecheck/dialects/hw/invalid.mlir, xdsl/dialects/hw.py
Another hopefully manageable chunk of HW, which introduces the symbol attributes. These are used in many circt dialects (e.g., seq) to define the names then referenced by the `InnerRefAttr`s and the like.
This is [the bit of the symbol rationale](https://circt.llvm.org/docs/RationaleSymbols/#inner-symbol) that gives details.
This PR also includes a small fix on the tests, simplifying the test file and undoing the over-correction of camel case to snake case on symbol mnemonics (we want those to be compatible with CIRCT).
Thanks a lot to @PapyChacal for all the help in deciphering where CIRCT hides the symbol attr tests.
=> dialects: (hw) Add `InnerSymAttr` attributes to HW dialect.

xdsl/dialects/hw.py
Quick PR to fix the currently failing CI
=> dialects (hw): Fix Formatting

tests/dialects/test_llvm.py, xdsl/dialects/llvm.py, xdsl/pattern_rewriter.py
Fixes a small bug in the constructor of the inline assembly op.
=> dialects: (llvm) Fix constructor for llvm.InlineAsmOp

tests/dialects/test_riscv.py, xdsl/dialects/riscv.py
The identity of registers is currently defined by a string. This can be problematic as RISC-V registers have alternative spellings which are then considered as unequal.
This PR is a first step towards fixing that issue by adding an optional `index` parameter to the type. The idea is to have a unique index that identifies the register in the future if it is a predefined register. Non-predefined registers such as the infinite `j[0-9]+` registers set `index` to `None` to signal that the spelling should be used for equality.
A future PR will add the `__eq__` implementation after the representation has proven itself.
Part of https://github.com/xdslproject/xdsl/issues/1760
=> dialects: (riscv) add index to registers

xdsl/pattern_rewriter.py, xdsl/rewriter.py
I'm messing about with some helpers that pass around what are effectively insertion points, this functionality makes that code simpler. It also feels like a general entropy minimising step.
=> core: add insert_op_at_location to PatternRewriter

tests/filecheck/dialects/pdl/mlir-tests.mlir, tests/filecheck/dialects/pdl/pdl_operand.mlir, tests/filecheck/dialects/pdl/pdl_operation.mlir, tests/filecheck/dialects/pdl/pdl_range.mlir, tests/filecheck/dialects/pdl/pdl_result.mlir, tests/filecheck/dialects/pdl/pdl_type.mlir, xdsl/dialects/pdl.py
It turns out PDL range types are not printed and parsed the natural way in MLIR, so this PR makes xDSL consistent with the MLIR implementation.
=> dialects: (pdl) Fix printer and parser for PDL range type

tests/dialects/test_comb.py, tests/filecheck/dialects/comb/comb_ops.mlir, xdsl/dialects/comb.py
The constructor, parser and printer of the comb concat op are incorrect. This PR fixes it, adds a useful builder for the concat operation and adds a verifier.
=> dialects: (comb) Fix concat op

tests/dialects/test_comb.py, tests/filecheck/dialects/comb/comb_ops.mlir, tests/filecheck/dialects/comb/comb_ops_err.mlir, xdsl/dialects/comb.py
The constructor, parser and printer of the comb extract op are incorrect. This PR fixes it and adds a verifier.
=> dialects: (comb) Fix extract op

tests/pattern_rewriter/test_pattern_rewriter.py, xdsl/pattern_rewriter.py
I found it was a little bit odd that this decorator did not allow the option for conversion to still be skipped even though the type matches the expected one. This change should be benign I expect?
=> rewriting: Extend TypeConversionPattern annotation

tests/dialects/test_gpu.py, tests/filecheck/dialects/gpu/ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/ops.mlir, xdsl/dialects/gpu.py
This pull request adds the `gpu.wait` op for GPU asynchronous execution. The `gpu.wait` op generates a token that can be used to enable asynchronous execution combined with other operations in `gpu` dialect.
=> dialects: (gpu) Adding `gpu.wait` op

Makefile
Currently the makefile interchangeably uses `venv` and `${VENV_DIR}` to refer to the virtual environment install directory. This change replaces all instances with the variable.
This allows to have e.g. 2 versions side-by-side:
```sh
$ make  # unchanged, builds into ./venv/
$ git checkout some-other-branch
$ make VENV_DIR=other-venv  # builds into ./other-venv/ without overwriting ./venv/
```
The trailing slash on the target name means you can use a hidden directory (e.g., `make VENV_DIR=.venv`) without the target being confused for a special Makefile target (`.c.o`, `.PHONY`, etc).
=> install: Consistently use VENV_DIR variable in Makefile

tests/filecheck/dialects/comb/comb_ops.mlir, xdsl/dialects/comb.py
The printer and parser of the ICmp operation were emitting/expecting an extra comma that is not present in the original dialect.
=> dialects: (comb) Fix icmp parser/printer discrepancy and 2-state semantics modelling

tests/pattern_rewriter/test_pattern_rewriter.py, xdsl/pattern_rewriter.py
When an operation is deleted, the pattern rewriter adds its operands with 1 use to the worklist of operations to change.
This change checks that these operands are not `ErasedSSAValue`, otherwise an erased operation would be added to the worklist.
I'm starting to think that the `ErasedSSAValue` design is bad, I'll be thinking of a way to change this.
=> core: Fix bug in pattern rewriter when ErasedSSAValue is present

tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir, xdsl/dialects/linalg.py
Fixes #2228: linalg.fill shouldn't have a fixed result
CC @gabrielrodcanal
=> dialects: (linalg) allow for empty results in linalg.fill custom format

tests/pattern_rewriter/test_pattern_rewriter.py, xdsl/pattern_rewriter.py
The documentation of `TypeConversionPattern` claims it supports attribute dictionaries, but does not walk them recursively. This PR fixes this behavior.
=> rewriting: Fix TypeConversionPattern recursive support for DictionaryAttr

tests/test_printer.py, xdsl/printer.py
Sometimes it is useful to know when printing what name has been chosen to print an SSA value (for example when SSA value names should map to names in an interface like in CIRCT's hardware modules). This PR introduces this feature to the printer. This also adjusts the type bounds on `print_list` so it remains happy with having `print_ssa_value` as its argument.
=> core: Make print_ssa_value return chosen name

tests/test_printer.py, xdsl/printer.py, xdsl/utils/lexer.py
Symbol names are not required to be identifiers, and in that case they should be printed as `@"non-identifier name"`, but xDSL would print them as `@non-identifier name`. This PR fixes this behavior.
=> core: Fix printing of non-identifier symbols

xdsl/transforms/reconcile_unrealized_casts.py
This PR reformulates the reconcile-unrealized-casts so it uses a pattern, so reconciliation can be applied by pattern rewrite drivers.
=> transformations: (reconcile-unrealized-casts) Make cast reconciliation available as a pattern

tests/test_parser.py, xdsl/parser/attribute_parser.py, xdsl/parser/core.py
For some reason when I added location parsing I made it protected. This PR makes it public.
=> core: Make location parsing public

tests/filecheck/dialects/x86/x86_assembly_emission.mlir, xdsl/dialects/x86/__init__.py, xdsl/dialects/x86/ops.py, xdsl/xdsl_opt_main.py
I've re-added the printing functionality with a filecheck to test it. I have temporarily brought back the get_register method to get the PR out, so please let me know what's the better way to do it. test.op no longer works when a particular register needs to be specified (it fails an assertion error during the printing). Riscv did it by starting off with operations that don't need register arguments, but I don't have those yet.
=> dialects: (x86) PR3 - Assembly emission

xdsl/transforms/reconcile_unrealized_casts.py
The pattern for unrealized casts reconciliation emits a lot of warnings when it fails to match. While this makes sense as a pass application, it clutters output in patterns where reconciliation is expected to fail. This PR makes the emission of warning togglable, disabled by default in the pattern and enabled in the pass.
=> transformations: (reconcile-unrealized-casts) Disable warnings in pattern by default

xdsl/transforms/test_lower_snitch_stream_to_asm.py
riscv-cse is currently buggy, this removes it from the pipeline until the bugs get fixed
#2384
=> transformations: (test-lower-snitch-stream-to-asm) remove riscv-cse

xdsl/dialects/linalg.py
This PR adds the key attributes `dilations` and `strides` to the `init`, which was omitted, and also we make an abstract superclass so we can subclass per permutation when adding future pooling operations
=> dialects: (linalg) add attributes to linalg.pooling_nchw_max and base class for pooling ops 

tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir, xdsl/dialects/linalg.py
resolves #2399
edit:  linalg.conv_2d_nchw_fchw accepts 3 total args not 4, meaning that the bias matrix from onnx.conv can't be added during, i think a linalg.add op will be required for lowering in that case
=> dialects: (linalg) add linalg.conv_2d_nchw_fchw

tests/filecheck/dialects/hw/hw_module.mlir, tests/filecheck/dialects/hw/hw_ops.mlir, tests/filecheck/dialects/hw/invalid.mlir, xdsl/dialects/hw.py, xdsl/printer.py
This PR introduces the `hw.module` and its companion `hw.output` from CIRCT, while adding various small enhancements to the general infrastructure to accommodate them. ModuleOps are used to specify self-contained hardware modules, akin to functions in software.
A `hw.module` looks like the following:
```
hw.module @name<param1: i1, param2: i2>(in %a: i8, in %b: i9, out c: i8) {
%res = arith.constant 0 : i8
hw.output %res : i8
}
```
While hardware modules have similar semantics to functions, both inputs and outputs in `hw.module` are defined within the parenthesis, as *ports*. This is because some ports may be both input and output in CIRCT (currently not supported). Modules can optionally receive static parameters (in the example, `param1` and `param2`). Those are akin to C++ value …
=> dialects: (hw) Add `hw.module` and `hw.output` operations

tests/filecheck/dialects/snitch_runtime/snitch_runtime_ops.mlir, tests/filecheck/transforms/convert-snrt-to-riscv-asm.mlir, xdsl/dialects/snitch_runtime.py, xdsl/tools/command_line_tool.py, xdsl/transforms/snrt_to_riscv_asm.py
Add `convert-snrt-to-riscv-asm` transformation that converts (some) snitch runtime ops into their assembly definitions.
This is part one of many, so more patterns coming up soon!
=> transformations: Add convert-snrt-to-riscv-asm pass to lower snrt ops to RISC-V dialect

tests/dialects/test_hw.py, xdsl/dialects/hw.py
This requires `InnerRefNamespaceLike`.
We use `abc.ABC` to reimplement the upstream mechanics of implementing this with `isa<InnerRefNamespaceLike>` and `InnerRefNamespaceLike::classof()`
Fixes #2402
=> dialects: (hw) Add InnerRefNamespaceTrait to HWModuleOp

tests/filecheck/dialects/seq/seq_ops.mlir, xdsl/dialects/seq.py
This op allows modeling registers. This is for now a very basic implementation which only partially matches the CompRegOp upstream. But it should be enough for many practical uses already!
=> dialects: (seq) Add CompRegOp

tests/filecheck/dialects/snitch_runtime/snitch_runtime_ops.mlir, tests/filecheck/transforms/convert-snrt-to-riscv-asm.mlir, xdsl/dialects/snitch_runtime.py, xdsl/transforms/snrt_to_riscv_asm.py
This PR partially initializes a transformation for lowering DMA-related operations to RISC-V dialect.
Specifically, `xdsl/transforms/snrt_to_riscv_asm.py` is enriched with the `LowerDMAStart1DWidePtr` class. There's some more stuff in there, detailed in [another (closed) PR](https://github.com/xdslproject/xdsl/pull/2411).
=> transformations: Refine and enhance lowering Snitch runtime DMA operations to RISC-V

tests/filecheck/dialects/builtin/attrs.mlir, xdsl/dialects/builtin.py
The previous logic to compute the lower signed bound for i0 integers attempted to compute `1 << -1` which Python does not like. This change translates the intuitive meaning of `1 << -1` into `1 >> 1` for the zero bitwidth case.
=> dialects: (builtin) Fix bound computation crash for i0

tests/filecheck/transforms/convert_onnx_to_linalg.mlir, xdsl/transforms/convert_onnx_to_linalg.py
wip #2395
i used xdsl/tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir to get an idea of how to do it, i feel this is "close"
=> transformations: (onnx) lower onnx.Conv to linalg 

tests/irdl/test_declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py
I was going to suggest the missing optional `$inner_sym` attr on #2404 but realised optional attributes don’t exist yet in the declarative format. It seemed a rather trivial extension so here’s my shot at it, let me know if something misses/feels wrong.
=> core: Add optional attributes to declarative assembly format

tests/dialects/test_accfg.py, tests/filecheck/dialects/accfg/accfg_ops.mlir, xdsl/dialects/accfg.py, xdsl/tools/command_line_tool.py
This PR adds the accfg dialect that @AntonLydike and me designed during a very productive week in Leuven
Accfg dialect contains ops to minimize setup in register-set-up accelerators.
Either through registers connected to a CPU core (like control and status registers) or memory mapped io (like setting registers over an AXI bus).
All operations are documented with docstrings.
Thanks for your reviews!
=> dialects: Add accfg dialect operations

tests/pattern_rewriter/test_pattern_rewriter.py, xdsl/pattern_rewriter.py
xDSL currently bails out completely on the first exception raised while rewriting.
This changes this behaviour by capturing the said exception and printing it in the IR's context, just like verification errors.
Thus, when reading the error, the user can see the state of the IR at the point where a specific pattern failed, making it easier to reason about fixes or improvements IMO.
This is mostly intended to help while *developing* patterns, not any statement on the "should they even fail" topic.
=> core: More informative rewrite errors.

Makefile
Fixes a stray slash introduced by #2316 that changed the venv target name form `venv` to `venv/`, as noticed in #2415.
=> misc: (Makefile) Remove trailing slash from venv target

tests/filecheck/dialects/seq/seq_invalid.mlir, tests/filecheck/dialects/seq/seq_ops.mlir, xdsl/dialects/seq.py
Now #2448 and #2407 are in we can finally complete what was left out of #2404:
- an optional attribute `inner_sym` 
- the second optional operand `powerOn`
=> dialects: (seq) Finish `seq.compreg` optionals

tests/filecheck/dialects/comb/comb_ops.mlir, xdsl/dialects/comb.py
Upstream expects `lowBit` casing.
=> dialects: (comb) Fix lowBit case in extract op

tests/filecheck/dialects/comb/comb_ops.mlir, xdsl/dialects/comb.py
Upstream CIRCT accepts any type in a mux. This fixes parity in xDSL.
=> dialects: (comb) Accept non-integer types in mux

tests/filecheck/dialects/seq/seq_invalid.mlir, tests/filecheck/dialects/seq/seq_ops.mlir, xdsl/dialects/seq.py
This PR adds the const clock operation. Because of the arguably very cursed way MLIR handles attribute parsing, we cannot reproduce the convenient structure upstream uses to easily parse the clock value. Instead, I set up a way for the attribute to expose this unstructured parsing for custom parsers.
=> dialects: (seq) Add ConstClockOp

tests/dialects/test_llvm.py, xdsl/dialects/llvm.py
There seems to have been a misunderstanding on the meaning of the element type in the llvm.getelementptr implementation in xDSL.
=> dialects: (llvm) Fix elem_type bug in GEPOp builder

tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir, tests/filecheck/transforms/stencil-storage-materialization.mlir, xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py, xdsl/transforms/experimental/stencil_storage_materialization.py
Lower and materialize `stencil.combine`; this is an addition to the original implementation, which only handles inlining `stencil.combine`s in one big `stencil.apply` with nested conditionals.
This will be implemented too at some point, but the way implemented here was a shorter first step.
I slid into refactoring `stencil.buffer`'s lowering too; I could split it if necessary.
This operation was previously lowered as part of `stencil.apply`'s pattern for technicalities; in a nutshell, the new worklist allows to decouple them, and it made sense to get `stencil.buffer` and `stencil.combine` to play along nicely!
=> transformations: lower `stencil.combine`, refactor `stencil.buffer`

xdsl/interactive/add_arguments_screen.py, xdsl/interactive/app.py
When pressing a pass that requires argument input, a new screen pops up. when you press "clear" (i.e. clear the screen) and then press "enter" (i.e. dismiss the screen) --> causes error. 
this should fix it.
=> interactive : remove bug that happens when argument screen is cleared and entered

tests/filecheck/dialects/x86/x86_assembly_emission.mlir, tests/filecheck/dialects/x86/x86_ops.mlir, xdsl/dialects/x86/__init__.py, xdsl/dialects/x86/ops.py
re-implementing the changes from #2456 after a merge conflict proved too annoying to handle. The changes have already been approved and I made sure that there were no errors during the copy-paste process.
=> dialects: (x86) PR5_3 - single operand instructions - source and destination 

tests/filecheck/dialects/x86/x86_assembly_emission.mlir, tests/filecheck/dialects/x86/x86_ops.mlir, xdsl/dialects/x86/ops.py
I've done some changes to the naming conventions following the suggestions of @tarinduj. This includes removing the single/doubleOperand parent classes (issue #2466), writing the class names in the format [Result]-[Operands]-Operation, and changing the individual names of the operations to prepare for the different configurations those instructions can exist in. The prefix signifies the type of the operand passed into the assembly instruction and is removed during assembly emission.
=> dialects: (x86) - Reformats and changes in naming convention

tests/filecheck/dialects/seq/seq_ops.mlir, tests/irdl/test_declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py
Those were currently using qualified attribute syntax (i.e., wrapping the parameters in the attribute's name).
This is not the intended behaviour: when parsing/printing a known attribute type, it should only print and parse its parameters.
The fully-qualified case is implemented upstream by an explicit wrapper (`qualified($attr)`) and could be added if needed; I see it is mostly used by the LLVM dialect upstream.
=> core: Implement unqualified attributes in declarative syntax.

.gitignore, docs/irdl.ipynb, docs/ret.mlir, tests/filecheck/dialects/onnx/onnx_invalid.mlir, tests/filecheck/dialects/scf/parallel_multiple_blocks.mlir, tests/filecheck/dialects/tensor/invalid_ops.mlir, tests/test_ir.py, xdsl/irdl/irdl.py
Minor refactor of error reporting, removing superfluous intermediary messages from IRDL.
More importantly, this was capturing the error thrown by constraints, forcing users to scroll back to the underlying exception; this enables to directly print messages as seen in:
- #2482
=> core: Remove redundant output from IRDLOperation's verification error.

tests/irdl/test_attribute_definition.py, tests/irdl/test_declarative_assembly_format.py, xdsl/dialects/builtin.py, xdsl/ir/core.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py, xdsl/irdl/irdl.py, xdsl/printer.py
Implement TypedAttribute, a baseclass for attributes having a type attribute :upside_down_face: Mirroring the MLIR interface.
This is useful for the declarative assembly format, where when referencing an integer of a known type, we want to parse and print it with its type elided.
=> core: Implement TypedAttribute, leverage in declarative assembly format.

tests/dialects/test_hw.py, tests/filecheck/dialects/hw/hw_instance.mlir, tests/filecheck/dialects/hw/invalid_instance.mlir, xdsl/dialects/hw.py
This PR adds a subset of the hw.instance operation, the dual of hw.module for instantiation.
=> dialects: (hw) Add hw.instance operation

xdsl/dialects/hw.py
While upstream MLIR decouples SymbolTables from operations, this is not the case in xDSL. As such, whenever one wants to reuse symbol table functionality, they have to declare an operation as a SymbolTable op. This was done on HWModuleOp to reuse SymbolTable functionality for the InnerSymbolTable, but in contrast to how it is done in upstream CIRCT, this thus requires the InnerSymbolTable to be a regular SymbolTable. This in turn blocks regular symbol referencing outside of the InnerSymbolTable.
This PR reverts this change for now. This should be reimplemented once xDSL supports decoupled symbol tables (or InnerRefNamespaceTrait is updated accordingly).
=> dialects: (hw) Revert HWModuleOp's usage of InnerRefNamespaceTrait

.github/workflows/ci-codecov.yml, .github/workflows/ci-mlir.yml
My understanding is that actions that are triggered by the workflow_run action are run with secrets enabled.
=> ci: use a separate workflow for codecov upload

tests/filecheck/dialects/builtin/dense_array_invalid_dims.mlir, tests/test_parser.py, tests/test_printer.py, xdsl/parser/attribute_parser.py, xdsl/parser/base_parser.py, xdsl/printer.py
This PR firstly will enabling parsing of true and false string literals of type i1 to 1 and 0 respectively for DenseBaseAttr (previously true or false strings resulted in an error, but MLIR can output these as type i1).
This also works around an issue with MLIR, where MLIR will segfault in DenseArrayElementParser when it parses 0 and 1 as type i1, as it expects the false and true strings instead.
=> core: Handling true and false literals in DenseBaseAttr

xdsl/dialects/ml_program.py, xdsl/dialects/riscv_func.py
I had forgotten to do this on existing dialects other than func.
=> dialects: Factor out sym_visibility parsing in all dialects

xdsl/dialects/hw.py
While the visibility test was working, the practical roundtripping of private modules did not work properly. The reason for this is that there was a typo in the definition of the visibility attribute, which was cancelled out by the fact that roundtriping goes through generic format!
This seems to be a more fundamental issue of the testing infrastructure, so I am not sure how to add more tests that would cover this. @math-fehr @superlopuh
=> dialects: (hw) Fix printing of module visibility

tests/filecheck/dialects/stencil/invalid.mlir, tests/test_traits.py, xdsl/dialects/stencil.py, xdsl/traits.py
Implement HasAncestor, the transitive cousin of HasParent.
=> core: Implement HasAncestor.

tests/filecheck/dialects/x86/x86_assembly_emission.mlir, tests/filecheck/dialects/x86/x86_ops.mlir, xdsl/dialects/x86/__init__.py, xdsl/dialects/x86/ops.py
Added support for operations that have one memory access and one register operand. The result is saved to the memory location.
=> dialects: (x86) PR8 - MR Operations

tests/dialects/test_mpi_lowering.py, xdsl/transforms/lower_mpi.py
The currently used NullOp isn't defined in MLIR anymore; this was not caught on DeVito's side as we don't use MPI_Init from the xDSL compiled code there...
closes #2523
=> transformations: Switch MPI lowering to use llvm.mlir.zero

tests/filecheck/dialects/x86/x86_assembly_emission.mlir, tests/filecheck/dialects/x86/x86_ops.mlir, xdsl/dialects/x86/__init__.py, xdsl/dialects/x86/ops.py
Added support for operations with one destination register, one memory access and one immediate.
=> dialects: (x86) PR11 - RMI Operations

xdsl/dialects/x86/ops.py
As per suggestion, I made a helper function for the memory accesses
=> dialects: (x86) - mem access helper

tests/filecheck/backend/riscv/memref_to_riscv.mlir, xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
This seems to be similar to what `--finalize-memref-to-llvm` does.
=> transformations: add malloc to riscv function call lowering

tests/filecheck/transforms/gpu-allocs.mlir, xdsl/tools/command_line_tool.py, xdsl/transforms/gpu_allocs.py
This new pass converts all `memref.(de)alloc`s to `gpu.(de)alloc`s.
The motivation is that my stencil conversion is now completely target-agnostic, except for allocations, for which there currently exists no way to express transparently and select a platform later, for example.
It is very rough at this point; i.e., could extend to more targets, or to more settings, but is good enough for what I want to do with it at the moment :slightly_smiling_face:
=> transformations: Implement and test `memref-to-gpu`.

tests/filecheck/backend/csl/print_csl.mlir, tests/filecheck/backend/riscv/riscv_register_allocation.mlir, tests/filecheck/dialects/air/air_ops.mlir, tests/filecheck/dialects/arith/canonicalize.mlir, tests/filecheck/dialects/onnx/onnx_ops.mlir, tests/filecheck/dialects/snitch_runtime/snitch_runtime_ops.mlir, tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir, tests/filecheck/transforms/convert_onnx_to_linalg.mlir, tests/filecheck/transforms/memref_streamify.mlir, tests/filecheck/transforms/stencil-storage-materialization.mlir, tests/test_printer.py, xdsl/ir/core.py, xdsl/printer.py
Found this adorable little fundamental crack while working on the OEC kernels.
xDSL is currently still able to print distinct values using the same name; which is a big no no no.
Basically our brave printer, willing to honor user-friendly name hints given to values, deduplicates value names when a given name_hint clashes with a previously printed name, by adding a `_1`, `_2`, or ... to the name.
Func fact is, if the printer already printed `%v` twice, i.e., actually printed them as `%v` and `%v_1`, it only sees `%v_1` printed as a deduplication of `v`. So if the next value is hinted as `v_1`, then no problem seen, and the printer will print the three ***distinct*** values as `%v`, `%v_1`, and `%v_1` again :warning: 
Here is @math-fehr 's solution: just strip all suffixes in the form of …
=> core: Fix xDSL printing multiple values with the same name.

tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir, tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir, xdsl/dialects/stencil.py, xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py, xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py, xdsl/transforms/experimental/stencil_storage_materialization.py
Some improvements on the conversion:
- Stop relying on explicit loop indices for accesses and returns; `stencil.index` is modelling just that, use it instead as a proxy.
- `stencil.apply` now simply creates its own loop indices and replaces `stencil.index`s appropriately.
- split `stencil.store` in its own pattern rather than a loop, didn;t serve any purpose at this point - resulting in the minor recording of subviews.
- Accessorily fix a corner-case bug when not cleaning up the unused cloned op in storage materialization.
As can be seen on the tests, it's a nonfunctional change on whatever was tested, but the current passes did not work on a proper open earth compiler kernel. It now does :tada:
=> transformations: stencil conversion fixes and improvements

tests/test_ssa_value.py, xdsl/ir/core.py
Forgot this last commit in #2545 
The initial fix only strips `_\d` (single-digit) suffixes, not `_\d+` (one-or-more digits) suffixes
=> core: Strip multi-digit suffixes in name_hint, not only single-digit.

.gitignore, flake.lock, flake.nix
Makes the following two changes to make building easier on nixos:
- Adds direnv files to gitignore
- Adds a basic flake that allows `make tests` to be run
@AntonLydike
=> installation: Add nix flake

tests/filecheck/dialects/memref_stream/ops.mlir, tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir, tests/filecheck/transforms/convert_memref_stream_to_loops.mlir, tests/filecheck/transforms/convert_memref_stream_to_snitch.mlir, tests/filecheck/transforms/memref_streamify.mlir, xdsl/dialects/memref_stream.py, xdsl/dialects/snitch_stream.py, xdsl/interpreters/tensor.py, xdsl/transforms/convert_memref_stream_to_snitch_stream.py, xdsl/transforms/memref_streamify.py
In the context of imperfectly nested and/or interleaving loops, the streams are not able to reuse the same iteration bounds. . This PR adds a StridePattern to memref_stream, with pretty syntax.
=> dialects: (memref_stream) add StridePattern

xdsl/dialects/x86/__init__.py, xdsl/dialects/x86/assembly.py, xdsl/dialects/x86/attributes.py, xdsl/dialects/x86/ops.py
I moved most of the printing and parsing methods to a separate file as per issue #2377. I also moved the LabelAttr to attributes.py because it was needed in both .assembly and .ops + it seemed to make sense.
I left the print_assembly and x86_code in .ops as otherwise it would create a circular import.
=> dialects: (x86) PR19 - move assembly helpers to separate class

tests/pattern_rewriter/test_pattern_rewriter.py, tests/test_rewriter.py, xdsl/pattern_rewriter.py, xdsl/rewriter.py
The block argument replacement was added to the core function, but only to one of the API ones. This PR adds it to all of them.
Also minor tweaks:
- Block inlining currently asserts the inlined block is part of a region, only to detach it. Switch to simply detaching it if attached.
- Block inlining currently asserts that the right number of block argument replacement values is passed. Switch to just not do argument replacement if no such values are passed.
=> core: Block inlining API improvements

tests/filecheck/parser-printer/parse_error.mlir, xdsl/tools/command_line_tool.py, xdsl/utils/lexer.py, xdsl/xdsl_opt_main.py
I think the effect it is self-explanatory in [the one changed test!](https://github.com/xdslproject/xdsl/pull/2563/files#diff-024119b9d92381358b7618228e4198476beb0ddce5f25b66d204eba6374ee83b).
=> core: fix line numbers in split input mode.

tests/filecheck/transforms/convert-snrt-to-riscv.mlir, xdsl/transforms/convert_snrt_to_riscv.py
Missing ops:
- `snrt.global_compute_core_idx`
- `snrt.global_compute_core_num`
- `snrt.global_dm_core_num`
- `snrt.cluster_compute_core_idx`
- `snrt.cluster_dm_core_idx`
These seem to be relatively unused in practice and are skipped for now.
=> transformations: (convert-snrt-to-riscv) Add lowerings for even more info ops

tests/dialects/test_hw.py, tests/filecheck/dialects/hw/invalid_instance.mlir, xdsl/dialects/hw.py
This only adds the HWModuleLike methods that are currently relevant. Eventually it may be nice to add them all, but as they are pretty niche and would require quite a few changes on HWModuleOp...
=> dialects: (hw) Add HWModuleLike trait

tests/filecheck/backend/csl/print_csl.mlir, tests/filecheck/dialects/csl/ops.mlir, xdsl/backend/csl/print_csl.py, xdsl/dialects/csl.py
* Added `CslModuleOp` to separate program from layout
* Added `LayoutOp` to specify the `layout` block
* Added traits to ensure ops are in correct module types.
=> dialects: (csl) add modules

tests/filecheck/backend/csl/print_csl.mlir, tests/filecheck/dialects/csl/ops.mlir, xdsl/dialects/csl.py
* The three kinds of tasks
* Tasks carry IDs they will be bound to (by the printer, coming in future PR)
* `csl.call`, for tasks and functions
* Removed `AttrSizedOperandSegments` from `csl.member_call` following a discussion with @AntonLydike
=> dialects: (csl) Added call op and tasks

tests/filecheck/dialects/csl/ops.mlir, xdsl/dialects/csl.py
This PR adds: 
* `csl.const_struct`
* `comptime_struct` literal constructor
* `csl.get_color`
* Corresponds to `@get_color` in CSL
* `csl.set_rectangle`
* Corresponds to `@set_rectangle` in CSL
* `csl.set_tile_code`
* Corresponds to `@set_tile_code` in CSL
=> dialects: (csl) Adding Constructors for `comptime_struct` and `color`, as well as some `layout` functions.

tests/filecheck/backend/csl/print_csl.mlir, xdsl/backend/csl/print_csl.py
Add csl backend support for the following operations:
* `scf.For`
* `scf.yield`
* `memref.global`
* `memref.get_global`
Also added the following types:
* `memref`
* `index`
=> backend: (csl) Add printing some scf and memref features

pyproject.toml
typing-extensions 4.12 is causing our CI to fail.
Restricting it will make the CI pass while we are identifying the issue
=> Fix typing-extensions version

.github/pull_request_template.md
Changes the link to point to the new PR naming guidelines section of the wiki
=> docs: Change link to pr title formatting

tests/filecheck/dialects/csl/ops.mlir, xdsl/dialects/csl.py
This PR adds:
* `csl.addressof`
* Take address of a value (required for `csl.export`)
* `csl.export`
* Exports symbol by ssa value and name (as a string) or by symbol name
* `csl.rpc`
* equivalend to `@rpc` in the language
* _NOTE:_ I thought `@rpc` was going away in SDK 1.1, but now I can't find a reference to it in the documentation.
* `csl.param`
* Module import parameters (with optional default values)
=> dialects: (csl) Added operations to manage symbols

tests/dialects/test_builtin.py, xdsl/dialects/builtin.py
api: Fixed builtin.DenseArrayBase not supporting IndexType as element type
Fixes issue #2604
=> api: Fixed builtin.DenseArrayBase not supporting IndexType

xdsl/transforms/common_subexpression_elimination.py
Refactor CSEDrive to make most things private and mostly expose `simplify`, applying CSE on one Operation/Block/Region.
Then just expose a public `cse` function as entry-point: any rewrite can now just import `cse` and use it during other transformation :slightly_smiling_face:
=> transformations: CSE: Refactor for reuse-friendliness

tests/filecheck/dialects/stencil/canonicalize.mlir, xdsl/dialects/stencil.py, xdsl/transforms/canonicalization_patterns/stencil.py
Stencil canonicalization now takes care of dropping unused operands.
Also leverage CSE after removing duplicated operands to simplify the body accordingly (i.e., get rid of now duplicated accesses)
=> dialects: stencil: more canonicalization

tests/dialects/test_arith.py, tests/filecheck/dialects/arith/arith_ops.mlir, xdsl/dialects/arith.py
Add the `mului_extended` and `mulsi_extended` from the `arith` dialect in MLIR
=> dialects: [arith] Add extended multiplication operations

tests/filecheck/backend/riscv/convert_func_to_riscv_func.mlir, tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir, tests/filecheck/dialects/riscv/riscv_ops.mlir, xdsl/dialects/riscv.py
Mostly impacts SSA counters in filechecks, and one assembly printing test.
=> dialects: (riscv) mark assembly region as isolated from above

tests/filecheck/dialects/memref_stream/ops.mlir, xdsl/dialects/memref_stream.py, xdsl/transforms/convert_linalg_to_memref_stream.py
We don't support window iterators. I also want to try adding our own "interleave" iterator type to model our current interleaving of operations.
=> dialects: (memref_stream) use memref_stream iterator type, not linalg

tests/filecheck/dialects/csl/ops.mlir, xdsl/dialects/csl.py
A basic implementation of dsd types and the `@get_dsd`. Custom array index expressions are not yet supported, and the current version should be understood (and printed) as accessing `A[i,j,k]` according to the number of dimensions and generate induction vars accordingly.
=> dialects: (csl) Data structure descriptors

tests/filecheck/backend/csl/print_csl.mlir, xdsl/backend/csl/print_csl.py
Printing for:
* `csl.call`
* `csl.task`
* `csl.func`
* Merged with `csl.task`
* `csl.export`
* `csl.layout`
Also introduces a divider between the program and layout, for ease of filechecking and splitting
=> backend: (csl) printing for functions, tasks and layout related things

xdsl/pattern_rewriter.py, xdsl/transforms/convert_linalg_to_loops.py, xdsl/transforms/convert_memref_stream_to_loops.py, xdsl/transforms/loop_nest_lowering_utils.py
A small refactor that makes some upcoming PRs less messy.
Note stacked PR.
=> transformations: linalg.generic to loops uses InsertPoint

tests/filecheck/dialects/csl/ops.mlir, xdsl/dialects/csl.py
Implementing support for CSL builtins that modify DSDs:
`@set_dsd_base_addr(input_dsd, base_addr)`
`@increment_dsd_offset(input_dsd, offset, elem_type)`
`@set_dsd_length(input_dsd, length)`
`@set_dsd_stride(input_dsd, stride)`
Each of these ops only works with specific DSD types, which is handled in the `verify_` method.
Added additional tests and support for `tensor` type as basis for mem dsds.
=> Dialects: (csl) adding dsd ops

tests/filecheck/dialects/memref_stream/verify.mlir, xdsl/dialects/memref_stream.py
=> dialects: (memref_stream) add a verifier for order of iterator types in memref_stream.generic

tests/filecheck/dialects/csl/ops.mlir, xdsl/dialects/csl.py
Simplify DSD types in IR by not carrying around element type information. Since this is only needed for the printing of `@increment_dsd_offset()`, we can provide a helper method instead to retrieve this information.
=> Dialects: (csl) Simplify DSD types in IR

tests/filecheck/backend/csl/print_csl.mlir, xdsl/backend/csl/print_csl.py
This PR adds
* Types
+ `csl.color`
* Attributes
+ Boolean attribute
+ String attribute
* Operations
+ `csl.param`
+ `csl.const_struct`
+ `csl.set_tile_code`
+ `csl.set_rectangle`
+ `csl.get_color`
+ `csl.rpc`
It adds the last changes made in #2592, which can be closed when this is merged.
=> backend: (csl) Added printing for `param`,  `comptime_struct` and some builtins

tests/dialects/test_irdl.py, tests/dialects/test_irdl_with_annotations.py, xdsl/irdl/irdl.py
This change makes IRDL accept non-irdl fields on `@irdl_op_definition` decorated classes, if they are all uppercase and annotated as `ClassVar`.
=> core: (irdl) Allow ClassVar with all uppercase name

docs/Toy/toy/rewrites/lower_toy_affine.py, docs/Toy/toy/rewrites/setup_riscv_pass.py, tests/pattern_rewriter/test_pattern_rewriter.py, tests/test_rewriter.py, xdsl/backend/riscv/lowering/convert_riscv_scf_to_riscv_cf.py, xdsl/backend/riscv/lowering/convert_snitch_stream_to_snitch.py, xdsl/backend/riscv/lowering/utils.py, xdsl/backend/riscv/riscv_scf_to_asm.py, xdsl/pattern_rewriter.py, xdsl/rewriter.py, xdsl/transforms/canonicalization_patterns/scf.py, xdsl/transforms/canonicalization_patterns/stencil.py, xdsl/transforms/convert_linalg_to_loops.py, xdsl/transforms/convert_memref_stream_to_loops.py, xdsl/transforms/convert_memref_stream_to_snitch_stream.py, xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py, xdsl/transforms/experimental/dmp/stencil_global_to_local.py, xdsl/transforms/experimental/function_constant_pinning.py, xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py, xdsl/transforms/experimental/stencil_tensorize_z_dimension.py, xdsl/transforms/loop_hoist_memref.py, xdsl/transforms/loop_nest_lowering_utils.py, xdsl/transforms/lower_riscv_func.py, xdsl/transforms/memref_streamify.py
This reduces the surface area of the Rewriter and PatternRewriter. Note that it doesn't modify the `matched_op` helpers, partially so that the diff doesn't baloon, and partially because I think they are actually quite helpful as they are. At least I'd love to talk about the matched_op helpers separately from this PR, if possible.
Resolves #859
=> core: unify (Pattern)Rewriter insertion and inlining APIs around InsertPoint

tests/dialects/test_irdl.py, tests/dialects/test_irdl_with_annotations.py, xdsl/irdl/irdl.py
This is to enhance PR [#2687](https://github.com/xdslproject/xdsl/pull/2687), which allowed uppercase `ClassVar` fields on ops.
This PR adds support for the case that an uppercase `ClassVar` is defined (without a value) in a superclass and assigned a value in a subclass. This is confirmed by performing the same check as in the other PR.
=> core: Allowing overload of ClassVar from superclass

tests/filecheck/backend/csl/print_csl.mlir, tests/filecheck/dialects/csl/ops.mlir, xdsl/backend/csl/print_csl.py, xdsl/dialects/csl.py
Enabling printing DSD ops to CSL.
=> dialects: (csl) print dsd ops

tests/filecheck/transforms/distribute-stencil.mlir
Just adding a minimal filecheck for the `distribute-stencil` pass as it is.
I think it shows some quirks nicely already! But point is to have a filecheck to have a bit of visibility over the next polishing steps.
=> tests: Add filecheck for distribute-stencil as it is.

tests/filecheck/dialects/memref/memref_ops.mlir, tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_mlir_conversion.mlir, xdsl/dialects/builtin.py, xdsl/dialects/memref.py
Also add minor helpers to builtin: `I1`,`I32`,`I64`, to use in type expressions.
=> dialects: Define memref.atomic rmw

docs/irdl.ipynb, tests/dialects/test_builtin.py, tests/irdl/test_attribute_definition.py, tests/irdl/test_operation_definition.py, tests/test_pyrdl.py, xdsl/dialects/builtin.py, xdsl/dialects/stencil.py, xdsl/irdl/declarative_assembly_format.py, xdsl/irdl/declarative_assembly_format_parser.py, xdsl/irdl/irdl.py, xdsl/utils/hints.py
Just define ConstraintContext to encapsulate the constraint variables used in verification and inference.
Also, define a default value for this argument in verification, to verify with an empty context.
=> core: Implement and use ConstraintContext

tests/filecheck/mlir-conversion/with-mlir/dialects/memref/canonicalize.mlir, xdsl/dialects/memref.py, xdsl/dialects/snitch_runtime.py
This PR adds `NoMemoryEffects` trait to ops from the memref and snitch_runtime dialect that should have them.
=> dialects: Add NoMemoryEffects to memref and snitch_runtime dialect ops

tests/filecheck/backend/csl/print_csl.mlir, xdsl/backend/csl/print_csl.py
This PR addresses a few minor details in csl printing QOL:
- Remove the requirement of there being exactly two csl modules (one layout and one program)
- Change the divider to the standard file-split divider
- Print the file name at the start of each file block
=> backend: (csl) Rework printing logic for printing individual modules

xdsl/dialects/csl.py
`set_tile_code` does not have to be a direct child of `layout`, e.g. it can be used in a loop. But it does have to occur in a `layout`.
_NOTE_: the parameter to `set_tile_code` is specified as `ComptimeStructType`, not `StructLike`. This is semantically correct (though undocumented), i.e. you can't do this:
```zig
const my_params = @import_module("my_params.csl")
...
@set_tile_code(..., my_params);
```
=> dialects: (csl) set_tile_code fix traits

tests/filecheck/backend/csl/print_csl.mlir, tests/filecheck/dialects/csl/ops.mlir, xdsl/backend/csl/print_csl.py, xdsl/dialects/csl.py
This adds a signedness cast op (to cast from signless to signed types), and the `concat_struct` builtin.
I also re-formatted the filechecks for the ops to be pretty and test both generic and custom syntax.
Relevant for #2703
=> dialect: (csl) Add signedness cast and concat struct ops

xdsl/dialects/builtin.py, xdsl/dialects/experimental/aie.py, xdsl/dialects/memref.py, xdsl/parser/attribute_parser.py
This is a barebone mimic of the upstream MemrefLayoutAttrInterface, as it does not implement any of the methods; only mark attributes as acceptable by the parser. This solve the parser problem though, and allow the same extensibility on accepted layouts.
The uniplemented methods were not implemented on the existing layout attributes anyway, so I'm in favor of just merging, moving on, and think about implementing them in an interface style later.
=> core: Implement MemrefLayoutAttr base class and use in parser.

tests/interactive/test_app.py
Prefer dynamic check over asserting equality to a hard-coded passes list, which results in hard-to-diagnose test failures when adding passes with shared characteristics.
=> interactive: remove hard-coded list for interactive condensed passes test

tests/filecheck/dialects/irdl/cmath_irdl_loading.py, xdsl/interpreters/irdl.py, xdsl/irdl/irdl.py
Some fixes on the irdl loading boilerplate introduced in:
- #2654 
Fixes:
- Properly wrap operand and result constraints in OperandDef / ResultDef. @math-fehr I'm not sure how variadicity/optionality works on the irdl dialect. Is it another op or an attribute on those ones?
- Use cleaner type constructors: Not sure why, but those over the top __new__ calls had undesired side effects. Those don't and just are cleaner!
- Cleaner baseclassing (don't fetch the full `__mro__`, let the Python type machinery handle it properly
- Makes types types!
=> misc: irdl loading fixes

xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
More efficient use of xdsl functionality.
=> transforms: (experimental) minor updates to stencil-tensorize-z-dim

xdsl/dialects/csl.py
Adding constructors for many CSL ops.
This was originally part of #2720
=> dialects: (csl) adding constructors for CSL ops

tests/filecheck/backend/csl/print_csl.mlir, xdsl/backend/csl/print_csl.py, xdsl/dialects/csl.py
This patch makes the printer promote certain values to inlined expressions (e.g. not creating a new `const x = 5;` variable for an `arith.constant` operation, or for arithmetic expressions.
This is for now applied very carefully to a select few operations. Some checks are performed, such as that the value is not referenced at any point using the `AddressOf`operation, that the operation that produced the value is pure, and more.
=> backend: (csl) Slightly rework printer to promote certain values to inline expressions

tests/dialects/test_memref.py, tests/filecheck/dialects/memref/memref_ops.mlir, xdsl/dialects/memref.py
I'm adding the memref.extract_strided_metadataop because I need an op to fetch the dynamic offset created by a subview, and otherwise I can not do  that. 
https://mlir.llvm.org/docs/Dialects/MemRef/#memrefextract_strided_metadata-memrefextractstridedmetadataop
=> dialects: Add memref.extract_strided_metadata op

tests/filecheck/dialects/qssa/ops.mlir, xdsl/dialects/qssa.py, xdsl/tools/command_line_tool.py
Add a simple quantum ssa dialect and a simple roundtrip filecheck test. Thought it would be better to split the work I was doing into multiple pull requests to make it easier to review so this doesn't have any rewrites yet
=> dialects: Add qssa dialect

flake.nix
The python installation of ruff doesn't work on nixos, so it'd be good to add it to the flake
=> installation: Add ruff to flake.nix

tests/interpreters/test_memref_stream_interpreter.py, xdsl/dialects/memref_stream.py, xdsl/interpreters/memref_stream.py, xdsl/transforms/convert_memref_stream_to_loops.py
This makes it a little easier to test for miscompilations in our flow from linalg to snitch
=> interpreter: (memref_stream) add interpreter support for imperfect nesting

tests/filecheck/parser-printer/builtin_attrs.mlir, xdsl/parser/attribute_parser.py, xdsl/printer.py
It's actually `unit` not the empty string.
=> dialects: (builtin) Fix printing and parsing of `UnitAttr`

tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir, xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
A minor fix (plus test case) that allows the transformation to work on `stencil.field` passed in as function arguments.
=> transforms: stencil-tensorize-z-dim accept stencil.field as function arg

tests/filecheck/transforms/convert_memref_stream_to_loops.mlir, xdsl/transforms/convert_linalg_to_loops.py, xdsl/transforms/convert_memref_stream_to_loops.py, xdsl/transforms/loop_nest_lowering_utils.py
We encode the affine map constraints in the streaming region setup, so we don't need the results of the affine.apply operation, unlike in the memref.load case. We could dce them away, but it feels better to not insert them in the first place.
=> transformations: do not insert affine.apply ops when streaming

pyproject.toml
Importing a dialect from a `.irdl` file now raises Pyright warnings about not finding the source file but only the type stubs, which is expected. Disable this warning to avoid the noise
=> testing: Ignore missing sources warning in pyright.

tests/dialects/test_scf.py, tests/irdl/test_operation_builder.py, xdsl/ir/core.py, xdsl/irdl/irdl.py, xdsl/printer.py, xdsl/traits.py, xdsl/transforms/experimental/lower_hls.py, xdsl/transforms/lower_affine.py, xdsl/transforms/lower_riscv_func.py
Comes with some minimal impacts on uses, but seems like a win in terms of communicating immutability.
=> core: make VarOperand, VarOpResult, and VarRegion tuple instead of list

tests/filecheck/dialects/qref/ops.mlir, xdsl/dialects/__init__.py, xdsl/dialects/qref.py
Adds a qref dialect to xdsl, a variant of the qssa dialect which stores qubits as references rather than values.
@AntonLydike if you are interested
=> dialects: Add qref dialect
